### ISSUE TITLE
Question about `awful.menu`

### ISSUE THREAD

**Issue by deb75** [awesomeWM/awesome#2430] opened 2018-10-12 19:03 UTC
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

Hello,

 I am trying to build a menu with `awful.menu` : 
``` lua
  local bmenu = nil

   local items = {}
   for _, v in pair(list) do
      items[#items + 1] = {
         string.format("%s %d %s", s1, d1, s2),
         function()
            if bmenu ~= nil then
               if bmenu.wibox.visible then
                  bmenu:hide()
               end
            end
         end,
         myicon
      }
   end

   local bmenu = awful.menu({
         items = items,
         theme =
            { width = 1500,
              height = 100,
              font = "Monospace 18"
            }
   })

   bmenu:show()
```

I would like the text (`string.format( ...`) to be displayed with different colors and fonts, like when using pango markups (`<span color = ... weight = ...>the texte</span> `), but I checked pango markups are not interpreted. Nevertheless by reading the wiki I figured out that it could be done with some widgets replacing the formatted string.

However, I could not find any examples of that, may someone indicate me if it is feasible ?

Thanks in advance for your help.

Regards

**Comment by Elv13** [comment] 2018-10-12 19:09
In my opinion, `awful.menu` is quite limiting and just doesn't scale when you are doing something complex. While it wont ever get merged, I once wrote a module to fix this

https://github.com/Elv13/radical

As far as I know, it still works and have all the features you can ever need and then some.

**Comment by Elv13** [comment] 2018-10-12 19:29
Git pull, I fixed this. The issue is that we added an official grid layout in v4.1 and Radical still had the older version I wrote before it was extended and improved by someone else.

**Closed** 2018-10-16 16:34 UTC
