### ISSUE TITLE
Cannot launch awesome WM in Arch Linux (2017.01.01) 

### ISSUE THREAD

**Issue by reliveyy** [awesomeWM/awesome#1349] opened 2017-01-02 11:59 UTC
awesome v3.5.9 (Mighty Revendark)
* Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
* Compiled against Lua 5.3.2 (running with Lua 5.3)
* D-Bus support: ?

```
# xinit
error: /user/share/awesome/lib/gears/surface.lua:39: Couldn't recognize the image file format for file '/usr/share/awesome/themes/default/backgournd.png'
```

I referenced issue #653 then execute command to find out if I have `png.so` or not
```
# gdk-pixbuf-query-loaders | grep -A 4 png.so
gives no results
```

I looked at https://www.archlinux.org/packages/extra/x86_64/gdk-pixbuf2/ for package contents and there is no `png.so` either.

**Comment by psychon** [comment] 2017-01-02 12:26
All that I can tell you is "your GdkPixbuf does not support PNG" and "please install a version of GdkPixbuf with PNG support".
Oh and: Once you figured out how to do that (e.g. ask on some Arch linux IRC channel or their forums or whatever; you might even report a bug against the awesome package since it is clearly a bug in their packaging) please leave a message here saying how to fix that.

Besides that, what do you want from me?

**Comment by Scimmia22** [comment] 2017-01-02 16:10
There's no *png.so because it's statically built into gdk-pixbuf, not a module. Your given command makes a large assumption.

**Comment by psychon** [comment] 2017-01-02 16:29
@Scimmia22 Ok, I did not know that gdk-pixbuf allows to link (some..?) plugins statically. @Scimmia22 Any other idea why gdk-pixbuf refuses to load the file?
@reliveyy Could you test with some other program if the PNG file is fine and can be opened?

**Comment by psychon** [comment] 2017-01-02 16:29
@Scimmia22 Also: What do you mean with "my given command"?

**Comment by Scimmia22** [comment] 2017-01-02 16:34
gdk-pixbuf-query-loaders | grep -A 4 png.so

It assumes all loaders are modules. It does appear to be an Arch issue, though; the OP has said that the problem went away after installing xfce4, so it looks like a missing dependency.

**Comment by psychon** [comment] 2017-01-02 16:43
> gdk-pixbuf-query-loaders | grep -A 4 png.so

Ah, you mean that command from a year ok. Well ok, I didn't know that. Do you know some other easy way to check for PNG support in gdk-pixbuf?

> the OP has said that the problem went away after installing xfce4, so it looks like a missing dependency.

Where did he say so?
@reliveyy Could you provide a list of all packages that were installed when you installed xfce4? One of those has to be the missing one.

I'm closing this since the issue is a) not ours and b) solved. It would be nice to figure out what the problem in Arch's package dependencies is anyway.

**Closed by psychon** 2017-01-02 16:43 UTC

**Comment by Scimmia22** [comment] 2017-01-02 16:44
For reference: https://bugs.archlinux.org/task/52334

**Comment by psychon** [comment] 2017-01-02 16:47
@Scimmia22 really?
> FS#52334 - Unable to find root device /dev/mapper/... after upgrade to linux 4.9.1

**Comment by Scimmia22** [comment] 2017-01-02 16:49
LOL, wrong paste, sorry.

https://bugs.archlinux.org/task/52333

**Comment by psychon** [comment] 2017-01-02 17:29
@Scimmia22 I bet you have the same issue as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=801170: Missing dependency on shared-mime-info.
Could you try something like `sudo mv /usr/share/mime/mime.cache /usr/share/mime/mime.cache.foo` and see if this is enough to reproduce the breakage for you?
(Yes, I should write this on the Arch linux bug tracker. No, I write it here instead.)
