### ISSUE TITLE
Extreme tearing / shearing.

### ISSUE THREAD

**Issue by richmartin** [awesomeWM/awesome#1678] opened 2017-03-26 16:39 UTC
Output of `awesome --version`:
awesome v4.1-6-g7818fd3 (Technologic)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.1

**How to reproduce the issue:**

Watch a video in VLC, or even just scroll a long page in a web browser.

**Actual result:**

Severe tearing (shearing) clearly visible in the video.

**Expected result:**
No tearing.

I have been suffering from terrible tearing when using Awesome. This is particularly noticeable in videos, but is also observable when simply scrolling in a long webpage. This makes watching videos impossible in Awesome; I have to switch to another WM such as Unity or Cinnamon.

This was a problem on 3.5 and I had some gently hope that it would be fixed by upgrading to 4.1. Unfortunately, not.

I have tried both with and without the --no-argb flag.

**Comment by psychon** [comment] 2017-03-26 19:11
Sorry, but we have nothing to do with VLC drawing its content. A WM just places windows, the rest happens between the client and the X11 server. So... what video driver are you using (intel/amd/nvidia, open source / binary blob)? Did you perhaps try some other backend in VLC (Xvideo, GLX, dunno what else is available).

Personally, I use `compton` since it removes tearing here (but I only have it in video playing, never happened to me on a web page).

**Comment by richmartin** [comment] 2017-03-27 19:53
So, if I understand you correctly, with awesome the client is interacting directly with the X server to render the content. But with Unity/Cinnamon/etc they have a built-in compositor which is somehow smarter than a naked X server at vsync'ing and therefore ensures there is no tearing. Right?

So to achieve the same with Awesome, I should run a compositor with the window manager.

I did try that, but I couldn't figure out how to run compton with Awesome. I tried starting compton (with `compton -b` and with all the various permutations of vsync options) from within Awesome, but I wasn't sure if it was doing anything and the tearing was unchanged (or, with some vsync options, it just froze the screen).

I tried all the (many) different VLC backends but they demonstrated tearing under Awesome  (except the ASCI-Art backend which showed no tearing at all! ;-) 

It's a Radeon card with the Radeon driver...
```
 >  sudo lshw -c video
  *-display                 
       description: VGA compatible controller
       product: Pitcairn XT [Radeon HD 7870 GHz Edition]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller bus_master cap_list rom
       configuration: driver=radeon latency=0
       resources: irq:39 memory:e0000000-efffffff memory:f7300000-f733ffff ioport:e000(size=256) memory:c0000-dffff

  > modinfo radeon
   filename:       /lib/modules/4.8.0-41-generic/kernel/drivers/gpu/drm/radeon/radeon.ko
   ...
```

**Comment by psychon** [comment] 2017-03-28 07:16
> So, if I understand you correctly, with awesome the client is interacting directly with the X server to render the content.

Yup.

> But with Unity/Cinnamon/etc they have a built-in compositor which is somehow smarter than a naked X server at vsync'ing and therefore ensures there is no tearing. Right?

It depends. X11 is complicated. Running a compositor can cause tearing or can fix tearing. It's a bit hit-and-miss, sorry.

**Comment by actionless** [comment] 2017-03-28 23:57
i am not trying to start a player war here, but have you tried in mpv?

**Comment by Elv13** [comment] 2017-05-25 08:19
Closing this as the issue is not within the boundary of what Awesome can be patched to fix (beside adding a compositor, but it was decided it will not happen).

**Closed by Elv13** 2017-05-25 08:19 UTC

**Comment by mingtingouyang** [comment] 2020-09-23 13:42
> Output of `awesome --version`:
> awesome v4.1-6-g7818fd3 (Technologic)
> • Compiled against Lua 5.2.4 (running with Lua 5.2)
> • D-Bus support: ✔
> • execinfo support: ✔
> • xcb-randr version: 1.4
> • LGI version: 0.9.1
> 
> **How to reproduce the issue:**
> 
> Watch a video in VLC, or even just scroll a long page in a web browser.
> 
> **Actual result:**
> 
> Severe tearing (shearing) clearly visible in the video.
> 
> **Expected result:**
> No tearing.
> 
> I have been suffering from terrible tearing when using Awesome. This is particularly noticeable in videos, but is also observable when simply scrolling in a long webpage. This makes watching videos impossible in Awesome; I have to switch to another WM such as Unity or Cinnamon.
> 
> This was a problem on 3.5 and I had some gently hope that it would be fixed by upgrading to 4.1. Unfortunately, not.
> 
> I have tried both with and without the --no-argb flag.

Same for me. I fixed this by adding following configuration into rc.lua

```lua
awful.spawn.with_shell("picom -b --backend glx")
```

**Comment by MrZammler** [comment] 2020-09-23 15:33
Not sure if your radeon is the same as mine (i.e. uses the same open source driver) but on my RX570 using the open source drivers, by adding:

```
Section "Device"
     Identifier "AMD"
     Driver "amdgpu"
     Option "TearFree" "true"
EndSection
```

In /etc/X11/xorg.conf all tearing is gone, without having to use a compositor.

**Comment by charanreigns** [comment] 2021-08-14 12:21
> Not sure if your radeon is the same as mine (i.e. uses the same open source driver) but on my RX570 using the open source drivers, by adding:
> 
> ```
> Section "Device"
>      Identifier "AMD"
>      Driver "amdgpu"
>      Option "TearFree" "true"
> EndSection
> ```
> 
> In /etc/X11/xorg.conf all tearing is gone, without having to use a compositor.

For me its just worked!
just removed Driver part
```

Section "Device"
     Identifier "INTEL"
     Option "TearFree" "true"
EndSection
```

@MrZammler  Thank you!
