### ISSUE TITLE
Konsole doesn't tile properly when opening a new window

### ISSUE THREAD

**Issue by aidanharris** [awesomeWM/awesome#1718] opened 2017-04-10 00:23 UTC
Output of `awesome --version`:

awesome v4.1-38-gedd8ea4a (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

Open a new Konsole window and it will open with a floating layout instead of tiling.

**Actual result:**

I've created a simple screencast illustrating the issue [here](https://www.dropbox.com/s/n5jar26piauw6ts/output.mp4?dl=0). To summarise the video, when opening a new Konsole window the window that opens does so with a floating window instead of tiling. I have been unable to get the window to switch from floating to tiling.

I've seen this occasionally happen with other applications too, but have been able to consistently re-produce this with Konsole. I've also tried temporarily removing my awesome configuration and the issue still occurs with the default config.

I'm pretty sure I didn't have this issue with Awesome 3, so I'm guessing this could be to do with a recent change of some sort?

**Expected result:**

It should tile.

**Comment by Veratil** [comment] 2017-04-10 04:44
It looks like (but hard to tell from the low resolution of the capture for me) this is opening with `_NET_WM_STATE_MAXIMIZED_HORZ` and `_NET_WM_STATE_MAXIMIZED_VERT` which will prevent it from tiling.

**Comment by psychon** [comment] 2017-04-10 07:28
Which means: You should un-fullscreen the window, for example by running `awesome-client 'client.focus.maximized_horizontally = false client.focus.maximized_vertically = false'` in one of the Konsole windows. (Except for any typos that I may have made)
Related to: #1599 #1559 #1712 #1715 (wow, this list is way too long)

**Comment by blueyed** [comment] 2017-04-10 07:38
btw: the default config has keybindings for this.

**Comment by Elv13** [comment] 2017-06-01 21:16
Can't reproduce with git master, should have been fixed by https://github.com/awesomeWM/awesome/pull/1748

**Closed by Elv13** 2017-06-01 21:16 UTC
