### ISSUE TITLE
Starting LibreOffice: function object._legacy_accessors: "indexing nil value"

### ISSUE THREAD

**Issue by Manfred-Knick** [awesomeWM/awesome#2908] opened 2019-10-13 13:22 UTC
awesome v4.3-486-gf294ab37-dirty (Too long)
• Compiled against Lua 5.1.5 (running with Lua 5.1)
• D-Bus support: yes
• xcb-errors support: no
• execinfo support: yes
• xcb-randr version: 1.6
• LGI version: 0.9.0

Lately, starting app-office/libreoffice-6.3.2.2:0::gentoo
throws similar error four times,
resulting from function object._legacy_accessors:
. . . /usr/share/awesome/lib/gears/object/properties.lua: {164 | 206 | 164 | 206} :
always
. . . attempt to index field '_private' (a nil value)
. relevant Object: 
. . . self._private

Afterwards, LibreOffice continues to work as expected.

**Comment by psychon** [comment] 2019-10-13 14:18
CC @Elv13 Your magic is breaking. And yes, it literally calls itself magic:
https://github.com/awesomeWM/awesome/blob/f294ab37fe1b78980fb9d8639f64c6977912cbad/lib/gears/object/properties.lua#L161-L164

All of this is so new that my local clone does not know the commit in question nor the line numbers in the file (properties.lua only has 89 lines here).

@Manfred-Knick Could you provide an actual error message as printed by awesome? Yours looks a bit... odd. The error message basically says that some code higher up the chain did something wrong, but your traceback does not include the code in question.

**Comment by psychon** [comment] 2019-10-13 14:19
Oh and: This might or might not be a duplicate of #2897 (line numbers are different)

**Comment by Aire-One** [comment] 2019-10-13 15:10
This error was mitigated by @Elv13 in #2897 a few days back with e888d983efcb3881bf864b8161f6f25b76f41e59 which is younger than f294ab37 (the awesome version from this issue).

@Manfred-Knick, you should try to update to latest master and see if it fixed the issue.

**Comment by Manfred-Knick** [comment] 2019-10-13 15:39
awesome v4.3-496-g344964a4-dirty (Too long)   :   same.

Error Message was hand-copied from screen - c.f. screenshot in  #2897 .

**Comment by Manfred-Knick** [comment] 2019-10-13 15:40
Just to confim: Starting other applications does not show these error messages.

**Comment by Elv13** [comment] 2019-10-13 19:35
The "'_private' (a nil value)" cannot happen anymore since the mitigation. Make sure you really installed the newer version. I made a proper fix yesterday, but writing additional tests uncovered more corner case. So I will keep polishing it more to prevent the cleaner fix from creating more subtle regressions.

**Comment by Manfred-Knick** [comment] 2019-10-13 21:23
Confirmation: after re-login / restart:    WORKSFORME.

awesome v4.3-496-g344964a4-dirty (Too long)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.0

**Comment by Elv13** [comment] 2019-10-13 23:02
Thanks for confirming.

**Closed by Elv13** 2019-10-13 23:02 UTC

**Comment by Manfred-Knick** [comment] 2019-10-14 07:25
Thanks for all your work!
