### ISSUE TITLE
Cannot minimize all windows on a tag

### ISSUE THREAD

**Issue by gmmeyer** [awesomeWM/awesome#92] opened 2015-01-28 18:24 UTC
If I have only one unminimized window (or only one window) on a tag, and try to minimize that window, it will minimize momentarily, then it will pop back up automatically. The background will very briefly flash, then the window will be raised.

This is new behavior since upgrading to 3.5.6.

**Comment by actionless** [comment] 2015-01-28 18:55
can you reproduce the problem with the latest git master? i suspect it can be fixed in this commit (https://github.com/awesomeWM/awesome/commit/254e50d88c5f58cb8b736dbb4681d020ddb88919)

**Comment by gmmeyer** [comment] 2015-01-28 20:07
I won't be able to test it immediately, I will report back when I have done so. :)

**Comment by blueyed** [comment] 2015-02-15 13:08
This is caused by 02be8943 (Unmap minimized clients) in v3.5.6 (3aeac38 in master).

It works when the mouse is not over the last to-be-minimized client.

@gmmeyer 
Can you confirm the workaround?

(I've just mentioned the commit in #99, too.)

**Comment by gmmeyer** [comment] 2015-02-18 17:39
I can confirm that workaround.

**Comment by psychon** [comment] 2015-02-25 20:56
Doesn't happen with my own awesome config... but is reproducable with the default config.

What happens: Awesome unmaps the client window and then the mouse enters the "frame window" (which is the one that contains the client window and where awesome e.g. draws its titlebars). This results in a `mouse::enter` signal and lua then focuses the window again, which unminimizes it.

(See commit message of the closing commit for more)

**Closed** 2015-02-25 20:56 UTC
Labels: bug

**Comment by dlussky** [comment] 2015-05-18 20:24
psychon,  can you suggest a workarond for this bug, who doesn't want to compile the whole thing from source?) Maybe one can include some hack in the config  until the fixed version will be released?

**Comment by blueyed** [comment] 2015-05-18 20:33
@dlussky 
Compiling from source is not that difficult after all.

And you would belong to the brave testers for awesome 3.6.. :)

Apart from that, there are a lot of niceties in "master", which you'll get on top of this bugfix.

**Comment by blueyed** [comment] 2015-05-18 20:33
But anyway, we should have a new release with this bugfix included, hopefully soon.

**Comment by dlussky** [comment] 2015-05-19 09:20
I am already building https://github.com/achaphiv/ppa-fonts/blob/master/openjdk-fontfix/README.md from time to time, and it takes soooo loooooong
But awesome must be lighter, so maybe building time will be reasonable) I'll try it this weekend)

**Comment by blueyed** [comment] 2015-05-19 14:02
It's a matter of minutes, and then seconds to update it.
