### ISSUE TITLE
Keyboard stops working in Chrome

### ISSUE THREAD

**Issue by kapsh** [awesomeWM/awesome#670] opened 2016-02-05 23:16 UTC
I encountered very strange behavior in interaction of Awesome and Chrome. 
Problem is 100% reproducible on both my systems with this steps: 
1. Launch Chrome. 
2. Open any link from any application. 
3. Link opened in Chrome. 
4. Any keyboard events stops working to Chrome. I can't enter text, I can't do awesome's mod4-j/k/c/etc. 

This isn't occured with other apps. This isn't occured on other WMs or on clean config. This is isn't occured when I remove this rule from rc.lua: `
	{ rule = { class = class_browser },
		properties = { tag = tags[1][2] }
	},`
But it's back when I add this rule to stock config from /etc/xdg/. 

Can anybody confirm this bug or explain me how to find root of the problem?

**Comment by psychon** [comment] 2016-02-06 08:06
Which awesome version? Which version of Chrome? Could you show the `xprop` output for Chrome? And yeah, I agree that this description sounds weird...

**Comment by kapsh** [comment] 2016-02-06 12:40
Ah sorry, I forgot to mention this.
```
awesome v3.5.8 (Major Tom)
 • Build: Jan 31 2016 18:44:19 for x86_64 by gcc version 5.3.0 (root@feline)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
```
```
_NET_WM_USER_TIME(CARDINAL) = 14687746
_NET_WM_DESKTOP(CARDINAL) = 1
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 1, 20
		program specified minimum size: 623 by 61
WM_NAME(UTF8_STRING) = "Keyboard stops working in Chrome · Issue #670 · awesomeWM/awesome - Google Chrome"
_NET_WM_NAME(UTF8_STRING) = "Keyboard stops working in Chrome · Issue #670 · awesomeWM/awesome - Google Chrome"
XdndAware(ATOM) = BITMAP
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x1, 0x0, 0x0
_NET_WM_ICON(CARDINAL) = 	Icon (64 x 64):
// skipped
WM_WINDOW_ROLE(STRING) = "browser"
WM_CLASS(STRING) = "google-chrome", "google-chrome"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 15813
WM_LOCALE_NAME(STRING) = "en_US.utf8"
WM_CLIENT_MACHINE(STRING) = "feline"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING
```

**Comment by maksbotan** [comment] 2016-02-13 21:06
Hi,
I can confirm this issue too, with awesome 3.5.8 and several chrome versions from 48 series.
This is very frustrating and seems to happen not only when opening links from apps. Moreover, I don't have any rules concerning google-chrome in my `rc.lua`.

P.S. Keyboard layout and mouse problem seems not to be solved for me as well. Should I open a new issue?

**Comment by psychon** [comment] 2016-02-14 13:28
All I can say is that I have no problems here with Chromium 47.0.2526.80.

P.S.: You have to decide that yourself. Is it a new problem or a duplicate of some other one? If you want my opinion about this, you'd have to tell me more about the problem you are seeing. But I guess this issue is the wrong place for that.

**Comment by psychon** [comment] 2016-02-14 14:32
Thanks to @maksbotan, I had the following idea: Could someone find the window id of chrome (e.g. `xwininfo` will give that one to you` and use `xev -id 0xTHE_WINDOW_ID` to get events for that window? I recommend to redirect the output of that command into a file. While `xev` is running, please cause the issue (open "a link from any application" and notice that you cannot type in Chrome anymore nor use awesome keybindings on it, I guess) and then you can stop `xev` via `CTRL-C`.

Describe exactly what you did and show me the result from `xev`.

**Comment by maksbotan** [comment] 2016-02-14 14:37
Here you are: https://bpaste.net/show/2d42c64ab09f
The bug was caused by running `google-chrome-stable ya.ru` from console. Please note that clicking on three different links in Quassel before that did not cause the bug.
You can see some key events with Backspace key -- those probably are the last keys that worked.

My chrome version is 48.0.2564.97. Binary chrome, not chromium.

**Comment by psychon** [comment] 2016-02-14 14:43
Hm, that didn't really help, sorry. :(

**Comment by kapsh** [comment] 2016-02-14 15:18
I figured out that when Chrome brokes - its hints are changed to this:
```
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: *False*
```
How can I trace how and from where this hints come from? 
`xprop -spy` shows only this after clicking to url:
```
_NET_WM_NAME(UTF8_STRING) = "Untitled - Google Chrome"
WM_NAME(UTF8_STRING) = "Untitled - Google Chrome"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		The urgency hint bit is set
_NET_WM_STATE(ATOM) = _NET_WM_STATE_DEMANDS_ATTENTION
//etc
```

**Comment by psychon** [comment] 2016-02-14 15:51
Issue is https://code.google.com/p/chromium/issues/detail?id=355034. That was fixed almost a year ago, how come the fix didn't reach the release versions of Chrome yet...?

(If chrome tells us "Clients accepts input or input focus: False", we honor that and don't give the input focus to Chrome. ICCCM requires this behavior from any window manager. I'd suggest you to report this to the Chrome bug tracker and leave a link to your report here.)

**Comment by psychon** [comment] 2016-02-15 17:05
Can you test with a newer version of Chrome? I can't find any use of `InputHint` in Chromium's source code and thus this shouldn't happen in some kind of "latest version": https://code.google.com/p/chromium/codesearch#search/&q=InputHint&sq=package:chromium&type=cs (Something like the code removed in https://src.chromium.org/viewvc/chrome/trunk/src/ui/views/widget/desktop_aura/desktop_window_tree_host_x11.cc?r1=259086&r2=259085&pathrev=259086 is necessary to change the "accepts input" field in `WM_HINTS`, for this the `InputHint` flag is needed)

**Comment by psychon** [comment] 2016-02-15 17:08
Oh and switching to another window and back to chromium should make input work again (assuming that chromium changed its `WM_HINTS` to `Accepts input: True` again; depending on the value of this flag, different things happen when chromium gets the input focus).

**Comment by kapsh** [comment] 2016-02-15 20:44
I've tested with Chrome 50.0.2645 and had same behavior — input brokes after opening link. 
Switching windows doesn't help too (yes, like in #699 — I can't even close broken window).

But I have tested awesome v3.5.2-1137-g8802560-dirty and it's all okay in it! Used this all day and never seen broken input.
And latest strange thing: in awesome from master WM_HINTS from Chrome looks like: `Client accepts input or input focus: True`.

**Comment by psychon** [comment] 2016-02-15 20:51
Can someone test this patch? It should apply against both 3.5 and master (and might actually fix something for 3.5).
```
diff --git a/objects/client.c b/objects/client.c
index fc1b31d..e5fd066 100644
--- a/objects/client.c
+++ b/objects/client.c
@@ -163,22 +163,8 @@ client_set_urgent(lua_State *L, int cidx, bool urgent)
 
     if(c->urgent != urgent)
     {
-        xcb_get_property_cookie_t hints =
-            xcb_icccm_get_wm_hints_unchecked(globalconf.connection, c->window);
-
         c->urgent = urgent;
 
-        /* update ICCCM hints */
-        xcb_icccm_wm_hints_t wmh;
-        xcb_icccm_get_wm_hints_reply(globalconf.connection, hints, &wmh, NULL);
-
-        if(urgent)
-            wmh.flags |= XCB_ICCCM_WM_HINT_X_URGENCY;
-        else
-            wmh.flags &= ~XCB_ICCCM_WM_HINT_X_URGENCY;
-
-        xcb_icccm_set_wm_hints(globalconf.connection, c->window, &wmh);
-
         luaA_object_emit_signal(L, cidx, "property::urgent", 0);
     }
 }
```
P.S.: Chromium is still broken and should be fixed if this fixes anything...

**Comment by mtsmfm** [comment] 2016-02-16 13:24
The problem is solved by applying that patch!

**Comment by psychon** [comment] 2016-02-16 14:31
Ok, in that case it's a race condition.

Awesome (wrongly) wants to update the urgent hint in `WM_NAME` and if it does so at the same time that chromium is updating its `WM_NAME` hint, awesome could overwrite chromiums attempt to accept focus again. The ICCCM standard says (AFAIR) that only the client itself should mess with that hint, so awesome shouldn't touch it.

Still, Chromium should still stop doing this crazy "no input" stuff.

I'll commit the above patch to awesome later (and cherry-pick it (and some other things?) into the 3.5 branch).

**Closed** 2016-02-16 18:35 UTC

**Comment by kapsh** [comment] 2016-02-16 20:49
Thanks man, 3.5.8 with this patch works fine.

**Comment by moepman** [comment] 2016-02-24 12:10
Will there be another 3.5.x release with this fix anytime soon?
