### ISSUE TITLE
CPU usage increases with use and does not return to idle

### ISSUE THREAD

**Issue by caleballen** [awesomeWM/awesome#3523] opened 2021-11-30 11:21 UTC
Output of `awesome --version`:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
1. Open AwesomeWM and record average CPU usage.
2. Use AwesomeWM with applications such as Steam, Discord, MS Teams, things that use the Wibox System Tray.
3. Open and close such applications.
4. Record CPU usage, maybe after about an hour as well.

**Actual result:**
Average CPU thread usage increases from about 2% to 10% or above. Closing all applications does not rectify and CPU usage remains at the high value. If more "usage" (steps 2+3) is done then CPU increases more, I've recorded as high as 70%

**Expected result:**
Average CPU thread usage does not increase substantially. Closing applications returns CPU usage to idle CPU.

**Comments**
I'm using the AwesomeWM available in Arch packages. I'm recording CPU with htop.
I normally do not use external displays, this issue is on a laptop using only the internal display. May also occur with multiple displays.
I suspect Steam is responsible for causing this issue and I think it's the system tray part but it's possible it's unrelated and something else is going on. If I get a chance I'll post my config and do some more digging, perhaps with latest git. If you need any more information let me know.
I'm curious to see if anyone else is getting this.

**Comment by caleballen** [comment] 2021-11-30 11:24
It could perhaps be related to #3373 and #2798

**Comment by actionless** [comment] 2021-11-30 11:42
> If I get a chance I'll post my config

does that means you can't reproduce it with the default config?

**Comment by caleballen** [comment] 2021-11-30 11:49
> > If I get a chance I'll post my config
> 
> does that means you can't reproduce it with the default config?

I haven't tried, I'll test that. My config doesn't do anything spectacular.

**Comment by caleballen** [comment] 2021-11-30 12:59
Apologies, I actually can't replicate it on the default config, while I can reliably on my setup. Is there any way I can inspect awesome's CPU usage to narrow down the cause?
[awesome_config.tar.gz](https://github.com/awesomeWM/awesome/files/7625880/awesome_config.tar.gz)

**Comment by Elv13** [comment] 2021-12-01 10:11
There was some profilers for Lua 5.1 which worked fine. There is probably a few for 5.3 too, but I didn't investigate. Usually, CPU usage is either due to excessive redraw, clients which try to resize themselves in an infinite loop because they hate tiled WMs or from frequent timers.

I will close this issue since it is resolved, but feel free to keep commenting or re-opening if needs be

**Closed by Elv13** 2021-12-01 10:11 UTC
