### ISSUE TITLE
Memory leak with gears.wallpaper

### ISSUE THREAD

**Issue by azazel7** [awesomeWM/awesome#368] opened 2015-07-29 00:24 UTC
It seems that, calling the function *gears.wallpaper.fit* many times will increase the amount of memory used by awesomeWM. As if the previous wallpaper were never freed.

**Comment by blueyed** [comment] 2015-07-29 10:28
Is this with the version from master?

Does it happen for maximised, too?

For reference: https://github.com/awesomeWM/awesome/blob/master/lib/gears/wallpaper.lua#L160

**Comment by psychon** [comment] 2015-07-29 14:46
I assume you are calling `gears.wallpaper.fit` in a loop. Could you also add `collectgarbage("collect")` to that loop?

This could be some large-ish `ImageSurface` that becomes garbage and wasn't collected by the garbage collector yet. If this is done in a loop, many such surfaces could accumulate in memory before the GC collects them.

**Comment by azazel7** [comment] 2015-08-03 07:19
It does the same with *gears.wallpaper.maximised*.
As I'm using archlinux repository, I think I'm really close to master.

Using *collectgarbage* doesn't change anything.

For the moment, it's not in a loop. I use a shortcut so I can change my wallpaper whenever I want without restarting *awesome*.

**Comment by psychon** [comment] 2015-08-03 08:21
I can't really find anything. The following code has a slight increase in memory usage (RES in top) from 20.something to 21.7 MiB, but I'm not sure what to make from that:

```
local wallpaper = require("gears.wallpaper")
local png = "/usr/share/icons/gnome/16x16/apps/wallpaper.png"
for i=1, 10000 do
	wallpaper.maximized(png)

	i = i + 1
	if i % 1000 == 0 then
		print(i)
	end
	collectgarbage("collect")
end
awesome.exit()
```
(I know that `awesome.exit()` should be `awesome.quit()`, but the above is what I actually measured. Whoops.)

Checking with `valgrind --tool=massif`, there might indeed be a small leak which I cannot figure out right now, but since I set the wallpaper 10k times with the above, that's not much memory and might just because valgrind took a snapshot while a wallpaper was being set:
```
90.74% (13,256,252B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->64.75% (9,458,392B) 0x3F84E4F7DF: g_try_malloc (in /usr/lib64/libglib-2.0.so.0.4400.1)
| ->64.60% (9,437,184B) 0x3F92A082A4: gdk_pixbuf_new (in /usr/lib64/libgdk_pixbuf-2.0.so.0.3100.4)
| | ->64.60% (9,437,184B) 0x3F92A1B36A: ??? (in /usr/lib64/libgdk_pixbuf-2.0.so.0.3100.4)
| |   ->64.60% (9,437,184B) 0x3F92A0CBC8: gdk_pixbuf_new_from_file (in /usr/lib64/libgdk_pixbuf-2.0.so.0.3100.4)
| |     ->64.60% (9,437,184B) 0x411010: draw_load_image (in /usr/bin/awesome)
[...]
| |                           
| ->00.15% (21,208B) in 1+ places, all below ms_print's threshold (01.00%)
| 
->14.07% (2,054,847B) 0x3F9CC19070: ??? (in /usr/lib64/liblua-5.3.so)
| ->06.09% (890,189B) 0x3F9CC1512C: ??? (in /usr/lib64/liblua-5.3.so)
| | ->01.74% (254,634B) 0x3F9CC1FAAF: ??? (in /usr/lib64/liblua-5.3.so)
| | | ->01.74% (254,634B) 0x3F9CC09BC8: lua_newuserdata (in /usr/lib64/liblua-5.3.so)
| | |   ->01.30% (190,280B) 0xBEFB036: ??? (in /usr/lib64/lua/5.3/lgi/corelgilua51.so)
| | |   | ->01.30% (190,280B) in 2 places, all below massif's threshold (01.00%)
| | |   |   
| | |   ->00.44% (64,354B) in 1+ places, all below ms_print's threshold (01.00%)
| | |   
| | ->01.69% (246,552B) in 4 places, all below massif's threshold (01.00%)
| | | 
| | ->01.57% (229,128B) 0x3F9CC1F984: ??? (in /usr/lib64/liblua-5.3.so)
| | | ->01.57% (229,128B) in 15 places, all below massif's threshold (01.00%)
| | |   
| | ->01.09% (159,875B) 0x3F9CC1F8B8: ??? (in /usr/lib64/liblua-5.3.so)
| |   ->01.09% (159,875B) in 6 places, all below massif's threshold (01.00%)
| |     
| ->04.27% (623,922B) in 19 places, all below massif's threshold (01.00%)
| | 
| ->03.70% (540,736B) 0x3F9CC239E0: ??? (in /usr/lib64/liblua-5.3.so)
|   ->03.49% (509,824B) 0x3F9CC23ED4: ??? (in /usr/lib64/liblua-5.3.so)
|   | ->02.14% (313,344B) 0x3F9CC173E5: ??? (in /usr/lib64/liblua-5.3.so)
|   | | ->01.51% (221,184B) 0x3F9CC17F1F: ??? (in /usr/lib64/liblua-5.3.so)
|   | | | ->01.51% (221,184B) 0x3F9CC1838B: ??? (in /usr/lib64/liblua-5.3.so)
|   | | |   ->01.51% (221,184B) in 29 places, all below massif's threshold (01.00%)
|   | | |     
|   | | ->00.63% (92,160B) in 1+ places, all below ms_print's threshold (01.00%)
|   | | 
|   | ->01.11% (162,304B) 0x3F9CC26AA6: ??? (in /usr/lib64/liblua-5.3.so)
|   | | ->01.11% (162,304B) in 5 places, all below massif's threshold (01.00%)
|   | |   
|   | ->00.23% (34,176B) in 1+ places, all below ms_print's threshold (01.00%)
|   | 
|   ->00.21% (30,912B) in 1+ places, all below ms_print's threshold (01.00%)
|   
->04.99% (729,480B) 0x3F8620C4EA: ??? (in /usr/lib64/libxcb.so.1.1.0)
| ->04.99% (729,480B) 0x3F8620A3EF: ??? (in /usr/lib64/libxcb.so.1.1.0)
|   ->04.88% (712,912B) 0x3F8620A83B: ??? (in /usr/lib64/libxcb.so.1.1.0)
|   | ->04.88% (712,912B) 0x3F8620AF75: ??? (in /usr/lib64/libxcb.so.1.1.0)
|   |   ->04.88% (712,912B) 0x3F8620BAA1: ??? (in /usr/lib64/libxcb.so.1.1.0)
|   |     ->04.88% (712,912B) 0x3F8620BB1F: xcb_wait_for_reply (in /usr/lib64/libxcb.so.1.1.0)
|   |       ->04.88% (712,840B) 0x4200B0: ??? (in /usr/bin/awesome)
|   |       | ->04.88% (712,840B) 0x3F9CC1235E: ??? (in /usr/lib64/liblua-5.3.so)
[...]
|   |       |                   
|   |       ->00.00% (72B) in 1+ places, all below ms_print's threshold (01.00%)
|   |       
|   ->00.11% (16,568B) in 1+ places, all below ms_print's threshold (01.00%)
|   
->04.75% (693,357B) in 248 places, all below massif's threshold (01.00%)
| 
->02.19% (320,176B) 0x3F8620C649: ??? (in /usr/lib64/libxcb.so.1.1.0)
  ->02.19% (320,176B) 0x3F8620A3EF: ??? (in /usr/lib64/libxcb.so.1.1.0)
    ->02.17% (316,832B) 0x3F8620A83B: ??? (in /usr/lib64/libxcb.so.1.1.0)
    | ->02.17% (316,832B) 0x3F8620AF75: ??? (in /usr/lib64/libxcb.so.1.1.0)
    |   ->02.17% (316,832B) 0x3F8620BAA1: ??? (in /usr/lib64/libxcb.so.1.1.0)
    |     ->02.17% (316,832B) 0x3F8620BB1F: xcb_wait_for_reply (in /usr/lib64/libxcb.so.1.1.0)
    |       ->02.17% (316,800B) 0x4200B0: ??? (in /usr/bin/awesome)
    |       | ->02.17% (316,800B) 0x3F9CC1235E: ??? (in /usr/lib64/liblua-5.3.so)
[...]
    |       |                   
    |       ->00.00% (32B) in 1+ places, all below ms_print's threshold (01.00%)
    |       
    ->00.02% (3,344B) in 1+ places, all below ms_print's threshold (01.00%)
```

**Comment by azazel7** [comment] 2015-08-03 22:31
After a quick look, it turn out that  if the same wallpaper is used, it doesn't increase the memory much.
Here is the exact lua code I use.

```
function scandir(directory)
    local i, t, file = 0, {}, io.popen('ls "'..directory..'"')
    for filename in file:lines() do
        i = i + 1 
        t[i] = directory..filename
    end 
    t[0] = i 
    file:close()
    return t
end
function change_wallpaper()
    beautiful.wallpaper = scandir(directory_walllpaper)
    for s = 1, screen.count() do
        local index_wallpaper = math.random(1, beautiful.wallpaper[0])
        --gears.wallpaper.fit("/home/magoa/images/wallpaper-94972.jpg", s)
        gears.wallpaper.fit(beautiful.wallpaper[index_wallpaper], s)
        collectgarbage("collect")
    end 
end
```
And the shortcut:
```
 awful.key({ modkey }, "q",
    function ()
        change_wallpaper()
    end),
```

After a hundred call of the shortcut, it increase the memory by 50MiB.

**Comment by psychon** [comment] 2015-08-04 09:04
rc.lua:
```lua
local surface = require("gears.surface")
local wp = require("gears.wallpaper")
local path = "/usr/share/backgrounds/images/default-16_10.png"
local limit = 1000
os.execute("mkdir -p /tmp/tmp ; cd /tmp/tmp ; for i in $(seq 1 " .. tostring(limit) .. ") ; do rm -f ${i}.png ; ln -s '" .. path .. "' ${i}.png ; done")
function run()
	for i=1, limit do
		wp.fit("/tmp/tmp/" .. i .. ".png")
		collectgarbage("collect")
	end
	collectgarbage("collect")
	print("done")
end
local t = timer({ timeout = 0 })
t:connect_signal("timeout", function()
	run()
	awesome.quit()
end)
t:start()
```
Memory usage according to `valgrind --tool=massif`:
```
    MB
17.55^#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#:::::::::::::::::::: : :: :  :::::::::::::::::::: ::::::::@      :: :@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : : : :::: :@      :  :@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : ::: :::: :@:::@::: ::@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : : : :::: :@: :@: : ::@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : : : :::: :@: :@: : ::@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : : : :::: :@: :@: : ::@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : : : :::: :@: :@: : ::@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : : : :::: :@: :@: : ::@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : : : :::: :@: :@: : ::@:
     |#: : : ::: :: : :: :  : :  :  :: :: :: ::: ::: : : : :::: :@: :@: : ::@:
     |#: : : ::: :: : :: : @::: :::::: :: :: ::: ::: : : : :::: :@: :@: : ::@:
   0 +----------------------------------------------------------------------->Gi
     0                                                                   455.0
```
So memory usage is pretty much constant over time.

Sorry, I guess I'm out of ideas.

**Comment by blueyed** [comment] 2015-08-04 10:22
@psychon 
Maybe the size of the images is important?
It seems like you have used small images when trying to reproduce it?
Can you provide the valgrind command, so we / @azazel7 could try to reproduce it this way?
Maybe there's something fixed it master, which is not fixed in Arch's repos (which is 3.5.6 I guess?!).

**Comment by psychon** [comment] 2015-08-04 11:35
I'm running 3.5.6, not master (sorry for not mentioning this earlier, but I doubt it matters much).

The command is `valgrind --tool=massif awesome`. This leaves behind a file called "massif.out.$PID" which you can look at with `ms_print massif.out.*`. This produces lots of output, beginning with the memory usage graph I showed in my last reply. The bar of `#` represents the peak memory usage, the `@` are snapshots. For each such snapshot a details description on where the memory was allocated follows.

You can also run awesome under valgrind, but the output file is only produced when awesome quits. So you'd have to set the wallpaper often and then stop awesome. This is why the "config file" I used is so minimal and quits awesome when it's done. Oh and it's best to have lots of `collectgarbage("collect")` even though this slows things down, because the memory usage graph naturally also includes garbage that wasn't collected yet.

**Comment by blueyed** [comment] 2015-08-04 15:18
@psychon 
> @blueyed Why is this a small wallpaper?  This is Fedora's default wallpaper with an aspect ratio of 16:10.

Sorry, misinterpreted the name, also from the previously used one (`/usr/share/icons/gnome/16x16/apps/wallpaper.png`).

**Comment by psychon** [comment] 2015-09-21 14:40
Here is another attempt (the theory was that the wibox had to be redrawn for the leak to actually occur. Nope):
```lua
dofile("/etc/xdg/awesome/rc.lua")
collectgarbage("collect")

local wp = require("gears.wallpaper")
local path = "/usr/share/backgrounds/images/default-16_10.png"
local limit = 1000
os.execute("mkdir -p /tmp/tmp ; cd /tmp/tmp ; for i in $(seq 1 " .. tostring(limit) .. ") ; do rm -f ${i}.png ; ln -s '" .. path .. "' ${i}.png ; done")
local count = 0
local t = timer({ timeout = 0.001 })
t:connect_signal("timeout", function()
    if count < limit then
        count = count + 1
        run()
    else
        awesome.quit()
    end
end)
function run()
    local i = count
    wp.fit("/tmp/tmp/" .. i .. ".png")
    collectgarbage("collect")
    if i % 10 == 0 then
        print(i * 100 / limit)
    end
end
t:start()
```
`valgrind --tool=massif awesome` tracked the following memory usage:
```
    MB
24.72^#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#:   ::@::  ::::::::::::::@@:::::::@::::@:::::::::@@:::::::::::::::@::@:
     |#    : @:   : :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
     |# :  : @: ::: :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
     |# :  : @: : : :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
     |# :  : @: : : :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
     |# :  : @: : : :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
     |# :  : @: : : :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
     |# :::: @: : : :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
     |# :: : @: : : :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
     |# :: : @: : : :: ::: :: ::@ : ::: :@:: :@: :: :: :@ ::: :: : : ::: @::@:
   0 +----------------------------------------------------------------------->Gi
     0                                                                   494.0
```
(This was again tested with awesome 3.5.6)
(And by the way, this peak right after startup is weird)

**Comment by psychon** [comment] 2016-02-06 15:36
Here is another attempt at reproducing this (just dump this into the default config, it will set a new wallpaper every 0.1 seconds from the configured directory):
```lua
local function scandir(directory)
    local i, t, file = 0, {}, io.popen('ls "'..directory..'"')
    for filename in file:lines() do
        i = i + 1 
        t[i] = directory..filename
    end 
    t[0] = i 
    file:close()
    return t
end
local function print_status()
	local f = io.open("/proc/self/status", "rb")
	print(f:read("*all"))
	f:close()
end
local wallpapers = scandir("/home/psychon/Wallpaper/")
print("Found " .. tostring(#wallpapers) .. " wallpapers")
print("Current memory usage:")
print_status()
local t = timer({ timeout = 0.1 })
t:connect_signal("timeout", function()
	collectgarbage("collect")
	if #wallpapers == 0 then
		print("Done, memory usage:")
		print_status()
		t:stop()
	else
		gears.wallpaper.fit(wallpapers[1])
		table.remove(wallpapers, 1)
	end
end)
t:start()
```
I have a couple of wallpapers laying around and I get the following output (trimmed to only contain the memory info):
```
Found 146 wallpapers
Current memory usage:
VmPeak:	  258536 kB
VmSize:	  227864 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   30996 kB
VmRSS:	   20764 kB
VmData:	   81196 kB
VmStk:	     136 kB
VmExe:	     320 kB
VmLib:	   15252 kB
VmPTE:	     328 kB
VmPMD:	      12 kB
VmSwap:	       0 kB

Done, memory usage:
VmPeak:	  451960 kB
VmSize:	  309212 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	  211088 kB
VmRSS:	   68372 kB
VmData:	  123224 kB
VmStk:	     136 kB
VmExe:	     320 kB
VmLib:	   15648 kB
VmPTE:	     448 kB
VmPMD:	      12 kB
VmSwap:	       0 kB
```
As you can see, there is not much of a change in memory usage. However, If I leave out the call to `collectgarbage("collect")`, the OOM killer stops the experiment. Lua doesn't know about the real size of these images and thus its garbage collector is too "nice" to them and doesn't collect them fast enough.

@azazel7 Are you still seeing this? Could you perhaps also try this patch? https://gist.github.com/psychon/c91bef5c37c9560e6431 It doesn't really help much here, but at least with it things also survive without the `collectgarbage("collect")` (put VmPeak ends up at 700MiB, about twice of the above value)

**Comment by psychon** [comment] 2016-03-04 08:55
Forget the patch I mentioned above. Could you try latest master? Specifically, something containing https://github.com/awesomeWM/awesome/pull/716.

**Closed** 2016-07-04 15:02 UTC
Labels: need info

**Comment by psychon** [comment] 2016-07-09 09:19
@azazel7 Are you perhaps using LuaJIT? I only tested with Lua. That might explain why I couldn't reproduce this.
