### ISSUE TITLE
Clarify timer API docs

### ISSUE THREAD

**Issue by RenaKunisaki** [awesomeWM/awesome#216] opened 2015-05-04 19:06 UTC
Demonstrated with a modified default rc.lua. Not sure if the issue is with the widget or the timer, but they're managing to linger around after the widget is replaced:

	$ 	diff -C3 rc-default.lua rc-test.lua 
	*** rc-default.lua	2015-04-25 00:56:57.254431414 -0400
	--- rc-test.lua	2015-05-04 15:02:21.364508406 -0400
	***************
	*** 112,117 ****
	--- 112,133 ----
	  -- Create a textclock widget
	  mytextclock = awful.widget.textclock()
	  
	+ 
	+ do
	+ 	myTestWidget = wibox.layout.fixed.horizontal()
	+ 	local myTextbox    = wibox.widget.textbox()
	+ 	myTestWidget:add(myTextbox)
	+ 	local myTimer = timer { timeout = 1 }
	+ 	local ticks = 0
	+ 	myTimer:connect_signal('timeout', function()
	+ 		ticks = ticks + 1
	+ 		print("tick", ticks)
	+ 		myTextbox:set_text(ticks)
	+ 	end)
	+ 	myTimer:start()
	+ end
	+ 
	+ 
	  -- Create a wibox for each screen and add it
	  mywibox = {}
	  mypromptbox = {}
	***************
	*** 187,192 ****
	--- 203,211 ----
		  left_layout:add(mylauncher)
		  left_layout:add(mytaglist[s])
		  left_layout:add(mypromptbox[s])
	+ 	if s == 1 then
	+ 		left_layout:add(myTestWidget)
	+ 	end
	  
		  -- Widgets that are aligned to the right
		  local right_layout = wibox.layout.fixed.horizontal()
	***************
	*** 201,206 ****
	--- 220,230 ----
		  layout:set_right(right_layout)
	  
		  mywibox[s]:set_widget(layout)
	+ 
	+ 
	+ 	--now replace that layout
	+ 	local newLayout = wibox.layout.align.horizontal()
	+ 	mywibox[s]:set_widget(layout)
	  end
	  -- }}}

This script creates a textbox and a timer, and has the timer update the textbox and also print a message to stdout. It adds the textbox to the left screen wibox but then replaces the contents of that wibox, so that textbox is no longer visible. It's only referenced by the previous layout which is no longer used and so should be collected. However you can see the timer will continue to tick long afterward...

**Comment by psychon** [comment] 2015-05-04 19:45
Well, sorry, but active timers are never garbage collected. When you `:start()` it, the C code adds a reference to it to prevent exactly this.

If you want to work around this (cheap hack): Use a weak table to save a reference to the widget. Stop the timer when the reference disappears.

Sorry.

**Comment by RenaKunisaki** [comment] 2015-05-04 22:09
OK. Maybe the docs should be updated to reflect that?

**Comment by psychon** [comment] 2015-05-05 05:20
What exactly would you think of? Right now the docs say "Timer objects. This type of object is useful when triggering events repeatedly. THe timer will emit the 'timeout' signal every N seconds, N being the timeout value."

**Comment by RenaKunisaki** [comment] 2015-05-05 05:51
"Note that a running timer will not be collected by Lua's garbage collector; use timer:stop() to allow the timer to be collected." or some such.

The way it is now, seems it's possible to lose a timer object, such that the only reference left is the one that keeps it going, so if you neglect to stop it when you're done with it, it's just leaked and wasting memory.

**Comment by RenaKunisaki** [comment] 2015-05-09 22:06
I think the timer documentation is a separate issue. Consider [this widget](http://pastebin.com/M04rSXy1), which uses a timer, but shuts it down when the widget is garbage collected. In order to allow reloading the wibox config without restarting Awesome, I use [this setup](http://pastebin.com/GXKuwiRy); then calling `reloadWibox()` re-creates the wibox for the screen.

In particular, this script creates a new layout box (`myLayout = wibox.layout.align.horizontal()`) and assigns it as the wibox's widget, replacing the previous one if any (`myWibox:set_widget(myLayout)`). This means the previous layout box is no longer used and should be collected; however, the textwidget's `__gc` method isn't called until Awesome exits, which suggests that it (and by extension, probably the old layout box) isn't collected when the layout box is replaced, even though it's not used anywhere.

**Comment by psychon** [comment] 2015-06-13 10:09
Note that you cannot use `__gc` from lua. It is only available to C code. You can try with something like this in the lua prompt:

    print(setmetatable({}, { __gc = function() print("gc") end }))
    print(collectgarbage("collect"))

**Comment by RenaKunisaki** [comment] 2015-06-13 20:04
Unless Awesome has changed something, that's [no longer true in 5.2](http://lua.org/manual/5.2/manual.html#2.5.1). It works for me in the interpreter as well:

```
$ lua5.2
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> print(setmetatable({}, { __gc = function() print("gc") end }))
table: 0x8494a0
> print(collectgarbage("collect"))
gc
0
> 
```

At least on my system Awesome is using Lua 5.2. Is that not normal?

**Comment by blueyed** [comment] 2015-07-23 23:26
I can confirm what @RenaKunisaki said.

Would it be feasible to stop a timer automatically, if the timer object is garbage collected? (not really knowing when this happens).  But after `t = nil`, the associated timer should be stopped also?!

**Comment by psychon** [comment] 2015-07-25 11:59
And what if I want a timer that never stops and don't have a good place to save a reference to it? Also, the timer would run for some "random" amount of time and then suddenly stop when the GC collects it? That'd be weird. Imagine a timer that calls `print("tick")`.

If you really want a garbage-collectable timer:
```
local create_gc_timer_mt = { __mode = "kv" }
function create_gc_timer_mt:__gc()
    local t = self._timer
    if t then t:stop() end
end
function create_gc_timer_mt:__index(key)
    return self._timer[key] -- Note: Throws an error if timer was GC'd
end
function create_gc_timer_mt:__newindex(key, value)
    self._timer[key] = value -- Note: Throws an error if timer was GC'd
end
function create_gc_timer(...)
    local result = setmetatable({}, create_gc_timer_mt)
    result._timer = timer(...)
    return result
end
```
(Yes, this does not work in lua 5.1. Sorry that I missed that change.)

**Comment by blueyed** [comment] 2015-07-25 13:15
> Also, the timer would run for some "random" amount of time and then suddenly stop when the GC collects it? That'd be weird

Noticed that, too. Agreed.

> If you really want a garbage-collectable timer:

Could/should `gears.timer` provide a helper method for this?

**Comment by psychon** [comment] 2015-07-25 13:29
Hm... `:weak_connect_signal` already solves have of this. How about a new argument `weak_disconnect_callback` to this function that is called when the signal connection goes/went away? It could be used to stop the timer once the callback function gets garbage collected.
(And yes, I agree that this makes a terrible API for users. To work around this, we'd need some function in `gears.timer` for setting up a timer without directly creating an object, I guess.)

**Comment by blueyed** [comment] 2015-07-25 13:57
> How about a new argument weak_disconnect_callback to this function that is called when the signal connection goes/went away?

:+1:

> terrible API for users … To work around this, we'd need some function in gears.timer for setting up a timer without directly creating an object, I guess.

Makes sense.

This reminds me of a local patch where I added this for the common case:

     --- Create a new timer object.
     -- @tparam table args Arguments.
     -- @tparam number args.timeout Timeout in seconds (e.g. 1.5).
    +-- @tparam[opt] function cb Callback, which automatically gets setup to be
    +--   called on the `timeout` signal.  The timer is automatically started in
    +--   this case.
     -- @treturn timer
    -timer.new = function(args)
    +timer.new = function(args, cb)
         local ret = object()
     
         ret:add_signal("property::timeout")
    @@ -100,14 +119,26 @@ timer.new = function(args)
             ret[k] = v
         end
     
    +    if cb then
    +        ret:connect_signal("timeout", cb)
    +        ret:start()
    +    end
    +
         return ret
     end

**Comment by psychon** [comment] 2015-07-25 14:47
If you really want that feature, we should turn this into a PR: https://gist.github.com/psychon/5e09f11d5d4a76c6ff39
(And perhaps also add `gears.timer.create(timeout, func)` and `gears.timer.weak_create(timeout, func)` in the same PR.)

**Comment by blueyed** [comment] 2015-07-25 16:48
Makes sense to me.
Will you do this?

**Comment by psychon** [comment] 2015-08-11 11:33
Done in https://github.com/awesomeWM/awesome/pull/401. Note that I decided in the end against adding something special to `gears.object` for this, because this might leave us with complicated interactions with the garbage collector if this were over-used. Perhaps it is really better to have special cases for this where needed.

**Comment by psychon** [comment] 2015-10-17 14:56
Fixed in various parts. Use `gears.timer.weak_start_new` to have the timer GC'able.

**Closed by psychon** 2015-10-17 14:56 UTC
Labels: enhancement
