### ISSUE TITLE
awful.keygrabber:add_keybinding(key) is causing "bad argument #1 to 'insert' (table expected, got nil)"

### ISSUE THREAD

**Issue by raven2cz** [awesomeWM/awesome#3608] opened 2022-04-17 12:04 UTC
Output of `awesome --version`:

awesome v4.3-1360-gc539e0e43

**How to reproduce the issue:**
```lua
local exit_screen_grabber

local function exit_screen_hide()
    exit_screen_grabber:stop()
    --exit_screen.visible = false
end
local function exit_screen_show()
    exit_screen_grabber:start()
    --exit_screen.visible = true
end

exit_screen_grabber = awful.keygrabber {
    keybindings = {
        awful.key({ key = 'Escape', modifiers = {},
                    on_press = exit_screen_hide}),
        awful.key({ key = 'q', modifiers = {},
                    on_press = exit_screen_hide})
    },
}

exit_screen_grabber:add_keybinding(
    awful.key({ key = 'x', modifiers = {}, on_press = exit_screen_hide})
)
```

**Actual result:**
Caused exception:
`/usr/share/awesome/lib/awful/keygrabber.lua:682: bad argument #1 to 'insert' (table expected, got nil)`

in keygrabber.lua row
`table.insert(self._private.keybindings[_keycode], key)`

**Expected result:**

The awful.key will be added to the exit_screen_grabber instance.

**Comment by Aire-One** [comment] 2022-04-17 17:34
Hello @raven2cz, 

Thank you for the error report. It looks like a duplicate of https://github.com/awesomeWM/awesome/issues/3567, so I'm closing this issue.

**Closed** 2022-04-17 17:34 UTC
Labels: duplicate
