### ISSUE TITLE
Debugging long and increasing main loop iteration freezes

### ISSUE THREAD

**Issue by tormoder** [awesomeWM/awesome#2191] opened 2018-02-12 20:45 UTC
Output of `awesome --version`:

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

Widget library: https://github.com/Mic92/vicious @ commit a81435e.
Config: https://bitbucket.org/tormoder/awesome/src
Distribution: Arch Linux

I'm sorry if this is not the right place to ask, but I could need some help debugging an issue where awesome after some time freezes sporadically with several main loop duration warnings printed to `stderr`, e.g.:

```
2018-01-23 09:58:48 W: awesome: a_glib_poll:432: Last main loop iteration took 14.416777 seconds! Increasing limit for this warning to that value.
2018-01-23 10:02:52 W: awesome: a_glib_poll:432: Last main loop iteration took 18.157562 seconds! Increasing limit for this warning to that value.
2018-01-23 10:07:06 W: awesome: a_glib_poll:432: Last main loop iteration took 32.075336 seconds! Increasing limit for this warning to that value.
2018-01-23 10:12:22 W: awesome: a_glib_poll:432: Last main loop iteration took 35.990005 seconds! Increasing limit for this warning to that value.
2018-01-23 10:33:01 W: awesome: a_glib_poll:432: Last main loop iteration took 55.814686 seconds! Increasing limit for this warning to that value.
```

I have used an almost similar config (only small machine specific adjustments to the widgets) on two other machines (Macbook Air and an Intel desktop) without any issues. This issue happens on a Macbook Pro 15" (2017). The issue happens regardless of whether an external monitor is connected. I would appreciate any tips on where to start looking.

**Comment by Elv13** [comment] 2018-02-12 21:32
You can use `strace` to find what the hell vicious is calling. In any case, the bug is on their side. No synchronous I/O operations should **ever** be done from Awesome main thread. It **will** freeze like this. If the issue is due to a "VFS file" in `/proc/` or `/sys`, those are potentially very high latency I/O access and are not guaranteed to be fast (some of these need to poll slow hardware interfaces). 

The `GIO` async API should always be used for files and `awful.spawn.easy_async` for commands. Module that do not comply with this guidelines are *expected* to cause this kind of issue. `vicious` predates the Awesome `GIO` "hard" dependency and the development is not as active as it was in 2008-2011. However at some point, they will need to complete is async port.

I have a MBP and had this issue. In my case it was due to a latency bug when reading the battery info. I "fixed" the issue this way https://github.com/Elv13/awesome-configs/blob/master/widgets/battery.lua

In any case, I will close this as it is most probably not an AwesomeWM issue.

As for your `rc.lua`. Is it up-to-date? It currently doesn't see to use vicious at all. Does it means the issue happen by importing the module alone?

**Closed by Elv13** 2018-02-12 21:32 UTC

**Comment by psychon** [comment] 2018-02-13 08:18
> I'm sorry if this is not the right place to ask,

No problem, this is the right place to ask. Also, don't worry about this being closed, you can still ask questions here. This just means that there is (likely) nothing that needs to be fixed in awesome itself.

@Elv13 `rc.lua` loads `widgets.lua` and that one in turn uses the following widgets from vicious, which in turn do the following things (assuming linux):
- thermal, reads `/sys/class/thermal/thermal_zone1/temp`
- mem, reads `/proc/meminfo`
- net, reads `/proc/net/dev`
- volume, starts & reads the output of `amixer -M get Master`
- batwidget, reads various files in `/sys/class/power_supply/BAT0`

>  I would appreciate any tips on where to start looking.

Since the working theory seems to be "this is due to vicious", I would start by temporarily disabling all vicious widgets. If this makes the problem go away (how can one be sure? I don't know), you can re-enable widgets one at a time to figure out which one causes this.
From the list above, the most likely reason IMO would be that `amixer -M get Master` takes so long, but even that doesn't seem convincing to me.

If you have a second computer and ssh set up, you could ssh to your working computer and run `pstree -p $(pidof awesome)` and `lsof -c awesome` while awesome is frozen. The first command prints all child processes of awesome, so if `amixer` shows up here, then it's `amixer` being slow. The second command prints a list of opened or mapped files by awesome. Hopefully this provides more useful information than `strace`ing awesome (which just produces way too much output and also produces output when there is currently no problem).

**Comment by tormoder** [comment] 2018-02-13 09:31
@Elv13, @psychon: Thank you very much.

I have currently disabled all vicious widgets, and so far everything is working fine.

I will try to reenable the widgets one-by-one as you suggested, and try your `ssh`/`pstree` tips when I have time.
