### ISSUE TITLE
Window resize is slow

### ISSUE THREAD

**Issue by Alvarocz** [awesomeWM/awesome#1213] opened 2016-11-07 20:23 UTC
Output of `awesome --version`:

_REPLACE with full version output_

**How to reproduce the issue:**

_REPLACE with step-by-step instructions on what to do_

**Actual result:**

_REPLACE with what happened_

**Expected result:**

_REPLACE with what should happen_

**Comment by blueyed** [comment] 2016-11-08 00:14
Duplicate of #1209 ?

**Comment by Elv13** [comment] 2016-11-08 00:22
@Alvarocz please correctly fill the bug report with enough information to be useful. In this case none was provided at all. So it may indeed be a duplicate of #1209 or FS#something (there was a bug for this filled in the days after 3.5.0 was released). I am closing this.

**Closed by Elv13** 2016-11-08 00:22 UTC

**Comment by Alvarocz** [comment] 2016-11-08 00:36
Sorry, i had an old version
