### ISSUE TITLE
infinite loop sometimes using keybind to clear notifications via naughty.destroy_all_notifications

### ISSUE THREAD

**Issue by dtzWill** [awesomeWM/awesome#2692] opened 2019-02-22 07:09 UTC
Output of `awesome --version`:

```
$ awesome --version
awesome 4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

FWIW this is with git and has been happening after recent-ish changes in past week or two.
Haven't chased it down yet, likely result of naughty rework?

**How to reproduce the issue:**

With the following in my rc.lua at the expected location for keybinds:
```
    awful.key({ modkey, }, "\\", naughty.destroy_all_notifications,                                                                                         
              {description = "clear notifications", group = "awesome"})
```

Sometimes using this keybind causes awesome to appear to hang,
with some basic htop/gdb inspection showing an infinite loop.

Unfortunately my lua-fu is weak but perhaps this doesn't quite work right after the change to notification destruction?

https://github.com/awesomeWM/awesome/blob/master/lib/naughty/core.lua#L289

Anyway if someone can take a look to see if there's anything obviously overlooked hopefully that's all there is to it.  Otherwise in the next few days I can try to chase down the introducing commit and perhaps more useful details about where things go wrong.

**Actual result:**

infinite loop

**Expected result:**

no hang or infinite loop

-----

May be duplicate of https://github.com/awesomeWM/awesome/issues/2138 but I'm not sure so filing new to avoid cluttering potentially unrelated ;).

**Comment by elenapan** [comment] 2019-02-22 13:13
After the commit that broke `replaces_id` (check issue #2678) I've been having the same issue whenever I try to dismiss notifications created with the following option of [notify-send.sh](https://github.com/vlevit/notify-send.sh):
` -R, --replace-file=FILE           Store and load notification replace ID to/from this file.`

Notifications created without this option or created with `naughty` seem to work fine.

```
awesome v4.3-97-g36d7535c (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by Elv13** [comment] 2019-02-22 16:26
I have zero time today and deadlines to deal with on other projects. However I spent some time improving https://github.com/awesomeWM/awesome/pull/2689, so at least that should help. But not for this issue, zombie notifications (destroyed, but kept alive by updates from dbus) are not explicitly handled right now, so their behavior is undefined. This has to be fixed. The road to #1874 is in its bumpy-est  stage.

**Comment by actionless** [comment] 2019-03-06 05:08
i can reproduce it only with google chrome and rocketchat (electron-based app), and the only thing i've got is this warning message:

```
2019-03-06 04:35:05 W: awesome: Trying to destroy the same notification twice. It was destroyed because: 1
```

**Comment by actionless** [comment] 2019-03-06 05:13
i remember last time i was having 1/100 problem with google chrome and rocketchat notifications because the pixmap wasn't copied by naughty and chrome was destroying while awesome was trying to use it

so i am wondering if it could be something similar, ie related to some of notification data being destroyed in chrome before copied by awesome?

**Comment by actionless** [comment] 2019-03-06 05:21
@Elv13  just removing this line should be enough to fix it, isn't it?

https://github.com/awesomeWM/awesome/blob/master/lib/naughty/notification.lua#L249

**Comment by psychon** [comment] 2019-03-06 17:44
>  because the pixmap wasn't copied by naughty and chrome was destroying it while awesome was trying to use it

What pixmap are you talking about? Notifications work via DBus. You cannot delete a part of a DBus message after it was sent?!?

> @Elv13 just removing this line should be enough to fix it, isn't it?
>
> https://github.com/awesomeWM/awesome/blob/master/lib/naughty/notification.lua#L249

What makes you think so? Now you destroy a notification twice, which means lots of code runs in a state it is not expected to run and lots of stuff will likely go wrong. This is similar to closing a file handle twice: It makes no sense...?

**Comment by actionless** [comment] 2019-03-06 18:22
> What pixmap

sorry, i meant surface: https://github.com/awesomeWM/awesome/pull/2362

> What makes you think so

i've amended to that message more after sending it

**Closed** 2019-03-18 18:03 UTC
