### ISSUE TITLE
'make package' in Git master generates (deb) package with wrong version number

### ISSUE THREAD

**Issue by madduck** [awesomeWM/awesome#1076] opened 2016-09-09 08:57 UTC
If I run make package from Git master HEAD right now, I get a package made with version number:

    3.5.2~git1965-g587cc53

This can't be right, as 3.5.9 is current. If the next major release is 3.6, I suggest to use

    3.6~git1965-g587cc53

Or if you want to base this on the last stable, use '+' instead:

    3.5.9+git1965-g587cc53

**Comment by blueyed** [comment] 2016-09-09 09:05
Duplicate of https://github.com/awesomeWM/awesome/issues/1047.

**Closed by blueyed** 2016-09-09 09:05 UTC

**Comment by madduck** [comment] 2016-09-09 09:11
Sorry that I missed this.
