### ISSUE TITLE
Chrome cannot talk to naughty, causing a 25 second DBUS communication timeout

### ISSUE THREAD

**Issue by 0jrp0** [awesomeWM/awesome#3552] opened 2022-01-21 17:26 UTC
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

Running on mixture of Debian Stable/Testing. Also, I'm using chrome-remote-desktop from a ChromeOS device to run awesome on the debian linux box.

```
$ loginctl show-session $XDG_SESSION_ID
Id=c1
User=15255
Name=jrp
Timestamp=Sat 2022-01-15 20:27:40 PST
TimestampMonotonic=2388141753
VTNr=0
TTY=chrome-remote-desktop
Remote=no
Service=chrome-remote-desktop
Scope=session-c1.scope
Leader=1369
Audit=4294967295
Type=x11
Class=user
Active=yes
State=active
IdleHint=no
IdleSinceHint=0
IdleSinceHintMonotonic=0
LockedHint=no
```

**How to reproduce the issue:**

```
$ time chrome www.google.com
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[2000019:2000192:0121/092206.444290:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[2000019:2000192:0121/092206.444313:ERROR:select_file_dialog_impl_portal.cc(243)] Failed to read portal version property
Opening in existing browser session.

real	0m25.664s
user	0m0.499s
sys	0m0.136s
```

**Actual result:**

25 second freeze after running the command.

`notify-send` can send messages to naughty.

**Expected result:**

This command should asynchronously bring up a new chrome tab for the URL and return ideally within 500ms or faster.

**Comment by 0jrp0** [comment] 2022-01-21 17:57
I found this code in chromium:

https://github.com/chromium/chromium/blob/c4d3c31083a2e1481253ff2d24298a1dfe19c754/ui/gtk/select_file_dialog_impl_portal.cc#L232-L247

I am now reading about xdg-desktop-portal:
https://github.com/flatpak/xdg-desktop-portal

Perhaps I have something misconfigured.

**Comment by staticssleever668** [comment] 2022-09-20 10:08
I have a similar problem, however it's caused by using playerctl library through LGI.
It can consistently be reproduce by simply starting mpv without any audio or video.

### Reproduction:

Put [this file](https://git.sr.ht/~showy_fence/dotfiles_awesomewm/blob/433167cebd582930ebc5c8153752aaf054491b44/signal/mpris.lua) into your configuration directory and use the following configuration file:

```lua
local mpris = require("mpris")

mpris.start()

awesome.connect_signal("gamer::mpris::init", function(player)
	print("New player: " .. player)
end)
```

When you run `mpv --player-operation-mode=pseudo-gui` you will get `New player: mpv` message, but the window will not appear and Awesome will be frozen.
After 25 seconds pass, it will unfreeze, the window will appear, and there will be a message like `Last main loop iteration took 25.123456 seconds!`.

(Sorry for not trimming down the `mpris.lua` file as much as possible, but I've spent way too much time debugging this and trying to find workarounds. I don't have any strength left in me to tinker with this. Perhaps, my best bet would be rewriting the module by using D-Bus directly, but I don't feel like it yet).

Program versions:

- awesome: 4.3 and 4.3.1529.gbde785ee6
- lua-lgi: 0.9.2
- mpv-mpris: 0.8.1
- mpv: 0.34.1
- playerctl: 2.4.1.r1.gb19a71c

Output of `awesome --version` I'm running right now:

```
awesome v4.3-1529-gbde785ee6 (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.1.0-beta3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

I have had this problem for over a year, to this may apply to older program versions as well.

**Comment by psychon** [comment] 2022-10-01 09:30
> Chrome cannot talk to naughty,

I wonder why Chrome would even have to talk to naughty. And how you figured out that this even is what is happening. Could someone capture some output from `dbus-monitor` while this problem is occuring?

@staticssleever668 Sorry, but I disagree that you are even talking about the same issue (no chrome, but instead some custom lua code talking to a media player). I hid your comment as "off-topic".

**Comment by actionless** [comment] 2022-10-04 13:18
i think 4.3 version indeed had some problem with notifications containing high-resolution icons/pictures, if i recall correctly, it wasn't duplicating the surface, so chrome was freeing the memory while notification was still displayed and it was causing weird behavior

i recommend trying if you still can reproduce the same problem with awesome latest git build

**Comment by Elv13** [comment] 2024-01-01 08:41
Closing since the code is rewritten

**Closed by Elv13** 2024-01-01 08:41 UTC
