### ISSUE TITLE
naughty.notify does not return id anymore, breaking replaces_id feature

### ISSUE THREAD

**Issue by BarbUk** [awesomeWM/awesome#2678] opened 2019-02-19 06:41 UTC
Output of `awesome --version`:

```
awesome v4.3-81-gddf422dd-dirty (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**
In rc.lua:
```lua
noti = {}
noti.id = nil
function noti:notify (text)
  self.id = naughty.notify({ text = text, timeout = 5, replaces_id = self.id}).id
end
```

From a terminal, execute several times
```bash
echo "noti:notify('test')" | awesome-client
```

**Actual result:**

Multiple notification

**Expected result:**

Only one notification, each new one replacing the old one.

**Notes**

It works as expected with this version:
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

Bisecting the code give this commit as not working: e13b9a48fffa5fdd99b6f676a2389a0b3ff15f45

The commit message say:
> The leaves the old
> `replaces_id` logic mostly intact for now to keep the full backward
> compatibility.

Is there a new way to replace a notification ?

**Comment by blueyed** [comment] 2019-02-19 17:19
As a workaround you could get the `id` through the callback I guess.
At least that's tested (see #2680).

**Comment by psychon** [comment] 2019-02-19 17:29
@blueyed This issue is about the following:
```
$ awesome-client 'return require("naughty").notify{ text = "text"}.id
$
```
Previously, there was an `id` property on notification objects. Now, there is apparently not any more.
The test in #2680 that gets the ID tests the DBus API and not the Lua API, so is (slightly) unrelated.

**Comment by Elv13** [comment] 2019-02-19 17:38
Now technically you can do `.message` or `.title` on the notification object without using the old ID based stuff. The IDs exist, but are currently restricted to notifications from dbus while before all notifications ended up with one. It's a regression and I will fix it. Not today, but soon.

**Comment by BarbUk** [comment] 2019-02-19 18:46
> Now technically you can do `.message` or `.title` on the notification object

Nice, I didn't know about that.

So to do a replacing notification, one can do something like that:
```lua
local noti = {}
noti.notification = nil
function noti:notify (message)
  if self.notification then
    self.notification.message = message
  else
    self.notification = naughty.notify({ message = message, timeout = 5 })
  end
end
```

**Comment by Elv13** [comment] 2019-02-19 18:57
Yes, this is documented here https://awesomewm.org/apidoc/classes/naughty.notification.html

It's brand new, this the commit that broke your setup.

Also, to avoid using the now deprecated `naughty.notify`, you can write it as:

```lua
    self.notification = naughty.notification {
        message = message, 
        timeout = 5
    }
```

**Comment by BarbUk** [comment] 2019-02-19 19:11
Thanks @Elv13 .

And to check for the notification expiration:
```lua
function noti:notify (message)
  if self.notification and not self.notification.is_expired then
    self.notification.message = message
  else
    self.notification = naughty.notification {
        message = message,
        timeout = 5
    }
  end
end
```

**Comment by blueyed** [comment] 2019-02-21 22:43
Looked into this: it appears the problem is that ids are not generated automatically anymore.
Should one get created automatically in the compat wrapper?
https://github.com/blueyed/awesome/blob/725a9e7e8df9452b91f0a3228efe040d48501e0e/lib/naughty/core.lua#L553-L556

**Comment by blueyed** [comment] 2019-02-24 18:29
Fixed by https://github.com/awesomeWM/awesome/pull/2689.

**Comment by actionless** [comment] 2019-02-24 18:41
now indtead of replacing new notification is being created

**Comment by actionless** [comment] 2019-02-24 18:44
also from time to time when trying to close notification now (after merging 2689) is a new error:

```
error: /usr/share/awesome/lib/naughty/core.lua:373: assertion failed!
2019-02-24 19:43:31 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
        /usr/share/awesome/lib/naughty/core.lua:373: in function 'func'
        /usr/share/awesome/lib/naughty/core.lua:196: in function 'func'
        /usr/share/awesome/lib/gears/object.lua:154: in function 'emit_signal'
        /usr/share/awesome/lib/naughty/notification.lua:252: in function 'destroy'
        /usr/share/awesome/lib/naughty/notification.lua:288: in function 'die'
        /usr/share/awesome/lib/naughty/layout/legacy.lua:531: in function 'release'
        /usr/share/awesome/lib/awful/button.lua:50: in function </usr/share/awesome/lib/awful/button.lua:50>
        [C]: in function 'emit_signal'
        /usr/share/awesome/lib/wibox/widget/base.lua:383: in function 'func'
        /usr/share/awesome/lib/gears/object.lua:148: in function 'emit_signal'
        /usr/share/awesome/lib/wibox/drawable.lua:431: in function </usr/share/awesome/lib/wibox/drawable.lua:426>
```

**Comment by Elv13** [comment] 2019-02-24 19:02
@actionless what's the latest master commit that can produce this backtrace? It was "easier" to trigger last week since nothing prevented the notifications from being destroyed multiple time in a row. This problem happened before, but it didn't assert. The assert  there to catch (and fix) the case where this is/was possible. This will help get rid of the occasional "holes" in the notification row. Can you try to investigate and reproduce. Maybe even create a regression test for this?

**Comment by actionless** [comment] 2019-02-24 19:40
i'll try to, but so far as i told it happens "from time to time" :-)
and, worth mentioning, on my own config, not default one

**Comment by blueyed** [comment] 2019-02-25 05:39
> now instead of replacing new notification is being created

Yes.  I can confirm that `replaces_ud` with `naughty.notify` does not appear to be honored.

**Closed** 2019-03-03 21:43 UTC
Labels: bug
