### ISSUE TITLE
can't launch awesome WM in freebsd10.1

### ISSUE THREAD

**Issue by erdosnew** [awesomeWM/awesome#653] opened 2016-01-24 15:49 UTC
i installed awesome WM in freebsd10.1 through 'pkg'.

however, i'm having difficulty launching it, error received:

-------------------
 error while running function
    stack traceback:
    [C]: in function 'load_image'
    /usr/share/awesome/lib/gears/surface.lua:39: in function </usr/share/awesome/lib/gears/surface.lua:24>
    (tail call): ?
    (tail call): ?
    /usr/share/awesome/lib/gears/wallpaper.lua:128: in function 'maximized'
    /etc/xdg/awesome/rc.lua:76: in main chunk
    error: /usr/share/awesome/lib/gears/surface.lua:39: Couldn't recognize the image file format for file '/usr/share/awesome/themes/default/background.png'
    E: awesome: main:535: couldn't find any rc file  
----------------------

**Comment by psychon** [comment] 2016-01-24 16:30
Your gdk-pixbuf doesn't support PNGs. However, since I have no clue about pkg, I cann't say more than that. Does this help you?

**Comment by psychon** [comment] 2016-01-24 16:45
Oh, two ideas: Does gdk-pixbuf claim to have PNG support? You can find out with `gdk-pixbuf-query-loaders | grep -A 4 png.so`. For me this displays (random things):
```
"/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so"
"png" 5 "gdk-pixbuf" "PNG" "LGPL"
"image/png" ""
"png" ""
"\211PNG\r\n\032\n" "" 100
```
The second idea is: Perhaps you are affected by https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790423? gdk-pixbuf uses magick to identify file types. Do you have something like `/usr/share/mime/mime.cache` in your file system?

**Comment by erdosnew** [comment] 2016-01-24 19:54
outputs of commands:

$ gdk-pixbuf-query-loaders | grep -A 4 png.so
"/usr/local/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so"
"png" 5 "gdk-pixbuf" "PNG" "LGPL"
"image/png" ""
"png" ""
"\211PNG\r\n\032\n" "" 100
$ cd /usr/share/mime/
cd: /usr/share/mime/: No such file or directory
$
----------------------------------

mime is not on my system.

**Comment by psychon** [comment] 2016-01-25 08:54
Ok, sorry. Then I'm out of clues. The only one that I have left is "The file `/usr/share/awesome/themes/default/background.png` might be damaged" and "Perhaps find some other program using gdk-pixbuf and see if it can open the file".

**Comment by psychon** [comment] 2016-02-16 20:25
One more thing: Could you try compiling the following program via e.g. `gcc test.c $(pkg-config --libs --cflags gdk-pixbuf-2.0) -Wall -Wextra -O3` and run it with some image file name as argument. That way you might have something for a bug report to FreeBSD (or this might work surprisingly).
```C
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
	int files = argc-1;
	int cur;

	for (cur = 1; cur < argc; cur++) {
		GdkPixbuf *pbuf;
		GError *error = NULL;

		printf("Trying to load '%s'...", argv[cur]);
		pbuf = gdk_pixbuf_new_from_file(argv[cur], &error);
		if (pbuf != NULL) {
			puts("Success");
			g_object_unref(pbuf);
		}
		if (error != NULL) {
			printf("Error: %s\n", error->message);
			g_error_free(error);
		}
	}

	printf("Done loading %d files\n", files);
	return 0;
}
```

**Comment by psychon** [comment] 2016-02-28 13:21
Ping? Did you try the above program?

Closing as "the only person who can reproduce disappeared".

**Closed by psychon** 2016-02-28 13:21 UTC

**Comment by erdosnew** [comment] 2016-05-12 02:57
i upgraded to freebsd10.3 and installed the latest awesome 3.5.8 - from awesome 3.5.6 in freebsd10.1.  now awesome works.  i think that's a bug in 3.5.6.

thanks!
