### ISSUE TITLE
Minimized should be per tag in multitag scenario

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#543] opened 2015-10-27 15:17 UTC
I just noticed that if a client is in multiple tags, it is minimized globally. I guess there should be a special codepath for this. I know it conflict with the X11 way of handling that, but from a logic POV, I think the current implementation can cause some confusion

This is a very minor issue as few people have workflow with either minimized clients or multi-tagged clients

**Comment by psychon** [comment] 2016-02-10 16:03
Duplicate of #231

**Closed by psychon** 2016-02-10 16:03 UTC
