### ISSUE TITLE
Support to wayland

### ISSUE THREAD

**Issue by Blackrucat** [awesomeWM/awesome#3374] opened 2021-06-24 02:41 UTC
We can't deny that Wayland is the future, it is much faster in a few ways it's even better for old computers like mine, it would be really great if AwesomeWM had Wayland support

**Comment by Elv13** [comment] 2021-06-24 03:42
Duplicate of https://github.com/awesomeWM/awesome/issues/159

This is unlikely to happen unless someone revive the waycooler backend. While the Lua portion of the code could work on wayland pretty much as is, the C core is built around xcb. If would not be a "new feature", it would be a complete rewrite of the backend.

**Closed by Elv13** 2021-06-24 03:42 UTC
