### ISSUE TITLE
"another window manager is already running" error after awesome was killed

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#615] opened 2015-12-31 17:08 UTC
I am using a wrapper script that does the following in a loop:

			awesome &
			wait

It allows me to kill awesome, and then a new binary will be used later.  (I have traps setup in the wrapper script for SIGUSR1 to make it loop.)

But surprisingly I was seeing the following error from `acquire_WM_Sn` once after I've killed the running awesome instance (SIGTERM):

> 2015-12-31 15:39:23 E: awesome: acquire_WM_Sn:266: another window manager is already running (selection owned; use --replace)

This should not happen really, because `awesome` was killed, and was only running on another X instance (if at all - I am not sure about this anymore).

It looked like the wrapper script was still executing the `wait` - although I would assume that it should have continued: awesome seemed to not be running anymore (although I have not checked the process table).

This was with awesome master (720cd87), and signalling the wrapper script again made it work as expected.

Not sure what to take from this, but I wanted to at least document this behaviour in case it happens again.

**Comment by psychon** [comment] 2016-01-02 15:39
I just want to share my small wrapper:
```sh
# This restarts awesome if it crashes
RET=1
while [ $RET -ne 0 ]
do
	/home/psychon/projects/awesome/awesome
	RET="$?"
	[ $RET -ne 0 ] && sleep 1
done
```
Killing awesome makes it exit with a non-zero exit status and the script starts it again.

On the actual problem: No idea what happened.

**Comment by psychon** [comment] 2016-02-28 13:30
Closing for now since this only happened once (right?), is thus unreproducible and we have no idea what to do about it.

**Closed by psychon** 2016-02-28 13:30 UTC
Labels: bug, need info

**Comment by actionless** [comment] 2016-03-08 00:16
i am using something like `awesome || openbox` to avoid eternal restarts on config mistakes

**Comment by blueyed** [comment] 2016-03-08 23:23
@psychon 
The `awesome & wait` usage pattern might be broken - I've switched away from it by now.

With `awesome &; wait` `awesome.quit()` would also not work for example: awesome quits (IIRC), but the script hangs at the `wait` still.  The same happens in case of segfaults.

Is there anything special in this regard that awesome is (not) doing with regard to handling signals?!

**Comment by psychon** [comment] 2016-03-09 08:39
@blueyed Nope, I can't even think of any way that awesome could exit without `waitpid()` noticing. The documented behaviour of `waitpid()` is quite explicit, I think.

However, according to some random man page on bash builtins, `wait` without any arguments waits for all children of the current shell, not just the one that was started last. Are you perhaps also starting other processes in the background, not just awesome?
