### ISSUE TITLE
awesome 4.1 does not work

### ISSUE THREAD

**Issue by CDitzel** [awesomeWM/awesome#1820] opened 2017-06-07 06:25 UTC
Output of `awesome --version`:

installed it from source

**How to reproduce the issue:**

I build awesome 4.1 from source by first extracting the archive and then doing make in the directory. I cd into the build folder and did cmake . -DCMAKE_INSTALL_PREFIX=/opt/awesome. After that I did make and make install which create an awesome.bin and awesome-client.bin under /opt/awesome/bin.

Hoever, I cannot choose awesome from my log-in screen. I dont have a  .xinitrc or .xsession file in my home direcotry, where I could add the exec awesome line.

**Actual result:**

nothing to choose from  in the log ins screen

**Expected result:**

awesome should be selectable from the log in screen

**Comment by psychon** [comment] 2017-06-07 07:29
Save https://gitweb.gentoo.org/repo/gentoo.git/tree/x11-wm/awesome/files/awesome-gnome.desktop into `/usr/share/xsessions/`and change both occurrences of `/etc/X11/Sessions/awesome` to `/opt/awesome/bin/awesome.bin` (why the heck do you have a `.bin` suffix here?).

**Comment by psychon** [comment] 2017-06-07 07:30
> Expected result:
> 
> awesome should be selectable from the log in screen

Well, awesome installed an `awesome.desktop` file as well, but thanks to the `prefix` it ended up in `/opt/awesome/share/xsessions/`. You could also try symlinking that file into `/usr/share/xsessions`, I guess. (And no, awesome should not install files outside of its `PREFIX`).

**Comment by CDitzel** [comment] 2017-06-07 07:45
Thank you for your help, but I only have those files here
[http://666kb.com/u.php](url)

**Comment by CDitzel** [comment] 2017-06-07 07:46
also dont have the path /etc/X11/Sessions/awesome

**Comment by psychon** [comment] 2017-06-07 08:04
Uhm... what's your login manager? Slim? Gdm? Kdm?
Also, I know that you do not have that path. I am suggesting to create it. For example:
```
cat > /usr/share/xsessions/awesome.desktop <<EOF
[Desktop Entry]
Name=awesome
Comment=Highly configurable framework window manager
TryExec=/opt/awesome/bin/awesome
Exec=/opt/awesome/bin/awesome
Type=Application
EOF
```
That should make "awesome" selectable in your login manager.

**Comment by CDitzel** [comment] 2017-06-07 10:52
> Well, awesome installed an awesome.desktop file as well, but thanks to the prefix it ended up in /opt/awesome/share/xsessions/. You could also try symlinking that file into /usr/share/xsessions, I guess. (And no, awesome should not install files outside of its PREFIX).

it did not end up in /opt/awesome/share/xsessions/ as evident by the screenshot.

Also did what you suggested in your last post and awesome was selectable in the log in screen. However, when I typed in my PW and hit Enter the screen blacked out for a second before returning to the log in screen, i.e. I cannot log in.

What to do now?

**Comment by psychon** [comment] 2017-06-07 12:59
> it did not end up in /opt/awesome/share/xsessions/ as evident by the screenshot.

The screenshot is from `/opt/awesome/bin`.

> What to do now?

Argh... This might be #1463, but I'm not sure.
Please copy `/opt/awesome/etc/xdg/awesome/rc.lua` to `~/.config/awesome/rc.lua` (create the directory if it does not yet exist).

If the above does not work, try installing Xephyr (just for testing, can be uninstalled later again) and run `Xephyr :1 & sleep 3 ; DISPLAY=:1 awesome` in a terminal. That should get us some error messages on why awesome fails to start.

**Comment by CDitzel** [comment] 2017-06-07 13:11
thank you again for your help =)

but there is only a bin directory under /opt/awesome, nothing more ...

**Comment by psychon** [comment] 2017-06-07 13:19
Oh.

> I build awesome 4.1 from source by first extracting the archive and then doing make in the directory. I cd into the build folder and did cmake . -DCMAKE_INSTALL_PREFIX=/opt/awesome

Could you remove the `/opt/awesome` directory, get a fresh tarball, extract it and install awesome via `make all install CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX=/opt/awesome"`. This should in the future get better due to #1788.

**Comment by CDitzel** [comment] 2017-06-07 14:03
once I cd into the unziped directory, I have to do make in order to create the build directory it says.

is this still valid or where do I type "make all install CMAKE_ARGS="-DCMAKE_INSTALL_PREFIX=/opt/awesome"  ?

**Comment by psychon** [comment] 2017-06-07 14:56
You cd into the unzipped directory and then run that command in there. (It creates a build directory which you can find under `./build/`, but that's not really important right now).

Alternatively, you can also run `mkdir build && cd build && cmake .. DCMAKE_INSTALL_PREFIX=/opt/awesome` inside of the unzipped source directory. This is more or less what the approach via running `make` directly also does.

The problem here is that currently our build malfunctions if you do not build inside of a special directory. I saw you used `cmake .` and that should e.g. mean no default config is created (however, it should still install an empty config file... no idea why it did not do that for you).

**Comment by CDitzel** [comment] 2017-06-07 15:48
and what is that special directory?

My unzipped folder is under Downloads and thats where I cd into before running make oO

**Comment by psychon** [comment] 2017-06-07 15:50
```
cd Downloads/awesome-*
mkdir build
cd build
cmake .. DCMAKE_INSTALL_PREFIX=/opt/awesome
make
make install
```

**Comment by CDitzel** [comment] 2017-06-07 15:59
dont know what I did wrong before, but now I have under /opt/awesome a bin directory as well as share and etc =)

**Comment by CDitzel** [comment] 2017-06-07 16:13
Ok I did everything as described: Replaced  

/usr/share/xsessions/awesome.desktop 

with

[Desktop Entry]
Name=awesome
Comment=Highly configurable framework window manager
TryExec=/opt/awesome/bin/awesome
Exec=/opt/awesome/bin/awesome
Type=Application


I do see awesome in the gdm login screen (where I can also select xfce) but after I type in my password the screen goes black and after a couple of seconds I am returned to the login prompt again oO

**Comment by CDitzel** [comment] 2017-06-07 16:24
Also Xephyr says


me@XYZ:/usr/share/xsessions Xephyr :1 & sleep 3 ; DISPLAY=:1 awesome
[1] 27390
The program 'awesome' is currently not installed. You can install it by typing:
sudo apt install awesome

**Comment by psychon** [comment] 2017-06-07 16:27
Whoops, sorry for that last one. Try `Xephyr :1 & sleep 3 ; DISPLAY=:1 /opt/awesome/bin/awesome`.

**Comment by CDitzel** [comment] 2017-06-08 05:19
typing that in opens a blank terminal window and when I click in there 
`Xephyr :1 & sleep 3 ; DISPLAY=:1 /opt/awesome/bin/awesome
[1] 23239
2017-06-08 07:17:28 W: awesome: screen_scan_randr_crtcs:417: Ignoring RandR, only a compatibility layer is present.
error while running function!
stack traceback:
	[C]: in function 'require'
	/opt/awesome/share/awesome/lib/gears/color.lua:15: in main chunk
	[C]: in function 'require'
	/opt/awesome/share/awesome/lib/gears/init.lua:10: in main chunk
	[C]: in function 'require'
	/home/XXX/.config/awesome/rc.lua:2: in main chunk
error: /opt/awesome/share/awesome/lib/gears/color.lua:15: module 'lgi' not found:
	no field package.preload['lgi']
	no file '/usr/local/share/lua/5.3/lgi.lua'
	no file '/usr/local/share/lua/5.3/lgi/init.lua'
	no file '/usr/local/lib/lua/5.3/lgi.lua'
	no file '/usr/local/lib/lua/5.3/lgi/init.lua'
	no file '/usr/share/lua/5.3/lgi.lua'
	no file '/usr/share/lua/5.3/lgi/init.lua'
	no file './lgi.lua'
	no file './lgi/init.lua'
	no file '/home/xxx/.config/awesome/lgi.lua'
	no file '/home/xxx/.config/awesome/lgi/init.lua'
	no file '/etc/xdg/xdg-xubuntu/awesome/lgi.lua'
	no file '/etc/xdg/xdg-xubuntu/awesome/lgi/init.lua'
	no file '/usr/share/upstart/xdg/awesome/lgi.lua'
	no file '/usr/share/upstart/xdg/awesome/lgi/init.lua'
	no file '/etc/xdg/awesome/lgi.lua'
	no file '/etc/xdg/awesome/lgi/init.lua'
	no file '/etc/xdg/awesome/lgi.lua'
	no file '/etc/xdg/awesome/lgi/init.lua'
	no file '/opt/awesome/share/awesome/lib/lgi.lua'
	no file '/opt/awesome/share/awesome/lib/lgi/init.lua'
	no file '/usr/local/lib/lua/5.3/lgi.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/lgi.so'
	no file '/usr/lib/lua/5.3/lgi.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lgi.so'
	no file '/home/xxx/.config/awesome/lgi.so'
	no file '/etc/xdg/xdg-xubuntu/awesome/lgi.so'
	no file '/usr/share/upstart/xdg/awesome/lgi.so'
	no file '/etc/xdg/awesome/lgi.so'
	no file '/etc/xdg/awesome/lgi.so'
	no file '/opt/awesome/share/awesome/lib/lgi.so'
error while running function!
stack traceback:
	[C]: in function 'require'
	/opt/awesome/share/awesome/lib/gears/color.lua:15: in main chunk
	[C]: in function 'require'
	/opt/awesome/share/awesome/lib/gears/init.lua:10: in main chunk
	[C]: in function 'require'
	/opt/awesome/etc/xdg/awesome/rc.lua:2: in main chunk
error: /opt/awesome/share/awesome/lib/gears/color.lua:15: module 'lgi' not found:
	no field package.preload['lgi']
	no file '/usr/local/share/lua/5.3/lgi.lua'
	no file '/usr/local/share/lua/5.3/lgi/init.lua'
	no file '/usr/local/lib/lua/5.3/lgi.lua'
	no file '/usr/local/lib/lua/5.3/lgi/init.lua'
	no file '/usr/share/lua/5.3/lgi.lua'
	no file '/usr/share/lua/5.3/lgi/init.lua'
	no file './lgi.lua'
	no file './lgi/init.lua'
	no file '/home/xxx/.config/awesome/lgi.lua'
	no file '/home/xxx/.config/awesome/lgi/init.lua'
	no file '/etc/xdg/xdg-xubuntu/awesome/lgi.lua'
	no file '/etc/xdg/xdg-xubuntu/awesome/lgi/init.lua'
	no file '/usr/share/upstart/xdg/awesome/lgi.lua'
	no file '/usr/share/upstart/xdg/awesome/lgi/init.lua'
	no file '/etc/xdg/awesome/lgi.lua'
	no file '/etc/xdg/awesome/lgi/init.lua'
	no file '/etc/xdg/awesome/lgi.lua'
	no file '/etc/xdg/awesome/lgi/init.lua'
	no file '/opt/awesome/share/awesome/lib/lgi.lua'
	no file '/opt/awesome/share/awesome/lib/lgi/init.lua'
	no file '/usr/local/lib/lua/5.3/lgi.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/lgi.so'
	no file '/usr/lib/lua/5.3/lgi.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lgi.so'
	no file '/home/xxx/.config/awesome/lgi.so'
	no file '/etc/xdg/xdg-xubuntu/awesome/lgi.so'
	no file '/usr/share/upstart/xdg/awesome/lgi.so'
	no file '/etc/xdg/awesome/lgi.so'
	no file '/etc/xdg/awesome/lgi.so'
	no file '/opt/awesome/share/awesome/lib/lgi.so'
2017-06-08 07:17:28 E: awesome: main:774: couldn't find any rc file
`

**Comment by Elv13** [comment] 2017-06-08 05:35
LGI doesn't seem to be in your `LUA_PATH`, you need to either set the variable correctly or install LGI in a system path. This isn't an Awesome issue, the same would happen with any application that use a shared library (be it in Lua, C* or Python).

\* C/C++ can be linked correctly, I know, but by default it wont (LD_LIBRARY_PATH)

**Comment by CDitzel** [comment] 2017-06-08 06:13
just installed lgi-dev via package manager. Did not solve the problem =/

**Comment by Elv13** [comment] 2017-06-08 06:24
Where did the package managed installed the files?

**Comment by CDitzel** [comment] 2017-06-08 06:32
I dont know =/ how can I find out or how can I install LGI in system path?

**Comment by Elv13** [comment] 2017-06-08 06:35
Use ` find /usr -iname 'ffi.lua'`

**Comment by CDitzel** [comment] 2017-06-08 06:42
> ditzel@mrm-93:/ find /usr -iname 'ffi.lua'
/usr/share/lua/5.1/lgi/ffi.lua
/usr/share/lua/5.2/lgi/ffi.lua
[1]+  Exit 1                  Xephyr :1  (wd: ~)
(wd now: /)

**Comment by Elv13** [comment] 2017-06-08 06:45
So, your LGI is for Lua 5.1 and Lua 5.2 and your Awesome for Lua 5.3.

This is a duplicate of https://github.com/awesomeWM/awesome/issues/1757, so I will close this. In your case, recompiling Awesome with Lua 5.1 should solve the issue. The variable are `-DLUA_INCLUDE_DIR=/usr/include/<insert the lua 5.1 dir name>`  `-DLUA_LIBRARY=/usr/lib/<the lua.so name for 5.1>`

**Closed by Elv13** 2017-06-08 06:45 UTC

**Comment by CDitzel** [comment] 2017-06-08 07:46
> 
lrwxrwxrwx 1 root root   35 Sep  3  2015 lfs.so -> ../../liblua5.1-filesystem.so.0.0.0
drwxr-xr-x 2 root root 4,0K Jun  8 08:12 lgi/
lrwxrwxrwx 1 root root   30 Aug 16  2015 lxp.so -> ../../liblua5.1-expat.so.0.0.0
xxx@xxx:/usr/lib/x86_64-linux-gnu/lua/5.1 cd lgi/
xxx@xxx:/usr/lib/x86_64-linux-gnu/lua/5.1/lgi l
total 0
lrwxrwxrwx 1 root root 31 Nov  6  2015 corelgilua51.so -> ../../../liblua5.1-lgi.so.0.0.0
xxx@xxx:/usr/lib/x86_64-linux-gnu/lua/5.1/lgi 

which .so do I have to choose?

**Comment by psychon** [comment] 2017-06-08 07:52
None of those. Try more like `ls -l /usr/lib/x86_64-linux-gnu/liblua*so`.

**Comment by CDitzel** [comment] 2017-06-08 09:02
so I did

> 
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/awesome -DLUA_INCLUDE_DIR=/usr/include/lua5.1 -DLUA_LIBRARY=/usr/lib/x86_64-linux-gnu/liblua5.1-lgi.so

and after typing make I get

> Scanning dependencies of target awesome
[  5%] Building C object CMakeFiles/awesome.dir/awesome.c.o
In file included from /home/xxx/Downloads/awesome-4.1/build/awesome.c:29:0:
/home/xxx/Downloads/awesome-4.1/build/xkb.h:26:17: fatal error: lua.h: No such file or directory
compilation terminated.
CMakeFiles/awesome.dir/build.make:62: recipe for target 'CMakeFiles/awesome.dir/awesome.c.o' failed
make[2]: *** [CMakeFiles/awesome.dir/awesome.c.o] Error 1
CMakeFiles/Makefile2:166: recipe for target 'CMakeFiles/awesome.dir/all' failed
make[1]: *** [CMakeFiles/awesome.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by psychon** [comment] 2017-06-08 09:07
Sounds like `/usr/include/lua5.1/lua.h` does not actually exist...? Or you already had a previous `cmake` call in there and CMake "helpfully" cached `LUA_INCLUDE_DIR` in its `CMakeCache.txt` and did not actually use your new value for that variable.

> -DLUA_LIBRARY=/usr/lib/x86_64-linux-gnu/liblua5.1-lgi.so

You really want `liblua[some number].so` here, not lgi. I do not what exact distribution you use, but [on debian amd64 this would be `/usr/lib/x86_64-linux-gnu/liblua5.1.so`](https://packages.debian.org/stretch/amd64/liblua5.1-0-dev/filelist)

**Comment by CDitzel** [comment] 2017-06-08 09:17
I am using Xubuntu 16.04 and installed lua via Synaptic =/

Dont know where I am going wrong

**Comment by CDitzel** [comment] 2017-06-08 09:48
I managed to install it and the output is now
![aw](https://user-images.githubusercontent.com/22954412/26922744-494b69be-4c40-11e7-8962-a5480b508464.png)


is there some minimal completely functional output out there that I can use to get started?

**Comment by psychon** [comment] 2017-06-08 10:25
Those warnings seem to be safe to ignore (for now...). Awesome should now also work when you log in to it.

> also, is there some minimal completely functional output out there that I can use to get started?

I don't understand the question? Output? Started? With what?

**Comment by CDitzel** [comment] 2017-06-08 11:09
sorry I misspoke, I meant template/rc.lua file to get me started. 

I understand that most commonly config files that work under Awesome 3.x are not compatible with awesome 4.x and vice versa

**Comment by psychon** [comment] 2017-06-08 11:14
You should have one under `/opt/awesome/etc/xdg/awesome/rc.lua`, I think.

**Comment by CDitzel** [comment] 2017-06-08 11:15
so I will copy that to my ~/.config/awesome folder and get started


are the copy cat themes compatible with awesome 4.1?

**Comment by psychon** [comment] 2017-06-08 11:27
I don't know. Feel free to try.

Your current theme should be under `/opt/awesome/share/awesome/themes/default/theme.lua`.

**Comment by CDitzel** [comment] 2017-06-08 12:03
thanks a lot guys for your help!
