### ISSUE TITLE
Using "run prompt" (Mod + R) doesn't use parameter from user like scaling

### ISSUE THREAD

**Issue by dummys** [awesomeWM/awesome#1770] opened 2017-05-04 18:50 UTC
Hi,
When I use the Mod + r to run program, it doesn't use my scaling factor for QT and GTK.
Those parameter are set in my .zshrc.
The code:
```lua
awful.key({ modkey }, "r", function () awful.screen.focused().mypromptbox:run() end,
    {description = "run prompt", group = "launcher"}), 
```
Is it a bug or it's by design ?
Thanks

**Comment by Elv13** [comment] 2017-05-04 19:21
First of all, Awesome uses neither Qt or GTK, so if you used their setting, nothing will happen. Then, in case you used the right way (which you did not describe), then it might still not work because depending on how Awesome is started, it might not start from a shell (therefor the parameters wont be set at all). Finally, only Awesome 4.0+ honor DPI.

See https://wiki.archlinux.org/index.php/HiDPI#X_Resources

**Comment by dummys** [comment] 2017-05-04 19:25
Hi, I think you didn't understand me.
I use awesome 4.0+ and my dpi is working very well. IT's only when I run a program thru the "run prompt" that the scaling and every other env var is not applied to the program I ran.
I never said that awesome use QT or GTK, I say when I launch application that use QT or GTK...

**Comment by Elv13** [comment] 2017-05-04 19:57
Then the second of my point applies:

> Then, in case you used the right way (which you did not describe), then it might still not work because depending on how Awesome is started, it might not start from a shell (therefor the parameters wont be set at all).

I answered both possible problems because the original question was ambiguous. So either start Awesome from a shell or add the variables in the `.desktop` so whatever DM you use pick them up. If you use xinitrc, `source` your zshrc (and/or add the variables in case `/etc/passwd` is set to dash or bash). Assuming the issue is that Awesome started without a shell, that should solve it.

**Comment by dummys** [comment] 2017-05-05 06:14
I use lxdm with:
```
## default session or desktop used when no systemwide config
session=/usr/bin/awesome
```
Is it not the right way to do ?

**Comment by psychon** [comment] 2017-05-05 06:30
When awesome starts a program, that program inherits all its environment variables.

> , it doesn't use my scaling factor for QT and GTK.
> Those parameter are set in my .zshrc.

I guess you are talking about `GDK_SCALE=2`. No idea which variable Qt uses. Obviously, awesome does not have this variable in its env.

You could add something like `require("lgi").GLib.setenv("GDK_SCALE", "2", true)` to your `rc.lua` to work around that. Besides that, no idea how to make lxdm set some environment variables (per user, I guess). Google also isn't being helpful right now.

> I use lxdm with:
> 
> ## default session or desktop used when no systemwide config
> session=/usr/bin/awesome
> 
> Is it not the right way to do ?

No idea about "right", but you could create a file like the following and use that as your session, if you wanted.

```sh
#!/bin/sh
export GDK_SCALE=2
exec /usr/bin/awesome
```

Sorry, but I'll close this because this is not an issue with awesome.

**Closed by psychon** 2017-05-05 06:30 UTC

**Comment by dummys** [comment] 2017-05-05 18:15
ok thanks for help.
