### ISSUE TITLE
Mouse resize in tile layout works weird for the bottom row when `size_hints_honor = false`

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#424] opened 2015-08-23 11:33 UTC
Steps to reproduce:
1) set `size_hints_honor = false` in the rules
2) switch to tile layout
3) open 3 or more clients
4) try to resize client on the most bottom row (either slave or master if there is two or more master clients, ie more than one row)

Client size will jump crazily, while on other rows resize happens as expected.

**Comment by motdef** [comment] 2015-11-21 19:09
I also have this issue. It looks like the bottom row client becomes vertically smaller with every mouse movement until it reaches zero and "rolls over" so that it fills the column.

**Comment by blueyed** [comment] 2015-11-21 23:40
Could not reproduce it with rxvt-unicode windows.
When mod-right-clicking the cursor jumps to the corner, and the window gets resized a bit already (gets ~10pt smaller, related to taskbar?! - I don't have them by default).

**Comment by actionless** [comment] 2016-03-03 12:54
i noticed too the issue with cursor moved few pixels when starting resize, but that's another one

**Comment by zhrts** [comment] 2017-01-24 23:20
I get even weirder behaviour, when resizing the lower clients of three or more `urxvtc` in a tiled layout, the one I'm clicking on will jump around and then stick to the geometry of one adjacent to it, persisting even after I close and open the clients. Adding more clients to the layout begins to cascade them, and then resizing again tiles them back to normal all at once. 0_o

**Comment by larkery** [comment] 2018-03-07 14:06
I think this is due to drag corner detection failing or mismatching somehow. When I drag from the top left corner of a window in the middle of the right column (with 3 windows in that column), the mouse warps to the bottom left position and awesome seems to try and drag the top left to that position.

This collapses the window to be very small.

Then, when I move the mouse, it snaps back to how it was before, dragging the bottom left corner (even though I clicked the top left). So, it looks like the sequence is something like:

- Click top left, resize handler starts resizing from top left
- Mouse cursor warps to bottom left position
- Resize handler attempts to resize by moving top left to bottom left
- Resize handler then starts trying to drag from bottom left
- Moving mouse 1px puts the bottom left back where it was (where cursor warped to)

**Comment by dimitris-triantafyllidis** [comment] 2021-04-19 23:47
@actionless I gave awesome a try today and stumbled upon this behaviour. Do you use gaps? I tried switching gaps off and the problem disappeared.

**Comment by Elv13** [comment] 2021-04-19 23:55
@dimitris-triantafyllidis try to disable size honoring (see the FAQ) to make this problem "go away" with gaps. A second step one could take is to forbid clients from resizing themselves.

The bug described in this issue can come from many small issues, but most of the time the client self-resize, its own size hints and the tiling engine start to fight each other in a feedback loop. One of the 3 has to stop for the feedback loop to break.

**Comment by actionless** [comment] 2021-04-22 15:46
i can reproduce it both with and without "useless_gaps"

i've updated the description to include info regarding `size_hints_honor = false`, i didn't realized it makes any effect, as i always using awesome with this setting from the very first day

**Closed** 2023-08-30 11:27 UTC
Labels: bug, need info
