### ISSUE TITLE
Question : awesome and touchscreen

### ISSUE THREAD

**Issue by deb75** [awesomeWM/awesome#2285] opened 2018-06-08 08:41 UTC
Hello,

I have a hybrid laptop (Surface Book) and I would like to make `awesome` more usable in tablet mode, although I am aware this is not the spirit of `awesome`

My first attempt was to find an application translating touchscreen events into key strokes, which are then passed to the focused clients.

Unfortunately, there are very few good working applications to manage touchscreen, among which is `touchegg`, but it segfaults oftenly. Gnome is said to have good touchscreen support, but I guess it is embedded within gnome.

Another idea would be to build a lua module to display a small panel mapped with square buttons (just like windows 10) and to assign to each button an action (close a window, open favorite app, ...), just like the awesome menu (which is already quite usable in tablet mode).

I wonder how I could build a panel mapped with square buttons (large enough for 2-3 fingers) with awesomes libraries. Would you have any idea to start from ?

Regards

**Comment by actionless** [comment] 2018-06-08 10:17
. Would you have any idea to start from ?

from `wibox()` widget, it can be used a stacked or floating panel

**Comment by psychon** [comment] 2018-06-09 07:35
> Another idea would be to build a lua module to display a small panel mapped with square buttons

Something like the following?
```lua
local function my_button(text, cb)
    local tb = wibox.widget.textbox(text)
    tb.align = "center"
    tb.valign = "center"
    tb:buttons(awful.button({}, 1, cb))
    return tb
end

local w = wibox{ x = 30, y = 30, width = 300, height = 300, ontop = true }
w:setup {
    forced_num_cols = 2,
    forced_num_rows = 2,
    homogeneous = true,
    expand = true,
    layout = wibox.layout.grid,
    my_button("notify", function() naughty.notify{ text = "Notify!" } end),
    my_button("close", function() if client.focus then client.focus:kill() end end),
    my_button("quit", function() awesome.quit() end),
    my_button("restart", function() awesome.restart() end)
}
w.visible = true
```

**Comment by deb75** [comment] 2018-06-12 21:12
Hi

Thanks very much for this `awesome` starting point :+1: 

I have been hacking it for some days for my needs, I would like each button to have a different color , but all my attempts failed, could you help me in this respect ?

**Comment by Elv13** [comment] 2018-06-12 21:16
you need to use `wibox.container.background`, but please create a gist or pastebin of your failed attempts so we can help you fix them.

**Comment by deb75** [comment] 2018-07-02 10:17
Hi,

I ended up implementing this : 

```lua

local wibox = require("wibox")
local awful = require("awful")
local naughty = require("naughty")
local gears = require("gears")
local beautiful = require("beautiful")
local xrandr = require("xrandr")

local xmin, ymin, spacing = 60, 60, 20
local bg = beautiful.bg_normal

local wibox_tree = {
   name = "root",
   width = 400,
   height = 400,
   spacing = 10,
   bg = "#ebebeb",
   forced_num_cols = 2,
   forced_num_rows = 2,
   {
      name = "exit",
      width = 400,
      height = 400,
      spacing = 10,
      bg = "#444444",
      forced_num_cols = 3,
      forced_num_rows = 2,
      row = 2, col = 2,
      image = os.getenv("HOME") .. "/.icons/door_exit.png",
      {
         row = 1, col = 1,
         image = os.getenv("HOME") .. "/.icons/power-logoff.png",
         callback = function() awful.spawn.easy_async(os.getenv("HOME") .. "/bin/at-exit.sh",
                                                      function(stdout) end) end
      },
      {
         row = 1, col = 2,
         image = os.getenv("HOME") .. "/.icons/power-shutdown.png",
         callback = function() awful.spawn.easy_async("/usr/bin/sudo /sbin/shutdown -h now",
                                                      function(stdout) end) end
      },
      {
         row = 1, col = 3,
         image = os.getenv("HOME") .. "/.icons/power-restart.png",
         callback = function() awful.spawn.easy_async("/usr/bin/sudo /sbin/reboot",
                                                      function(stdout) end) end
      },
      {
         row = 2, col = 1,
         image = os.getenv("HOME") .. "/.icons/power-hibernate.png",
         callback = function() awful.spawn.easy_async("systemctl hibernate",
                                                      function(stdout) end) end
      },
      {
         row = 2, col = 2,
         image = os.getenv("HOME") .. "/.icons/power-sleep.png",
         callback = function() awful.spawn.easy_async("systemctl suspend",
                                                      function(stdout) end) end
      },
      {
         row = 2, col = 3,
         image = os.getenv("HOME") .. "/.icons/power-lock.png",
         callback = function() awful.spawn.easy_async("/usr/bin/slock",
                                                      function(stdout) end) end
      }
   },
   {
      name = "apps",
      width = 400,
      height = 400,
      spacing = 10,
      bg = "#444444",
      forced_num_cols = 3,
      forced_num_rows = 2,
      row = 1, col = 2,
      image = os.getenv("HOME") .. "/.icons/my_apps.png",
      {
         row = 1, col = 1,
         image = os.getenv("HOME") .. "/.icons/terminal.png",
         callback = function() awful.spawn.easy_async(os.getenv("HOME") .. "/bin/urxvt.sh",
                                                      function(stdout) end) end
      },
      {
         row = 1, col = 2,
         image = os.getenv("HOME") .. "/.icons/emacs.png",
         callback = function() awful.spawn.easy_async(os.getenv("HOME") .. "/bin/emacs.sh",
                                                      function(stdout) end) end
      },
      {
         row = 1, col = 3,
         image = os.getenv("HOME") .. "/.icons/qutebrowser.png",
         callback = function() awful.spawn.easy_async(os.getenv("HOME") .. "/bin/qutebrowser",
                                                      function(stdout) end) end
      },
      {
         row = 2, col = 1,
         image = os.getenv("HOME") .. "/.icons/styluslab-write.png",
         callback = function() awful.spawn.easy_async(os.getenv("HOME") .. "/usr/src/Write/Write",
                                                      function(stdout) end) end
      },
      {
         row = 2, col = 2,
         image = os.getenv("HOME") .. "/.icons/xournal.png",
         callback = function() awful.spawn.easy_async("/usr/bin/xournal", function(stdout) end) end
      },
      {
         row = 2, col = 3,
         image = os.getenv("HOME") .. "/.icons/firefox.png",
         callback = function() awful.spawn.easy_async(os.getenv("HOME") .. "/bin/firefox-esr",
                                                      function(stdout) end) end
      },
   },
   {
      name = "awesome",
      width = 400,
      height = 400,
      spacing = 10,
      bg = "#444444",
      forced_num_cols = 2,
      forced_num_rows = 2,
      row = 1, col = 1,
      image = os.getenv("HOME") .. "/.icons/awesome.png",
      {
         row = 1, col = 1,
         image = os.getenv("HOME") .. "/.icons/screenshot.png",
         callback = function() awful.spawn.easy_async(os.getenv("HOME") .. "/bin/print.sh",
                                                      function(stdout) end) end
      },
      {
         row = 1, col = 2,
         image = os.getenv("HOME") .. "/.icons/screen_resolution.png",
         callback = xrandr.xrandr
      }
   }
}


local function find_space(wibox_list, wibox_name, xmin, ymin, spacing)
   local xmax, ymax = xmin, ymin

   for _, wb in pairs(wibox_list)
   do
      if wb.visible then
         if xmax < (wb.x + wb.width) then
            xmax = wb.x + wb.width
         end
         if ymax < (wb.y + wb.height) then
            ymax = wb.y + wb.height
         end
      end
   end

   xmax = xmax + spacing
   ymax = ymax + spacing

   local s = awful.screen.focused()

   local xrest = s.geometry.width - xmax
   local yrest = s.geometry.height - ymax

   if xrest > yrest then
      if wibox_list[wibox_name].width < xrest then
         return { x = xmax, y = ymin, hide = false }
      elseif wibox_list[wibox_name].height < yrest then
         return { x = xmin, y = ymax, hide = false }
      else
         return { x = xmin, y = ymin, hide = true }
      end
   else
      if wibox_list[wibox_name].height < yrest then
         return { x = xmin, y = ymax, hide = false }
      elseif wibox_list[wibox_name].width < xrest then
         return { x = xmax, y = ymin, hide = false }
      else
         return { x = xmin, y = ymin, hide = true }
      end
   end
end


local function set_callback(mywidget, wibox_tree, wibox_list)
   if wibox_tree.callback ~= nil then
      -- If a callback is specified, apply it and remove all wiboxes.
      mywidget:buttons(awful.button({}, 1, function()
                             for _, wb in pairs(wibox_list) do
                                wb.visible = false
                             end
                             wibox_tree.callback()
      end))
   else
      -- If no callback specified, assume this is the button linked to the wibox itself.
      mywidget:buttons(awful.button({}, 1, function()
                             if wibox_list[wibox_tree.name].visible == true then
                                wibox_list[wibox_tree.name].visible = false
                             else
                                local space = find_space(wibox_list, wibox_tree.name,
                                                         xmin, ymin, spacing)

                                wibox_list[wibox_tree.name].x = space.x
                                wibox_list[wibox_tree.name].y = space.y

                                if hide == true then
                                   for _, wb in pairs(wibox_list) do
                                      wb.visible = false
                                   end
                                end

                                wibox_list[wibox_tree.name].visible = true
                             end
      end))
   end
end


local function make_wibox_list(wibox_tree, xmin, ymin, bg, wibox_list)
   -- Create wibox if there exists a name.
   if wibox_tree.name ~= nil then
      wibox_list[wibox_tree.name] = wibox{
         x = wibox_tree.x or xmin,
         y = wibox_tree.y or ymin,
         width = wibox_tree.width * wibox_tree.forced_num_cols +
            (wibox_tree.spacing or 0) * (wibox_tree.forced_num_cols - 1),
         height = wibox_tree.height * wibox_tree.forced_num_rows +
            (wibox_tree.spacing or 0) * (wibox_tree.forced_num_rows - 1),
         ontop = wibox_tree.ontop or true,
         bg = wibox_tree.bg or bg
      }

      wibox_list[wibox_tree.name]:setup {
         forced_num_cols = wibox_tree.forced_num_cols,
         forced_num_rows = wibox_tree.forced_num_rows,
         spacing = wibox_tree.spacing or 0,
         homogeneous = true,
         expand = true,
         layout = wibox.layout.grid
                                        }
   end

   -- Recursively make wiboxes.
   for _, wibox_tree_up in ipairs(wibox_tree)
   do
      local mywidget = make_wibox_list(wibox_tree_up, xmin, ymin, bg, wibox_list)

      if mywidget ~= nil then
         wibox_list[wibox_tree.name].widget:add_widget_at(mywidget,
                                                          wibox_tree_up.row,
                                                          wibox_tree_up.col,
                                                          1, 1)
      end
   end

   -- If there is an image or a text then create a button.
   if wibox_tree.image ~= nil then
      local mywidget = wibox.widget.imagebox()
      mywidget:set_image(wibox_tree.image)
      set_callback(mywidget, wibox_tree, wibox_list)
      return mywidget
   elseif wibox_tree.text ~= nil then
      local mywidget = wibox.widget {
         markup = wibox_tree.text,
         align  = "center",
         valign = "center",
         widget = wibox.widget.textbox
      }

      if wibox_tree.bgimage ~= nil then
         return wibox.widget {
            mywidget,
            bgimage = wibox_tree.bgimage,
            widget = wibox.container.background
         }
      elseif wibox_tree.bg ~= nil then
         return wibox.widget {
            mywidget,
            bg = wibox_tree.bg,
            widget = wibox.container.background
         }
      else
         return wibox.widget {
            mywidget,
            shape = gears.shape.rounded_rect,
            widget = wibox.container.background
         }
      end
   else
      return wibox_tree.name
   end
end

local wibox_list = {}

awful.spawn.easy_async(make_wibox_list(wibox_tree, xmin, ymin, bg, wibox_list), function(stdout) end)

local function toggle()
   local is_one_visible = false

   for _, wb in pairs(wibox_list) do
      if wb.visible == true then
         is_one_visible = true
         break
      end
   end

   -- If one wibox is visible, assume we want to close them all,
   -- without opening the root one, otherwise toggle the root one.
   if is_one_visible then
      for _, wb in pairs(wibox_list) do
         wb.visible = false
      end
   else
      wibox_list["root"].visible = wibox_list["root"].visible == false
   end
end


return {
   toggle = toggle
}
```

Sorry for the long post, this is a module which implements nested wiboxes.

I wanted something easily configurable, so it took me a few time to perform it.

The idea is to fill a list called `wibox_tree` . The first level of the list is the "root" menu, the top left hand corner square on the illustration below. I can then write as many sublists as I want which defines nested wiboxes (the two rectangles). When a list contains a `name` field and does not contain a `callback` field, it is assumed the widget is associated to the wibox and touching the button toggles the wibox visibility. Otherwise, the widget is whatever I want it to be, through the definition of the callback function.

The recursive function `make_wibox_list` takes the `wibox_tree` list and outputs a flat wibox list, which is used to toggle the wibox visibility.

I would like t go further by implementing different callback functions depending on the number of fingers used to touch the buttons, but this requires a touchscreen manager (like `touchegg`).

![screenshot_11-57-20](https://user-images.githubusercontent.com/19540378/42157935-49273350-7def-11e8-8cdb-6e31ad3624a9.png)

Being a newbie in awesome wm implementation, feel free to tell me what could be improved.

Regards

**Comment by deb75** [comment] 2018-07-02 10:21
I accidentally closed the question.

**Comment by actionless** [comment] 2018-07-02 10:34
i think in touchegg you just assign multiple fingers to mouse6, mouse7, etc and other "special" mouse buttons other than left, right and middle click, scroll

in awesome wm just bind accordingly that `mouse6` button to that button in which you want to handle mutiple fingers


(btw also using awesome on lenovo yoga with touch screen, but i didn't implemented any extra for that; however in compare to default config i have some small extras to make awesome usable with mouse only, ie without keyboard)

**Comment by deb75** [comment] 2018-08-02 20:39
Hello,

I would like a function to be called whenever an `imagebox` appears, for example to set its image.

I initially tried with `wibox:emit_signal("hello")` and `widget:connect_signal("hello", function(obj) ... end)`.
where `wibox` is the wibox containing the widget. I assume the widget is passed as first argument to the callback function (obj).

But nothing happens. How could I make this work ?

**Comment by psychon** [comment] 2018-08-03 06:54
Are you looking for the `property::visible` signal of the wibox? This signal is emitted whenever the visibility status of the wibox changes, i.e. both when it becomes hidden and when it becomes visible. The argument to the signal callback will be the whole wibox.

I do not understand what you mean with "when an imagebox appears". Does the above already answer your question?

**Comment by deb75** [comment] 2018-08-03 07:24
Hi,

Thanks very much for your answeer.

Yes, it's quite I am looking for.

I have several wibox containing each a set of widget (imagebox or textbox). By touching the screen, I make visible or invisible the wiboxes. Each time one wibox becomes visible, I would like all the imagebox it contains be updated, this is what I was meaning by "when an imagebox appears".

When I make visible one wibox with `wibox.visible = true`, it emits the signal `property::visible`. How can I catch this signal and make a call to a function that will work on each imagebox contained by the wibox ?

My guess is that I cannot use `widget:connect_signal("property::visible", callback)` because this is not the property of the widget itself (?).

I could instead use `wibox:connect_signal("property::visible", callback)` with a `callback` function that would loop over each widget contained by the wibox (?). Is this possible ? Or you know maybe a smarter way ?

Regards

**Comment by Elv13** [comment] 2018-08-05 23:05
Why not using a single wibox for all the widgets? Wiboxes can have transparent background and fill the screen. I mean, looping over all wiboxes is possible, but that's rather overkill. There is an awful.layout.grid.

**Comment by deb75** [comment] 2018-08-12 19:41
Hi,

I want to cycle over all widgets contained in one wiboxes. Is it possible ? How can I do that ?

But, to which signal should I connect to in order to call a function when a widget becomes visible (through the wibox that contains it) ?

Regards

**Comment by psychon** [comment] 2018-08-13 07:04
How can a widget be invisible even though the wibox that contains it is visible? When a wibox is visible, all its widgets are visible, too. I fail to understand the problem that you are trying to solve, sorry.

**Comment by deb75** [comment] 2018-08-13 09:58
Hi

Thanks for your answeer, so for making me unclear. Answeering to your latest edit : how do you update the widgets inside the wibox ? Is there a function to loop over each widget inside the function. This wil do it.

Regards

**Comment by psychon** [comment] 2018-08-13 10:28
Uhm... Something like this?
```lua
local function call_with_widgets(widget, callback)
    callback(widget)
    for _, child in ipairs(widget.get_children and widget:get_children() or {}) do
        call_with_widgets(child, callback)
    end
end
call_with_widget(screen[1].mywibox.widget, print)
```
(I'm not quite sure if the "check if `get_children` exists"-dance is necessary, but having it in there won't hurt)

**Comment by Elv13** [comment] 2018-10-07 01:54
Closing as it is a question and not a bug

**Closed by Elv13** 2018-10-07 01:54 UTC

**Comment by zaoqi-unsafe** [comment] 2018-12-31 10:11
is it useable?

**Comment by deb75** [comment] 2018-12-31 20:38
> is it useable?

Hi, what do you mean exactly by "it" and "useable" ?

I use on a daily basis what I developed above and I am very happy with it as it makes `awesome` awesome on a touchscreen laptop. I more and more change the keyboard shortcuts into widgets with which I can interact on the screen.

But do not retrieve the above code, I have been enhancing it since the post, if you are interested I can repost it.
