### ISSUE TITLE
Possible regression in require with Lua 5.4

### ISSUE THREAD

**Issue by Blakeinstein** [awesomeWM/awesome#3563] opened 2022-02-09 07:33 UTC
Output of `awesome --version`:
```
awesome v4.3-1348-g2d6244f94 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**
A quick way to reproduce the issue, is to use https://github.com/manilarome/the-glorious-dotfiles .
The repo comes with a PKGBUILD to take a backup of you current config, and then use the newer configs.

**Actual result:**

The default config loads instead, on .xsession-errors, an error log can be seen.
```
error while running function!
stack traceback:
	[C]: in function 'assert'
	/usr/share/awesome/lib/wibox/widget/base.lua:999: in function 'wibox.widget.base.check_widget
'
	/usr/share/awesome/lib/wibox/widget/base.lua:747: in upvalue 'drill'
	/usr/share/awesome/lib/wibox/widget/base.lua:742: in upvalue 'drill'
	/usr/share/awesome/lib/wibox/widget/base.lua:742: in upvalue 'drill'
	/usr/share/awesome/lib/wibox/widget/base.lua:742: in upvalue 'drill'
	/usr/share/awesome/lib/wibox/widget/base.lua:814: in function 'wibox.widget.base.make_widget_
declarative'
	(...tail calls...)
	/home/blaine/.config/awesome/layout/control-center/init.lua:88: in main chunk
	[C]: in function 'require'
	/home/blaine/.config/awesome/layout/init.lua:3: in main chunk
	[C]: in function 'require'
	/home/blaine/.config/awesome/rc.lua:27: in main chunk
error: /usr/share/awesome/lib/wibox/widget/base.lua:999: Type should be table, but is string
```

**Expected result:**

No error should have popped up. Seems like there was a breaking change. Other users have also reported having a similar issue on my reddit post. https://www.reddit.com/r/awesomewm/comments/snjqgr/error_with_manilaromes_glorius_dotfiles

**Comment by pepijnKrijnsen** [comment] 2022-02-09 16:33
The `base.lua` module includes the following check to make sure that the widget that has been created is in fact a table:
`assert(type(widget) == "table", "Type should be table, but is " .. tostring(type(widget)))`

(NB: the call to `tostring()` is redundant in this case because `type()` always returns a string, but this is not the cause of the error.)

`base.lua` is called by several 'default' Awesome widgets, so if something obvious was broken (e.g. the function always returns a string instead of a table) we would be noticing in many places.

The return value of `make_widget_declarative` depends on the arguments it's called with (and, by extension, the arguments with which the `drill()` function is called). It should never return a string, but knowing the arguments that the-glorious-dotfiles passes to the function will help to determine what's causing this problem.

**Comment by Blakeinstein** [comment] 2022-02-10 06:52
> knowing the arguments that the-glorious-dotfiles passes to the function will help to determine what's causing this problem.

Here is the failing code in the glorius dotfiles, the first of, atleast
https://github.com/manilarome/the-glorious-dotfiles/blob/f3c7cae9ec45e5b3fc8ef93063df23ccbaab3838/config/awesome/linear/layout/control-center/init.lua?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L85-L119

Also suggested in the reddit post was another piece of failing config,
```lua
local bar = wibox.widget {
    bar_shape = gears.shape.rounded_bar,
    bar_color = beautiful.bg_focus .. "66",
    bar_active_color = "#5a189a",

    handle_shape = shape_helper.circle(10), // my helper
    handle_width = 0,
    handle_color = "#5a189a",

    value = 40,
    minimum = 0,
    maximum = 100,
    forced_width = 240,
    forced_height = 16,

    widget = wibox.widget.slider
}
```

Additionally, both blocks seem to work correctly somewhere around this speicific commit https://aur.archlinux.org/cgit/aur.git/commit/?h=awesome-git&id=e5bc47045c89d8906a4f5556306ac699ae4d77d0

**Comment by Aire-One** [comment] 2022-02-10 18:23
I have downloaded the linear theme from the glorious-dotfiles and I can confirm I have the issue. I'll investigate what's going on...

(Given the issue was only reproduced from this particular theme, I'll add the "user config help" label waiting we found what happens)

**Comment by Aire-One** [comment] 2022-02-11 09:05
I have found where the issue comes from, but it's hard to say for sure what exactly happens at this point of my investigation.

I had a chat with @sclu1034 on this topic. We came to the conclusion that there is a regression in Lua 5.4 require function. Here are the information we currently have:

Calling the `require` can return the module absolute path instead of the actual returned value of the module.

- This behavior seems to be triggered by calling (a lot of time?) the `require` function to generate anonymous "complex" objects.
- It doesn't seem to be randomly triggered, since it always happen at the exact same spot.
- This behavior only occurs with Lua 5.4, if I build awesome against Lua 5.3 for example, the error vanishes.

Hence, our conclusion that, the `require` function seems to be broken/have a regression with Lua 5.4.

Thanks, @latipun7, for pointing out more example of this bug. I didn't take the time to also investigate them, but given the circumstances, I guess this is exactly the same issue.

So now, I'll try to figure out an easy to reproduce scenario and escalate the issue to the Lua mailing list.

(CC @alerque, maybe you should revert the Lua 5.4 upgrade you applied to awesome/lgi arch and AUR package waiting for us to figure out a solution)

Side note: As a potential short-term fix (if you want to stick to Lua 5.4), we can overpass this behavior from by storing the generated object from the "widget.blue-light" module in a local variable (change to apply to the block of code @Blakeinstein linked earlier):

```lua
-- First store the module's returned object in a varible
local b = require('widget.blue-light')

local main_control_row_two = wibox.widget {
    layout = wibox.layout.flex.horizontal,
    spacing = dpi(10),
    format_item_no_fix_height(
        {
            layout = wibox.layout.fixed.vertical,
            spacing = dpi(5),
            require('widget.airplane-mode'),
            require('widget.bluetooth-toggle'),
-- Now, use the variable instead of calling require
            -- require('widget.blue-light')
            b
-- end of changes
        }
```

**Comment by Aire-One** [comment] 2022-02-11 09:12
@maths-lover That's an interesting finding! It's however not consistent with my results in my test environment, where I exclusively start awesome in Xephyr using the `--config` and `--search` flags to select the `rc.lua` and externals libs I want to use :thinking:

**Comment by sclu1034** [comment] 2022-02-11 09:27
Given that this seems to be an issue with Lua itself, all tests/test reports should include the full output of `awesome --version`.

@maths-lover Please check what versions of Lua/Awesome you're running your tests with.

**Comment by alerque** [comment] 2022-02-11 09:29
@Aire-One I'm following this, but just FYI the [community]/awesome package is still using Lua 5.3 pending several issues. The only one using it is currently the AUR/awesome-git package, and I think it's fair that that one follow the latest development attempts, 100% working or not.

The [community]/lua-lgi is available for 5.4, but the [community]/lua53-lgi variant is still available so I don't think anything needs doing in the official repos.

**Comment by maths-lover** [comment] 2022-02-11 12:24
@Aire-One
`awesome --version` returns the following

```
awesome v4.3-1349-g86b6c49a0 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```

And I'm running Archlinux with Linux kernel version 5.16.8 (if it even matters)
Lua 5.4.4 as indicated above

I'm not sure what else to include, but here it is for now.

**Comment by Aire-One** [comment] 2022-02-20 16:45
Ok, I fill a little stupid about that... I tried to wrap my head on this issue again. Turns out Lua 5.4 changed returned values of `require`.  See https://www.lua.org/manual/5.3/manual.html#pdf-require vs https://www.lua.org/manual/5.4/manual.html#pdf-require.

> In any case, require returns the final value of package.loaded[modname]. Besides that value, require also returns as a second result the loader data returned by the searcher, which indicates how require found the module. 

So basically, with Lua 5.4, `require` works like this `local mod, searcher = require "module"`. It means that when the glorious-dotfiles do `format_item_no_fix_height({ ..., require() })`, you have to expect `require` to return 2 values, and since it's the last item, Lua spread these 2 values (https://www.lua.org/pil/5.1.html).

This is the first call to `format_item_no_fix_height` from the `main_control_row_two` widget that we looked at earler:

![2022-02-20-172412_1151x187_scrot](https://user-images.githubusercontent.com/6602958/154852804-45424dbc-f40c-4f8f-86f6-54c83b9ff2ef.png)

As you can see, `widget` has the `layout` and `spacing` properties, as expected, then 4 (yeap, that's not 3) values:

- 1: `require('widget.airplane-mode')`
- 2: `require('widget.bluetooth-toggle')`
- 3 and 4: `require('widget.blue-light')`

I could have seen that before, I ran the debugger countless times on this call to understand what's going on, but somehow managed to miss it for too long...

Anyway. I guess we now have a clear understanding of the "bug". At the level of awesome, there is nothing more we can do. I'll close this issue and apply the "user-config-help". My suggestion would be to fix all these "wild" call to `require`, maybe use of `require("widget.something")[1]` everywhere can be enough :shrug: 

(ping @manilarome and @WillPower3309 since your Awesome WM configuration repositories were mentioned as affected by this new behavior)

**Closed by Aire-One** 2022-02-20 16:45 UTC
Labels: bug, confirmed, upstream, Lua 5.4

**Comment by WillPower3309** [comment] 2022-02-20 17:21
> Ok, I fill a little stupid about that... I tried to wrap my head on this issue again. Turns out, Lua 5.4 changed returned values of `require`.  See https://www.lua.org/manual/5.3/manual.html#pdf-require vs https://www.lua.org/manual/5.4/manual.html#pdf-require.
> 
> > In any case, require returns the final value of package.loaded[modname]. Besides that value, require also returns as a second result the loader data returned by the searcher, which indicates how require found the module. 
> 
> So basically, with Lua 5.4, `require` works like this `local mod, searcher = require "module"`. It means that when the glorious-dotfiles do `format_item_no_fix_height({ ..., require() })`, you have to expect `require` to return 2 values, and since it's the last item, Lua spread these 2 values (https://www.lua.org/pil/5.1.html).
> 
> This is the first call to `format_item_no_fix_height` from the `main_control_row_two` widget that we looked at earlier:
> 
> ![2022-02-20-172412_1151x187_scrot](https://user-images.githubusercontent.com/6602958/154852804-45424dbc-f40c-4f8f-86f6-54c83b9ff2ef.png)
> 
> As you can see, `widget` has the `layout` and `spacing` properties, as expected, then 4 (yeap, that's not 3) values:
> 
> - 1: `require('widget.airplane-mode')`
> - 2: `require('widget.bluetooth-toggle')`
> - 3 and 4: `require('widget.blue-light')` (the widget and the module path are spread, since it's the last item)
> 
> I could have seen that before, I ran the debugger countless times on this call to understand what's going on, but somehow managed to miss it for too long...
> 
> Anyway. I guess we now have a clear understanding of the "bug". At the level of awesome, there is nothing more we can do. I'll close this issue and apply the "user-config-help" tag. My suggestion would be to fix all these "wild" call to `require`, maybe use of `require("widget.something")[1]` everywhere can be enough :shrug: 
> 
> (ping @manilarome and @WillPower3309 since your Awesome WM configuration repositories were mentioned as affected by this new behavior)

Thanks a ton for the ping, I'll look into this!

**Comment by Blakeinstein** [comment] 2022-02-26 12:43
> Anyway. I guess we now have a clear understanding of the "bug". At the level of awesome, there is nothing more we can do. I'll close this issue and apply the "user-config-help" tag. My suggestion would be to fix all these "wild" call to `require`, maybe use of `require("widget.something")[1]` everywhere can be enough shrug

Since the glorius dotfiles have been archived, I will give a regex search and replace a shot. Not familiar with lua that much but I hope the following suffices

`(\s{2,})require\('(.*)'\)` replaced with `(\s{2,})require\('(.*)'\)` using vscode. Will update if it works, will also write a sed alternative

**Comment by sclu1034** [comment] 2022-02-26 15:16
> maybe use of `require("widget.something")[1]` everywhere can be enough

That would not produce the desired effect, and instead create weird behaviour based on whatever `widget.something` returns. You would not be indexing _the list of return values_, but _the first return value_. In most cases, it would be `nil`.

What you're looking for is `table.pack(require("<path>"))[1]`.

> `(\s{2,})require\('(.*)'\)`

A more accurate search regex for this particular issue would be something like `[,{][\s\n]*require\([^)]+\)[\s\n]*,?[\s\n]*\}`.
This
- checks (decently accurate) if it is the last or only entry in a table
- allows values other than just single-quoted strings as argument to `require` (e.g. double-quoted strings or variables)

**Comment by GentikSolm** [comment] 2022-04-07 05:56
What a goose chase this was to find, thank you so much for this.

**Comment by tkoeppe** [comment] 2022-06-24 19:49
Could you not just replace any bare `f()` with `(f())` to get only a single value out?
