### ISSUE TITLE
Awesome not changing tag on URL clicking.

### ISSUE THREAD

**Issue by osleg** [awesomeWM/awesome#455] opened 2015-09-16 14:21 UTC
2 tags, first tag with terminal second with firefox
Expected behaviour:
In terminal I have a URL, clicking on this url should focus FF and switch the tag to second.

Current Behaviour:
Clicking on link making focus switch to FF from terminal but the tag does not switching.

**Comment by blueyed** [comment] 2015-09-24 11:28
This is with master?
Has it changed recently?
Is it related to Firefox only?

**Comment by osleg** [comment] 2015-09-24 15:30
It is with master.
I've not idea when did it change since i was using 3.5.6 stable and then moved to git instantly.
Sadly I have no idea no ideas what else should work this way so I'm not sure whether it's FF only :)

**Comment by blueyed** [comment] 2015-09-24 15:47
You could try with another browser, from the command line.
I will look into this later in more depth.

**Comment by actionless** [comment] 2015-09-24 22:20
can this one fix your issue?
https://github.com/awesomeWM/awesome/pull/438

**Comment by blueyed** [comment] 2015-09-24 22:42
I can reproduce it using the default config (regarding `ewmh.activate`, the `request::activate` handler).

I've tried to bisect it, but it seems to be an issue for longer (HEAD~100 at least).
I've also tried #470, but that did not help.

The problem here is the unconditional `client.focus = c`, which will nowadays move the focus to the non-visible client.  This was not the case a while ago, and then the tag/client would have been marked as urgent.
That would be the expected behavior currently - and there is some (not really correct) [FAQ](http://awesome.naquadah.org/wiki/FAQ#Why_are_new_clients_urgent_by_default.3F) about restoring the previous behavior in that case.

Additionally, there appears some (newer?) issue with the taglist, which won't be updated for the urgent client in it.  The `urgent_count` seems to be handled properly, and moving to another tag (not the urgent one), will then display it as urgent.
The latter issue gets fixed / worked around with #474.

**Comment by blueyed** [comment] 2015-09-24 23:09
The problem with the tag widget not highlighting the urgent tag is this code (from https://github.com/awesomeWM/awesome/blob/0414a579c280a78887bf74b754389216311511ed/lib/awful/widget/taglist.lua#L49-L94):

    local sel = capi.client.focus
    …
    if sel then
        if taglist_squares_sel then
            -- Check that the selected client is tagged with 't'.
            local seltags = sel:tags()
            for _, v in ipairs(seltags) do
                if v == t then
                    bg_image = taglist_squares_sel
                    bg_resize = taglist_squares_resize == "true"
                    is_selected = true
                    break
                end
            end
        end
    end
    if #cls == 0 and t.selected and taglist_squares_sel_empty then
        bg_image = taglist_squares_sel_empty
        bg_resize = taglist_squares_resize == "true"
    elseif not is_selected then
        if #cls > 0 then
            if taglist_squares_unsel then
                bg_image = taglist_squares_unsel
                bg_resize = taglist_squares_resize == "true"
            end
            if bg_occupied then bg_color = bg_occupied end
            if fg_occupied then fg_color = fg_occupied end
        else
            if taglist_squares_unsel_empty then
                bg_image = taglist_squares_unsel_empty
                bg_resize = taglist_squares_resize == "true"
            end
            if bg_empty then bg_color = bg_empty end
            if fg_empty then fg_color = fg_empty end
        end
        if tag.getproperty(t, "urgent") then
            if bg_urgent then bg_color = bg_urgent end
            if fg_urgent then fg_color = fg_urgent end
        end
    end

The part handling "urgent" is never reached, because `is_selected` will be true.

**Comment by psychon** [comment] 2015-09-25 08:01
Hm, ok. I don't remember why I allowed focusing not-`c:isvisible()` clients. Perhaps that should be reverted? Alternatively, perhaps we should not unset urgent if a not-visible client gets focused and only do so when the client is focused *and* visible... Just some quick thoughts.

**Closed** 2015-09-25 08:15 UTC
Labels: bug

**Comment by blueyed** [comment] 2015-09-25 08:27
@psychon 
> why I allowed focusing not-`c:isvisible()`

It was me, in 2174b80c3fbb4ad6d380069dd02f7883f1258333 via https://github.com/awesomeWM/awesome/pull/118.

See also https://github.com/awesomeWM/awesome/issues/143#issuecomment-75123959.
