### ISSUE TITLE
Hang/freeze of Firefox (from v85 on), Chromium and Electron based apps

### ISSUE THREAD

**Issue by leonixyz** [awesomeWM/awesome#3241] opened 2021-01-05 09:11 UTC
Running awesome on Arch Linux.
~~~
awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
~~~

**Description**

The behaviour described here is happening since a long time, but I always thought it's Chromium/Electron's fault, because it only happened until now on Electron apps (and Chromium): Signal Desktop, Visual Studio Code, Sublime Text, Atom, Insomnia client (note that it does *not* happen with Rocketchat, which is AFAIK electron based as well). See as reference https://github.com/signalapp/Signal-Desktop/issues/2741

As suggested on that issue, I tried installing dunst but it does not start because naughty is taking precedence over it when registering the freedesktop:

```
CRITICAL: Cannot acquire 'org.freedesktop.Notifications': Name is acquired by 'naughty' with PID '670'.
```

In any case, I doubt this has to do with notifications, because AFAIK Sublime Text and Atom does not trigger any notifications at all, and I would rather blame either the compositor (xcompmgr in my case), or more probably how awesome is handling some unknown API which was used by Chromium/Electron since a while, and just sneaked into Firefox 85.

From a couple of days it also started happening with Firefox 85 (currently `firefox-developer-edition` package on Arch Linux). Firefox 84 seems still working fine on the very same environment, I have `firefox` package installed as well, and when I run that browser, the behaviour does not happen.

I will not be able to keep working for a long time with my beloved awesome if this starts happening on `firefox` as well. I can keep the package downgraded for some weeks, but at some point I will have to move away from awesome.

**How to reproduce the issue:**

The issue happens randomly. I wasn't able to track it down to any specific event, but it definitely happens consistently on Chromium/Electron based apps.

**Actual result:**

The content of the above mentioned program windows becomes unresponsive. Any window content is not updated. If you hide the window by clicking on the window title in the tasklist, the screen is updated and shows your wallpaper. If you then re-click on the tasklist to show the window again, just the window border is shown and the content keeps showing the wallpaper. MOD + SHIFT + C does not work, I have to kill the process manually.

**Expected result:**

The window content should keep being displayed as usual.

**Comment by psychon** [comment] 2021-01-05 09:20
Random idea: Does starting awesomeWM with `--no-argb` help? If so, that'd point fingers at your video driver / Xorg.

> (xcompmgr in my case)

What happens when you `pkill xcompmgr`? Does this make things visible again?

> because naughty is taking precedence over it

If you want to disable naughty's dbus support, try replacing `local naughty = require("naughty")` with `local old_dbus = dbus; dbus = nil ; local naughty = require("naughty") ; dbus = old_dbus`. (This hack will not with git/master.)

Alternatively, adding `package.loaded["naughty.dbus"] = {}` should work with any version of this Lua code (must be done before `naughty` is loaded, so best at the very beginning of the config).

**Comment by leonixyz** [comment] 2021-01-05 13:24
> What happens when you `pkill xcompmgr`? Does this make things visible again?

it does.

I will try disabling the compositer and see if the system becomes stable again.

Thanks

**Comment by unai-ndz** [comment] 2021-01-06 05:29
Any reason for using xcompmgr? If not you could try  picom or compton as an alternative.

**Comment by leonixyz** [comment] 2021-01-08 12:24
> Any reason for using xcompmgr? If not you could try picom or compton as an alternative.

actually no. The only one is to have my urxvt semi transparent so that i can put it over a browser and read the page while i'm typing into the terminal.

But it happens so rarely, and it can be avoided by simply using the tiling feature, than i'm thinking about not having any compositor at all

**Comment by leonixyz** [comment] 2021-01-08 12:36
In any case, it just happened again. And the compositor was not running. @psychon can we reopen the issue?

**Comment by actionless** [comment] 2021-01-13 06:28
> awesome v4.3 (Too long)

i remember that rocketchat-notifications issue (it was something about duplicating surface of notification icon), it must be fixed in the latest git master

**Comment by vincentbernat** [comment] 2021-01-14 19:34
it seems this issue happens with more and more app. I have it with Firefox and Discord and I remember that in the past, the issue didn't exist with Firefox. Also, there are reports than Telegram fixed it with: https://github.com/telegramdesktop/tdesktop/issues/8768. However, as there are many apps that would need "fixing", it may be better to understand what the problem is.

Random tests. I have added a callback to remove the icon and it doesn't change anything at all. I am unable to reproduce with `notify-send`, even with an icon. If I suspend the notifications, the problem is still here. Reloading awesome doesn't change a thing. Also, this is awesome that is freezing: typing in a terminal is not interrupted, but switching between windows is. Not having an icon does not solve the issue.

A convenient way to test: https://www.bennish.net/web-notifications.html

**Comment by vincentbernat** [comment] 2021-01-14 20:37
❦ 14 janvier 2021 12:20 -08, Uli Schlachter:

>> typing in a terminal is not interrupted, but switching between windows is.
>
> So, `awesome-client 'return 42'` still works? That would mean that
> AwesomeWM did not freeze / its main loop is still running.

No, awesome-client 'return 42' does not work. Note the freeze is short
for me. Less than two seconds.

>> Reloading awesome doesn't change a thing.
>
> This means you restarted AwesomeWM and the problem persists? Uhm. That makes no sense to me.
> I'm still tempted to blame Xorg / the video driver, but I have no idea what could happen there.
>
> Did anyone yet try whether [starting AwesomeWM with `--no-argb`
> helps](https://github.com/awesomeWM/awesome/issues/3241#issuecomment-754513513)?
> That's the usual trick to make video driver bugs that only AwesomeWM
> triggers go away.

No change for me. Note that the problem happens when NOT displaying a
notification (by suspending them with naughty.suspend()).

From the Signal bug report, I would think something DBus related.
Awesome is using an asynchronous request to receive information and for
some reason, it takes time.

**Comment by actionless** [comment] 2021-01-15 04:31
i still recommend first trying with the latest git master, because all the details of this issue are extremely familiar to the one which was already fixed

**Comment by leonixyz** [comment] 2021-01-15 06:52
I'm pretty sure @vincentbernat is having a different kind of problem.

* When the abovementioned apps freeze, I'm still able to switch between windows, and the non-freezed ones works as usual. If i open a new terminal window and execute `awesome-client 'return 42'` I get `double 42` as output
* Moreover, the freeze does not last just 2 seconds. As i already wrote in the first comment, I have to manually kill the app.
* Restarting awesome (i suppose the default key bind is modkey+CTRL+R) does not fix the issue.
* `--no-argb` does not work, I just managed to reproduce the behaviour, once in an awesome session started without the parameter, and then in another one started with the parameter. The apps freezing in my case were Atom and Signal.

**Comment by vincentbernat** [comment] 2021-01-15 08:10
OK, sorry for derailing the issue. I will try with master and open a new bug if it still happens with me.

**Comment by actionless** [comment] 2021-01-15 09:28
@leonixyz

> However, before trying --no-argb I was still running xcompmgr, and when one window did freeze, i killed xcompmgr and it fixed the problem.

so just to summarize, does any of symptoms you describing are happening (*without* compositor running) 1) with `--no-argb`  2) without `--no-argb`

if answer to both of the questions is "no" -- that might be a problem in compositor itself

in case if second answer is 'yes' -- that might be even more tricky, as the problem could be anywhere, even in video driver

**Comment by DGoedtkindt** [comment] 2021-02-11 11:48
To answer @actionless.  
I have the same issue where at random moments nearly all my windows would freeze until I quit awesome. I tried with and without  ```--no-argb```, with not effect. I don't use a compositor.

**Comment by DGoedtkindt** [comment] 2021-02-16 07:27
I have an idea of what causes the problem. I use the xf86-video-intel driver on Arch. I heard that this drivers causes problems and indeed since I deactivated it two days ago I haven't had a single transparent window freeze.

**Comment by groceryheist** [comment] 2021-03-15 05:40
I also found that disabling the xf86-video-intel driver resolves the issue. I was having the issue in debian 11.

**Closed** 2021-04-01 15:17 UTC
Labels: hardware, upstream
