### ISSUE TITLE
GUI not responding to mouse input after bluetooth headset is activated

### ISSUE THREAD

**Issue by hakunamenta** [awesomeWM/awesome#635] opened 2016-01-16 21:55 UTC
Whenever i connect my bluetooth headset via blueman-applet, all GUI elements of awesome stop responding to mouse input.  Other X clients are unaffected and the icons of other programs also still work as expected.  The problem persists after i switch of the bluetooth device.  this problem does not occur in plasma thus it might be a bug of awesome.

Versions of software in use:
% awesome --version
awesome v3.5.6 (For Those About To Rock)
 • Build: May  5 2015 05:45:29 for x86_64 by gcc version 5.1.0 (builduser@)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔

% blueman-applet --version
blueman-applet version 2.0.2 starting

Xorg version:
Name                 : xorg-server
Version              : 1.18.0-4

% lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

**Comment by nereusx** [comment] 2016-01-16 22:03
I have notice it too, but when I change keyboard layout (language). The keyboard commands work well but I didnt test it well.

**Comment by psychon** [comment] 2016-01-17 10:25
Duplicate of #415. Close all your running Qt apps and it will work again. Qt is stealing our input events (=asking for them in a way so that we do not get them). Some part of a work around is in https://github.com/awesomeWM/awesome/commit/a86d1137eeaa70e6cc138e2a0b89f2e6196a08f7, but I cannot do anything about Qt stealing mouse clicks on the root window.

**Closed by psychon** 2016-01-17 10:25 UTC

**Comment by hakunamenta** [comment] 2016-01-17 15:02
thank you psychon.  terminating some qt apps did indeed help. but there are still some qt apps running.  is there a way to find out which app is "responsible" ?

**Comment by psychon** [comment] 2016-01-17 15:23
@hakunamenta When a new input device appears, the X11 server says "hey everyone, there is a new slave device". Qt wants to know from which device a mouse event came and thus it re-requests all its "I want information about mouse events"; however, this time it does so in a slightly different way.

The above is done by Qt everywhere. So really, all of them should cause this.
And no, I don't know of any way to read the eventmasks out from X.org (well, gdb could work, but that does not count).

**Comment by hakunamenta** [comment] 2016-01-17 15:31
just curious: is this X specific?  or could similar problems occur when all windows are using wayland?

**Comment by psychon** [comment] 2016-01-18 07:48
This is in Qt's XCB code, so just alone makes it X specific. Then, AFAIK one of the goals of Wayland is to be safer than X11 and just from that I would expect that clients cannot steal each other's input events (oh and in Wayland, Awesome would be the compositor, so it would decide which clients gets an input event; there is no X11 server).
