### ISSUE TITLE
taglist sometimes doesn't update it's highlighting

### ISSUE THREAD

**Issue by holgerschurig** [awesomeWM/awesome#1322] opened 2016-12-28 17:26 UTC
Output of `awesome --version`:

awesome v4.0-13-g9077dec (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

It is reproducible with the standard rc.lua in a Xephyr: `DISPLAY=:1 awesome -c /etc/xdg/awesome/rc.lua`

Now enter two clients on different tags: `Mod4+Enter Mod4+2 Mod4+Enter`

Notice that switching between the tags always updates the highlighting in the taglist: `Mod4+1 Mod4+2 Mod4+1 Mode+2`

But when you switch to an empty tag and then back to a populated tag, the highlighting won't be updated (the clients from tag 2 will be shown, it's just in the taglist): `Mod4+3 Mod4+2`

The taglist get back into sync if I switch to a populated tag: `Mod4+1 Mod4+2`

**Comment by psychon** [comment] 2016-12-28 19:17
What's your video driver? Can you Mod4+Left-click a client to move and move it over the taglist and back again? Does that update the part of the tasklist that was covered by the client (while the rest still stays "wrong")?

**Comment by cyberxndr** [comment] 2016-12-29 07:25
I can confirm the issue. Moving client with Mod4+Left-click correctly refreshes taglist and tasklist. Videodriver is `vboxvideo`.

**Comment by holgerschurig** [comment] 2016-12-29 09:02
I used Xephyr, as I already wrote.

On my main X11, I'm using modesetting according to my /var/log/Xorg.log.0. I'm still at OpenBox until awesome works comforbly at my home desktop. BTW, I'm using some awesome 3.x version on my company desktop without this issue, so it's probably an awesome 4.x issue.

I doubt however that bug has anything to do with the video driver, I use the same driver since months and no other X11 app has any issues updating any contents. I quickly updated X from Debian SID, so now my modesetting driver is 1.18.4, but the awesome bug is still there.

**Comment by holgerschurig** [comment] 2016-12-29 09:05
BTW, I can't find where I can assign the "Bug" label to this issue

**Comment by holgerschurig** [comment] 2016-12-29 09:06
Ah, I hate this github thingy. Now I closed this issue accidentally and can't open it again.

**Comment by psychon** [comment] 2016-12-29 09:17
Does starting awesome with `--no-argb` make the issue go away for you, too? It does for me.
(All of this points to video-driver-or-Xorg-bug, but since no one ever believes me when I claim that, I will stop repeating it)

**Comment by cyberxndr** [comment] 2016-12-29 09:40
`--no-argb` fixes the problem for me

**Comment by taptap** [comment] 2016-12-29 12:06
Issue in question happened to me too, but after I switched from nvidia proprietary blob to free radeon driver on awesome 3.5.
Haven't yet tested it on 4.0 though.

I too suspect that this is video driver/Xorg bug.

**Comment by psychon** [comment] 2016-12-29 14:52
The result of one more day with banging my head against Xorg's source code is: https://bugs.freedesktop.org/show_bug.cgi?id=99220
That bug also has a "patch" which "makes the problem go away" by needlessly having the server do more work than should be necessary. This patch should not have any effect, but since it does, something wrong is going on inside of the server. Feel free to bribe some Xorg developer into looking into this issue.

**Comment by actionless** [comment] 2017-02-08 19:57
can this be closed?

**Comment by psychon** [comment] 2017-02-09 11:09
Closing as a combination of "reporter disappeared", "fixed by --no-argb" and "upstream bug https://bugs.freedesktop.org/show_bug.cgi?id=99220 (which also has fixes pending)".

**Closed by psychon** 2017-02-09 11:09 UTC
Labels: bug, confirmed, no-argb, upstream

**Comment by psychon** [comment] 2017-05-25 13:53
Upstream bug was just (supposedly) fixed.
