### ISSUE TITLE
Problem with hotkeys

### ISSUE THREAD

**Issue by aoleynichenko** [awesomeWM/awesome#1638] opened 2017-03-07 05:59 UTC
It seems that hotkey combinations which contains letter keys ("s", "r", etc) don't work. However, Mod4+Enter works properly (opens Terminal). I've tried to modify the rc.lua file as follows (to activate Run):
`
-- Prompt
awful.key({ modkey },            "#27",     function () awful.screen.focused().mypromptbox:run() end,
              {description = "run prompt", group = "launcher"}),`

Suprisingly it works for me (keycode of 'r' is equal to 27 on my laptop).
What may be wrong? My clumsy solution solves the problem, is it possible to suppose more elegant one?

King regards,
Alexander

----------------------------------------------------------------------
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**
My locale:
[username@servername ~]$ locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=

**Comment by psychon** [comment] 2017-03-07 08:25
What's your keyboard layout? (Output of `setxkbmap -query`)

**Comment by aoleynichenko** [comment] 2017-03-07 16:36
psychon,


$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     ru,us
options:    terminate:ctrl_alt_bksp,grp:alt_shift_toggle,grp_led:scroll

**Comment by psychon** [comment] 2017-03-07 17:30
I guess the problem is (at least partially) that there is no "r" key on your keyboard: https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/KB_Russian.svg/2000px-KB_Russian.svg.png

**Comment by aoleynichenko** [comment] 2017-03-07 18:43
psychon,

certainly, you are right :) of course, I've switched to the us keyboard layout before I try to use shortcute in Awesome. However, hotkeys defined via the keycodes (as I've described above) works even under Russian keyboard layout, too

**Comment by actionless** [comment] 2017-03-10 16:27
just a random guess, if switching the order of layouts from `ru,us` to `us,ru` changing the behavior?

**Comment by captainju** [comment] 2017-03-17 08:52
I have the same bug, on a french keyboard 

➜  ~ setxkbmap -query
rules:      evdev
model:      pc105
layout:     fr,fr
variant:    bepo,azerty
options:    grp:shifts_toggle,grp_led:scroll

➜  ~ awesome --version
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

modkey + <key> doesn't work for a few keys, but it works with a modifier, for example modkey + CTRL + <key>

**Comment by nicodebo** [comment] 2017-03-17 11:49
### Issue

I'm not sure if my issue is related to this one but I have similar issues on a french keyboard layout.

### mappings and related errors

I have remapped : 

* `Super+à` to `lua execute prompt`
* `Super+z` to `run prompt`

and those mappings give me the following errors; respectively:

* /home/debz/.config/awesome/rc.lua:330: attempt to index a nil value (field 'mypromptbox')
* /home/debz/.config/awesome/rc.lua:323: attempt to index a nil value (field 'mypromptbox')

However, those hereabove errors does not trigger when I keep the default mappings of awesome.

### rc.lua

The related lines of my rc.lua:
```lua
   323	    awful.key({ modkey },            "z",     function () awful.screen.focused().mypromptbox:run() end,
   324	              {description = "run prompt", group = "launcher"}),
```

```lua
   326	    awful.key({ modkey }, "à",
   327	              function ()
   328	                  awful.prompt.run {
   329	                    prompt       = "Run Lua code: ",
   330	                    textbox      = awful.screen.focused().mypromptbox.widget,
   331	                    exe_callback = awful.util.eval,
   332	                    history_path = awful.util.get_cache_dir() .. "/history_eval"
   333	                  }
   334	              end,
   335	              {description = "lua execute prompt", group = "awesome"}),

```

### Misc info

```
$ awesome --version
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     fr
variant:    bepo
```

**Comment by fishman** [comment] 2017-03-19 21:00
i just spent some time debugging this. for me it's fixed when i disable the normal keymap and go full dvorak

`Option "XkbLayout" "us"` instead of `Option "XkbLayout" "us,de"` (us is with variant dvorak)

Also interesting thing is that when i use a xmodmap with keysym and I execute it during xinitrc it seems to map different keys than after running it in a terminal in awesome.

in the terminal it will map the proper keysyms but when run in xinitrc it will map the non variant version

so `keysym e = e E EuroSign` would lead to 2 e  keys. the same happens when I run the xmodmap command inside of rc.lua

it's unclear to me if this is an issue of xorg or awesome

**Comment by Elv13** [comment] 2017-06-02 02:38
@nicodebo The `nil` value error is clearly due to changes to your config, the keybinding is definitely triggered.

As for the other issue where the `r` key doesn't exist. If it doesn't exists, then the keybinding wont fire, I think this is logical. The keybinding is *on the symbol*, not the keycode. I will close this for now. There is other open issues that track the real corner case where this breaks (like changing layouts).

**Closed by Elv13** 2017-06-02 02:38 UTC

**Comment by MarvelWild** [comment] 2021-05-29 08:57
Issue is closed, but i have same problem.

**Comment by Luis-Licea** [comment] 2023-01-03 03:35
@MarvelWild I suppose the solution is to use `xev` to figure out the keycode for each letter. For example:
```lua
-- Use `xev` to get the key codes.
local keys = {
    q = "#24",
    w = "#25",
    e = "#26",
    r = "#27",
    t = "#28",
    y = "#29",
    u = "#30",
    i = "#31",
    o = "#32",
    p = "#33",

    a = "#38",
    s = "#39",
    d = "#40",
    f = "#41",
    g = "#42",
    h = "#43",
    j = "#44",
    k = "#45",
    l = "#46",

    z = "#52",
    x = "#53",
    c = "#54",
    v = "#55",
    b = "#56",
    n = "#57",
    m = "#58",
}
globalkeys = gears.table.join(
    -- Replace "j" with keys.j
    awful.key({ modkey,           }, keys.j,
        function ()
            awful.client.focus.byidx( 1)
        end,
        {description = "focus next by index", group = "client"}
    ),
    -- Replace "k" with keys.k
    awful.key({ modkey,           }, keys.k,
        function ()
            awful.client.focus.byidx(-1)
        end,
        {description = "focus previous by index", group = "client"}
    )
)
```

**Comment by slava110** [comment] 2023-08-20 15:01
@Elv13 is it possible to have some kind of key-to-keycode conversion by default in AwesomeWM?
Table with keys made by @Luis-Licea is a workaround. While it works, it isn't ideal. Not only it doesn't exist by default (and you need to manually replace all these keys in `rc.lua` with `keys._` after installation), but it also doesn't show key names in the help menu.
![image](https://github.com/awesomeWM/awesome/assets/26705162/a87e14eb-4ca9-497d-8442-5d27ff0cef02)

**Comment by psychon** [comment] 2023-08-27 09:38
> some kind of key-to-keycode conversion by default in AwesomeWM

Random side-comment: Keyboard layouts are complicated. I am not quite sure what you mean with `key`, but I guess / fear that keyboard layouts do not work that way and are way more complicated.

Example: Keys like `a` are simple which can only generate `a` and `A`, but e.g. my `e` key can do all of `e`, `E`, `€`. 

Example: The caps-lock key. is a locked modifier. And XKB also has the concept of latched modifiers (like caps-lock, but automatically de-activates after the next key press).

Example: All the contents of https://github.com/xkbcommon/libxkbcommon/blob/master/src/x11/keymap.c just exist to query information about the keyboard layout from the X11 server and to translate it into the format that is used internally by xkbcommon. And this feels like a lot of code just for this.
