### ISSUE TITLE
Is this resizing behavior normal?

### ISSUE THREAD

**Issue by der-zonk** [awesomeWM/awesome#3339] opened 2021-04-27 19:33 UTC
Output of `awesome --version`:

```
awesome v4.3-992-gfda950d18 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

compiled awesome-git from AUR with yay, copied rc.lua & mytheme.lua from apidoc, added gaps to the mytheme.lua. If I resize with the mouse using the titlebar, the windows freak out.. It's the same without gaps but it's not as bad as with gaps. I was told this might be a bug and that I might want to share here.. reference: https://www.reddit.com/r/awesomewm/comments/my1rll/is_this_resizing_behavior_normal/
I made a new video with the new rc.lua applied.. it's basically the same as before..

**Actual result:**

https://imgur.com/0Sv5WJ7

**Expected result:**

Not wonky resizing maybe? If it's not a bug then it's the worst first impression I had from a wm..

**Comment by actionless** [comment] 2021-04-28 05:11
duplicate of https://github.com/awesomeWM/awesome/issues/424

**Closed by actionless** 2021-04-28 05:11 UTC
