### ISSUE TITLE
mpv's window-dragging feature doesn't work in awesome

### ISSUE THREAD

**Issue by sammoth** [awesomeWM/awesome#2980] opened 2020-02-01 20:11 UTC
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Open a video in mpv with it floating and its window-dragging feature enabled, eg `mpv --window-dragging xxx.mp4`. It's supposed to let you grab the window with the left mouse button on the picture and drag it around.

**Actual result:**

The window doesn't move

**Comment by psychon** [comment] 2020-02-01 20:27
Assuming I followed the code correctly:

- `--window-dragging` sets some `allow_win_drag` variable: https://github.com/mpv-player/mpv/blob/05fb6f906de25016faff2bdedd1f47f1e4077554/input/input.c#L202 (which, by the way, defaults to "enabled" https://github.com/mpv-player/mpv/blob/05fb6f906de25016faff2bdedd1f47f1e4077554/input/input.c#L220)
- This variable is used here: https://github.com/mpv-player/mpv/blob/05fb6f906de25016faff2bdedd1f47f1e4077554/input/input.c#L1069-L1076
- And that function is used here: https://github.com/mpv-player/mpv/blob/93a6308bb762dc1c43e0301c7b6e977078bead9c/video/out/x11_common.c#L1168-L1187

Looks like this uses `_NET_WM_MOVERESIZE`. Assuming I am right, this is a duplicate of #2140.

**Closed by psychon** 2020-02-01 20:27 UTC
Labels: duplicate, enhancement
