### ISSUE TITLE
Awesome freezes for a few seconds after switching TTY's on Xfce4

### ISSUE THREAD

**Issue by K4in-5037** [awesomeWM/awesome#1686] opened 2017-03-30 18:28 UTC
**Output of `awesome --version`:**

awesome v4.1-dirty (Technologic)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.0

Using Xfce 4.12

**How to reproduce the issue:**

1. Open a xfce4 X11 session.
2. Run awesome
3. Switch to another tty via alt+ctrl+F[1-12]
4. Return to your previous tty in which awesome is running  

**Actual result:**

Awesome is unresponsive for about 15 seconds, in this time shortcuts and mouse input doesn't work, however keyboard input works in the focused windows, then the queued actions execute and it returns to normal function.

**Expected result:**

To be responsive immediately after switching TTY's

I'm attaching the error output of awesome when reproducing this issue, I think it will be helpful 
[awesome.log.txt](https://github.com/awesomeWM/awesome/files/883400/awesome.log.txt)

**Comment by psychon** [comment] 2017-03-31 07:28
Could you test if this is a duplicate of #1494? I.e. do you get exactly the same result when running `xmodmap <(for x in $(seq 1 1000) ; do echo "keycode 107 = parenleft " ; done)` in a shell? (Perhaps you should try `seq 1 100` first instead of `seq 1 1000`, 1000 might be a bit high and take a long time...)

**Comment by K4in-5037** [comment] 2017-03-31 16:06
Yes, that seems to be the case, I can reproduce the same behavior with that script, though I didn't have xmodmap installed so I guess xfce do something to the keyboard configuration when you change tty's?

**Comment by K4in-5037** [comment] 2017-04-02 17:58
I'm going to answer my previous question with a yes, xfce modifies or updates the keyboard layout everytime the TTy is changed, I found a workarround in the xfce settings manager > keyboard > layout, there is a checkbox that says "use default system options" if I uncheck that the problem disappear, I'll leave it like that since I have my options configured directly in the xorg files but still this might be a nuisance for those who use the xfce config panel to set their keyboard layouts.

**Closed** 2017-04-02 18:12 UTC
