### ISSUE TITLE
Panel not responding mouse when I switching to russian keyboard

### ISSUE THREAD

**Issue by egordorichev** [awesomeWM/awesome#196] opened 2015-04-04 07:20 UTC
Good morning! I found bug: when I'm switching to Russian keyboard, top panel not responding.

**Comment by psychon** [comment] 2015-04-04 08:01
Same bug in the old tracker: https://awesome.naquadah.org/bugs/index.php?do=details&task_id=982

**Comment by egordorichev** [comment] 2015-04-04 08:57
Im using gentoo. Should I install patch from the old tracker?

**Comment by vdrandom** [comment] 2015-04-04 09:40
Both workarounds still work well enough, although I'd prefer some kind of workaround to be implemented in awesome itself (don't like the idea of manually editing / patching packages or making one of the files in the package immutable).

**Comment by osleg** [comment] 2015-04-04 09:42
Wow thanks @egordorichev, I was wondering why sometimes I'm unable to close notifications or click on tags with mouse, nice finding!

**Comment by egordorichev** [comment] 2015-04-04 10:00
Thanks, @osleg.

**Comment by cmgrange** [comment] 2015-04-30 05:51
Have same issue.
awesome v3.5.6
xkbcomp 1.3.0

**Comment by Suseika** [comment] 2015-05-10 06:51
This issue has been bugging me for years, please fix.

**Comment by Temp24354** [comment] 2015-05-11 10:52
Please!

**Comment by blueyed** [comment] 2015-05-11 11:03
The issue in the old tracker (https://awesome.naquadah.org/bugs/index.php?do=details&task_id=982) has a patch.
Please try it and report back if it works for you.

**Comment by Temp24354** [comment] 2015-05-11 11:22
I have built awesome from git and now that's what works: if I set up keyboard layouts using rc.lua (http://awesome.naquadah.org/wiki/Change_keyboard_maps) and change layout to russian, all the keybinds and mousebinds work properly (have not checked simple setxkbmap, but there should be no difference). Seems like everything is OK now.
Could you please have a look at this bug?: https://github.com/awesomeWM/awesome/issues/219

**Comment by Temp24354** [comment] 2015-05-11 11:43
I have built Awesome from git and that's what I can see: 
If switching layouts is implemented via setxkbmap, all the keybinds and mousebinds work fine with both Russian and English layouts. 
If switching layouts is implemented using rc.lua (http://awesome.naquadah.org/wiki/Change_keyboard_maps, AwesomeWM solutions), then Awesome's keybinds work with any layout, but other windows' keybinds (such as firefox) only work with English layout.
P.S. Could you please have a look at https://github.com/awesomeWM/awesome/issues/219 when you have time?

**Comment by vovkav** [comment] 2015-05-11 19:23
plz, fix

**Comment by blueyed** [comment] 2015-05-12 12:23
Has anybody tried the patch?

"plz, fix" etc won't help much, but a pull request would.

**Comment by Temp24354** [comment] 2015-05-12 13:10
I have now applied this patch to x11-xkb-utils and built it, restarted system 
With awesome 3.5.6 it did not solve the bug, while with awesome built from git there is no such problem (even without x11-xkb-utils patch).

**Comment by actionless** [comment] 2015-05-12 13:41
i can confirm what not able to reproduce it on current git

**Comment by Temp24354** [comment] 2015-05-12 18:29
So, it seems like in current git-version this bug no longer reproduces.

**Comment by egordorichev** [comment] 2015-05-13 08:41
Ok. I will try git version.

**Comment by egordorichev** [comment] 2015-05-23 05:20
No. Bug stayed in git version.

**Comment by anton-tsyganenko** [comment] 2015-06-09 15:15
confirm this bug, fixed after installing git version (awesome-git from arch user repository)

**Comment by anton-tsyganenko** [comment] 2015-06-09 15:39
Oops, in aur was awesome-git-3.5.2.433.ge30a8c1-1. So I confirm the bug, but didn't test the latest git version.

**Comment by Elv13** [comment] 2015-06-09 18:04
Can you try with https://github.com/awesomeWM/awesome/pull/227 ?

**Comment by anton-tsyganenko** [comment] 2015-06-09 19:02
Should I 3.5.6 or master (which looks to work)?

**Comment by Elv13** [comment] 2015-06-09 19:08
This
https://github.com/petoju/awesome.git

**Comment by anton-tsyganenko** [comment] 2015-06-09 19:15
It works, just as master. And I'm unable to change the layout:
![2015-06-09-221337_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4764069/8067216/fea2e912-0ef4-11e5-917a-0dbeffa00fa2.png)

**Comment by Elv13** [comment] 2015-06-09 19:24
Known issue, the API changed and is (currently) not compatible (the argument order changed). We may or may not hack this to support the old API. This require some free time, and none of us have any ;)

So glad to know, I will close this as a duplicate of #227

**Closed by Elv13** 2015-06-09 19:24 UTC

**Comment by anton-tsyganenko** [comment] 2015-06-09 19:27
Sorry for offtopic, when are you going to release next version?

**Comment by Elv13** [comment] 2015-06-09 19:30
when its ready

**Comment by anton-tsyganenko** [comment] 2016-01-30 14:10
This bug looks not to be fixed in awesome 3.5.7-1 (arch). I request re-opening.

**Comment by blueyed** [comment] 2016-01-30 14:47
@anton-tsyganenko 
3.5.7 only got a few fixes, and apparently not https://github.com/awesomeWM/awesome/pull/227.

**Comment by psychon** [comment] 2016-01-30 17:10
#227 isn't a fix, it adds a new feature. That's not something that should be added to the stable branch. As we recently demonstrated, the 3.5 branch isn't really tested before a release and thus I don't think we should backport more stuff than we already do.

**Comment by barwinko** [comment] 2016-01-31 16:30
Nothing changed with 3.5.8 release. I still can't click on panel elements (tags, task-tabs, tray) when my keyboard layout is Cyrillic.
```
awesome v3.5.8 (Major Tom)
 • Build: Jan 31 2016 18:13:00 for x86_64 by gcc version 5.3.0 (@T420)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
``` 
```
xkbcomp 1.3.1
```
workaround like years before: use xkbcomp 1.2.3

**Comment by psychon** [comment] 2016-02-01 08:56
Sorry, but that workaround will stay as long as awesome 3.5 stays.

**Comment by haata** [comment] 2016-02-06 06:06
Building awesome from master works for me!

This issue also shows up when plugging in certain peripherals after X starts up. Particularly mice.
Been bugging me for months, thanks a lot!
