### ISSUE TITLE
Client keys no longer work after upgrade to 3.5.7

### ISSUE THREAD

**Issue by baguette** [awesomeWM/awesome#656] opened 2016-01-27 15:52 UTC
After upgrading to 3.5.7, none of my client keys work at all. Global keys still work fine. I've tried restarting awesome with no luck. I've had to downgrade to 3.5.6 for the time being to get my client keys back.

**Comment by psychon** [comment] 2016-01-27 16:44
Since it happens with 3.5.7, it's likely a duplicate of https://github.com/awesomeWM/awesome/issues/639 / https://github.com/awesomeWM/awesome/issues/640 / https://github.com/awesomeWM/awesome/issues/646.
Do you do anything keyboard-layout related? Perhaps run something that implements per-window keyboard layout? Anything else that might change keyboard layouts "a lot"?

**Comment by baguette** [comment] 2016-01-27 17:22
I only have a single call to setxkbmap to swap caps lock and control in my rc.lua. As far as I know, there's nothing else keyboard-related going on.

**Comment by psychon** [comment] 2016-01-27 17:31
Hm... ok, then I'm out of ideas. This happens with all programs (e.g. a terminal?) and not just with  some special one? Obviously this works for other people out there, so "something" must be different for you.

Does it also happen with the default rc.lua? Just the X server and awesome running? Any other ideas? Are you perhaps on gentoo and can easily test the patch from #639?

**Comment by baguette** [comment] 2016-01-27 19:05
All programs, as far as I can tell. CRUX user, actually. I'll test the patch after I get off work tonight :)

**Comment by baguette** [comment] 2016-01-28 16:49
Sorry for taking so long to get back to you. The patch works beautifully. I took the liberty of including it with the awesome port for CRUX. Thank you!

**Comment by baguette** [comment] 2016-01-28 16:50
I should mention, though you're probably already aware, that building from master also works fine :)

**Closed** 2016-01-28 16:49 UTC

**Comment by psychon** [comment] 2016-01-28 17:14
Sounds like I should do the cherry-pick that someone recently requested and get 3.5.8 out of the door this weekend...
