### ISSUE TITLE
Background of transparent icons in systray is not refreshed

### ISSUE THREAD

**Issue by petoju** [awesomeWM/awesome#2449] opened 2018-10-22 22:18 UTC
Output of `awesome --version`:

awesome v4.2-496-g2458f127-dirty (Human after all)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

1. Update to Ubuntu 18.10 with awesome built from latest head, maybe unknowingly break drivers (3D acceleration and games still work)
2. Look into systray 

**Actual result:**

In systray, background of transparent icons is not refreshed. Background of systray itself is fine, but background of transparent icon gets color of last window or window border being there. Foreground is also fine.

**Expected result:**

Background of icons will be consistent independently from what was above the icons before.

Note: this issue is similar to other systray problems, but this differs from each of them at least a bit. I have the solution, that works for me.

**Comment by petoju** [comment] 2018-10-22 22:22
Fix for this is in
https://github.com/awesomeWM/awesome/pull/2450

**Comment by psychon** [comment] 2018-10-23 06:05
Here is a screenshot of my wibar. As you can see, at the right side there is a tray icon with a transparent background. This tray icon correctly shows the background color of my wibar.

![foo](https://user-images.githubusercontent.com/89482/47339031-36f2f580-d69a-11e8-9ffb-e5dae3f0bb03.png)

So, could you perhaps provide some more information? Anything that might be different between your system and mine?

**Comment by psychon** [comment] 2018-10-23 06:08
> background of transparent icon gets color of last window or window border being there.

> this issue is similar to other systray problems, but this differs from each of them at least a bit.

How is it different from #2190? To me, this just sounds like another problem caused by Qt grabbing a screenshot and just using that for the background of its systray icon. (Although that doesn't explain why your patch then fixes this...)

That issue then links to #1720, #1738, #1856, #283, #176, and #1947. I didn't look at all of them, I just copied over the list from #2190, but how come you are sure that your issue is different than all of these?

**Comment by McSinyx** [comment] 2018-10-23 07:31
Slightly related to [this GTK+ 3 systray bug](https://old.reddit.com/r/awesomewm/comments/9jlsef/my_system_tray_displays_the_icons_somehow_broken/):

![](https://i.redd.it/l97nf2c7hyo11.png)

I'm leaving it here so that others can find it through issue search.

**Comment by psychon** [comment] 2018-10-23 07:48
Uhh, yeah, that bug... That one would actually be "fixed" by @petoju 's patch.

@petoju Do you happen to be running GTK 3.24?

**Comment by McSinyx** [comment] 2018-10-23 08:10
I'm on GTK+ 3.24 and can reproduce the bug easily with nm-applet and ibus applet (please ignore the black frame which is caused by scrot's glitch):

![2018-10-23-150914_144x36_scrot](https://user-images.githubusercontent.com/13689192/47345725-aa662880-d6d5-11e8-9568-3e9755af1891.png)

**Comment by kajzersoze** [comment] 2018-10-23 08:38
I'm having this problem only with Qt apps and only when Awesome is restarted, I'll try mentioned patch, hope it solves it, because it's annoying...

**Comment by kajzersoze** [comment] 2018-10-23 08:58
The patch doesn't fix the problem with Qt apps, same thing happens, nothing changed.

**Comment by sbraz** [comment] 2018-10-23 21:47
I've bisected GTK and this was introduced by [x11: Always set None pixmap for no background](https://github.com/GNOME/gtk/commit/01d1bc3c75fd0eff5665f5b9c690c5e1e6c65f13). Should I open a GTK bug?

**Comment by petoju** [comment] 2018-10-23 21:54
sbraz: I just linked the GTK bug and they refer to the change you also found.

**Comment by psychon** [comment] 2018-10-24 06:32
Closing, since this is a bug in GTK and not in awesome. This is broken in GTK 3.24 and works in any other version of GTK. Please subscribe to the GTK bug tracker for getting a notification when GTK fixes this. In the mean time, I guess you can build your own, local version of GTK with https://github.com/GNOME/gtk/commit/01d1bc3c75fd0eff5665f5b9c690c5e1e6c65f13 reverted.

Sorry that this cannot be worked around in awesome (without doing "ugly stuff" that should not be done with tray icons).

**Closed by psychon** 2018-10-24 06:32 UTC

**Comment by KhaimovMR** [comment] 2019-09-04 10:04
I don't know if it's related, but I too leave it here: http://i.imgur.com/YkTlkbM.png
