### ISSUE TITLE
May not be a bug of awesomewm--recent update of google-chrome does not automatically redraw the client

### ISSUE THREAD

**Issue by liquiddandruff** [awesomeWM/awesome#195] opened 2015-04-03 06:12 UTC
Say google-chrome is maximized on desktop 1 and the user switches to desktop 2.

When switching back to desktop 1, everything that google-chrome would have covered is not updated--we see a freeze frame of pixels from desktop 2, with the exception of explicit redraws from animated view elements, ie the blinking of the cursor in a textbox. Forcing a client redraw with super+F by fullscreening the client returns chrome to normal.

Here's what it looks like. Have anyone else experienced similar problems?

![selection_003](https://cloud.githubusercontent.com/assets/2075654/6978777/36a71f00-d98e-11e4-9bd9-88d8c33a5c6f.png)

**Comment by vdrandom** [comment] 2015-04-03 08:35
I don't (nvidia with proprietary driver). Which GPU do you use? I've encountered similar problems with the awesome bar on Intel HD on my laptop.

**Comment by liquiddandruff** [comment] 2015-04-03 08:40
That may well be the problem; my laptop has the same integrated graphics (i5 3220m).

**Comment by actionless** [comment] 2015-04-03 09:06
https://github.com/awesomeWM/awesome/issues/179

**Comment by Elv13** [comment] 2015-04-03 18:32
Duplicate of #179

**Closed by Elv13** 2015-04-03 18:32 UTC
