### ISSUE TITLE
I am wondering: "Will wayland support be looked at again now that wayland has matured a bit?"

### ISSUE THREAD

**Issue by Eddieddg1** [awesomeWM/awesome#3969] opened 2024-10-17 20:05 UTC
It is literally the only thing keeping me on X11/Xorg. I would love to see wayland support for awesome.

**Comment by sclu1034** [comment] 2024-10-18 08:21
This has nothing to do with maturity. Porting AwesomeWM would be a tremendous amount of work, and so far, no one has shown up willing to do that work.

**Comment by actionless** [comment] 2024-10-18 18:37
please learn to use search, instead of creating 100th duplicate of the same question

**Closed by actionless** 2024-10-18 18:37 UTC
