### ISSUE TITLE
Emacsclient frames are not managed by Awesome 3.5.7

### ISSUE THREAD

**Issue by bvtrach** [awesomeWM/awesome#646] opened 2016-01-20 16:04 UTC
Hi,

I've updated Awesome to version 3.5.7, and emacsclient windows stopped responding to window management commands (i.e. Modkey-O, Modkey-Shift-C, etc). They can still be moved to another screen by mouse. Also, windows started from the autostart code also don't respond to these keys - but I'm not sure if this is the same issue.

The xprop of emacsclient window is here: http://pastebin.com/CQnhJwLv
rc.lua is here: http://pastebin.com/yUA0DHMR

It's possible reproduce the issue with emacsclient on default config too, but it happens much more rarely, and I haven't figured out the exact circumstances when it happens yet.

Thanks for any help.

**Comment by jeeger** [comment] 2016-01-20 19:10
It seems like this malfunction is caused by commit ff799a0f5dba06beed9f13939237899e53ff8fd8, as the failure seems to be random (works for some windows sometimes, and fails on other times). 

Unfortunately, I don't have git setup with awesome, could someone else test this?

**Comment by psychon** [comment] 2016-01-21 09:08
If so, then this is another duplicate of #639 (although I'm curious how emacs manages to cause this... and only sometimes?)

**Comment by blueyed** [comment] 2016-01-21 23:11
Closing as duplicate of #639 - please leave any more feedback there.

**Closed by blueyed** 2016-01-21 23:11 UTC

**Comment by psychon** [comment] 2016-01-22 08:00
Since this sounds different enough from #639: Can someone test if the patch there also fixes this issue?

**Comment by FloGa** [comment] 2016-01-22 08:54
I can't exactly reproduce this issue with my configs (furthermore I am not a native emacs user), but there are quite some lines in the given rc.lua that change the keyboard layout, especially when using emacs. So my wild guess here is, that with using the given rc.lua you reliably hit the same issue as #639 and it *should* be fixed by psychon's patch.

**Comment by psychon** [comment] 2016-01-22 09:03
Uhhh. I missed that. Thanks @FloGa. The config also starts `kbdd` and does something keyboard-widget-like based on that. Google suggests https://github.com/qnikst/kbdd and now this suddenly feels a lot like #639, because suddenly "changing the keyboard layout" is involved.

@bvtrach Can you test if the issue goes away when you stop using kbdd? (Or when you apply the fix from #639)

**Comment by bvtrach** [comment] 2016-01-22 11:25
I have tested the patch, it fixes the issue. Thank you.
