### ISSUE TITLE
"Portal Stories: Mel" crashes on launch

### ISSUE THREAD

**Issue by xentropy** [awesomeWM/awesome#305] opened 2015-07-12 10:28 UTC
Hi! Thanks for making this great WM.

I'm currently using version 3.5.6.

The game **Portal Stories: Mel**
http://store.steampowered.com/app/317400/
which is a free add-on to Portal 2 crashes on launch: 

>X Error of failed request:  BadMatch (invalid parameter attributes)
>  Major opcode of failed request:  42 (X_SetInputFocus)
>  Serial number of failed request:  1636
>  Current serial number in output stream:  1638

I'm not sure it's a bug in the WM but it works flawless on KDE 
with the very same setup.

**Comment by benoit-pierre** [comment] 2015-07-12 11:14
It looks like a duplicate of #292. Is your Steam runtime up-to-date? I can't reproduce the problem.

**Comment by xentropy** [comment] 2015-07-12 15:28
Thanks for your reply!

Steam just issued an update yesterday.
I'm participating in the beta releases.

**Comment by xentropy** [comment] 2015-07-12 15:43
Opting out of Beta fixed the issue.

Strange...

Thanks again for all your excellent work!

**Comment by benoit-pierre** [comment] 2015-07-12 15:57
That's it then: the beta version use a more recent version of SDL with the bug present. Hopefully they will update to the latest master of SDL (with the fix).

**Closed** 2015-07-13 14:17 UTC
