### ISSUE TITLE
How to get notification padding when using naughty.layout_box

### ISSUE THREAD

**Issue by vn-ki** [awesomeWM/awesome#3088] opened 2020-05-01 16:32 UTC
I'm using master and when I use `naughty.connect_signal("request::display"` with `naughty.layout_box`, the padding set in `naughty.config.padding` is lost.

I tried adding some margin in the `widget_template` of layout box but that seems to being blurred by the compositor.

**Comment by actionless** [comment] 2020-05-01 17:41
duplicate of https://github.com/awesomeWM/awesome/issues/3051

**Closed by actionless** 2020-05-01 17:41 UTC
