### ISSUE TITLE
awesome-4.0  dont work with fbpanel

### ISSUE THREAD

**Issue by landscape69** [awesomeWM/awesome#1517] opened 2017-02-03 01:27 UTC
Output of `awesome --version`:

2017-02-03 02:20:30 W: Cannot reliably detect EOF on an GIOInputStream with this LGI version
2017-02-03 02:20:30 /usr/share/awesome/lib/beautiful/xresources.lua:84: W: Failed to get xrdb value 'Xft.dpi'.
2017-02-03 02:20:30 /usr/share/awesome/lib/beautiful/xresources.lua:54: W: Failed to get xrdb value 'background'.
2017-02-03 02:20:30 W: beautiful: can't get colorscheme from xrdb (using fallback).
2017-02-03 02:20:48 E: Error during a protected call: /usr/share/awesome/lib/awful/tag.lua:1390: invalid object
stack traceback:
	[C]: in function 'tags'
	/usr/share/awesome/lib/awful/tag.lua:1390: in function </usr/share/awesome/lib/awful/tag.lua:1389>
	(tail call): ?
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:30: in function </usr/share/awesome/lib/gears/protected_call.lua:28>
	(tail call): ?
	/usr/share/awesome/lib/gears/timer.lua:167: in function </usr/share/awesome/lib/gears/timer.lua:165>
^[

**Comment by psychon** [comment] 2017-02-03 08:07
Unless proven wrong, I will assume that this is a duplicate of the thing already fixed in #1372 / 90bbcf19038b0f951883303db9f7a4ce474e40bd

**Closed by psychon** 2017-02-03 08:07 UTC
