### ISSUE TITLE
Awesome WM won't start with my system language but it works with English.

### ISSUE THREAD

**Issue by TaylanTatli** [awesomeWM/awesome#75] opened 2015-01-06 18:30 UTC
Sorry, i registered to report bug on https://awesome.naquadah.org/bugs/ but site doesn't allow me to open new report. So my problem is, awesome wm won't start because my system language is Turkish. But it works when i start it with "LC_ALL=en_US.UTF-8 startx". Here is the output when i tried to start it with my default system language (Turkish):

```
error while running function
stack traceback:
	[C]: in function 'assert'
	/usr/share/lua/5.2/lgi/override/cairo.lua:673: in main chunk
	[C]: in function 'require'
	/usr/share/lua/5.2/lgi/namespace.lua:176: in function </usr/share/lua/5.2/lgi/namespace.lua:148>
	(...tail calls...)
	/usr/share/awesome/lib/gears/color.lua:15: in main chunk
	[C]: in function 'require'
	/usr/share/awesome/lib/gears/init.lua:11: in main chunk
	[C]: in function 'require'
	/home/doublet/.config/awesome/rc.lua:9: in main chunk
error: /usr/share/lua/5.2/lgi/override/cairo.lua:673: assertion failed!
error while running function
stack traceback:
	/usr/share/awesome/lib/gears/color.lua:62: in function 'create_solid_pattern'
	/usr/share/awesome/lib/gears/color.lua:211: in function </usr/share/awesome/lib/gears/color.lua:187>
	(...tail calls...)
	/usr/share/awesome/lib/wibox/drawable.lua:133: in function 'set_bg'
	/usr/share/awesome/lib/wibox/drawable.lua:265: in function </usr/share/awesome/lib/wibox/drawable.lua:230>
	(...tail calls...)
	/usr/share/awesome/lib/wibox/init.lua:100: in function </usr/share/awesome/lib/wibox/init.lua:96>
	(...tail calls...)
	/usr/share/awesome/lib/naughty.lua:440: in function 'notify'
	/etc/xdg/awesome/rc.lua:18: in main chunk
error: /usr/share/awesome/lib/gears/color.lua:62: attempt to call field 'create_rgba' (a nil value)
E: awesome: main:535: couldn't find any rc file
```

**Comment by blueyed** [comment] 2015-01-06 21:15
The error appears to come from `/usr/share/lua/5.2/lgi/override/cairo.lua:673`.

Can you paste it and its surrounding context?
Does commenting it fix or improve/change the issue for you? (as a workaround)

**Comment by TaylanTatli** [comment] 2015-01-06 21:22
```
   if cairo.version >= (info.since or 0) then
      local name = info[1]
      local obj = assert(cairo[name], name)
      obj._parent = info.parent
      if info.methods then
	 -- Go through description of the methods and create functions
	 -- from them.
	 obj._method = {}
	 local cprefix = 'cairo_' ..
	    (info.cprefix or
	     name:gsub('([%l%d])([%u])', '%1_%2'):lower() .. '_')
	 local self_arg = { obj }
	 for method_name, method_info in pairs(info.methods) do
	    if cairo.version >= (method_info.since or 0) then
	       method_info.name = 'cairo.' .. name .. '.' .. method_name
	       method_info.addr = assert(                                                                <-- This line 673
		  cairo._module[
		     method_info.cname or (cprefix .. method_name)])
	       if not method_info.static then
		  table.insert(method_info, 1, self_arg)
	       end
	       method_info.ret = method_info.ret or ti.void
	       obj._method[method_name] = core.callable.new(method_info)
	    end
	 end
      end
```

I don't know which lines to comment. :/

**Comment by blueyed** [comment] 2015-01-06 22:12
Which one is line 673? (there are two assert statements in what you've pasted).

> I don't know which lines to comment. :/

I've meant the assert statement that's causing problems.
But that won't help probably. You might have to debug it, e.g. add print statements there to see what's going on: what is different there when using LANG=C (or what you've used) compared to using your system settings.

**Comment by TaylanTatli** [comment] 2015-01-07 00:26
I wrote " <-- This line 673"

Sorry, my English is not good.Can you explain me what to do simply?

**Comment by blueyed** [comment] 2015-01-07 02:48
I cannot help you much further. I was just trying to help you debug it.

The problem appears to be that some cairo module is not available:

    > cairo._module[method_info.cname or (cprefix .. method_name)]

You could add the following code before the assert and then see what gets printed:

    print(method_info)
    print(cprefix)
    print(method_name)

But you might want to wait for someone else to help with that - I might be on a totally wrong track.

**Comment by TaylanTatli** [comment] 2015-01-08 10:22
A big update: I don't need to use LC_ALL anymore, because just changing LC_CTYPE to english is working. Awesome starts and all programs are Turkish. :) But i don't know what is LC_CTYPE for?

**Comment by blueyed** [comment] 2015-01-08 16:24
According to `man locale` it's for "Character classification and case conversion.".

**Comment by TaylanTatli** [comment] 2015-01-08 17:13
So it's not important so much? Anyway, at least it's working.:)

**Comment by blueyed** [comment] 2015-01-08 21:03
I'm glad it's working for you!

It does not seem to be important, and probably triggers a bug somewhere, where upper-/lowercasing is an issue.

**Comment by psychon** [comment] 2015-01-10 12:35
I can reproduce this issue and it is not in awesome, but in lgi (as one could already guess before):

    $ lua -e 'print(os.setlocale("tr_TR.UTF8")) ; print(require("lgi").cairo)' 
    tr_TR.UTF8
    lua: /usr/share/lua/5.1/lgi/override/cairo.lua:673: assertion failed!
    stack traceback:
    	[C]: in function 'assert'
    	/usr/share/lua/5.1/lgi/override/cairo.lua:673: in main chunk
    	[C]: in function 'require'
    	/usr/share/lua/5.1/lgi/namespace.lua:176: in function </usr/share/lua/5.1/lgi/namespace.lua:148>
    	(tail call): ?
    	(command line):1: in main chunk
    	[C]: ?

**Comment by psychon** [comment] 2015-01-10 12:49
And here is some more compact, self-standing example demonstrating the problem:

    $ lua -e 'function f() s = "I" ; return s:lower() end ; print(os.setlocale("")) ; print(f()) ; print(os.setlocale("tr_TR.UTF8")) ; print(f()) '
    de_DE.UTF-8
    i
    tr_TR.UTF8
    I

(Technical details: lgi has the strings "ImageSurface" and "get_width" and it tries to generate the name of the corresponding C function which is `cairo_image_surface_get_width`. However, in a turkish locale it ends up with `cairo_Image_surface_get_width`. The following assertion failure is just the resulting "whoops, there is no such function"-error.)

@TaylanTatli Since you seem to know turkish, can you tell us why "i" is not the lower-case version of "I"?

I reported this issue to LGI and thus will close this one.
Upstream issue: https://github.com/pavouk/lgi/issues/97

**Closed by psychon** 2015-01-10 12:49 UTC
Labels: question

**Comment by psychon** [comment] 2015-01-10 12:53
http://en.wikipedia.org/wiki/Dotted_and_dotless_I

**Comment by TaylanTatli** [comment] 2015-01-10 13:09
You found the answer on wikipedia. :) That İ and ı are really problem for us. Lots of app lives problem with them. Thank you. :)

**Comment by psychon** [comment] 2015-02-01 11:09
This was now fixed in LGI upstream

**Comment by TaylanTatli** [comment] 2015-02-01 11:16
Thanks.
