### ISSUE TITLE
Binary tree / BSP-style / tmux-style manual window tiling

### ISSUE THREAD

**Issue by skrzyp** [awesomeWM/awesome#2745] opened 2019-04-11 11:20 UTC
Output of `awesome --version`:

```
$ awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

1. Be an user
2. Install `i3`/`bspwm`/`herbsluftwm`
3. Use it for a while
4. Stumble upon AwesomeWM on some article/irc/screenshot/github
4.1 (optional) Get amazed about its wide feature set, consistent configuration and lot of possibilities
5. Install it out of curiosity
6. Run it
7. Spawn 2 terminal windows
8. Try to split one of them vertically

**Actual result:**

Window gets placed on the other half in default stacking layout

**Expected result:**

Window should be split vertically to allow users manually split and cut their workspaces as they'd like.

I think the default form issue form and title explains that enough from user POV. But if someone doesn't know, i3/herbstluftwm/bspwm/tmux manage windows/panes in binary tree, where each "node" can be "split" vertically or horizontally, allowing **you to control the layout in real time, instead of writing a layout description for every case you need**, which is time-consuming and doesn't always work for newcomers. And after years of using these tools mentioned before, so-called "dynamic" tiling might feel counter-intuitive, decreasing an experience from using AwesomeWM.

`i3` guide explains this behavior in technical details: https://i3wm.org/docs/userguide.html#_tree

**Comment by Elv13** [comment] 2019-04-11 19:27
Duplicate of https://github.com/awesomeWM/awesome/pull/644

**Closed by Elv13** 2019-04-11 19:27 UTC
