### ISSUE TITLE
Tag rule: 3 screens; Firefox w/ 3 windows; raise_or_spawn only functions for primary screen

### ISSUE THREAD

**Issue by mxmilkiib** [awesomeWM/awesome#3855] opened 2023-09-14 05:17 UTC
Output of `awesome --version`:

4.3
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

As title

**Actual result:**

The second and third Firefox windows open on the second and third monitor, but only on the tag that was active at that point, not the tag the windows rule has.

**Comment by actionless** [comment] 2023-09-14 09:03
could you reproduce it with any other WM?
i'm pretty sure it's because of firefox trying to restore its position

**Comment by mxmilkiib** [comment] 2023-09-18 01:59
So I went to about:config and turned widget.disable-workspace-management to false (I guess I had an issue with a previous WM years ago), and that fixed the desktop Firefox not spawning on the correct tag on non-active outputs!

My problem now is almost the same but with the "raise" part of "raise_or_spawn"; when I  `awful.spawn.raise_or_spawn("firefox" ...`, this only raises the Firefox window on the active output.

Specifically I mean: When another output is active, and I hit the hotkey, the active output changes to the primary output and then the primary output changes tag the Firefox tab (if that tab is not already active).

**Comment by actionless** [comment] 2023-09-18 05:52
you mean you specified the screen number/obj in the rule, but it's getting ignored?

**Comment by Elv13** [comment] 2024-01-01 08:02
There isn't much we can do here. Given you solved the "first" problem, it is sadly as good as it is going to get without playing with Firefox profiles and sandboxing. Firefox (and Chrome) use a rather complex maze of processes, isolated workers, shared memory and RPCs. When you spawn a "new" Firefox, it just calls the existing ones and ask for a new window. This means we can't track which window comes from which `awful.spawn` calls. Even more modern APIs like the ones used by KDE and Gnome fail at this. We use a rather ancient and fragile API called "startup notification", which Firefox fail to implement correctly.

Closing this as a downstream (Firefox) bug. It needs to be fixed there, which after decades of being a problem, wont happen.

**Closed by Elv13** 2024-01-01 08:02 UTC
Labels: downstream
