### ISSUE TITLE
Maximized Firefox windows not restored properly after fullscreen (F11)

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#245] opened 2015-05-26 18:05 UTC
TEST CASE:

1. Tiled layout, with a maximized Firefox window (Mod4-m).
2. Press F11 to switch Firefox into fullscreen mode.
3. Press F11 again.

There will be a gap (~35px) between awesome's taskbar and the Firefox window.
The Firefox window will not be recognized as "maximized" anymore, but only "floating".
The bottom of the Firefox window is aligned to the bottom (and not overlapping), reducing the window's height effectively (by ~35px) after leaving fullscreen mode.

The same behavior occurs when using awesome's fullscreen shortcut (`mod4+f`).

**Comment by aelspire** [comment] 2015-05-30 08:58
With Chromium something similar occur, after leaving fullscreen mode "maximized" state is lost, but without gap issue and it stay floating only if I made it floating before. I also installed Firefox and tested it - Firefox work the same too, I cannot reproduce gap issue (awesome remember previous floating client position so maybe this is cause of the gap). Losing "maximized" look to me like limitation, I think the cause of such behavior is:

1. Firefox get "maximized"
2. When toggling fulscreen on - "maximized" mark was turned off.
3. When toggling fulscreen off - "fullscreen" mark was turned off, but WM and application do not have memory of previous state so client is not marked as "maximized", so if it was floating before, awesome restore previous position and size.

I tested it with:
1. Make Firefox floating
2. Resize and move Firefox window
3. Maximize Firefox
4. Press F11 or mod4+f to switch Firefox into fullscreen mode
5. Press F11 or mod4+f again
Result: Firefox lost "maximized" state but floating window is correctly restored wit size and position like in 2. 

Losing maximized state occur with all clients, not only Chomium and Firefox.

**Comment by blueyed** [comment] 2015-06-30 11:24
The problem with Firefox is that it forgets about the window's maximized state when coming back from fullscreen.  Seems to be this (old) bug: https://bugzilla.mozilla.org/show_bug.cgi?id=425086

I cannot reproduce the additional gap issue currently anymore.

> WM and application do not have memory of previous state

Firefox should be able to keep track of this, shouldn't it?

I've added the following to my config to handle this now.
It keeps track of the "maximized" properties (delayed, and skipped when in "fullscreen"), and then restores them after "fullscreen".

    -- Restore maximized state after fullscreen (Firefox).
    -- https://github.com/awesomeWM/awesome/issues/245
    local restore_properties = {}
    local restore_timer
    local delayed_store_if_not_filtered = function(c, prop, filter)
      -- Stop an already running (global) timer.
      if restore_timer then restore_timer:stop() end

      restore_timer = timer({timeout = 1})  -- delay storing of props by 1 sec.
      restore_timer:connect_signal("timeout", function()
        restore_timer:stop()
        local signal = "property::"..prop
        if not filter(c) then
          if not restore_properties[c] then restore_properties[c] = {} end
          restore_properties[c][prop] = c[prop]
        end
      end)
      restore_timer:start()
    end
    capi.client.connect_signal("property::maximized_vertical", function(c)
      delayed_store_if_not_filtered(c, 'maximized_vertical', function(c) return c.fullscreen end)
    end)
    capi.client.connect_signal("property::maximized_horizontal", function(c)
      delayed_store_if_not_filtered(c, 'maximized_horizontal', function(c) return c.fullscreen end)
    end)
    -- Restore props when coming from fullscreen.
    capi.client.connect_signal("property::fullscreen", function(c)
      if not c.fullscreen and restore_properties[c] then
        for k, v in pairs(restore_properties[c]) do
          c[k] = v
        end
        restore_properties[c] = nil
      end
    end)

**Comment by psychon** [comment] 2015-07-05 14:28
Uhm. I'm confused. For some reason (EWMH?), maximized and fullscreen are incompatible, so setting `c.fullscreen = true` unsets `maximized`, `maximized_horizontal` and `maximized_vertical`. So when coming back from fullscreen, the window should be tiled normally. Why is your firefox floating?

(Sorry if this isn't the result that you are hoping for, but if we were to define some priority like "if both fullscreen and maximized, fullscreen wins", then setting maximized on a fullscreen window will have no effect, which can be confusing)

**Comment by blueyed** [comment] 2015-07-05 15:17
> Why is your firefox floating?

I have Firefox often floating/maximized on the small screen - not related to the issue.

> then setting maximized on a fullscreen window will have no effect, which can be confusing

I think that it would be OK to have to unset fullscreen in this case.

**Comment by d125q** [comment] 2015-08-18 19:30
This issue occurs with other clients, too, such as [DeaDBeeF](http://deadbeef.sourceforge.net/). Furthermore, when `fullscreen` unsets `maximized_horizontal` and `maximized_vertical`, `c.fullscreen` is still **false** (which is why I think the timer in @blueyed config is there, please correct me if I'm wrong).

It seems to me that this issue is related to awesome, and not to the applications themselves.

**Comment by blueyed** [comment] 2015-08-18 20:53
@d125q 
The flow is: `client_set_fullscreen` sets `c->fullscreen` (objects/client.c), and indeed calls `client_set_maximized` before.
After setting `c->fullscreen`, `request::fullscreen` is emitted and then `property::fullscreen`.
But changing this order does not really solve the issue, because the old state is forgotten.

I'll look into providing a patch/PR to address this (by not unsetting the other state(s)).

From http://standards.freedesktop.org/wm-spec/latest/ar01s05.html:

> _NET_WM_STATE_FULLSCREEN indicates that the window should fill the entire screen and have no window decorations. Additionally the Window Manager is responsible for restoring the original geometry after a switch from fullscreen back to normal window. For example, a presentation program would use this hint.

Also http://standards.freedesktop.org/wm-spec/latest/ar01s09.html#STACKINGORDER does not indicate that "fullscreen", "above" or "below" are mutually exclusive, but only that the WM should handle it correctly when stacking the windows.

**Closed** 2015-09-02 20:30 UTC
Labels: bug, upstream
