### ISSUE TITLE
horizontal/vertical maximize broken

### ISSUE THREAD

**Issue by mvduin** [awesomeWM/awesome#2061] opened 2017-10-16 12:04 UTC
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**

- maximized_horizontally or maximized_vertically of a window to true.
- attempt to move or resize the window

**Actual result:**

The window can be moved and resized freely in all directions.

**Expected result:**

The window should be constrained to remain horizontally or vertically maximized.

This is a regression, it worked correctly in 4.0.

**Comment by psychon** [comment] 2017-10-16 13:44
Loosely related with: #2036 

> This is a regression, it worked correctly in 4.0.

I guess this was introduced in commit 631e75a7573e69d16c6636882e05301d76ff20d6. Before that, there were a callback on `property::geometry` which enforced maximisation and fullscreen status. Afterwards, there is not.
To quote the commit message: "And stop listening to property::geometry, it's no longer needed." :-)

CC @Elv13

**Comment by psychon** [comment] 2017-10-16 13:45
Actually... closing as duplicate of #2036. That one even points to the same commit for the same reason.

**Closed by psychon** 2017-10-16 13:45 UTC

**Comment by mvduin** [comment] 2017-10-16 13:53
Ah lol I didn't even think to check whether full-maximize was also affected (I never use it). I saw #2036 but assumed it was unrelated based on the original title.

Thanks!
