### ISSUE TITLE
Awful/placement.lua bad argument

### ISSUE THREAD

**Issue by Titan-C** [awesomeWM/awesome#1456] opened 2017-01-24 22:02 UTC
Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

It is not always reproducible. I launch an emacs(25.1.1) client and sometimes it does open and is placed according to the tiling scheme. Other times it jus presents a containing box, it is just a border placed in the middle of the screen and emacs never load up into it.

**Actual result:**
When I have this box that should be my emacs client but never loaded. I press the key shortcuts to maximize it or make it full screen. Emacs loads and displays but I get the extra warning

```
Oops, an error happened!

/usr/share/awesome/lib/awful/placement.lua:1688: bad argument # -2 to 'geometry' (value in [1.0, 65535.0] expected, got 0.0)
```
If I instead try to swap/focus this box using the keyboard shortcuts nothing happens. Only the other open clients are swaped/focused according to the tiling scheme.

**Expected result:**
Open emacs client, and it is visible and placed according to the tiling layout.

**Comment by Elv13** [comment] 2017-01-25 06:25
Hello,

The emacs issues has been fixed in git-master. As for the placement error, I already have a pull request open that improves this. Fullscreen is working fine, but maximize was undertested in v4.0.

Closing as this is part duplicate of #1321 and part duplicate of #1369 / #1436

**Closed by Elv13** 2017-01-25 06:25 UTC
