### ISSUE TITLE
AwesomeWM kill command not working, after "startx" in TTY only

### ISSUE THREAD

**Issue by Bujiraso** [awesomeWM/awesome#2145] opened 2017-12-18 18:01 UTC
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

1. With no configuration outside of the default needed (i.e. /etc/xdg/awesome/rc.lua can be used), simply run startx in a tty, having configured .xinitrc to run "exec awesome"
2. Run a terminal (Mod4+Enter)
3. Press Mod4+SHIFT+C to kill the client

**Actual result:**

Client is not killed.

**Expected result:**

Client is killed.

**Additional Troubleshooting Notes:**

* First off, all other key combinations appear to work fine. Switching tags, pulling up the awesome menu, launching commands, changing layouts, etc.
* There are no errors on start-up of awesomeWM, nor any in the remaining tty when I close the session.
* I've run a Xephyr session with awesome in it and for some reason the keystrokes *do* work there. So color me incredibly puzzled, as the xev keycodes being sent are seemingly identical.
* I'm not running any processes, daemons, or DE's that I think should be conflicting here (to be specific, I'm running as little as possible, no DE at all at the moment). I don't have xfce, nor any configurations for it which are known to conflict (mentioned on the Arch Wiki).
* I don't use this key combination for anything in particular elsewhere.

**Comment by psychon** [comment] 2017-12-18 19:40
> as the xev keycodes being sent are seemingly identical.

What's the output of `xev` here for these cases exactly?

What happens when you bind some other keybinding to `c:kill()`? I.e., is `kill` not working or is it the keybinding?

What's the output of `setxkbmap -query`? Is it the same in Xephyr?

**Comment by Bujiraso** [comment] 2017-12-19 20:12
Ok! Figured it out!
It might still be a bug so I'll let you guys decide to close it or now, but thank you @psychon for the help finding the work-around.
So I use quite a few different keyboard layouts in gdm and it appears to have set the xkbmap to something that awesome didn't like.

Outside of Xephyr, the xkbmap is:
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,us
variant:    ,dvorak
```

Inside of Xephyr, I had simply:
```
$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us
```

When I ran a quick setxkbmap -layout "us" (i.e. cleared the second "us layout, dvorak variant"), the problem went away.
The Xev output complains about a disfocus event on the window, so a component of this bug may be that there is no focused window, no client to kill, but there's certainly a couple parts left to discuss.

**Bugged xev output:**

```
KeyPress event, serial 35, synthetic NO, window 0xe00001,
    root 0x294, subw 0x0, time 21976791, (108,61), root:(109,767),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 35, synthetic NO, window 0xe00001,
    root 0x294, subw 0x0, time 21977064, (108,61), root:(109,767),
    state 0x40, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

FocusOut event, serial 35, synthetic NO, window 0xe00001,
    mode NotifyGrab, detail NotifyAncestor

FocusOut event, serial 35, synthetic NO, window 0xe00001,
    mode NotifyUngrab, detail NotifyPointer

FocusIn event, serial 35, synthetic NO, window 0xe00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 35, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   4   0   0   0   0   0   0   0   0   0   
           32  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   
```

Here's what it should have looked like, according to Xephyr.

**Working Xephyr xev output:**

```
KeyPress event, serial 32, synthetic NO, window 0x800001,
    root 0x27d, subw 0x0, time 22176259, (123,115), root:(124,525),
    state 0x0, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XmbLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x800001,
    root 0x27d, subw 0x0, time 22176403, (123,115), root:(124,525),
    state 0x0, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyPress event, serial 35, synthetic NO, window 0x800001,
    root 0x27d, subw 0x0, time 22177106, (123,115), root:(124,525),
    state 0x0, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 35, synthetic NO, window 0x800001,
    root 0x27d, subw 0x0, time 22177510, (123,115), root:(124,525),
    state 0x40, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

ClientMessage event, serial 35, synthetic YES, window 0x800001,
    message_type 0x125 (WM_PROTOCOLS), format 32, message 0x126 (WM_DELETE_WINDOW)
```

So here's the a strange kicker -- if I press *both* "c"'s (qwerty "c" and dvorak "c", which is an "i" in qwerty), **then the kill works**! Most importantly to this: it must be Dvorak first; order is important.
I'll write the hotkey strings as Qwerty only to reduce confusion: pressing Mod4+SHIFT+C+I does not work (even if C is lifted and re-pressed), where Mod4+SHIFT+I+C issues the kill command every time without fail.

So it appears Awesome is iterating through each keyboard and verifying that the "c" key is being pressed *in each one* before issuing the kill command? Except backwards according to the list.

Relevant xev output of Mod4+SHIFT+I+C

```
KeyPress event, serial 32, synthetic NO, window 0x1800001,
    root 0x294, subw 0x0, time 23409169, (123,59), root:(2044,580),
    state 0x10, keycode 133 (keysym 0xffeb, Super_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyPress event, serial 35, synthetic NO, window 0x1800001,
    root 0x294, subw 0x0, time 23409571, (123,59), root:(2044,580),
    state 0x50, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

ClientMessage event, serial 35, synthetic YES, window 0x1800001,
    message_type 0x165 (WM_PROTOCOLS), format 32, message 0x166 (WM_DELETE_WINDOW)
```

Note that neither "I" nor "C" appears. For reference these are my "I" and "C" if I just press them in the same problematic configuration.

```
KeyPress event, serial 35, synthetic NO, window 0x1800001,
    root 0x294, subw 0x0, time 23496030, (145,3), root:(2066,524),
    state 0x10, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XmbLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x1800001,
    root 0x294, subw 0x0, time 23496121, (145,3), root:(2066,524),
    state 0x10, keycode 54 (keysym 0x63, c), same_screen YES,
    XLookupString gives 1 bytes: (63) "c"
    XFilterEvent returns: False

KeyPress event, serial 35, synthetic NO, window 0x1800001,
    root 0x294, subw 0x0, time 23496319, (145,3), root:(2066,524),
    state 0x10, keycode 31 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XmbLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False

KeyRelease event, serial 35, synthetic NO, window 0x1800001,
    root 0x294, subw 0x0, time 23496425, (145,3), root:(2066,524),
    state 0x10, keycode 31 (keysym 0x69, i), same_screen YES,
    XLookupString gives 1 bytes: (69) "i"
    XFilterEvent returns: False
```

Likely you'll be able to reproduce my issue by merely running `$ setxkbmap -layout "us,us" -variant ",dvorak"`, but let me know if that fails and I can give any other information that might be pertinent to dev'ing a fix.

**Comment by psychon** [comment] 2017-12-20 09:13
Ah, thanks.

Closing as a duplicate of #1389. We... well, "have some problems with keyboard layouts".

Since X11 is X11, there is the "original way" to do keyboard inputs. This is what `xmodmap` modifies. Then the X Keyboard extension (XKB) came and brought a new way. So far we only use/support XKB for keygrabbers (e.g. the prompt) while keybindings still use the X11 core protocol to do its things.

I briefly looked into fixing awesome to use XKB everywhere, but the [protocol specification](https://www.x.org/docs/XKB/XKBproto.pdf) is a PDF file with 155 pages, on top of which one likely also needs to read & understand the [library specification](https://www.x.org/docs/XKB/XKBlib.pdf) which has another 241 pages.
Compared with the complete [X11 protocol specification](https://www.x.org/releases/X11R7.5/doc/x11proto/proto.pdf) (161 pages), XKB is a huge monster that I didn't look at too closely and which I don't really feel like looking at.

**Closed by psychon** 2017-12-20 09:13 UTC
