### ISSUE TITLE
Memory leak by xdotool use

### ISSUE THREAD

**Issue by pmasterc3** [awesomeWM/awesome#2258] opened 2018-05-04 22:43 UTC
Output of `awesome --version`:

$ awesome --version
awesome v4.2 (Human after all)
 â¢ Compiled against Lua 5.3.3 (running with Lua 5.3)
 â¢ D-Bus support: â
 â¢ execinfo support: â
 â¢ xcb-randr version: 1.6
 â¢ LGI version: 0.9.2

**How to reproduce the issue:**

Start awesome 4.2 (on debian 10), start xterm and execute the following script:
`#/bin/sh

set -e
set -x

AP=$(pidof awesome)
O="$HOME/awesome/"

cp /proc/$AP/smaps  "$O/smaps.pre.txt"
cp /proc/$AP/maps  "$O/maps.pre.txt"
pmap "$AP" > "$O/pmap.pre.txt"

xdotool mousemove 500 400 click --repeat 1000000 --delay 1 1

cp /proc/$AP/smaps  "$O/smaps.post.txt"
cp /proc/$AP/maps  "$O/maps.post.txt"
pmap "$AP" > "$O/pmap.post.txt"`

**Actual result:**
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND   
 1426 pmaster   20   0  710624 274280  17852 S   0.0   7.3   2:22.62 awesome 

 $ diff maps.pre.txt maps.post.txt 
4c4
< 55d13e83d000-55d13fc32000 rw-p 00000000 00:00 0                          [heap]
---
> 55d13e83d000-55d14dd74000 rw-p 00000000 00:00 0                          [heap]

 $ diff pmap.{pre,post}.txt  
5c5
< 000055d13e83d000  20436K rw---   [ anon ]
---
> 000055d13e83d000 251100K rw---   [ anon ]
350c350
<  total           474056K
---
>  total           704720K
```

**Expected result:**
Less memory used

**Comment by psychon** [comment] 2018-05-05 03:49
My first guess would be: Welcome to language with a garbage collector.

> and execute the following script:

Well, the only important part is `xdotool mousemove 500 400 click --repeat 1000000 --delay 1 1`, right? The rest of the script does not actually do much.
Is it important if:
- the xterm really is an xterm?
- the xterm contains position 500x400? (I.e., are we talking about clicks on the root window, or clicks on xterm?)

> --repeat 1000000 --delay 1 

That's one million milliseconds, right? So, 1000 seconds, which are about 17 minutes. Plus whatever additional time delay xdotool runs into. Sigh, okay, I'll wait.
Since I guess you already checked: How is the memory usage when just run awesome for 17 minutes without clicking around? Is it much different?
Right now I'm running awesome in `Xephyr` and under `valgrind --tool=massif`. I'll edit-update this comment with results.

== Just an empty Xephyr + lots of clicks ==
Not measured yet.

== urxvt containing 500x400 + lots of clicks ==
Not measured yet.

== urxvt containing 500x400 + just wait 17 minutes ==
Not measured yet.

**Comment by psychon** [comment] 2018-05-05 03:56
https://sources.debian.org/src/xdotool/1:3.20160805.1-3/xdo.c/?hl=934#L934
Uhm, xdotool leaves the button down for DEFAULT_DELAY = 12 milliseconds. So we are talking about 13 milliseconds per iterations, which means three and a half hours in total. Plus whatever time xdotool needs between those `usleep` calls. That's ridiculously long. Please tell me my math is wrong!

**Comment by psychon** [comment] 2018-05-05 04:42
Here is a simple patch to awesome's C code that can be used to reproduce the "problem" (this just needs the `refresh` signal to be emitted, so this patch does a million main loop iterations):
```diff
diff --git a/awesome.c b/awesome.c
index 3513cecf4..3edcba99c 100644
--- a/awesome.c
+++ b/awesome.c
@@ -501,6 +501,15 @@ exit_help(int exit_code)
     exit(exit_code);
 }
 
+static gboolean
+do_some_loops(gpointer unused)
+{
+    static int iterations = 0;
+    if (iterations++ > 1000000)
+        g_main_loop_quit(globalconf.loop);
+    return G_SOURCE_CONTINUE;
+}
+
 /** Hello, this is main.
  * \param argc Who knows.
  * \param argv Who knows.
@@ -530,6 +539,8 @@ main(int argc, char **argv)
         { NULL,      0, NULL, 0 }
     };
 
+    g_idle_add(do_some_loops, NULL);
+
     /* Make stdout/stderr line buffered. */
     setvbuf(stdout, NULL, _IOLBF, 0);
     setvbuf(stderr, NULL, _IOLBF, 0);
```
and this patch gets rid of the "problem":
```diff
diff --git a/lib/gears/timer.lua b/lib/gears/timer.lua
index 3f88d70a3..059305fe1 100644
--- a/lib/gears/timer.lua
+++ b/lib/gears/timer.lua
@@ -227,6 +227,7 @@ end
 
 local delayed_calls = {}
 capi.awesome.connect_signal("refresh", function()
+    if #delayed_calls == 0 then return end
     for _, callback in ipairs(delayed_calls) do
         protected_call(unpack(callback))
     end
```
The patch just gets rid of a trivial memory allocation in Lua. However, since this is quite a synthetic test, I do not think we should try to avoid memory allocations too much for it. If someone were to submit this patch (with proper line breaks around the `return`) as a PR, I would not mind it, but I won't submit a PR myself. Completely idle main loop iterations are just some special case that I do not think is worth optimising for. This is a garbage collected language and the garbage collector should, well, collect garbage.

**Comment by psychon** [comment] 2018-05-05 05:55
With the above test case, I did a git bisect with the git repository from https://github.com/lua/lua. The result is:
```
51e8f08e609b20af6f70641855d9be5edb2f1328 is the first bad commit
commit 51e8f08e609b20af6f70641855d9be5edb2f1328
Author: Roberto Ierusalimschy <roberto@inf.puc-rio.br>
Date:   Mon May 28 17:41:00 2012 -0300

    more efficient way to apply 'stepmul' + some changes in GC parameters

:100644 100644 fc888d0497ef93e4916972b43b4cc41f1424d72f 64e8df97c0279a9164c89b71f1f58104d5f7278a M	lgc.c
```
Commit 51e8f08e plus the following patch does not have this problem:
```diff
diff --git a/lgc.c b/lgc.c
index 64e8df97..6934be2a 100644
--- a/lgc.c
+++ b/lgc.c
@@ -1098,7 +1098,10 @@ static void step (lua_State *L) {
   debt = (debt / STEPMULADJ) + 1;
   debt = (debt < MAX_LMEM / stepmul) ? debt * stepmul : MAX_LMEM;
   do {  /* always perform at least one single step */
+#define workrate(x,mul)  \
+       ((x) < MAX_INT/80 ? ((x) * 80) / mul : ((x) / mul) * 80)
     lu_mem work = singlestep(L);  /* do some work */
+    work = workrate(work, stepmul);
     debt -= work;
   } while (debt > -GCSTEPSIZE && g->gcstate != GCSpause);
   if (g->gcstate == GCSpause)
```
With random modifications, I came up with: Lua 5.3.0 plus the following patch also does not have this problem.
```diff
diff --git a/lgc.c b/lgc.c
index 185c1d8c..d73256a7 100644
--- a/lgc.c
+++ b/lgc.c
@@ -1115,6 +1115,7 @@ void luaC_step (lua_State *L) {
   }
   do {  /* repeat until pause or enough "credit" (negative debt) */
     lu_mem work = singlestep(L);  /* perform one single step */
+    work -= 30;
     debt -= work;
   } while (debt > -GCSTEPSIZE && g->gcstate != GCSpause);
   if (g->gcstate == GCSpause)
```
So somewhere Lua's garbage collector is mis-estimating the amount of work it did.

**Comment by psychon** [comment] 2018-05-05 05:57
Never mind, this problem was already fixed in Lua's git by the following commit:
```
commit 7b1fba69b7a887e37e57744309299d134e76e06e (HEAD, refs/bisect/bad)
Author: Roberto Ierusalimschy <roberto@inf.puc-rio.br>
Date:   Mon Nov 7 10:38:35 2016 -0200

    using 'lastfree == NULL' to signal that table is using the dummy
    node for its hash part + new macro 'allocsizenode'
```
Thus, no point in talking to the Lua devs about this.
According to `git describe`, the above commit is 23 commits after Lua 5.3.3 and already part of Lua 5.3.4. Thus, we just have to wait for Debian to update its Lua version and I will close this.

**Closed by psychon** 2018-05-05 05:57 UTC

**Comment by psychon** [comment] 2018-05-05 05:59
Well, okay. You might want to report this to Debian so that they update to Lua 5.3.4. It seems like no one is working on that so far.

**Comment by pmasterc3** [comment] 2018-05-05 09:33
Thanks for the quick response!
