### ISSUE TITLE
Unwanted transpartent border for fullscreen MPV related to fullscreen_hide_border since 4.1

### ISSUE THREAD

**Issue by AAAAM** [awesomeWM/awesome#1696] opened 2017-04-02 12:28 UTC
Output of `awesome --version`:
awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**How to reproduce the issue:**
- use version 4.1 (issue solved by downgrading to 4.0)
- do **not** set fullscreen_hide_border to false in the theme.lua file (setting to false solve the issue)
- run mpv on any video (I have not experienced this issue with any other program so far)
- toggle fullscreen (with awesome key binding, or through mpv itself)

**Actual result:**
![transparent_border_top_left](https://cloud.githubusercontent.com/assets/8276204/24585872/0864c9ca-1795-11e7-875d-7f43cbf040d8.png)
There is a transparent border of what I assume to be one pixel on the left and on top, which allows you to see the black/white/blue colors of my status bar on top, and a black line on the left.

**Expected result:**
![normal](https://cloud.githubusercontent.com/assets/8276204/24585884/3786d5ea-1795-11e7-8f4b-8729c14e9a34.png)
Result with "fullscreen_hide_border = false", or with awesome 4.0, or with any program (that I have tested) but mpv.
No border for fullscreen window.
Note that using a theme with border_width set to 0 does not raise this issue.

**Comment by psychon** [comment] 2017-04-02 15:02
Duplicate of #1607

**Closed by psychon** 2017-04-02 15:02 UTC
