### ISSUE TITLE
Support HiDPI

### ISSUE THREAD

**Issue by berlam** [awesomeWM/awesome#760] opened 2016-03-16 09:40 UTC
Changing the DPI in `.Xresources` has no effect to the awesome font rendering and wibox scaling.
Currently I am using `Debian Testing` with `awesome 3.5.6` and a DPI of 144.
Other GTK apps are shown in the right scaled size.

I am not an expert on this kind of programming, but I think this might be a problem with the configuration of Pango and Cairo which should already support HiDPI.

After a quick look into the awesome sources I found following code in `core.lua` and other components:

```Lua
    local ctx = PangoCairo.font_map_get_default():create_context()
    ctx:set_resolution(beautiful.xresources.get_dpi())
```

Is HiDPI currently supported?

**Comment by psychon** [comment] 2016-03-16 09:46
Not in 3.5 and I think the code you showed above isn't in 3.5. Can you try with the latest Git version (which should pick up `Xft.dpi` from your `.Xresources`)? (`make packages` should provide you a .deb that you then can (hopefully) install with `dpkg -i the-file.deb`. However, that was merged to git just yesterday and I guess you'd be the first one to try this. :-) )

**Comment by berlam** [comment] 2016-03-16 09:57
I will give it a try later this day and report back here (for Packaging and HiDPI). Thank you! :-)

**Comment by psychon** [comment] 2016-03-16 10:03
Oh and: There were API changes since 3.5. Your current config likely won't work. I suggest trying this with the default config (this should be enough to see what the font size looks like).

**Comment by actionless** [comment] 2016-03-16 10:57
it works 100% correctly only when setting this theme: https://github.com/awesomeWM/awesome/tree/master/themes/xresources

otherwise only fonts will be scaled but some controls won't. but they will attempt to enlarge to fit the bigger font so probably you'll have only some problems with margins' sizes.

also it will pick up the colors from your ~/.Xresources (they should be set unprefixed, ie `*color1:    #aa3683`)

@psychon what do you think about setting it as a default theme btw?

**Comment by psychon** [comment] 2016-03-16 11:08
@actionless Uhm, I don't know. Why not? I guess, if the fallbacks look similar to the default theme, most people won't even notice. However, this makes it harder to change the theme and so would kind of defeat the point of having `beautiful`.... at least a bit?

**Comment by actionless** [comment] 2016-03-16 11:14
we could change fallback to look a bit closer to the default because now it set to this theme http://dotshare.it/public/images/uploads/873.jpg

**Comment by Elv13** [comment] 2016-03-16 20:20
Or just "merge" the HiDPI parts into all other themes and ignore the xressources colors?

**Comment by actionless** [comment] 2016-03-16 21:33
or that

but i thought what picking not only dpi but also colors as well from ~/.Xrexources could be even nicer

and, as @psychon suggested, if we will change the fallback values to match the curernt default theme users who are not set them will not notice any difference

**Comment by Elv13** [comment] 2016-03-16 21:36
I am not sure it wont make a difference. Many people just set those colors and expect them in terminals. I know you can add namespace, but I don't think people expect those colors to be used outside of X11 terminals emulators anymore. AFAIK, no toolkit still use them.

**Comment by psychon** [comment] 2016-03-17 08:03
(awesome doesn't ask for a specific namespace in the resource database, does it?)

I like @Elv13 suggestion. Why shouldn't all themes use `dpi()` for stuff that's specified in something-similar-to-inches?

**Comment by actionless** [comment] 2016-03-17 12:19
it doesn't by default (it's supported in the current c code though, `class` argument)

i don't mind both ways

**Comment by psychon** [comment] 2016-07-04 15:20
Reporter vanished ("I will try later this day" four months ago), the discussion went a bit off-topic and the issue should already be fixed in master (but not in 3.5). Closing.

**Closed by psychon** 2016-07-04 15:20 UTC

**Comment by l0b0** [comment] 2016-11-02 08:48
Any idea when this will be released? [Building awesome-git in Arch Linux seems to be broken](https://aur.archlinux.org/packages/awesome-git) ATM.

**Comment by psychon** [comment] 2016-11-02 09:36
The comment with `-DGENERATE_DOC=False` is right. Since Arch doesn't have a non-broken ldoc, disabling doc generation is needed.

**Comment by l0b0** [comment] 2016-11-02 21:03
Where do I have to put `-DGENERATE_DOC=False`?

**Comment by psychon** [comment] 2016-11-03 08:05
It is an argument to cmake, so inside of the PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=awesome-git#n47

**Comment by l0b0** [comment] 2016-11-03 18:31
Thanks, that got me some way further towards compiling. After installing xcb-util-xrm I'm still getting this error:

```
$ makepkg --syncdeps --install
[…]
[  3%] Linking C executable awesome
CMakeFiles/awesome.dir/awesome.c.o: In function `main':
awesome-git/src/build/awesome.c:620: undefined reference to `xcb_xrm_database_from_default'
awesome-git/src/build/awesome.c:622: undefined reference to `xcb_xrm_database_from_string'
CMakeFiles/awesome.dir/xrdb.c.o: In function `luaA_xrdb_get_value':
awesome-git/src/build/xrdb.c:42: undefined reference to `xcb_xrm_resource_get_string'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/awesome.dir/build.make:1113: awesome] Error 1
make[1]: *** [CMakeFiles/Makefile2:70: CMakeFiles/awesome.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```

Do you know if Awesome is compatible with xcb-util-xrm 1.0-3, which is what is currently in Arch Linux?

**Comment by actionless** [comment] 2016-11-03 18:48
remove build files and try again, i've noticed the same problem when was building it for the first time

**Comment by l0b0** [comment] 2016-11-03 19:09
Thank you, that worked!

**Comment by blueyed** [comment] 2016-11-03 22:43
Hmm, the line does not match?!
It is not that one:
https://github.com/awesomeWM/awesome/blob/0e81479a3f905f4551c88e4ad480972f1a9cff7b/lib/awful/tag.lua#L635 ?!

```lua
function tag.getmwfact(t)
    util.deprecate("Use t.master_width_factor instead of awful.tag.getmwfact")

    return tag.object.get_master_width_factor(t or ascreen.focused().selected_tag)
end
```

**Comment by blueyed** [comment] 2016-11-03 22:44
But let's stop spamming this issue: please create a new one, or ask on IRC.

**Comment by l0b0** [comment] 2016-11-09 20:07
Thank you; I can confirm that font scaling does work on an up-to-date Arch Linux. Will report a minor issue with the square in the corner of the tag indicators separately.

**Comment by kierun** [comment] 2016-11-17 10:52
Any idea when a new release of Awesome will happen so that this change can filter into Fedora? Currently, the Fedora package installs version 3.5.9 (Mighty Ravendark).

**Comment by psychon** [comment] 2016-11-17 11:38
Right now there seem to be many people with not enough time to work on the remaining issues. So sorry, but no, I cannot answer that question.
(Remaining things are mostly minor stuff that anyway has to be done)

**Comment by kierun** [comment] 2016-11-17 15:32
@psychon Thank you. I was just curious, nothing bad implied. ☺
