### ISSUE TITLE
Prompt handles 2-byte Unicode symbols as 2 separate symbols

### ISSUE THREAD

**Issue by loredan** [awesomeWM/awesome#1596] opened 2017-02-24 18:55 UTC
**Note: issue title is my guess for what is happening, I could be wrong**

After 4.0 update when I try to remove cyrillic symbols from the prompt, it takes two backspace presses to remove one symbol. Moreover, if I click backspace once and try to enter something, it doesn't show entered symbols, however when you're trying to continue removing symbols it seems like those symbols you entered are actually there, just not shown.

My guess is that prompt removes just one byte upon pressing backspace, instead of a 2-byte symbol

Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

_Case 1_
1. Mod4+R to open the prompt (assuming default keybindings)
2. Enter symbol 'Ф' (it can be copied and pasted with Shift+Insert)
3. Press backspace

_Case 2_
1. Mod4+R to open the prompt
2. Enter symbol 'Ф' (it can be copied and pasted with Shift+Insert)
3. Press backspace
4. Enter symbols 'abcd'
5. Press backspace until the prompt is empty, counting the presses

**Actual result:**

_Case 1_
Symbol 'Ф' stays in the prompt and removed only by second backspace press

_Case 2_
Symbols 'abcd' are not shown in the prompt, however it takes 5 backspace presses to clear the prompt, which corresponds with the symbols entered

**Expected result:**

_Case 1_
Prompt should be cleared by just one backspace press

_Case 2_
Symbol 'Ф' should be removed by the first backspace press, subsequently entered symbols should be shown in the prompt

**Comment by psychon** [comment] 2017-04-26 15:49
Duplicate of #974

**Closed by psychon** 2017-04-26 15:49 UTC
