### ISSUE TITLE
Unreal Editor Crashes on Awesome

### ISSUE THREAD

**Issue by smalltock** [awesomeWM/awesome#680] opened 2016-02-10 04:50 UTC
I'm trying to run the Unreal 4 Editor. It crashes when I load a project. I've opened a ticket with them, but I figure I should post it here as well. Reason being that UE4 Editor only crashes under Awesome, not under XFCE or i3wm or any other WM/DE.

Here's the stdout log from UE4 Editor... error on line 453:  
http://pastebin.com/3xxBfqPE

Here's a video of the bug in action:  
https://www.youtube.com/watch?v=TIVjZRdhKks

Here's the thread I posted on the Unreal site:  
https://answers.unrealengine.com/questions/366175/how-can-i-get-ue4editor-to-run-on-my-machine-gento.html

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:53
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by smalltock** [comment] 2016-02-10 04:54
Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

**Comment by psychon** [comment] 2016-02-10 08:47
Some ideas:
- Could you try running awesome with `--no-argb`?
- https://github.com/awesomeWM/awesome/issues/305 / https://github.com/awesomeWM/awesome/issues/292 / https://bugzilla.libsdl.org/show_bug.cgi?id=2997 (what's your awesome version? Can you try with awesome-git?) (The BadMatch sounds similar to this)

> Also, the UE4 code is available if you link your github account with your Unreal account, just in case you want to get a look

....

**Comment by psychon** [comment] 2016-02-28 13:16
No news for almost three weeks, so closing under the assumption that $SOMETHING fixed things

**Closed by psychon** 2016-02-28 13:16 UTC

**Comment by smalltock** [comment] 2016-02-28 20:27
Oh, no I'm sorry. I was just occupied with other things. The --no-argb option does stop the crashes. Version 3.5.6

I'll try current git later on, but really, it's not an issue for me.

**Comment by smalltock** [comment] 2016-02-28 20:27
Oh, no I'm sorry. I was just occupied with other things. The --no-argb option does stop the crashes. Version 3.5.6

I'll try current git later on, but really, it's not an issue for me.

**Comment by smalltock** [comment] 2016-02-28 20:27
Oh, no I'm sorry. I was just occupied with other things. The --no-argb option does stop the crashes. Version 3.5.6

I'll try current git later on, but really, it's not an issue for me.

**Comment by psychon** [comment] 2016-02-29 09:15
In that case the issue is somewhere in Unreal-land. For some reason they assume some specific visual for the WM's frame window.

**Comment by psychon** [comment] 2016-02-29 09:16
Oh and: The behaviour on current git should be the same. At least I have no idea why it should be different (the behaviour with regard to `--no-argb` should be the same)

**Comment by machin3io** [comment] 2017-03-16 15:17
Seems to work fine for me, when the layout is floating. Crashes if not.
