### ISSUE TITLE
Using Awesome kills my entire system

### ISSUE THREAD

**Issue by YJH16120** [awesomeWM/awesome#3312] opened 2021-04-04 07:33 UTC
# Info about Awesome
```
yjh@yjh:~/sandbox/my-setup$ awesome --version
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
I'm on Ubuntu 20.04.2.0 LTS

# Reproducing the issue
1. Have a fresh instance of awesome installed
2. Get the default `rc.lua`, and place it in `~/.config/awesome/`
3. Install nitrogen and set any background
4. Go to the bottom of `rc.lua` and add `awful.spawn.with_shell("nitrogen --restore")
5. Restart awesome `super+shift+r`
6. If you have dual monitors (or more) use xrander to extend them.
7. Restart awesome again. 
8. Restart your machine
9. When logging in you'll reach a screen that says something along the lines of "... clean ... blocking" press `alt+shift+f2`
10. Once at tty2, login with  credentials,
11. perform these commands:
```
sudo apt-get purge 'nvidia.*'
sudo apt autoremove
sudo apt-get install xserver-xorg-video-intel
sudo reboot
```
12. Login but with Ubuntu (on Wayland) option (to enable it select the user, at the bottom right find the gear icon, and select Ubuntu on Wayland), if you try and log into any other option it'll loop infinitely, meaning you select the user enter the correct password, the screen flashes and takes you back to the user select screen.
13. Reboot the machine again, either through the command line or the GUI.

# Actual result
This actually happened to me twice, so I got two results but I didn't record the first one. The first one just refused to turn off, I had to wait for my laptop to die naturally, delete Ubuntu then did a clean install. 

The second time this happened I did record and I was able to re-install Ubuntu after wiping it.  [Video](https://youtu.be/qOnz9gdibq4)

# Expected result

I can reboot my machine and see my wallpaper loaded.

**Comment by Elv13** [comment] 2021-04-05 05:09
Sorry, but that seems pretty impossible. There is just no way AwesomeWM can brick the system like that. I mean, it literally has no code that can do what you describe.

The closest that can happen is that AwesomeWM dead locks (because something in the config calls stuff like `io.popen` or `os.execute` which then call the WM, which is blocking waiting for them to return). But `spawn_with_shell` itself doesn't do that.

Then again, even if *that* happens, you would still be able to get to the Ubuntu login page and select something else than Awesome and it would just work. Awesome is an X11 application just like any other. It does not install drivers or messes with the X config itself.

If you start AwesomeWM in Xephyr rather than boot into it, do you see error message or anything strange? Because if not, I don't think there is much I can do to help you debug your system. What you describe is a problem not caused by Awesome. I use Awesome on Ubuntu 20.04 at work with Nvidia and it works just fine

**Comment by YJH16120** [comment] 2021-04-05 05:50
When this happened the first time, I had to re-install Ubuntu. I gave AwesomeWM another try and the same thing happened. So I had to re-install.

**Comment by Elv13** [comment] 2021-04-05 05:54
I don't doubt something happened, but what you describe isn't possible within the scope of what Awesome can and cannot do to your system. Are you sure your system was really broken and choosing something else in the login prompt didn't work?

**Comment by YJH16120** [comment] 2021-04-05 07:19
It was *really* broken. I literally couldn't turn it off, even when holding the power button.

**Comment by Elv13** [comment] 2021-04-05 08:05
> even when holding the power button.

For 5 seconds? That's sounds implausible, those switches are usually hard wired to the power supply. If it's really the case, then that would be a rather catastrophic driver/hardware bug causing an actual hardware lockup (not a kernel panic). I have not seen any hardware do that in like 20 years (and yes, that was Windows Millennium edition). 2010-2012 Mac Book pro (last gen non-retina and first-gen retina) also have a buggy uEFI multi-gpu implementation and the GPU can sometime do funky things, but not *exactly* what you describe. But I don't think you have this specific hardware.

If what you report is correct, then hilariously, running compoton before Awesome might have been the solution, but I wont advise to try. You risk hard bricking your computer each time you run into this problem.

In any case, only an hardware bug, somehow triggered by the wallpaper app can cause this. Awesome worked fine until the wallpaper app change to `rc.lua`. There nothing to do on AwesomeWM side, so I will close this issue. AwesomeWM does **not** set the driver/module and does **not** render the screen on the GPU, X11 does. Wayland based WMs actually render the screen/scene, but not non-compositing WMs like AwesomeWM.

**Closed by Elv13** 2021-04-05 08:05 UTC

**Comment by YJH16120** [comment] 2021-04-05 08:24
> For 5 seconds?
I managed to turn it off the second time. When this happened the **first** time I had to let my laptop die on it's own.

**Comment by actionless** [comment] 2021-04-05 09:33
@YJH16120  please consider reporting this issue to ubuntu community instead

**Comment by Aire-One** [comment] 2021-04-05 10:22
I'm not sure to understand step 11. Why do you uninstall Nvidia drivers to switch to intel X drivers, then using Wayland in step 12?

> The second time this happened I did record and I was able to re-install Ubuntu after wiping it. Video

Looking at the video, (thanks YouTube for 0.25 speed), I can read "SQUASHFS error: Failed to read block XXX". This can be caused by an error while installing Ubuntu or by hardware malfunction.

**Comment by actionless** [comment] 2021-04-05 10:27
> SQUASHFS error: Failed to read block 

btw funny fact, a big fraction of errors reported to Themix/Oomox were originally caused by disk malfunction (and because some themes are using thousands of files, ad copying them to some location of newly generated theme, it was quick to uncover disk errors :) )

**Comment by YJH16120** [comment] 2021-04-05 11:07
> @YJH16120 please consider reporting this issue to ubuntu community instead or mb even to laptop manufacturer (if they support linux officially)

Alright

**Comment by YJH16120** [comment] 2021-04-05 11:08
> I'm not sure to understand step 11. Why do you uninstall Nvidia drivers to switch to intel X drivers, then using Wayland in step 12?
> 
> > The second time this happened I did record and I was able to re-install Ubuntu after wiping it. Video
> 
> Looking at the video, (thanks YouTube for 0.25 speed), I can read "SQUASHFS error: Failed to read block XXX". This can be caused by an error while installing Ubuntu or by hardware malfunction.

Well I didn't know that.
