### ISSUE TITLE
Google chrome push notification style issue.

### ISSUE THREAD

**Issue by anuke** [awesomeWM/awesome#2186] opened 2018-02-09 17:28 UTC
`awesome --version`:
awesome v4.2-249-g584c5ce (Human after all)
 • Compiled against Lua 5.2.4 (running with Lua 5.2)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.4
 • LGI version: 0.9.0

**How to reproduce the issue:**
* Google chrome 64.0.3282.140
* Open the page: https://web-push-book.gauntface.com/demos/notification-examples/
* click any notification button
* see result http://files.i1s.ru/0209202120.png

**Actual result:**
![0209202120](https://user-images.githubusercontent.com/39700/36040822-b2735a38-0dd7-11e8-822d-bbe4f1322e45.png)
http://files.i1s.ru/0209202120.png

**Expected result:**
Several versions ago it was as usual google chrome style notification.

**Comment by 0x041E** [comment] 2018-02-09 17:35
Google chrome has switched from their notifications to linux native notifications which is why it changed. This is not an Awesome WM issue. If Chrome doesn't have option to fall back to the previous notification system i don't think there's anything you can do about it.

**Comment by anuke** [comment] 2018-02-09 18:01
I switched to Unity window manager and Chrome notifications looks like as usual.

**Comment by Elv13** [comment] 2018-02-09 18:22
> looks like as usual.

Well, you can use an alternate notification daemon in Awesome or pimp the built-in notification looks. Google Chrome finally respect the official notification specification. This is a feature, not a bug. Whether or not it's doing the same in all WM is beside the point.

It previously misbehaved and not is compliant. Closing this since the change is on their side *and* they did the *right* thing.

As for the icon size, there is a theme variable you can set to limit them.

**Closed by Elv13** 2018-02-09 18:22 UTC
