### ISSUE TITLE
To show the right version on a manual build

### ISSUE THREAD

**Issue by aajjbb** [awesomeWM/awesome#1270] opened 2016-12-13 17:43 UTC
Hi,
Currently, awesome shows version `awesome v3.5.2-2236-g6b2a752 (The Fox)` when it's compiled from source, as far as I know, we are close to release v4.0 from awesome, so the version shown is not right.

**Comment by Elv13** [comment] 2016-12-13 17:58
You are right, but this is unlikely to be fixed before the release, see the links below.

Duplicate of:

https://github.com/awesomeWM/awesome/issues/1047
https://github.com/awesomeWM/awesome/issues/1266

**Comment by psychon** [comment] 2016-12-13 17:58
Uhm... I don't really understand the issue here.

Release tarballs have a file `.version_stamp` containing the version number. This file is added by the machinery for creating releases (`make dist` which just runs `build-utils/dist.sh` with the desired version number as its argument). Thus, for the next release, nothing needs to be done.

When no `.version_stamp`-file exists (i.e. you are building from git), `awesomeConfig.cmake` uses `git describe --dirty` to come up with a version number. This is what you are seeing in your case. This also works as intended, I think.

All together, the version output is managed automatically. What is it that should change?

**Closed** 2016-12-13 17:58 UTC

**Comment by Elv13** [comment] 2016-12-13 18:08
> All together, the version output is managed automatically. What is it that should change?

Consider the solution proposed in #1266

    grep 3.5.2 -C3 logs/*awesome* --color 

On my laptop (only connected to IRC a few hours a day. Record this issue being raised 23 times (and yes, I curated the result) in the last 18 months. It has also been raised in a few issues and other communication channels. Whether or not it bothers you doesn't change the fact that this is a big problem for many. See all the :+1 on the issues related to this from people who otherwise never comment on anything else beside being in the "watch" list. This is why I proposed to clear this up in #1266 by officially switching to a rolling release version naming scheme. This would clear up all of these issues. 4.1234 is the Awesome 4 API plus 1234 improvements. Right now, the stable is 3.5.9 and the current is 3.5.2-2236 "random API changes with 2236 improvement over a random old 3 years old version".

**Comment by psychon** [comment] 2016-12-13 19:30
I read that "I'd stay with the auto-magic version numbers, but I'd change the frequency of git tags being added". So the implementation part of version numbers stays how they are.

**Comment by Elv13** [comment] 2016-12-13 19:45
I'd stay with the auto-magic version numbers, <s>but I'd change the frequency of git tags being added</s> but bump the first number and tag new version **when the API changes** instead of *random point we declare stable*.

**Comment by aajjbb** [comment] 2016-12-14 20:17
I wasn't aware of the other discussions about this issue, but I believe that a rolling release tagging system would be a good option as @Elv13 pointed out, as awesome has been developed in a 'rolling release way' informally about a time.
