### ISSUE TITLE
Slow menubar startup

### ISSUE THREAD

**Issue by Architektor** [awesomeWM/awesome#1496] opened 2017-01-31 15:47 UTC
Hey there I'm using fresh awesome v4 and I'm curious why the prompt (or whatever the mod+p thing name is) is starting awfully slow. I love the feature but when i press mod+p for the first time after reboot my whole machine is paralyzed for about ten seconds. After the prompt appears, it's quite laggy and every symbol i type renders in the text box with a huge pain. Then the whole thing caches to ram (i dunno actually but feels like) and the magic prompt is working as expected, with a speed of an eagle. Do someone know what causes this slow behaviour? I'm bad at lua/c code, but i'm starting my investigation, cause now it feels like this monster is grepping my whole filesystem on the first launch

**Comment by Elv13** [comment] 2017-01-31 15:49
This is because it does ~10k file system requests looking for icons of the right size and `.desktop`. I guess you have a 4200 RPM hard drive. I have a version that does the same thing in < 500ms, but it depends on GTK and its cache, so it cannot be used in the "standard version" of the menubar.

**Comment by Architektor** [comment] 2017-01-31 15:59
@Elv13 I still have the old laptop without SSD. So i'll try to somehow turn off icons at all in my setup. Ty for response.

**Comment by yejingchen** [comment] 2017-02-23 08:45
Hello, I also experienced this issue since awesome 4.0. My system is Arch Linux, `awesome --version` gives:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

I tried running `journalctl -f` and wait until there is no log appearing, then I press Super+P, and the following lines appeared:

```
E: Error opening directory '/usr/local/share/applications': No such file or directory
W: awesome: a_glib_poll:389: Last main loop iteration took 3.056006 seconds! Increasing limit for this warning to that value.
```

I wonder if there exists another way to improve this without changing to SSD?

**Comment by Elv13** [comment] 2017-02-23 18:11
Of course. My config has a version of the menu that's as fast as Gnome2 one. In theory, it's code could be merged into the menubar and solve the problem. However it's a lot of work and I wont do it as less and less people have the issue and it adds a new dependency (GTK) on Awesome. *But*, if you are willing to do it, then I can see this being merged if the GTK code path is optional

https://github.com/Elv13/awesome-configs/blob/master/utils/fd_async.lua
https://github.com/Elv13/awesome-configs/blob/master/customMenu/appmenu.lua

**Comment by actionless** [comment] 2017-02-24 10:05
i don't mind having gtk as a dependency :3  
https://github.com/awesomeWM/awesome/issues/1560

**Comment by psychon** [comment] 2017-03-07 14:21
I extracted the code that `menubar` uses to "find stuff". It is here: https://gist.github.com/psychon/e181ac6af54b70687ce0d4d4e4126d0f

Could everyone who has this slowness problem download this, run the following and tell me the result?
```
echo 3 | sudo tee /proc/sys/vm/drop_cache
lua menu_example.lua
lua menu_example.lua
```
Each time the program is run, it does two complete lookups of "everything" and prints the time each one took. This does two lookups, because for the second one some caches that we implemented where already filled.

I get:
```
3
Please run the following first to get 'slow results': echo 3 | sudo tee /proc/sys/vm/drop_caches
error	Error opening directory '/usr/local/share/applications': No such file or directory
result:	table: 0x55cae87f01a0
done in 0.127 sec

error	Error opening directory '/usr/local/share/applications': No such file or directory
result:	table: 0x55cae891f710
done in 0.0302 sec

Please run the following first to get 'slow results': echo 3 | sudo tee /proc/sys/vm/drop_caches
error	Error opening directory '/usr/local/share/applications': No such file or directory
result:	table: 0x55a475f9c380
done in 0.073 sec

error	Error opening directory '/usr/local/share/applications': No such file or directory
result:	table: 0x55a47601e280
done in 0.029 sec
```
So with my SSD, actually hitting disc is about two times slower than when stuff already is in RAM. And after the caching stuff we have implemented is filled, this gets again faster by factor two.

> This is because it does up to ~10k file system requests

According to `strace -c`, the whole program does a total of 2596 syscalls for me. So I seriously doubt that there are 10k file system requests.
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
  0.00    0.000000           0       505           read
  0.00    0.000000           0        11           write
  0.00    0.000000           0       367       125 open
  0.00    0.000000           0       242           close
  0.00    0.000000           0        14         9 stat
  0.00    0.000000           0       221           fstat
  0.00    0.000000           0       760       695 lstat
  0.00    0.000000           0        51           poll
  0.00    0.000000           0        62           mmap
  0.00    0.000000           0        46           mprotect
  0.00    0.000000           0         2           munmap
  0.00    0.000000           0        23           brk
  0.00    0.000000           0         4           rt_sigaction
  0.00    0.000000           0         3           rt_sigprocmask
  0.00    0.000000           0        88        23 access
  0.00    0.000000           0         2           clone
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         6           getdents
  0.00    0.000000           0         1           getrlimit
  0.00    0.000000           0         1           getresuid
  0.00    0.000000           0         1           getresgid
  0.00    0.000000           0         3         3 statfs
  0.00    0.000000           0         1           arch_prctl
  0.00    0.000000           0       177         3 futex
  0.00    0.000000           0         1           set_tid_address
  0.00    0.000000           0         1           set_robust_list
  0.00    0.000000           0         2           eventfd2
------ ----------- ----------- --------- --------- ----------------
100.00    0.000000                  2596       858 total
```

**Comment by Wayneoween** [comment] 2017-09-23 11:31
So after migrating from 3.5.6 (Ubuntu 16.04 repo) to 4.2 from git this issue occured for me.
These values come from a Samsung SSD 256GB.

```
marius at pewpew in ~
$ echo 3 | sudo tee /proc/sys/vm/drop_caches 
3
marius at pewpew in ~
$ lua menu_example.lua 
Please run the following first to get 'slow results': echo 3 | sudo tee /proc/sys/vm/drop_caches
result:	table: 0x1024b60
done in 0.425 sec

result:	table: 0x121c7d0
done in 0.102 sec

marius at pewpew in ~
$ lua menu_example.lua 
Please run the following first to get 'slow results': echo 3 | sudo tee /proc/sys/vm/drop_caches
result:	table: 0xef5670
done in 0.328 sec

result:	table: 0x119efa0
done in 0.103 sec
```

This isn't terrible, but not what `.xsession-errors` is telling me:

```
2017-09-23 13:20:34 W: awesome: a_glib_poll:432: Last main loop iteration took 0.185712 seconds! Increasing limit for this warning to that value.
2017-09-23 13:20:58 W: awesome: a_glib_poll:432: Last main loop iteration took 3.152936 seconds! Increasing limit for this warning to that value.
```

I would totally be okay if it'd just take a second for that initial lookup, even the 3+ seconds are bearable.

Just wanted to add some info to this. Side note since it just occured to me, if I'd be to run your lua script before typing meta+p, it could work around that initial wait, probably. :thinking:

**Comment by unode** [comment] 2017-10-27 16:03
I'm suffering from this issue after migrating to NixOS which makes use of an unconventional `bin` folder with several levels of symlinks.

With another Linux distribution it takes a fraction of a second to launch for the first time (I have an SSD).
In NixOS it takes roughly 8 seconds every time after `awesome.restart()` and is instantaneous every other time. Dropping caches has some effect but is not the major source of slowdown.

The menu script above finishes rather quickly but I suspect due to not finding any desktop files. The locations `/usr/share/applications` and `/usr/local/share/applications` do not exist. Pointing it to the actual location `/run/current-system/sw/share/applications` makes it take 0.5 seconds, which is still far from the 8 seconds that awesome displays.

From conversations with @Elv13 on `#awesome@OFTC` it's likely that the extra time is due to building a cache of icons but I'd need a more accurate benchmark script to be able to tell.

On the same line of thought, if anyone is using a slow disk and NixOS the 8 second figure might look a lot worse.

**Comment by unode** [comment] 2017-10-27 16:29
Did an strace of awesome by attaching `strace -c -p $(pidof awesome)` after `awesome.restart()` and launching `menubar.show()` for the first time. After seeing the menubar I hit <kbd>Esc</kbd> to cancel the menubar and hit <kbd>Ctrl</kbd>+<kbd>C</kbd> on the strace giving:

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 47.37    0.013434        1919         7           clone
 29.07    0.008246           0     64031     63822 lstat
 22.15    0.006281          17       359         1 read
  0.85    0.000241          27         9           write
  0.25    0.000071           0      2371           gettimeofday
  0.11    0.000032           0        77           futex
  0.06    0.000018           0       211           access
  0.05    0.000013           0       193        28 open
  0.05    0.000013           0       164           fstat
  0.05    0.000013           0       379         8 lseek
  0.00    0.000000           0       167           close
  0.00    0.000000           0        43           stat
  0.00    0.000000           0       192           poll
  0.00    0.000000           0         7           mmap
  0.00    0.000000           0         5           mprotect
  0.00    0.000000           0       176           brk
  0.00    0.000000           0         6           rt_sigaction
  0.00    0.000000           0         4           rt_sigreturn
  0.00    0.000000           0        36           writev
  0.00    0.000000           0       231       191 recvmsg
  0.00    0.000000           0         4           wait4
  0.00    0.000000           0         1           fcntl
  0.00    0.000000           0         3         3 mkdir
  0.00    0.000000           0        42           readlink
  0.00    0.000000           0         1           restart_syscall
  0.00    0.000000           0       113           clock_gettime
  0.00    0.000000           0        12           pipe2
------ ----------- ----------- --------- --------- ----------------
100.00    0.028362                 68844     64053 total
```

**Comment by Elv13** [comment] 2017-10-27 16:36
> it's likely that the extra time is due to building a cache of icons but I'd need a more accurate benchmark script to be able to tell.

By default, Awesome would not use the cache anyway unless you monkeypatch it to do so. All I was saying is that the cache should be built despite all the magic NixOS does. We *could* make use of it and my version *does*.

On normal systems with fast SSD, it is < 0.5s despite not using it. If you have an SSH and 8s, then there is something really, really wrong with the way it's done. 

Now that LGI 0.9.2 is released, we have an LGI release that's finally good enough to enable the (optional) cache without the low risk of segfault it used to have. However, Awesome still officially support LGI 0.8. So unless we are very agressive at bumping the requirements (and forcing downstream [U16.04/Debian9] to update their package, it will take a while.

**Comment by psychon** [comment] 2017-10-28 09:11
>  29.07    0.008246           0     64031     63822 lstat

That's a lot of failing `lstat` calls (99.7%), but more interesting, they almost take no time (8 milliseconds)...?!? Also, what's up with the seven calls to `clone`???

**Comment by unode** [comment] 2017-10-28 12:12
This might be due to some of the custom widgets I have on awesome.

Here's another replicate:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 59.11    0.018942        2706         7           clone
 19.74    0.006326           0     64031     63822 lstat
 17.02    0.005455          12       445         1 read
  2.75    0.000882          11        81           futex
  0.81    0.000261          26        10           write
  0.29    0.000094           5        18           pipe2
  0.20    0.000064           0      2518           gettimeofday
  0.04    0.000013           0       206           close
  0.03    0.000011           0       324       264 recvmsg
  0.00    0.000000           0       229        37 open
  0.00    0.000000           0        43           stat
  0.00    0.000000           0       191           fstat
  0.00    0.000000           0       289           poll
  0.00    0.000000           0       388        12 lseek
  0.00    0.000000           0         4           mmap
  0.00    0.000000           0         3           mprotect
  0.00    0.000000           0       178           brk
  0.00    0.000000           0        10           rt_sigaction
  0.00    0.000000           0         5           rt_sigreturn
  0.00    0.000000           0        60           writev
  0.00    0.000000           0       211           access
  0.00    0.000000           0         6           wait4
  0.00    0.000000           0         1           fcntl
  0.00    0.000000           0         3         3 mkdir
  0.00    0.000000           0        42           readlink
  0.00    0.000000           0         1           restart_syscall
  0.00    0.000000           0       153           clock_gettime
------ ----------- ----------- --------- --------- ----------------
100.00    0.032048                 69457     64139 total
```

and one with about as much time as the first takes to run but having awesome "idle"
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 72.68    0.068537        3607        19           clone
 26.11    0.024618          47       527           read
  1.15    0.001083          57        19           write
  0.02    0.000018           0       870           poll
  0.02    0.000015           0       928           gettimeofday
  0.01    0.000013           0      1039       898 recvmsg
  0.01    0.000011           0       262           fstat
  0.01    0.000007           0        19           rt_sigreturn
  0.00    0.000000           0       367       105 open
  0.00    0.000000           0       376           close
  0.00    0.000000           0        38        38 lseek
  0.00    0.000000           0        38           rt_sigaction
  0.00    0.000000           0       144           writev
  0.00    0.000000           0        19           wait4
  0.00    0.000000           0         1           restart_syscall
  0.00    0.000000           0       521           clock_gettime
  0.00    0.000000           0        57           pipe2
------ ----------- ----------- --------- --------- ----------------
100.00    0.094302                  5244      1041 total
```

**Comment by psychon** [comment] 2017-10-30 12:47
Could someone test if the following patch makes a difference? https://gist.github.com/psychon/36263447afcb3b6d9457515ea56ed7dd

Instead of checking the existence of each individual file, this now once lists the whole directory contents and uses that information to decide which files exist. Implementation based on (from https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html):

> Implementation Notes
>
> The algorithm as described in this document works by always looking up filenames in directories (a stat in unix terminology). A good implementation is expected to read the directories once, and do all lookups in memory using that information.
>
> This caching can make it impossible for users to add icons without having to restart applications. In order to handle this, any implementation that does caching is required to look at the mtime of the toplevel icon directories when doing a cache lookup, unless it already did so less than 5 seconds ago. This means that any icon editor or theme installation program need only to change the mtime of the the toplevel directory where it changed the theme to make sure that the new icons will eventually get used.

(Note: The current patch is slightly wrong since it checks the mtime of `/usr/share/icons` instead of `/usr/share/icons/Adwaita`)

**Comment by unode** [comment] 2017-10-30 14:39
Overall it takes a bit longer, ~13 seconds instead of ~8 on my system.
`strace` looks a lot better in terms of `lstat` though (2 replicates below):

```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 57.56    0.006811        1362         5           clone
 37.40    0.004425          11       409         1 read
  1.46    0.000173          19         9           write
  1.32    0.000156           0      3941      3006 lstat
  0.63    0.000074           0       651        28 open
  0.45    0.000053           0      1038           getdents
  0.31    0.000037           0       625           close
  0.22    0.000026           0       751           stat
  0.21    0.000025           0       622           fstat
  0.18    0.000021           0       750           readlink
  0.10    0.000012           0       247       192 recvmsg
  0.08    0.000010           0        81           futex
  0.08    0.000009           0       115           clock_gettime
  0.00    0.000000           0       226           poll
  0.00    0.000000           0       384         8 lseek
  0.00    0.000000           0         4           mmap
  0.00    0.000000           0         3           mprotect
  0.00    0.000000           0       172           brk
  0.00    0.000000           0         6           rt_sigaction
  0.00    0.000000           0         4           rt_sigreturn
  0.00    0.000000           0        54           writev
  0.00    0.000000           0       212           access
  0.00    0.000000           0         4           wait4
  0.00    0.000000           0         3         3 mkdir
  0.00    0.000000           0      2070           gettimeofday
  0.00    0.000000           0         1           restart_syscall
  0.00    0.000000           0        12           pipe2
------ ----------- ----------- --------- --------- ----------------
100.00    0.011832                 12399      3238 total

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 57.65    0.004633        1158         4           clone
 35.02    0.002814           8       371         1 read
  2.70    0.000217          27         8           write
  2.54    0.000204           0      3941      3006 lstat
  1.44    0.000116           0       751           stat
  0.25    0.000020           0      2064           gettimeofday
  0.21    0.000017           0       599           close
  0.19    0.000015           0        78           clock_gettime
  0.00    0.000000           0       623        20 open
  0.00    0.000000           0       602           fstat
  0.00    0.000000           0       158           poll
  0.00    0.000000           0       382         6 lseek
  0.00    0.000000           0         4           mmap
  0.00    0.000000           0         3           mprotect
  0.00    0.000000           0       143           brk
  0.00    0.000000           0         4           rt_sigaction
  0.00    0.000000           0         3           rt_sigreturn
  0.00    0.000000           0        39           writev
  0.00    0.000000           0       212           access
  0.00    0.000000           0       169       129 recvmsg
  0.00    0.000000           0         3           wait4
  0.00    0.000000           0      1038           getdents
  0.00    0.000000           0         3         3 mkdir
  0.00    0.000000           0       750           readlink
  0.00    0.000000           0        79           futex
  0.00    0.000000           0         1           restart_syscall
  0.00    0.000000           0         9           pipe2
------ ----------- ----------- --------- --------- ----------------
100.00    0.008036                 12041      3165 total
```

**Comment by psychon** [comment] 2017-11-15 14:47
Uhm. On my system, there are 31247 calls to lstat for something that involved opening the menubar. Of those, 28949 remain if I make awesome stop looking up the icons for applications. 2298 remain if I do the equivalent of `menubar.menu_gen.lookup_category_icons = function() end`. 0 remain if I do both.

So, just about 7% of the time(?) is used for looking up icons of actual programs. Most `lseek` calls are used for category icons. What the heck!?

Could people test if `menubar.menu_gen.lookup_category_icons = function() end` makes things noticeably faster?

**Comment by unode** [comment] 2017-11-15 23:42
That's pretty impressive. `menubar.menu_gen.lookup_category_icons = function() end` makes the menubar show up almost immediately. As in, I don't have enough time to start/stop a timer.

And I can confirm that program icons are still displayed. They show up maybe 1 second later. Still perfectly reasonable timing.

**Closed** 2017-11-18 00:49 UTC

**Comment by port19x** [comment] 2023-05-29 09:24
If someone else is here from their favorite search engine looking to completely disable icons in the menu bar, 
`menubar.utils.lookup_icon = function() end` worked for me.
