### ISSUE TITLE
Tooltip placement error 

### ISSUE THREAD

**Issue by Trial97** [awesomeWM/awesome#3557] opened 2022-02-04 08:00 UTC
Output of `awesome --version`:

```
awesome v4.3-1348-g2d6244f94-dirty (Too long)
 • Compiled against Lua 5.4.3 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
```
**How to reproduce the issue:**

Wanted to have a tooltip for a widget  with the following:
```
awful.tooltip({
        objects= {widget_button},
        mode = 'outside',
        text = 'text'
})
```
Then move the cursor over the widget to display the tooltip

**Actual result:**

I'm getting an error regarding a bad argument:
```
2022-02-04 09:50:57 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	[C]: in field 'field'
	/usr/share/lua/5.4/lgi/record.lua:118: in function </usr/share/lua/5.4/lgi/record.lua:92>
	(...tail calls...)
	[C]: in metamethod 'newindex'
	/usr/share/lua/5.4/lgi/record.lua:178: in function </usr/share/lua/5.4/lgi/record.lua:162>
	(...tail calls...)
	/usr/share/awesome/lib/awful/placement.lua:823: in upvalue 'fit_in_bounding'
	/usr/share/awesome/lib/awful/placement.lua:1817: in function </usr/share/awesome/lib/awful/placement.lua:1740>
	(...tail calls...)
	/usr/share/awesome/lib/awful/tooltip.lua:175: in upvalue 'apply_outside_mode'
	/usr/share/awesome/lib/awful/tooltip.lua:201: in upvalue 'set_geometry'
	/usr/share/awesome/lib/awful/tooltip.lua:221: in upvalue 'show'
	/usr/share/awesome/lib/awful/tooltip.lua:772: in local 'func'
	/usr/share/awesome/lib/gears/object.lua:160: in function 'gears.object.emit_signal'
	/usr/share/awesome/lib/wibox/drawable.lua:329: in upvalue 'emit_difference'
	/usr/share/awesome/lib/wibox/drawable.lua:350: in upvalue 'handle_motion'
	/usr/share/awesome/lib/wibox/drawable.lua:443: in function </usr/share/awesome/lib/wibox/drawable.lua:443>
error: /usr/share/lua/5.4/lgi/record.lua:118: bad argument #3 to 'field' (number has no integer representation)
```

**Expected result:**

The tooltip should be displayed outside.
With the other mode(`mouse`) is used there is no error.

**Comment by Aire-One** [comment] 2022-02-04 08:48
Hello,

Awesome with Lua 5.4 needs the latest version of LGI that is not yet released. You have to make sure you manually build and install it from source https://github.com/pavouk/lgi.

**Comment by Trial97** [comment] 2022-02-04 09:16
Hi @Aire-One,

As I installed awesome with `pamac` it automatically installed the [lua-lgi-git](https://aur.archlinux.org/packages/lua-lgi-git) AUR package.
Shouldn't this AUR package be the latest version of the library?

**Comment by Aire-One** [comment] 2022-02-04 10:04
Hm... Yes I think it should be the correct version then. 

In this case, that would mean the issue is indeed a regression in awesome. I'll not have the time to investigate the issue right now, tho... Sorry @Trial97.

**Comment by Aire-One** [comment] 2022-02-05 12:54
Hello @Trial97, 

I had some time to investigate your issue, here is my current status:

Sadly, I didn't have the luck to replicate the issue.

My awesome version: (identical to yours)

```sh
$ ./build/awesome --version
awesome v4.3-1348-g2d6244f94-dirty (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no
````

Here is the patch I have applied on top of the default awesomerc.lua:

```patch
diff --git a/awesomerc.lua b/awesomerc.lua
index bdbdbaa73..2f7854f15 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -1,7 +1,7 @@
 -- awesome_mode: api-level=4:screen=on
 -- If LuaRocks is installed, make sure that packages installed through it are
 -- found (e.g. lgi). If LuaRocks is not installed, do nothing.
-pcall(require, "luarocks.loader")
+--pcall(require, "luarocks.loader")
 
 -- @DOC_REQUIRE_SECTION@
 -- Standard awesome library
@@ -185,6 +185,18 @@ screen.connect_signal("request::desktop_decoration", function(s)
         }
     }
 
+
+    s.testimagewidget = wibox.widget {
+        image  = beautiful.awesome_icon,
+        resize = false,
+        widget = wibox.widget.imagebox
+    }
+    s.testimagewidget_tooltip = awful.tooltip {
+        objects= { s.testimagewidget },
+        mode = 'outside',
+        text = 'text'
+    }
+
     -- @DOC_WIBAR@
     -- Create the wibox
     s.mywibox = awful.wibar {
@@ -202,6 +214,7 @@ screen.connect_signal("request::desktop_decoration", function(s)
             s.mytasklist, -- Middle widget
             { -- Right widgets
                 layout = wibox.layout.fixed.horizontal,
+                s.testimagewidget,
                 mykeyboardlayout,
                 wibox.widget.systray(),
                 mytextclock,
```

![2022-02-05-133651_1920x2280_scrot](https://user-images.githubusercontent.com/6602958/152642611-927ee7d5-ecdc-4ef0-8a10-5ff22b16b9ee.png)

I had no error in the logs.

The error logs you provided sounds like there is a place in our code where we fail our math, `bad argument #3 to 'field' (number has no integer representation)` :shrug: I'll try to give a look in this direction and come back later.

**Comment by Trial97** [comment] 2022-02-05 17:50
Hi @Aire-One,

Thanks for investigating this!
I could still reproduce the error using the provided patch on the default awesomerc.lua.
Also, I had some time today and tested this on a secondary laptop, but I got the same error.

**Comment by Trial97** [comment] 2022-02-05 18:36
Hi @Aire-One,

I also tested this on a fresh Manjaro virtual machine and I was still able to reproduce it.
As I do not know if what I did is right here the steps I followed:
1. Start from Manjaro xfce edition
2. Install from AUR both [awesome-git](https://aur.archlinux.org/packages/awesome-git) and [lua-lgi-git](https://aur.archlinux.org/packages/lua-lgi-git) 
3. Add the pathed config in ~/.config/awesome
4. Switch to awesomeWM session 
5. When I hover over the button I get the same error 

Hope this helps

**Comment by pepijnKrijnsen** [comment] 2022-02-09 16:43
If it helps - using @Aire-One's code I don't get an error either. Popup appears as normal.

```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**Comment by Aire-One** [comment] 2022-02-14 18:29
No progress to report, but I randomly had the error while building awesome :

````
[ 86%] Generating doc/images/AUTOGEN_awful_tooltip_mouse.svg
Result: 1
Error:
/usr/bin/lua: /usr/share/lua/5.4/lgi/record.lua:118: bad argument #3 to 'field' (number has no integer representation)
stack traceback:
        [C]: in field 'field'
        /usr/share/lua/5.4/lgi/record.lua:118: in function </usr/share/lua/5.4/lgi/record.lua:92>
        (...tail calls...)
        [C]: in metamethod 'newindex'
        /usr/share/lua/5.4/lgi/record.lua:178: in function </usr/share/lua/5.4/lgi/record.lua:162>
        (...tail calls...)
        ...e/aireone/documents/prog/awesome/lib/awful/placement.lua:806: in upvalue 'fit_in_bounding'
        ...e/aireone/documents/prog/awesome/lib/awful/placement.lua:1559: in function <...e/aireone/documents/prog/awesome/lib/awful/placement.lua:1482>
        (...tail calls...)
        /home/aireone/documents/prog/awesome/lib/awful/tooltip.lua:139: in upvalue 'apply_outside_mode'
        /home/aireone/documents/prog/awesome/lib/awful/tooltip.lua:165: in upvalue 'set_geometry'
        /home/aireone/documents/prog/awesome/lib/awful/tooltip.lua:185: in upvalue 'show'
        /home/aireone/documents/prog/awesome/lib/awful/tooltip.lua:691: in local 'func'
        /home/aireone/documents/prog/awesome/lib/gears/object.lua:135: in function 'gears.object.emit_signal'
        /home/aireone/documents/prog/awesome/lib/wibox/init.lua:254: in local 'func'
        /home/aireone/documents/prog/awesome/lib/gears/object.lua:135: in function 'gears.object.emit_signal'
        /home/aireone/documents/prog/awesome/lib/wibox/drawable.lua:361: in local 'func'
        /home/aireone/documents/prog/awesome/lib/gears/object.lua:135: in function 'gears.object.emit_signal'
        ...ne/documents/prog/awesome/tests/examples/shims/mouse.lua:35: in function 'mouse.coords'
        ...me/tests/examples/awful/tooltip/preferred_alignment2.lua:27: in main chunk
        ...documents/prog/awesome/tests/examples/awful/template.lua:12: in main chunk
        [C]: in ?
```

**Comment by Aire-One** [comment] 2022-02-16 08:07
It took me too long to realize that I run `make -j5`, so 5 jobs in parallel. Logs were mixed up,  that's why the error looked random to me at build time... It actually can be consistently reproduced with the `tests/examples/awful/tooltip/preferred_alignment2.lua` example.

As a side note, I successfully attach the debugger https://github.com/tomblind/local-lua-debugger-vscode with:

```
        {
            "type": "lua-local",
            "request": "launch",
            "name": "Debug examples/awful/*",
            "cwd": "${workspaceFolder}/tests/examples/awful",
            "stopOnEntry": false,
            "program": {
                "file": "${workspaceFolder}/tests/examples/awful/template.lua",
                "lua": "/usr/bin/lua"
            },
            "args": [
                "${workspaceFolder}/tests/examples/awful/tooltip/preferred_alignment2.lua",
                "${workspaceFolder}/build/doc/images/AUTOGEN_awful_tooltip_preferred_alignment2"
            ],
            "env": {
                "LUA_PATH": "${workspaceFolder}/tests/examples/shims/?.lua;${workspaceFolder}/tests/examples/shims/?/init.lua;${workspaceFolder}/tests/examples/shims/?;${workspaceFolder}/lib/?.lua;${workspaceFolder}/lib/?/init.lua;${workspaceFolder}/lib/?;${workspaceFolder}/themes/?.lua;${workspaceFolder}/themes/?;/usr/share/lua/5.4/?.lua;/usr/share/lua/5.4/?/init.lua;/usr/lib/lua/5.4/?.lua;/usr/lib/lua/5.4/?/init.lua;./?.lua;./?/init.lua",
                "SOURCE_DIRECTORY": "${workspaceFolder}",
                "AWESOME_THEMES_PATH": "${workspaceFolder}/themes/",
            },
        },
        {
            "type": "lua-local",
            "request": "launch",
            "name": "Debug examples/awful/* Lua 5.3",
            "cwd": "${workspaceFolder}/tests/examples/awful",
            "stopOnEntry": false,
            "program": {
                "file": "${workspaceFolder}/tests/examples/awful/template.lua",
                "lua": "/usr/bin/lua5.3"
            },
            "args": [
                "${workspaceFolder}/tests/examples/awful/tooltip/preferred_alignment2.lua",
                "${workspaceFolder}/build/doc/images/AUTOGEN_awful_tooltip_preferred_alignment2"
            ],
            "env": {
                "LUA_PATH": "${workspaceFolder}/tests/examples/shims/?.lua;${workspaceFolder}/tests/examples/shims/?/init.lua;${workspaceFolder}/tests/examples/shims/?;${workspaceFolder}/lib/?.lua;${workspaceFolder}/lib/?/init.lua;${workspaceFolder}/lib/?;${workspaceFolder}/themes/?.lua;${workspaceFolder}/themes/?;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;/usr/lib/lua/5.3/?.lua;/usr/lib/lua/5.3/?/init.lua;./?.lua;./?/init.lua",
                "SOURCE_DIRECTORY": "${workspaceFolder}",
                "AWESOME_THEMES_PATH": "${workspaceFolder}/themes/",
            },
        }
```

My finding are not surprising at all and match the stack trace: 

https://github.com/awesomeWM/awesome/blob/bd776c98015767e156556e6651da4241b657d5bb/lib/awful/placement.lua#L806

This function call needs a table with integers while we have some floating values.

We can find the definition for this in lgi sources:

https://github.com/lgi-devs/lgi/blob/master/lgi/override/cairo.lua#L123-L128

The error seems to only happen with Lua 5.4 / LGI master. With my tests on Lua 5.3, there is no error at all. So I'm not sure if that's a regression from Lua/lgi. Maybe there was something before that allows to use floating numbers :shrug:

**Comment by Aire-One** [comment] 2022-02-17 17:15
Actually not related to the Lua version, see https://github.com/awesomeWM/awesome/pull/3572#issuecomment-1043190878

**Comment by Aire-One** [comment] 2022-07-01 07:21
Fixed by https://github.com/awesomeWM/awesome/pull/3572. I'm closing the issue.

**Closed by Aire-One** 2022-07-01 07:21 UTC
Labels: bug, confirmed
