### ISSUE TITLE
GC does not free some data

### ISSUE THREAD

**Issue by SammysHP** [awesomeWM/awesome#1489] opened 2017-01-29 20:52 UTC
```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

```lua
local gears = require("gears")
local textbox = require("wibox.widget.textbox")

local test = {}

function test:_update_widget()
    self.widget.text = math.random(100,999)
end

function test.new()
    local self = setmetatable({}, { __index = test })

    self.widget = textbox()
    self.widget.text = "test"

    gears.timer.start_new(0.1, function() self:_update_widget(); return true end)

    return self
end

testwidget = test.new()
-- add testwidget to wibar
```

**Actual result:**

The process of awesome starts with 24 MB resident memory. It increases constantly and after a few minutes stabilizes at 35 MB. Then a while later it starts increasing again.

**Expected result:**

Memory should stay near 24 MB.

**More details:**

If you add `collectgarbage()` in the timer callback after `self:_update_widget()` the memory size will not increase and stays slightly above 24 MB.

PS: Sorry for the bad title, please fix if you know a better one.

**edit:** Even these two lines of code result in increasing memory usage:

```lua
testwidget = wibox.widget.textbox()
gears.timer.start_new(0.1, function() testwidget.text = math.random(100,999); return true end)
```

Running it at lower frequency (e.g. 2s interval) doesn't help (it takes much longer, though).

**Comment by psychon** [comment] 2017-01-30 08:27
Not much time to investigate right now, but:

> -- add testwidget to wibar

Does this not occur without this? I.e. does this need the widget to be displayed somewhere to caused increasing memory usage?

> local self = setmetatable({}, { __index = test })

Does your widget even display correctly? Such metatable magic should cause problems. Can you try if it works if you do:
```lua
local self = textbox()
self.widget = self -- This line just exists so that the rest of the code continues working; I don't want to fix all of it up right now.
```

**Comment by SammysHP** [comment] 2017-01-30 10:17
> Does this not occur without this? I.e. does this need the widget to be displayed somewhere to caused increasing memory usage?

It appears to occurs only if the widget is added to the wibar.

> Does your widget even display correctly?

Yes

> Such metatable magic should cause problems.

It is from your mpc.lua… (You shouldn't have added it to the recipes.)

**Comment by psychon** [comment] 2017-01-30 16:11
Hm, I cannot reproduce. I took the original example, lowered the timeout to `0.01` and ran it under `valgrind --tool=massif`. Memory usage looks non-interesting over time:
```
    MB
27.67^##                                                                      
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#                                                                       
     |#      ::                 @  :              ::              :  :        
     |#      :        ::        @  :  :  :  :     :  ::    :  ::  :  :  :  @ :
     |#      :  :  @  :  :: :@ :@ ::  :  :  :  : ::  :     :  :  :: @:  :  @ :
     |#     ::  :  @  :  :  :@ :@ ::  :  :  :  : ::  : ::  :  :  :: @: :: :@ :
     |#  :: :: ::  @ ::  :  :@ :@ ::  ::::  : :: :: :: :  :: :: ::::@: :: :@ :
     |#  :  :: ::  @::: @:  :@::@::::::: :  : :: :: :: :  :: :: ::::@::::::@::
     |# ::  :: ::  @::: @: ::@::@:::: :: :::: ::@:: :: : @:: :: ::::@::::::@::
     |# :: ::: ::::@::: @: ::@::@:::: :: :: ::::@:: :: : @::::: ::::@::::::@::
     |# :: ::: ::: @::: @: ::@::@:::: :: :: ::::@:: :: : @::::: ::::@::::::@::
     |# :: ::: ::: @::: @: ::@::@:::: :: :: ::::@:: :: : @::::: ::::@::::::@::
     |# :: ::: ::: @::: @: ::@::@:::: :: :: ::::@:: :: : @::::: ::::@::::::@::
     |# :: ::: ::: @::: @: ::@::@:::: :: :: ::::@:: :: : @::::: ::::@::::::@::
   0 +----------------------------------------------------------------------->Gi
     0                                                                   44.48
```
Any hints for me?

Can you try running the pure-Lua example from https://github.com/pavouk/lgi/issues/60 to see if you are affected by that bug?

**Comment by SammysHP** [comment] 2017-01-30 17:02
Hmm, my massif graph looks similar. Also I noticed that there is just an initial rise. Sometimes (!) it will rise again after some time. Here is a graph with `while true; do ps --pid … -o rss= >> mem.log; sleep 2; done`.

```lua
testwidget = wibox.widget.textbox()
gears.timer.start_new(0.1, function() testwidget.text = math.random(100,999); return true end)
```

![](https://cloud.githubusercontent.com/assets/922874/22432690/07bea220-e716-11e6-8689-924f84f661f3.png)


```lua
testwidget = wibox.widget.textbox()
gears.timer.start_new(0.1, function() testwidget.text = math.random(100,999); collectgarbage(); return true end)
```

![](https://cloud.githubusercontent.com/assets/922874/22432721/1bc11a64-e716-11e6-93f2-e91c8c15daeb.png)


I might try your pure-lua example later.

**Comment by alosich** [comment] 2017-07-13 05:32
Not sure if this related: I'm using gears timer and spawn_easy_async to create widget that updated continously from output of command:

```lua
function info_text_widget(image, timeout, command)
   local layout = wibox.layout.fixed.horizontal()

   if image then
      layout:add(image_widget(local_image(image)))
   end

   local text = wibox.widget.textbox()   

   gears.timer.start_new(timeout, 
                         function () 
                            awful.spawn.easy_async(command, 
                                                   function (stdout, stderr, reason, exit_code) 

                                                      text.markup = stdout

                                                   end)

                            return true
                         end)

   layout:add(text)

   return layout
end
```

this causes awesome wm to consume a lot of CPU (~50% of 8 cores) after several (10-15) hours of work.

Restarting awesome helps to reduce CPU consumption back, but it will grow again eventually.

I tried to set markup from output of "math.random" (i.e. just replace "stdout" to "math.random") as in previous comments, and problem not reproduced.

Output of commands include the the spans (<span ...> tag) for setting colors in text.

I have 7 such widgets, 5 of them updated every second, 2 every 5 seconds.

**Comment by Plasticoo** [comment] 2017-08-02 21:40
I do have the same issue. AwesomeWM should stay at 24MB, but goes beyond 100MB. 
Removed all widgets but it still happens. Added a timeout for the garbage collection function, but it still goes up to 70MB.

**Comment by psychon** [comment] 2017-08-03 08:19
@Plasticoo I cannot reproduce.

I took 58bb3dde4a78cebf941ba3e6d344e43ed4789d3e, applied the following patch and let `tests/run.sh /dev/null` run a bit:
```diff
diff --git a/awesomerc.lua b/awesomerc.lua
index 00d1b60..c750ed0 100644
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -582,3 +587,18 @@ end)
 client.connect_signal("focus", function(c) c.border_color = beautiful.border_focus end)
 client.connect_signal("unfocus", function(c) c.border_color = beautiful.border_normal end)
 -- }}}
+local i = 0
+gears.timer.start_new(60, function()
+       print(collectgarbage("count"))
+       i = i + 1
+       if i >= 10 then
+               i = 0
+               collectgarbage("collect")
+               print("after collect", collectgarbage("count"))
+       end
+       return true
+end)
+gears.timer.start_new(5, function()
+       print("after startup", collectgarbage("count"))
+       return false
+end)
diff --git a/tests/run.sh b/tests/run.sh
index 138c129..f7c94c6 100755
--- a/tests/run.sh
+++ b/tests/run.sh
@@ -181,7 +181,7 @@ start_awesome() {
     cd "$build_dir"
     # Kill awesome after $timeout_stale seconds (e.g. for errors during test setup).
     # SOURCE_DIRECTORY is used by .luacov.
-    DISPLAY="$D" SOURCE_DIRECTORY="$source_dir" timeout "$timeout_stale" "$AWESOME" -c "$RC_FILE" "${awesome_options[@]}" > "$awesome_log" 2>&1 &
+    DISPLAY="$D" SOURCE_DIRECTORY="$source_dir"  "$AWESOME" -c "$RC_FILE" "${awesome_options[@]}" > "$awesome_log" 2>&1 &
     awesome_pid=$!
     cd - >/dev/null
 
```
Relevant part of output is:
```
== Running /dev/null ==
at beginning of rc.lua	105.3603515625
after startup	4758.34375
4778.3251953125
4797.8193359375
4817.3134765625
4836.8076171875
4872.3017578125
4891.7958984375
4911.2900390625
4930.7841796875
4950.2783203125
4969.7724609375
after collect	3604.021484375
3676.732421875
3696.2802734375
3715.7744140625
3735.2685546875
3754.7626953125
3774.2568359375
3793.7509765625
3813.2451171875
3832.7392578125
3852.2333984375
after collect	3550.0390625
3622.818359375
3642.3662109375
3661.8603515625
3681.3544921875
3700.8486328125
3720.3427734375
3739.8369140625
3759.3310546875
3778.8251953125
3798.3193359375
after collect	3550.0390625
3622.818359375
3642.3662109375
```
At the same time I used `ps` at random intervals to grab a snapshot of the resident size (RSS). I only saw the values 24704 and 24968, and the later number "stayed around" for most of the time.

So: I cannot reproduce what you report.

------

I'm closing this issue since the original report was unreproducable and didn't have any activity (real) for a while. Plus, the "me too"s aren't helping, sorry. This just mixed possibly different issues and reproducers.

Instead, please open new issues, provide version numbers and step by step instruction (e.g. "apply this patch to the default config, start awesome and just wait for 10 minutes. Memory usage will have gone from 24MiB to 24GiB.".

**Closed by psychon** 2017-08-03 08:19 UTC
Labels: need info

**Comment by SammysHP** [comment] 2017-08-03 09:19
Sorry for the lack of response, but I had nothing to contribute. Yes, the issue is still present in

```
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

But I had no severe issues in real-life usage. My testcase from above

```lua
testwidget = wibox.widget.textbox()
gears.timer.start_new(0.1, function() testwidget.text = math.random(100,999); return true end)
```

still results in increasing memory usage, but it stabilizes usually at some point. So it might just be the GC that just does not keep up with with the garbage.

I'm fine with closing this issue.

**Comment by 7ocb** [comment] 2017-11-23 15:03
To workaround this issue (thanks guys from irc channel for direction of searching of workaround) instead of using gears.timer for constantly refreshing text views I use following script:

```bash
#!/bin/bash

# this is script to run other command, get it's output, compare output to
# previous output, and echo new output only if it differs.

# params:

SECOND_DELAY=$1

shift

RESULT=""

while true ; do 
    NEW_RESULT=$("$@")

    if ! [ "$NEW_RESULT" == "$RESULT" ] ; then
        echo "$NEW_RESULT"
        RESULT="$NEW_RESULT"
    fi

    sleep $SECOND_DELAY
done
```
All it does is calling command with specified interval and emits command's output as next line in case if output differs from previous output.

and this is code of simple text widget, it changes timer call with calling of this script with timeout and command:

```lua
function info_text_widget(timeout, command)
   local layout = wibox.layout.fixed.horizontal()

   local text = wibox.widget.textbox()   

   local resulting_command = "bash -c '~/.config/awesome/scripts/timer_runner.sh " .. timeout .. " " .. command .. "'"

   awful.spawn.with_line_callback(resulting_command, {
                                     stdout = function(line) 
                                                 text.markup = line
                                              end,
                                     stderr = function(line)
                                                 text.markup = line
                                              end
                                  })

   layout:add(text)

   return layout
end
```

and use it like this:

```lua      
layout:add(info_text_widget(1, "MY_SCRIPTS_DIR/panel-time"))
```

this does not seem to cause growing of memory usage and cpu consumption.
