### ISSUE TITLE
Maximized windows should not get resized

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#1676] opened 2017-03-26 14:00 UTC
A maximized urxvt window should not get resized when using the following command to send escape codes to resize it: `printf '\e[8;50;100t'`.

This also affects fullscreen windows.

I think the size should still be honored/remembered, but should only have an effect when the window is floating again.

With a single tiled client this will still shortly resize the window, but then it's put back into tiling mode again.  In this case there should be no flickering at all, i.e. the resizing should be ignored there, too.

awesome v4.1-6-g7818fd3d-dirty (Technologic)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.4)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

**Comment by Elv13** [comment] 2017-03-26 19:18
Have you tried https://github.com/awesomeWM/awesome/pull/1606 (+ a modified handler)?

In any case, this is not a regression. Until #1606 is merged, there is no way to block these requests, they are always granted.

**Comment by Elv13** [comment] 2017-05-24 07:37
@blueyed The patches required to be able to fix this using the request API are now merged. In theory, improving the new `awful.ewmh.client_geometry_requests` function should help solve this. It wasn't in the maximize PR because it was already scary enough as it was.

**Closed** 2017-10-25 13:36 UTC
Labels: bug
