### ISSUE TITLE
The top and bottom titlebars always get size priority

### ISSUE THREAD

**Issue by Aproxia-dev** [awesomeWM/awesome#3951] opened 2024-09-07 21:16 UTC
Output of `awesome --version`:

```
awesome v4.3-1588-gb54e50ad6 (Too long)
 • Compiled against Lua 5.4.4 (running with 0.9.2)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: /usr/share/lua/5.4/lgi/version.lua
 • Transparency enabled: yes
 • Custom search paths: no

```

**How to reproduce the issue:**

Make a top and a bottom titlebar of one color, then make a left and a right titlebar of a different color.

```lua
awful.titlebar(c, {
  position = 'top',
  size = 10,
  bg = '#ff0000',
})

awful.titlebar(c, {
  position = 'bottom',
  size = 10,
  bg = '#ff0000',
})

awful.titlebar(c, {
  position = 'left',
  size = 10,
  bg = '#00ff00',
})

awful.titlebar(c, {
  position = 'right',
  size = 10,
  bg = '#00ff00',
})
```

**Actual result:**

The top and bottom titlebars take size priority, and the corners will have their color
![image](https://github.com/user-attachments/assets/a4db2493-7de2-4f86-ae85-d778ef8904c5)

**Expected result:**

The titlebar that's initialized last would take size priority, in this case the left and the right titlebar

![image](https://github.com/user-attachments/assets/287d94b3-c313-4fd1-925d-6af0dc6007a9)

**Additional notes:**

I ran into this issue trying to make vertical rounded titlebars and ended up with the following:

![image](https://github.com/user-attachments/assets/5a7f678f-3b21-4af4-8641-2d4f45fa10db)

I'm using titlebars to make borders on the top and the bottom, as the actual borders provided by beautiful don't have antialiasing if you round the client itself, which is really noticeable on my monitor.

As far as I can tell, the "top/bottom takes size priority" behaviour is hardcoded, and I guess it does make sense, I just ran into an unfortunate edge case in which this behaviour is limiting.
https://github.com/awesomeWM/awesome/blob/03285e8589b5fe2ed6a7dc74fd754db3685116d1/objects/client.c#L3458-L3498

**Comment by Elv13** [comment] 2024-09-08 10:58
Yes, this is currently a limitation. This issue is a duplicate of https://github.com/awesomeWM/awesome/issues/650 (there's also some demo code about how to fix it) and there is some extra insight in https://github.com/awesomeWM/awesome/issues/3951 .

The general idea is to deprecate `awful.titlebar` and make an `awful.decoration` module to replace it. That module would expose the client content as a normal `wibox.widget` and the API would otherwise be a normal wibox. However, nobody is working on that right now and I have very limited time these days. It would not be that hard to implement if somehow has the time. Most of the code is provided in one of psychon comment. All it needs is all the boilerplate to make it a module and all the documentation+example work.

**Comment by Elv13** [comment] 2024-09-08 10:58
Closing as a duplicate of #650

**Closed by Elv13** 2024-09-08 10:58 UTC
Labels: duplicate, user config help
