### ISSUE TITLE
Run prompt doesn't show

### ISSUE THREAD

**Issue by sproott** [awesomeWM/awesome#3351] opened 2021-05-25 17:50 UTC
Output of `awesome --version`:

```
awesome v4.3-1030-gb65025ef6 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: no
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

1. launch awesome
2. press the shortcut for opening the run prompt (Super+r)

**Actual result:**

The run prompt doesn't show even after typing something into it. Only doing an update such as clicking the corner icon that opens the menu makes the run prompt show.

**Expected result:**

The run prompt should be shown immediately.

**Comment by sclu1034** [comment] 2021-05-25 18:20
Sounds like it's related to/a duplicate of https://github.com/awesomeWM/awesome/pull/3238#issuecomment-841792244.

**Comment by sproott** [comment] 2021-05-25 19:44
Alright, that's most likely it. Probably should keep this issue open for tracking purposes though, right?

**Comment by sclu1034** [comment] 2021-05-26 07:11
Definitely.

**Comment by Aire-One** [comment] 2021-05-28 13:07
I can confirm. It doesn't occur when running awesome from Xephyr, I had to run the master branch of awesome-git with the default awesomerc as my graphical environment to reproduce.

(For some reason, it doesn't affect my personal config... Maybe my backgrounds/margins containers have something to do?)

**Closed** 2021-06-04 21:25 UTC
Labels: bug, confirmed

**Comment by Aire-One** [comment] 2021-06-04 21:28
@sproott, can you please confirm the proposed PR fixes this issue? I have no time to check by myself right now.

**Comment by sproott** [comment] 2021-06-05 22:13
Yes, it seems to be working properly again, thanks.

**Comment by Aire-One** [comment] 2021-06-06 17:09
Thank you, @sproott, for your confirmation. I finally had time to test, I can also confirm the issue has been fixed.

Let's keep this issue closed, then :)
