### ISSUE TITLE
Rendering error in awesomebar

### ISSUE THREAD

**Issue by ghost** [awesomeWM/awesome#1947] opened 2017-07-28 05:41 UTC
Output of `awesome --version`:

awesome v4.2 (Human after all)
 â¢ Compiled against Lua 5.3.4 (running with Lua 5.3)
 â¢ D-Bus support: â
 â¢ execinfo support: â
 â¢ xcb-randr version: 1.5
 â¢ LGI version: 0.9.1

**How to reproduce the issue:**

Run application messengerfordesktop.
Observe icon in systray.
![awesomebar-2017-07-27_22 25 35](https://user-images.githubusercontent.com/6833696/28703980-7e0895de-731c-11e7-9251-d7c3026ed1be.png)

**Actual result:**

Icon is now shifted to upper left corner, slightly truncated, and repeated on right.
(the white circle icon with 3 black dots in the attached image)

**Expected result:**

Up until the update to awesome that I made last week, the icon appeared proper and centered in the square area provided. Since this error appeared just after updating awesome I assume the error is related to that.

**Comment by psychon** [comment] 2017-07-28 06:59
Well, which awesome version did you have before the update?
Could you run `xwininfo -tree -frame` in a terminal and click on awesome's wibar? That should provide you with the actual size of the tray icon window. Note that awesome only places these windows, it does not draw them. If you wouldn't say that this used to work, I'd guess that messangerfordesktop has a hardcoded tray icon size and does not work with larger sizes...

**Comment by blueyed** [comment] 2017-08-11 07:10
@jtgd 
Can you provide an update regarding this issue, please?

**Comment by bobojet** [comment] 2017-09-13 04:56
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

Output from "xwininfo -tree -frame"                                                                                                                      

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x200010 "Awesome drawin"

  Root window id: 0x1d7 (the root window) "LG3D"
  Parent window id: 0x1d7 (the root window) "LG3D"
     1 child:
     0x200006 "Awesome systray window": ("awesome" "awesome")  58x29+2257+0  +2257+0
        2 children:
        0x600010 "chromium": ("chromium" "Chromium")  29x29+29+0  +2286+0
           1 child:
           0x600011 (has no name): ()  1x1+-1+-1  +2285+-1
        0x600003 "chromium": ("chromium" "Chromium")  29x29+0+0  +2257+0
           1 child:
           0x600004 (has no name): ()  1x1+-1+-1  +2256+-1


![image](https://user-images.githubusercontent.com/31912575/30360260-9d302ea0-9850-11e7-8aa3-502d33a9edc9.png)

**Comment by jtgd** [comment] 2017-09-22 05:29
I don't recall what version I had before, but with Arch I try to keep up to date fairly often, so perhaps it was the next previous one.

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x600010 "Awesome drawin"

  Root window id: 0x26e (the root window) (has no name)
  Parent window id: 0x26e (the root window) (has no name)
     1 child:
     0x600006 "Awesome systray window": ("awesome" "awesome")  42x21+1611+0  +1611+0
        2 children:
        0x340000b "electron": ("electron" "Electron")  21x21+21+0  +1632+0
           1 child:
           0x340000c (has no name): ()  1x1+-1+-1  +1631+-1
        0x1e0001d "clipit": ("clipit" "clipit")  21x21+0+0  +1611+0
           1 child:
           0x1e0001e (has no name): ()  1x1+-1+-1  +1610+-1

**Comment by psychon** [comment] 2017-09-22 16:20
Hm... weird.
Looking at your screenshots, the icon (including the repeated part) has the same size as is indicated by xwininfo. So for @bobojet this means that the "cut of point" of the second chromium icon is 29 pixels away from the left edge of the first chromium icon. In other words, the systray icon has the expected size, but "thinks" it is smaller than it actually is. No idea why.

> Up until the update to awesome that I made last week, the icon appeared proper and centered in the square area provided

So... the icon already was smaller than the wibar, but it just happened to be centered in the available space, right? So in other words, this problem is quite old, but only recently became noticable since the symptoms got worse.

**Comment by bobojet** [comment] 2017-09-22 16:41
I have had this problem for a few months now. If I reset met rc.lua, I still see the issue, but it is less severe.

xwininfo: Window id: 0x200016 "Awesome drawin"

  Root window id: 0x1d7 (the root window) "LG3D"
  Parent window id: 0x1d7 (the root window) "LG3D"
     1 child:
     0x200006 "Awesome systray window": ("awesome" "awesome")  52x26+2367+0  +2367+0
        2 children:
        0x600064 "chromium": ("chromium" "Chromium")  26x26+26+0  +2393+0
           1 child:
           0x600065 (has no name): ()  1x1+-1+-1  +2392+-1
        0x600060 "chromium": ("chromium" "Chromium")  26x26+0+0  +2367+0
           1 child:
           0x600061 (has no name): ()  1x1+-1+-1  +2366+-1

![image](https://user-images.githubusercontent.com/31912575/30755012-431e9aba-9fc5-11e7-9007-24673bf0c5df.png)

**Comment by psychon** [comment] 2017-09-22 16:55
@bobojet How do you get a tray icon for chrom(e/ium)?

**Comment by bobojet** [comment] 2017-09-22 16:58
@psychon The icon appears due to the "let chrom(e/ium) run in the background" setting.

**Comment by psychon** [comment] 2017-09-23 14:22
@bobojet I didn't find that setting in chromium's settings page, got some pointers for me?

**Comment by bobojet** [comment] 2017-09-23 17:32
@psychon In the settings, search for "background". You will see an option: "Continue running background apps...". That is the one I use and the one that gives me the icon.

**Comment by psychon** [comment] 2017-09-23 19:36
That setting is enabled here (and I'm quite sure I never touched it) and I have no tray icon to play with. Perhaps I actually need some background app, whatever that is?

**Comment by bobojet** [comment] 2017-09-24 07:41
I'm using hangouts.

**Comment by psychon** [comment] 2017-09-24 08:41
Okay, that gives me a tray icon, but no problems. Sorry.

I used the default config, added `height = 30` to the wibar and ran awesome+chromium in Xephyr. The resulting tray icon didn't have the problem that we are looking for.

**Comment by bobojet** [comment] 2017-09-24 08:47
Can you try adding "Xft.dpi:        150" to your .Xresources and reloading awesome to see if has any effect?

**Comment by psychon** [comment] 2017-09-24 09:02
That makes the available space to small for chromium, but doesn't trigger the problem.
![screen](https://user-images.githubusercontent.com/89482/30781005-c0c61eae-a117-11e7-9662-7db8f27e585a.png)

**Comment by bobojet** [comment] 2017-09-24 09:49
So how should we debug this? Just as @jtgd, I am running Arch.

**Comment by psychon** [comment] 2017-09-24 11:23
I don't know... Does `awesome-client 'screen[1].mywibox.height = 42'` have any nice effects? (I.e.: Forcing a resize of the tray icon). Do you have some small program that you could run under `x11trace` / `xtrace` and get me the logs (together with the output of `xwininfo` as mentioned above)?

**Comment by bobojet** [comment] 2017-09-24 11:46
That command dit not have any effects at all. I tried running a test application to see if I can reproduce the glitch, but it only seems to happen with Chromium.
I used this app, but this seems to work fine: https://github.com/elboulangero/gtk-status-icon-size-test

**Comment by YaLTeR** [comment] 2018-01-15 06:10
Not sure if related, but I had the Dropbox icon render like this for about as long as I used awesome:
![image](https://user-images.githubusercontent.com/1794388/34929285-f5044cda-f9d3-11e7-88e1-c5f3c92c8a37.png)

**Comment by Elv13** [comment] 2018-01-15 06:21
@YaLTeR https://github.com/awesomeWM/awesome/issues/1856

**Comment by p-himik** [comment] 2018-01-29 15:50
I have noticed a similar behavior when switching from one display to another with a lower resolution:
![image](https://user-images.githubusercontent.com/4410314/35519383-a272f0e2-0546-11e8-8ca8-9b172b36f099.png)
Notice the red rectangle to the left of the systray. It's the volume widget, and what I presume is its old rendered version is under some icons to the right. It's just as the background was not refreshed for some reason.

**Comment by grafa** [comment] 2018-05-13 12:50
Hey guys, I'm experiencing quite similar problem. I don't think I have to open up new issue so I'm writing here.

Some tray icons like Telegram or VLC (no icon in my icon pack for both) have left and bottom border. I guess it's more like visible background behind the icon that regular border.

Any ideas guys?

![image](https://user-images.githubusercontent.com/198654/39967526-0a8c63a8-56bd-11e8-8ef0-827e41f91712.png)

**Comment by psychon** [comment] 2018-05-15 05:49
@actionless Unrelated to this issue and no, the C code only hands out the number of systray icons and no other information. (Some day, every single systray icon could be handled similarly to clients, could be placed individually, and could be queried for things like `.name`; today is not that day)

**Comment by Elv13** [comment] 2018-12-22 04:39
Closing because GTK is apparently going to fix it https://gitlab.gnome.org/GNOME/gtk/issues/1280

**Closed by Elv13** 2018-12-22 04:39 UTC
Labels: need info
