### ISSUE TITLE
no icon in notify nm-applet

### ISSUE THREAD

**Issue by xhc1** [awesomeWM/awesome#2533] opened 2019-01-03 08:53 UTC
`awesome --version`:
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

when nm-applet starts missing icon in notify popup, but text shows connecting / disconnecting

**Comment by psychon** [comment] 2019-01-03 09:03
You are talking about notifications through naughty (the small little popups that appear), right? You are not talking about a system tray icon?
Could you run `dbus-monitor` in a terminal, cause such an icon to appear and provide the output of `dbus-monitor`?
Also, what kind of system are you on? (Debian testing, Arch, FreeBSD, ...)

**Comment by xhc1** [comment] 2019-01-03 09:10
using fedora 28 and it steps to reproduce:

1. start nm-applet (no problems in systray)
2. enable notification in nm-applet, make some connection
3. notification about connection will appeard, but only text, icon of nm-applet is missing in notification

I tried dbus-monitor, here is output:

`signal time=1546506323.252121 sender=org.freedesktop.DBus -> destination=:1.53 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.53"
signal time=1546506323.252161 sender=org.freedesktop.DBus -> destination=:1.53 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.53"
method call time=1546506344.533908 sender=:1.20 -> destination=:1.16 serial=17 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "NetworkManager"
   uint32 0
   string "nm-no-connection"
   string "Disconnected"
   string "The network connection has been disconnected."
   array [
      string "disable-disconnected-notifications"
      string "Don’t show this message again"
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 0
      )
      dict entry(
         string "desktop-entry"
         variant             string "nm-applet"
      )
      dict entry(
         string "transient"
         variant             boolean true
      )
   ]
   int32 -1
method return time=1546506344.542417 sender=:1.16 -> destination=:1.20 serial=11 reply_serial=17
   uint32 4
method call time=1546506346.249177 sender=:1.1 -> destination=org.freedesktop.DBus serial=15 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=ReleaseName
   string "org.freedesktop.ReserveDevice1.Audio0"
signal time=1546506346.249634 sender=org.freedesktop.DBus -> destination=:1.1 serial=35 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string "org.freedesktop.ReserveDevice1.Audio0"
signal time=1546506346.249652 sender=org.freedesktop.DBus -> destination=(null destination) serial=36 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.ReserveDevice1.Audio0"
   string ":1.1"
   string ""
method return time=1546506346.249673 sender=org.freedesktop.DBus -> destination=:1.1 serial=37 reply_serial=15
   uint32 1
method call time=1546506346.425157 sender=:1.20 -> destination=:1.16 serial=18 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=CloseNotification
   uint32 4
signal time=1546506346.430192 sender=:1.16 -> destination=(null destination) serial=12 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 4
   uint32 3
method return time=1546506346.430223 sender=:1.16 -> destination=:1.20 serial=13 reply_serial=18
method call time=1546506346.430228 sender=:1.20 -> destination=:1.16 serial=19 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "NetworkManager"
   uint32 0
   string "nm-device-wired"
   string "Connection Established"
   string "You are now connected to “enp4s0f2”."
   array [
      string "disable-connected-notifications"
      string "Don’t show this message again"
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 0
      )
      dict entry(
         string "desktop-entry"
         variant             string "nm-applet"
      )
      dict entry(
         string "transient"
         variant             boolean true
      )
   ]
   int32 -1
method return time=1546506346.438432 sender=:1.16 -> destination=:1.20 serial=14 reply_serial=19
   uint32 5
signal time=1546506351.428818 sender=:1.16 -> destination=(null destination) serial=15 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=NotificationClosed
   uint32 5
   uint32 1
method call time=1546506384.157583 sender=:1.1 -> destination=org.freedesktop.DBus serial=16 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RequestName
   string "org.freedesktop.ReserveDevice1.Audio0"
   uint32 5
signal time=1546506384.157627 sender=org.freedesktop.DBus -> destination=(null destination) serial=38 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.ReserveDevice1.Audio0"
   string ""
   string ":1.1"
signal time=1546506384.157649 sender=org.freedesktop.DBus -> destination=:1.1 serial=39 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string "org.freedesktop.ReserveDevice1.Audio0"
method return time=1546506384.157663 sender=org.freedesktop.DBus -> destination=:1.1 serial=40 reply_serial=16
   uint32 1
signal time=1546506398.826849 sender=:1.24 -> destination=(null destination) serial=98 path=/com/canonical/menu/160003E; interface=com.canonical.dbusmenu; member=LayoutUpdated
   uint32 74
   int32 0
signal time=1546506398.827029 sender=:1.24 -> destination=(null destination) serial=99 path=/com/canonical/menu/1600042; interface=com.canonical.dbusmenu; member=LayoutUpdated
   uint32 32
   int32 0
`

**Comment by psychon** [comment] 2019-01-03 09:30
The first notification just uses `nm-no-connection` for the icon and the second one uses `nm-device-wired`.
These files are provided by the package `nm-connection-editor`: `/usr/share/icons/hicolor/*/apps/nm-no-connection*` (I have four such file on my Fedora 28 box).
These files are provided by the package `gnome-icon-theme-legacy`: `/usr/share/icons/gnome/*/status/nm-no-connection.png`.

Actually... naughty should (almost) find the icons there. It uses `awful.util.geticonpath` and this function would guess the right path *if* `/usr/share/icons/hicolor` where added to `naughty.config.icon_dirs` and the `icon_size` were configured correctly... Yeah, almost.

Anyway, I will have to close this as a duplicate of #908.

**Closed by psychon** 2019-01-03 09:30 UTC

**Comment by Elv13** [comment] 2019-01-04 22:43
I added `hicolor` to the notification refactoring branch. I will add some regression tests later.
