### ISSUE TITLE
CMake configure_file should be disabled for the CodeCov build 

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#962] opened 2016-06-11 20:33 UTC
This way, the line number will be correct again. Until that, the coverage report is just gamification, it's technically useless when there is expanded documentation. And yes, I just took a look, CodeCov is Awesome!

Also, it seems, at least from the look of the front page, that the test code is included in the coverage report.

I may do that eventually, but I wont have much time for Awesome in the coming months.

**Comment by psychon** [comment] 2016-06-12 08:26
The line numbers were already off for coveralls and apparently it wasn't a problem there...? This part of the problem isn't new, but I agree that fixing it would be nice.

For the test code: Yup, it's included and I don't understand why it is not included in coveralls. This can be fixed with a suitable exclude rule. I'll handle that.

**Closed** 2017-01-08 21:13 UTC
