### ISSUE TITLE
Weird fonts on starting awesome window manager

### ISSUE THREAD

**Issue by premraj59** [awesomeWM/awesome#3133] opened 2020-07-21 09:23 UTC
Output of `awesome --version`:

awesome v4.3 (Too long)
Compiled against Lua 5.3.5 (running with Lua 5.3)

Can anyone explain why awesome window manager has these weird boxes instead of fonts?

![15953231946406689980493134454733](https://user-images.githubusercontent.com/53263555/88036648-7bf2d700-cb61-11ea-80f2-2b8fb637ef38.jpg)

I am on Arch linux. Started awesome using xorg xinit from tty1

**Comment by psychon** [comment] 2020-07-22 12:59
> Can anyone explain why awesome window manager has these weird boxes instead of fonts?

Missing fonts? (And no, I do not know what some font packages in arch are called nor do I know why your xterm manages to find fonts)
Does running `pango-view --text test` in a terminal also result in boxes? If so, pango fails at findings a font.

Those boxes contain characters in hex. E.g. the xterm starts with `0072` `006F` `006F` `0074`. According to `man ascii`, this is `root`. So... yeah (no idea where Pango gets the font for showing these numbers from, perhaps it is built in?).

**Comment by hyde-stevenson** [comment] 2020-07-28 12:34
Hmm I have the same thing today after I restarted X ... I dont remember removing fonts on my side :man_shrugging:

**Comment by psychon** [comment] 2020-07-28 14:10
@hyde-stevenson Does `pango-view` as suggested above also not work for you?

**Comment by hyde-stevenson** [comment] 2020-07-28 14:20
it works on my side ... weird I cant upload a screenshot to show you how it looks like 

I uploaded somewhere else :

[awesomewn](https://lazybear.io/img/awesome.png)

**Comment by premraj59** [comment] 2020-07-29 15:40
I installed the cinammon desktop environment and then exited and logged in and awesome was fine. Doing pango-view after that and everything was ok. I did not run pango-view before that.

**Comment by hyde-stevenson** [comment] 2020-08-04 23:59
I upgraded xfonts-terminus and everything came back in order :)

**Comment by psychon** [comment] 2020-08-05 14:26
Sounds like this now works for everyone, so closing.

**Closed by psychon** 2020-08-05 14:26 UTC
Labels: invalid, need info, submitter gone

**Comment by hyde-stevenson** [comment] 2020-08-07 18:01
good for me :)

**Comment by ayush-india** [comment] 2022-02-18 07:06
> xfonts-terminus

help i am having the same issuse and i am on ubunut so how can i fix it pls help because i am beginner 

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

and ask if any thing is needed

**Comment by Aire-One** [comment] 2022-02-18 09:04
Hello,

Reading this thread sounds like the issue is not awesome, but a not-properly installed font.

> Does running `pango-view --text test` in a terminal also result in boxes? If so, pango fails at findings a font.

@ayush-india, can you try it?
