### ISSUE TITLE
Terminal Editor Sakura locks up on certain actions with Awesome 4.0

### ISSUE THREAD

**Issue by module0x90** [awesomeWM/awesome#1435] opened 2017-01-23 11:53 UTC
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

1) Start Sakura, terminal emulator, 3.3.4 or even latest 3.4.0.
2) Make sure it's not in fullscreen (F11), or it won't happen
3) ANY of the following actions will lock the terminal window, there might be some more:
         * Ctrl-Shift-T    for opening a new tab
         * Ctrl + '+'
         * Ctrl + '-'
         * Right-Click, then choose "New Tab"

**Actual result:**

Locks the terminal Window.

**Expected result:**

Shouldn't lock the terminal window. Downgraded temporarily to Awesome 3.5.9-1, but left Sakura (and Awesome Config) untouched. With that version the above works. 4.0-1 breaks this.
I also submitted a bug report to Sakura, but realized it doesn't seem to be a problem with them.
https://bugs.launchpad.net/sakura/+bug/1658657

**Comment by psychon** [comment] 2017-01-25 09:47
Could this be a duplicate of https://github.com/awesomeWM/awesome/issues/1340 ? Can you test if this still happens with current git/master, i.e. does https://github.com/awesomeWM/awesome/commit/5dc88da3bda3f8626d1f43b5cd1db10950c5cb76 fix it?

**Comment by module0x90** [comment] 2017-01-25 11:45
Hi,

I compiled on Arch Linux against current master, e2edabb8, and this version fixes my problem.

Many thanks.
Thomas

--
www​.​preissler​.​co​.​uk | Twitter: @module0x90
GPG: BA359D78200264B363314AF5E3839138A11FFD2A

January 25 2017 9:47 AM, "Uli Schlachter"  wrote:
	Could this be a duplicate of #1340 (https://github.com/awesomeWM/awesome/issues/1340) ? Can you test if this still happens with current git/master, i.e. does 5dc88da (https://github.com/awesomeWM/awesome/commit/5dc88da3bda3f8626d1f43b5cd1db10950c5cb76) fix it?

**Closed** 2017-01-25 12:00 UTC
