### ISSUE TITLE
For some applications, "input passthrough" does not work.

### ISSUE THREAD

**Issue by meetcw** [awesomeWM/awesome#3431] opened 2021-09-09 11:43 UTC
Some applications support "input passthrough". 

When I close Picom, it works fine.

However, if I open Picom,  "input passthrough" will not work.

I don't know if that is an awesomewm bug or not, but Picom with Openbox works as expected.

Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

- Install [Peek](https://github.com/phw/peek) and Picom
- Open Picom and Peek
- Move the Peek window above any window
- Click the record area of the Peek window, and the Peek window still get input

**Actual result:**

The Peek window still get input.

**Expected result:**

Forward the inputs to the window below the Peek window.

**Comment by skela** [comment] 2021-11-22 12:16
Have the same issue with peek v1.5.1 and awesomevm v4.3

**Comment by Aire-One** [comment] 2021-11-22 18:13
Hello,

I just installed peek, and it seems to work as expected on my computer running awesome git version.

I'll try later with the stable version, to confirm it doesn't work there. But for now, it seems the issue is resolved in with the awesome git version.

**Closed** 2022-04-27 14:40 UTC
