### ISSUE TITLE
Layoutlist memory leak

### ISSUE THREAD

**Issue by aalhitennf** [awesomeWM/awesome#2846] opened 2019-08-06 17:00 UTC
Output of `awesome --version`:

awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2

**How to reproduce the issue:**

Add layoutlist popup to your config (straight from docs) :
`awful.popup {`
`    widget = awful.widget.layoutlist {`
`         screen      = 1,`
`         base_layout = wibox.layout.flex.vertical`
`    },`
`    maximum_height = #awful.layout.layouts * 24,`
`    minimum_height = #awful.layout.layouts * 24,`
`    placement      = awful.placement.centered,`
` }`

Then keep switching tags, rapidly if you want to see results.

**Actual result:**

Awesomes memory usage keeps going up. With default config ~2mb per switch, with more specified layoutlist i experienced 5-10mb per tag switch.

**Expected result:**

Memory should not be eaten like that.

**Comment by psychon** [comment] 2019-08-06 18:02
I appended this to the default config and ran AwesomeWM under `valgrind --tool=massif`:
```lua
awful.popup {
    widget = awful.widget.layoutlist {
        screen = 1,
        base_layout = wibox.layout.flex.vertical
    },
    maximum_height = #awful.layout.layouts * 24,
    minimum_height = #awful.layout.layouts * 24,
    placement = awful.placement.centered,
}
local counter = 0
gears.timer.start_new(0.01, function() counter = counter + 1 awful.tag.viewnext() return true end)
gears.timer.start_new(30, function()
    print("did this many switches:", counter)
    awesome.quit()
end)
```
Result is (after just 130 tag switches):
```
    MB
263.4^                                                                      : 
     |                                                                   @@#: 
     |                                                                @@@@@#::
     |                                                             @@@@@@@@#::
     |                                                           @@@@@@@@@@#::
     |                                                        @@@@@@@@@@@@@#::
     |                                                     @@@@@@@@@@@@@@@@#::
     |                                                  @@@@@@@@@@@@@@@@@@@#::
     |                                               @@@@@@@@@@@@@@@@@@@@@@#::
     |                                             @@@ @@@@@@@@@@@@@@@@@@@@#::
     |                                          @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |                                      @@@@@@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |                           @@@:     ::@@@ @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |                        @@:@@ :  :::::@@@ @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |                     ::@@@:@@ ::::::::@@@ @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |                  @@@: @@@:@@ ::::::::@@@ @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |                ::@ @: @@@:@@ ::::::::@@@ @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |          :  @@@::@ @: @@@:@@ ::::::::@@@ @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |       :@@:::@@ ::@ @: @@@:@@ ::::::::@@@ @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
     |::::::::@@:::@@ ::@ @: @@@:@@ ::::::::@@@ @@@@@@ @@@@@@@@@@@@@@@@@@@@#::
   0 +----------------------------------------------------------------------->Gi
     0                                                                   27.84
```
Peak snapshot (with `ms_print --threshold 10`) is:
```
85.99% (235,771,029B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->76.95% (210,977,296B) 0x56F3E50: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| ->38.78% (106,329,056B) 0x56F9908: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | ->28.67% (78,614,368B) 0x56F9DC5: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | ->17.00% (46,617,504B) 0x56EB1C4: lua_rawset (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | ->15.15% (41,546,304B) 0x57009E6: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | | ->15.15% (41,546,304B) 0x56EF584: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   ->15.15% (41,542,208B) 0x56FC354: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   | ->15.15% (41,542,208B) 0x56EF997: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   ->15.09% (41,380,352B) 0x56EF9C0: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | ->15.09% (41,377,792B) 0x56EED81: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | | ->15.09% (41,377,792B) 0x56EFC4A: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |   ->15.09% (41,377,792B) 0x56EB593: lua_pcallk (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     ->15.04% (41,232,384B) 0x1330C7: luaA_dofunction (lualib.h:76)
| | | | |   |   | |     | ->15.04% (41,232,384B) 0x1330C7: signal_object_emit (luaobject.c:253)
| | | | |   |   | |     |   ->15.03% (41,203,712B) 0x131BA1: luaA_class_emit_signal (luaclass.c:341)
| | | | |   |   | |     |   | ->15.03% (41,203,712B) 0x1334E3: luaA_object_emit_signal (luaobject.c:309)
| | | | |   |   | |     |   |   ->15.03% (41,203,712B) 0x146D19: tag_view (tag.c:290)
| | | | |   |   | |     |   |     ->15.03% (41,203,712B) 0x146D19: luaA_tag_set_selected (tag.c:496)
| | | | |   |   | |     |   |       ->15.03% (41,203,712B) 0x131F96: luaA_class_newindex (luaclass.c:487)
| | | | |   |   | |     |   |         ->15.03% (41,203,712B) 0x56EF584: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |           ->15.03% (41,203,712B) 0x56EF962: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |             ->15.03% (41,203,712B) 0x56FA186: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |               ->15.03% (41,203,712B) 0x56FCB83: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                 ->15.03% (41,203,712B) 0x56EF997: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                   ->15.03% (41,203,712B) 0x56EF9C0: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                     ->15.03% (41,203,712B) 0x56EED81: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                       ->15.03% (41,203,712B) 0x56EFC4A: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                         ->15.03% (41,203,712B) 0x56EB593: lua_pcallk (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                           ->15.03% (41,203,712B) 0x5700F7F: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                             ->15.03% (41,203,712B) 0x56EF584: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                               ->15.03% (41,203,712B) 0x56FC354: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                                 ->15.03% (41,203,712B) 0x56EF997: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   |   | |     |   |                                   
| | | | |   |   | |     |   ->00.01% (28,672B) in 1+ places, all below ms_print's threshold (10.00%)
| | | | |   |   | |     |   
| | | | |   |   | |     ->00.05% (145,408B) in 1+ places, all below ms_print's threshold (10.00%)
| | | | |   |   | |     
| | | | |   |   | ->00.00% (2,560B) in 1+ places, all below ms_print's threshold (10.00%)
| | | | |   |   | 
| | | | |   |   ->00.06% (161,856B) in 1+ places, all below ms_print's threshold (10.00%)
| | | | |   |   
| | | | |   ->00.00% (4,096B) in 1+ places, all below ms_print's threshold (10.00%)
| | | | |   
| | | | ->01.85% (5,071,200B) in 1+ places, all below ms_print's threshold (10.00%)
| | | | 
| | | ->11.67% (31,986,176B) 0x56FB414: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | ->10.34% (28,360,736B) 0x56FCB83: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | | ->10.34% (28,360,736B) 0x56EF997: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   ->10.29% (28,223,776B) 0x56EF9C0: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   | ->10.24% (28,089,088B) 0x56EED81: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   | | ->10.24% (28,089,088B) 0x56EFC4A: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   | |   ->10.24% (28,089,088B) 0x56EB593: lua_pcallk (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | |   | |     ->10.24% (28,089,088B) in 3+ places, all below ms_print's threshold (10.00%)
| | | | |   | |     
| | | | |   | ->00.05% (134,688B) in 1+ places, all below ms_print's threshold (10.00%)
| | | | |   | 
| | | | |   ->00.05% (136,960B) in 1+ places, all below ms_print's threshold (10.00%)
| | | | |   
| | | | ->01.32% (3,625,440B) in 2+ places, all below ms_print's threshold (10.00%)
| | | | 
| | | ->00.00% (10,688B) in 1+ places, all below ms_print's threshold (10.00%)
| | | 
| | ->10.00% (27,423,392B) 0x56FE24C: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | ->10.00% (27,423,392B) 0x56EF997: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | |   ->10.00% (27,423,392B) in 2+ places, all below ms_print's threshold (10.00%)
| | |   
| | ->00.11% (291,296B) in 1+ places, all below ms_print's threshold (10.00%)
| | 
| ->33.86% (92,844,128B) 0x56F231D: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | ->25.53% (69,992,216B) 0x56F9392: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | ->24.14% (66,196,704B) 0x56FCAE2: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | | ->24.14% (66,196,704B) 0x56EF997: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   ->23.83% (65,331,728B) 0x56EF9C0: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | ->23.80% (65,256,688B) 0x56EED81: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | | ->23.80% (65,256,688B) 0x56EFC4A: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |   ->23.80% (65,256,688B) 0x56EB593: lua_pcallk (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     ->17.61% (48,285,608B) 0x1330C7: luaA_dofunction (lualib.h:76)
| | | |   | |     | ->17.61% (48,285,608B) 0x1330C7: signal_object_emit (luaobject.c:253)
| | | |   | |     |   ->17.60% (48,253,688B) 0x131BA1: luaA_class_emit_signal (luaclass.c:341)
| | | |   | |     |   | ->17.60% (48,253,688B) 0x1334E3: luaA_object_emit_signal (luaobject.c:309)
| | | |   | |     |   |   ->17.60% (48,246,968B) 0x146D19: tag_view (tag.c:290)
| | | |   | |     |   |   | ->17.60% (48,246,968B) 0x146D19: luaA_tag_set_selected (tag.c:496)
| | | |   | |     |   |   |   ->17.60% (48,246,968B) 0x131F96: luaA_class_newindex (luaclass.c:487)
| | | |   | |     |   |   |     ->17.60% (48,246,968B) 0x56EF584: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |       ->17.60% (48,246,968B) 0x56EF962: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |         ->17.60% (48,246,968B) 0x56FA186: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |           ->17.60% (48,246,968B) 0x56FCB83: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |             ->17.60% (48,246,968B) 0x56EF997: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |               ->17.60% (48,246,968B) 0x56EF9C0: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                 ->17.60% (48,246,968B) 0x56EED81: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                   ->17.60% (48,246,968B) 0x56EFC4A: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                     ->17.60% (48,246,968B) 0x56EB593: lua_pcallk (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                       ->17.60% (48,246,968B) 0x5700F7F: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                       | ->17.60% (48,246,968B) 0x56EF584: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                       |   ->17.60% (48,246,968B) 0x56FC354: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                       |     ->17.60% (48,246,968B) 0x56EF997: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                       |       ->17.60% (48,246,968B) 0x56EF9C0: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                       |         ->17.60% (48,246,968B) 0x56EED81: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                       |           ->17.60% (48,246,968B) 0x56EFC4A: ??? (in /usr/lib/x86_64-linux-gnu/liblua5.3.so.0.0.0)
| | | |   | |     |   |   |                       |             
| | | |   | |     |   |   |                       ->00.00% (0B) in 1+ places, all below ms_print's threshold (10.00%)
| | | |   | |     |   |   |                       
| | | |   | |     |   |   ->00.00% (6,720B) in 1+ places, all below ms_print's threshold (10.00%)
| | | |   | |     |   |   
| | | |   | |     |   ->00.01% (31,920B) in 1+ places, all below ms_print's threshold (10.00%)
| | | |   | |     |   
| | | |   | |     ->06.19% (16,971,080B) in 2+ places, all below ms_print's threshold (10.00%)
| | | |   | |     
| | | |   | ->00.03% (75,040B) in 1+ places, all below ms_print's threshold (10.00%)
| | | |   | 
| | | |   ->00.32% (864,976B) in 1+ places, all below ms_print's threshold (10.00%)
| | | |   
| | | ->01.38% (3,795,512B) in 2+ places, all below ms_print's threshold (10.00%)
| | | 
| | ->08.33% (22,851,912B) in 4+ places, all below ms_print's threshold (10.00%)
| | 
| ->04.31% (11,804,112B) in 3+ places, all below ms_print's threshold (10.00%)
| 
->09.04% (24,793,733B) in 4+ places, all below ms_print's threshold (10.00%)
```
All that this tells us is "the memory is being eaten by Lua".

`collectgarbage("collect")` does not really help. According to `collectgarbage("count")`, there is about 4700 (KiB?) in use after startup, 214930 when the above code is done and 141070 after collecting garbage three times.

Also, the layoutlist is *seriously slow*. As written above, with the layoutlist this manages 131 tag switches in 30 seconds. Without the layoutlist, this gets 700 tag switches done.

@Elv13 Ideas? I'm bad at debugging this kind of general high memory usage things. I can debug "why is this object here not being collected", but dunno what to do about high memory usage.

**Comment by psychon** [comment] 2019-08-06 18:16
Found it. In the layoutlist, `self._private.data` grows without bounds. `reload_cache` re-creates all layout "objects" on each call and `awful.common.list_update` then creates widgets for them and saves them in `self._private.data`. After 128 tag switches, there are 3328 entries in `self._private.data`.

`awful.widget.taglist` uses a weak table instead and I guess the layoutlist should do the same. The following patch helps at least a bit (memory usage is halved, but still way too high):
```diff
diff --git a/lib/awful/widget/layoutlist.lua b/lib/awful/widget/layoutlist.lua
index 6cb3ff18e..8458cebb1 100644
--- a/lib/awful/widget/layoutlist.lua
+++ b/lib/awful/widget/layoutlist.lua
@@ -327,7 +327,7 @@ function layoutlist:set_widget_template(widget_template)
     self._private.widget_template = widget_template
 
     -- Remove the existing instances
-    self._private.data = {}
+    self._private.data = setmetatable({}, { __mode = 'k' })
 
     -- Prevent a race condition when the constructor loop to initialize the
     -- arguments.
@@ -403,7 +403,7 @@ local function new(_, args)
     ret._private.style   = args.style or {}
     ret._private.buttons = args.buttons
     ret._private.source  = args.source
-    ret._private.data = {}
+    ret._private.data = setmetatable({}, { __mode = 'k' })
 
     reload_cache(ret)
 
```
```
    MB
110.4^                                                                      # 
     |                                                          @          @# 
     |                                                        @@@        ::@# 
     |                                              @        :@ @       :::@# 
     |                                             @@       ::@ @       :::@#:
     |                                   @        :@@      :::@ @    @:::::@#:
     |                                 @@@      :::@@     @:::@ @   :@: :::@#:
     |                        @@      :@ @:    :: :@@::  :@:::@ @  ::@: :::@#:
     |                        @ :    ::@ @:  :::: :@@: :::@:::@ @  ::@: :::@#:
     |                      @@@ :  ::::@ @: :: :: :@@: :::@:::@ @::::@: :::@#:
     |                 :  ::@ @ : :: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     |               @@: :: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     |             @@@ : :: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     |             @ @ :::: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     |           @@@ @ :::: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     |        @::@ @ @ :::: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     |      ::@: @ @ @ :::: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     | ::   : @: @ @ @ :::: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     | : @::: @: @ @ @ :::: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
     | : @: : @: @ @ @ :::: @ @ :::: ::@ @:::: :: :@@: :::@:::@ @: ::@: :::@#:
   0 +----------------------------------------------------------------------->Gi
     0                                                                   26.98
```

**Comment by Elv13** [comment] 2019-08-06 18:30
can you make a PR? I am at work right now but I will just merge it

**Comment by psychon** [comment] 2019-08-06 18:51
Nope, not enough time either, sorry.
Also, the patch does not seem to help enough. Without the layoutlist, we have way less memory usage (again for the 30 seconds full of tag switches):
```
    MB
28.92^ #                                                                      
     | #                                                                      
     | #                                                                      
     | #                                                                      
     | #                                                                      
     | #                                                                      
     | #                    :      :      ::                          :      :
     | # :           :     ::      :      :      :     ::     ::     ::     ::
     | # :           :     ::     ::     ::     @:     :      ::    :::    :::
     | #::    :     ::    :::     ::    @::     @:    ::     :::   ::::    :::
     | #::    ::   :::    :::    :::    @::   ::@:   :::     :::   @:::   @:::
     | #::   :::  @:::   ::::    :::   :@::   : @:   :::   :::::  :@:::  :@:::
     | #::   ::: :@::::: ::::  :::::: ::@:: ::: @:  ::::  :: ::: ::@::: ::@:::
     | #::  :::: :@:::: ::::: :: :::::::@:: @ : @:  ::::  :: ::: ::@::::::@:::
     | #::  ::::::@:::: :::::::: :::::::@:: @ : @::::::: ::: ::::::@::::::@:::
     | #::::::::::@:::: :::::::: :::::::@:: @ : @:: :::: ::: ::::::@::::::@:::
     | #::: ::::::@:::: :::::::: :::::::@:: @ : @:: :::: ::: ::::::@::::::@:::
     | #::: ::::::@:::: :::::::: :::::::@:: @ : @:: :::: ::: ::::::@::::::@:::
     | #::: ::::::@:::: :::::::: :::::::@:: @ : @:: :::: ::: ::::::@::::::@:::
     | #::: ::::::@:::: :::::::: :::::::@:: @ : @:: :::: ::: ::::::@::::::@:::
   0 +----------------------------------------------------------------------->Gi
     0                                                                   29.88

```

**Comment by Elv13** [comment] 2019-08-07 07:25
> Without the layoutlist, we have way less memory usage 

This is to be expected, but not by that much. There is 64x64x4x33 bytes worth of surfaces caching, with tons of overhead. Then there is all some extra overhead created by all the background containers. Then there's quite a lot of "temporary" lambdas.

The problem is buried a bit deep. Actually it doesn't exist.

First, the baseline case with your patch is identical:

![Screenshot_20190807_031006](https://user-images.githubusercontent.com/340384/62601978-9be1aa00-b8c0-11e9-81d3-bfc0872d8f6b.png)

Here's what happen with some `garbagecollect()` at the end of `reload_cache`:

![Screenshot_20190807_030747](https://user-images.githubusercontent.com/340384/62601907-718fec80-b8c0-11e9-9d13-1d399e364e6b.png)

*(Note that the curve "levelling" is because garbagecollect gets slower as time goes on.)*

Now, but "really" helping the GC and using the `kv` table mode, it gets back to normal:

![Screenshot_20190807_031101](https://user-images.githubusercontent.com/340384/62602033-bca9ff80-b8c0-11e9-8a93-552601388ee9.png)

*This is safe since the widgets are kept in the hierarchy and the cached object in a strong table. Why are the widgets leaking, I don't know yet. I tried emptying the `cache` table before discarding it, but it didn't help. Something else keeps a weak reference on the widget and Lua GC is too dumb to GC something that is help weakly by key somewhere and value somewhere else?*

Both combined do:

![Screenshot_20190807_031330](https://user-images.githubusercontent.com/340384/62602180-21fdf080-b8c1-11e9-8364-0b4f2024cd07.png)

So in the last graph there is only a little leak. Replacing the popup with a wibox didn't help. More aggressive GC reduce the leaks, but that might be because it runs less iterations.

On a less relevant note, @psychon, you should *really* try heaptrack, it is sooooo much better than massif. It actually produce a meaningful backtrace of temporary allocations instead of massif garbage.

**Comment by Elv13** [comment] 2019-08-07 08:27
After little tweaks:

![Screenshot_20190807_042828](https://user-images.githubusercontent.com/340384/62607125-8f168380-b8cb-11e9-93e8-37372d348716.png)

*Technically it could be possible to create a testcase to still reproduce the problem by creating new layouts for each run. However nobody does that, ever.*

**Comment by Elv13** [comment] 2019-08-10 20:18
This should be fixed in git-master, and the layoutlist will also be several order of magnitude faster now that the widget caching actually acts as a cache.

**Closed by Elv13** 2019-08-10 20:18 UTC
