### ISSUE TITLE
Ugly artifact showing up on Telegram icon in top menu

### ISSUE THREAD

**Issue by hholst80** [awesomeWM/awesome#2190] opened 2018-02-12 11:08 UTC
Output of `awesome --version`:

```
$ awesome --version
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Start the QT Telegram client.

**Actual result:**

![image](https://user-images.githubusercontent.com/6200749/36094075-25d1c3cc-0fed-11e8-86df-f29d7d94a7c6.png)

**Expected result:**

I would think the white ugly artifact on the Telegram icon not to show up.

**Comment by psychon** [comment] 2018-02-12 12:58
Closing this as a duplicate of #1720, #1738, #1856 (the description for the last one sounds the most related and this also links to some more duplicates: #283 #176).

The short version is: Qt improved their rendering model in Qt5 and now they cannot draw systray icons correctly anymore. They expect the systray to implement some new specification that awesome does not implement. Without the specification, they basically try to to take a screenshot and use that as the background for the tray icon. The result is... random.

Oh and: Also related: #1947

**Closed by psychon** 2018-02-12 12:58 UTC
