### ISSUE TITLE
Improve handling of moving foo.lua to module (foo/init.lua)

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#244] opened 2015-05-26 16:48 UTC
With `beautiful` being moved to a module (`beautiful.lua` =>  `beautiful/init.lua` etc) (#229), `make install` will not remove the now obsolete `beautiful.lua`, which results in this file being preferred.

Since there is no `make uninstall` target, this has to be handled manually.

Is there a better way?

Can we make `make install` to remove the obsolete file, or add a `make uninstall` command?
The latter would have to be run before a new `make install` would update the list of installed files though probably.

Changing Lua's `package.path` would also work, but this appears to be contrary to Lua conventions:

```
diff --git i/luaa.c w/luaa.c
index 2c16152..3842108 100644
--- i/luaa.c
+++ w/luaa.c
@@ -462,8 +462,8 @@ luaA_init(xdgHandle* xdg)
     }

     /* add Lua lib path (/usr/share/awesome/lib by default) */
-    lua_pushliteral(L, ";" AWESOME_LUA_LIB_PATH "/?.lua");
     lua_pushliteral(L, ";" AWESOME_LUA_LIB_PATH "/?/init.lua");
+    lua_pushliteral(L, ";" AWESOME_LUA_LIB_PATH "/?.lua");
     lua_concat(L, 3); /* concatenate with package.path */
     lua_setfield(L, 1, "path"); /* package.path = "concatenated string" */
```

This happened with the dbus split already, and now with https://github.com/awesomeWM/awesome/pull/229.

**Comment by psychon** [comment] 2015-05-26 19:36
Urgh. I like people who use package managers. :-(
http://www.cmake.org/Wiki/CMake_FAQ#Can_I_do_.22make_uninstall.22_with_CMake.3F

**Comment by psychon** [comment] 2015-07-04 13:19
Could we print a warning during `make install`?

**Comment by blueyed** [comment] 2015-07-04 18:15
Possibly.

I've used the following in a custom script myself , before `make install`:

    # Handle migrations of Lua files to modules.
    sudo rm -r /usr/local/share/awesome/lib/beautiful* .build-*/lib/beautiful* || true

**Comment by Elv13** [comment] 2016-09-11 05:29
Can we close this? It isn't really a bug. It is the same for any project. If a C project remove a public `.h`, then the same thing happen. `make uninstall` exist for a reason.

**Comment by psychon** [comment] 2016-09-11 07:53
We do not have a `make uninstall`, do we?
But I'd say "package managers exist for a reason". I'd conclude that we cannot do anything about this and close this, yeah.

**Comment by Elv13** [comment] 2016-12-08 02:49
Re-opening, Legacy230 on IRC had upgrade issues because of this and he wont be the last. The problem is, Awesome _almost_ work with `beautiful.lua` and `naughty.lua`, so it might give the impression that Awesome 4.0 is buggy because of those leftovers modules from 3.5.9. I didn't test, but can't we manually curate the `LUA_PATH` and associated variables to always favor `foo/init.lua` instead of `foo.lua`?

**Comment by psychon** [comment] 2016-12-08 08:33
```diff
diff --git a/luaa.c b/luaa.c
index e5cd055..7e91865 100644
--- a/luaa.c
+++ b/luaa.c
@@ -746,12 +746,12 @@ luaA_init(xdgHandle* xdg, string_array_t *searchpath)
         size_t len = a_strlen(*entry);
         lua_pushliteral(L, ";");
         lua_pushlstring(L, *entry, len);
-        lua_pushliteral(L, "/?.lua");
+        lua_pushliteral(L, "/?/init.lua");
         lua_concat(L, 3);
 
         lua_pushliteral(L, ";");
         lua_pushlstring(L, *entry, len);
-        lua_pushliteral(L, "/?/init.lua");
+        lua_pushliteral(L, "/?.lua");
         lua_concat(L, 3);
 
         lua_concat(L, 3); /* concatenate with package.path */
```
Yes, we can (said Obama). However, doesn't this just mean the same issue will appear when we ever move something in the other direction (`foo/init.lua` replaced with `foo.lua`)?

If you really want to fix this, I guess we need a `foo.lua` containing `return require("foo.init")` (and a comment explaining why this is done). That should also work if we ever do a move towards `foo.lua`.

Do we want to do this for `beautiful` and `naughty`?
(Run-time cost: None; Start-up cost: I'd say negligible)

**Closed** 2016-12-08 22:53 UTC
Labels: enhancement
