### ISSUE TITLE
Root window seems to be currupted with compositing enabled. Some regions are transparent in window area.

### ISSUE THREAD

**Issue by zabrielza** [awesomeWM/awesome#493] opened 2015-10-01 19:02 UTC
Hello,
 I have compositing problems with compton. The windows are in regions transparent, showing the wallpaper and windows below that window. I have started this thread: https://bbs.archlinux.org/viewtopic.php?id=203005, but no luck getting it fixed. 

These are two screenshots in order to describe better the problem. I have this only on awesome wm, not in fluxbox or openbox or xmonad. 

http://s21.postimg.org/dzmn3eql3/screenshot15.jpg
http://s13.postimg.org/mt7zmjsdz/screenshot27.jpg

I'm stuck, i have searched everywhere, anyone seems to have this problem.

Here is my rc.lua file if it matters, https://pastee.org/p4tzx . Also, i run comton with compton -bCG --active-opacity=1 .

**Comment by Elv13** [comment] 2015-10-01 21:50
Awesome version (if 3.5.6, can you reproduce the bug with master, it's in AUR)
And can you try

```sh
    feg --bg-scale /path/to/a.png
```

Where you replace `/path/to/a.png` with a real image path

**Comment by zabrielza** [comment] 2015-10-02 06:48
I am using awesome 3.5.6-2 and compton-git 0.1_beta2.68.gb1889c1-1. I have already tried 
feh --bg-scale /path/to/a.png, same results.

**Comment by psychon** [comment] 2015-10-02 07:10
Sorry, but in X11, a window manager only places windows and isn't involved in drawing them. You could try running awesome with `--no-argb` and see if that helps (but this will break real transparency for windows that support it). Besides that, I would suggest to report this to compton (https://github.com/chjj/compton) (and add a link here pointing to the issue there).

**Comment by zabrielza** [comment] 2015-10-02 08:25
I have already reported this in compton. https://github.com/chjj/compton/issues/310. I will try running with --no-argb . So you say it is not related to awesome wm right? It is weird because in any other window manager i had not this problem.

**Comment by psychon** [comment] 2015-10-02 12:02
Code: https://guides.github.com/features/mastering-markdown/ (the short version is: Use ` around words, or three of them on their own line for blocks of code.)

I guess the bug is in your video driver, but I do not know exactly.

First: Instead of transparency, you will now likely get "transparency over a black background". 
As I said, a WM does not draw windows, it only places them. For drawing things like a titlebar, the WM creates its own window and makes the "real window" a child window of this. The black that you see is the black background of this frame window. By default, awesome creates the window in a way that tells the X11 server "I might use transparency" and in this case the black background gets ignored by the X.org server (I don't actually know why and no, we do not "actively" draw this black background, I don't know why the black is black).

Second: There were bugs like this before, also without any composite manager at all. In this case, when the "I might use transparency"-hint is turned off, the issues disappeared (and of course transparency did not work any more). Because only the X11-server is involved in the drawing here, the issue must be in the server. Because this issue does not occur for everyone, I guess the problem is in the video driver (but I'm not sure). This is why the `--no-argb` switch was created that just turns off this "transparency support stuff". The effect of this switch to awesome is minimal. It only modifies two arguments in the call for creating a window (bit depth 24 vs 32 and a suitable visual for that bit depth).

Finally: awesome is lazy and always uses this "I might use transparency hint", even if the real client window does not have this hint. I once checked fluxbox' source code (for figuring out how this transparency stuff can be made to work) and they only use this hint on their frame window if the "contained window" has it, too. I guess eventually I should stop being lazy and un-lazy awesome so that it does the same? (Also: 99% of windows don't use transparency).
Hm... On the other hand, this would mean that real transparency will not work in titlebars any more and the lua code might start using this at any time...

**Comment by zabrielza** [comment] 2015-10-02 22:23
Thank you for this fine description of why things occur. So, why do I have this problem only with awesome wm? As I said not in xmonad or fluxbox,openbox.Where should I address this issue? I am using amd catalyst driver by Vi0L0 for HD 4890 graphics card. ( I apologize for the late response!)

**Comment by psychon** [comment] 2015-10-03 09:54
Well, as I said in the "finally"-part:

Awesome always creates its frame windows with 32 bpp (the "I might use transparency"-hint) while fluxbox will normally use 24 bpp (no transparency), except for client windows which themselves have 32 bpp.
In a nutshell: The thing that awesome does is also done by fluxbox, but only for windows which contain transparency. Thus, fluxbox always does what awesome does with `--no-argb` (except for some special windows which actually use transparency).

So the bug doesn't happen with fluxbox, because fluxbox "hides the bug" while awesome on the other hand supports real transparency in the titlebar.

And I think the bug is in the X11 server or the video driver (amd catalyst).

**Comment by zabrielza** [comment] 2015-10-03 10:10
So, fluxbox use 24 bpp, until someone makes it use 32bpp right? I mean, in fluxbox when i configured it, I had transparency enabled in all windows without a problem. Was it in 24 bpp or 32bpp? As for the real transparency in the titlebar, in my situation, the problem isn't only in the titlebar, but in the whole window. That's the way i understand what you are saying but I apologize if I cannot understand. And just to be sure, so when we execute awesome with `--no-argb` it use 24 bpp . Are there any other window managers which use 32bpp in order to test compton or other compositors with them?

**Comment by psychon** [comment] 2015-10-03 11:54
Sorry, I only ever looked at fluxbox' source code.
You can figure out the depth of a window via `xwininfo` and `xwininfo -frame`. The first one reports information about the actual window (here I just had `Depth: 24` with urxvt) while the second one looks at the frame that the WM adds (`Depth: 32`). When starting urxvt with `urxvt -depth 32`, then both values report a depth of 32.

**Comment by Elv13** [comment] 2017-05-27 03:09
@psychon Can this be closed?

**Comment by psychon** [comment] 2017-05-27 07:30
Closing as "not our bug". I do not think we can do anything about this. Might be fixed by an Xorg, video driver or compton update.

**Closed by psychon** 2017-05-27 07:30 UTC
Labels: need info, no-argb
