### ISSUE TITLE
concatenate tag instead of switching to tag

### ISSUE THREAD

**Issue by choosy** [awesomeWM/awesome#264] opened 2015-06-15 09:49 UTC
Hi,

I am using:

awesome v3.5.6 (For Those About To Rock)
 • Build: Jan 17 2015 02:26:27 for x86_64 by gcc version 4.9.2 (mockbuild@)
 • Compiled against Lua 5.3.0 (running with Lua 5.3)
 • D-Bus support: ✔

on a Fedora 22 which runs inside a VirtualBox.

The behaviour I am observing, is with a default rc.lua.

When I press modkey+number, instead of completely switching to the tag, it underlines the next tag and shows the focused client of that tag, without switchint to the tag. I've learned on irc that this is called that it concatenates the tag, which is normally done when pressing ctrl.
So even if I don't press ctrl, and I just use modkey+tag-number, it acts like I do press ctrl, it concatenates that tag.
The temporary quick workaround for this, is that I have enabled:
local titlebars_enabled=true

This automatically does some activity on the focused client, which I guess triggers some signal because awesome will completely switch to that tag. 

However, I think that describing it like ctrl is stucked is misleading, since other awesome shortcuts don't act like ctrl is already pressed. 
For example, if I press modkey+"r" it opens the "Run" prompt. I really have to press ctrl+modkey+"r" 
to have awesome restarted.

Thank you

**Comment by psychon** [comment] 2015-06-15 17:36
Could you check with `xprop -root _NET_CURRENT_DESKTOP`? That should return the lowest index (zero-based, so tag 1 has index 0)  of any selected tag. So if this really has both tags 1 and 2 selected when you want to switch to 2, then this should still say 2.

I guess that this is a duplicate of some bugs where the redrawing doesn't redraw. The bug is in the X11 server and can be worked around by starting awesome with the `--no-argb` argument. Some bugs in FS are https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1089 and https://awesome.naquadah.org/bugs/index.php?do=details&task_id=1060 and their duplicates.

**Comment by psychon** [comment] 2016-02-22 16:42
Apparently someone found a work-around or stopped using awesome...

**Closed** 2016-02-22 16:42 UTC
Labels: need info

**Comment by choosy** [comment] 2016-04-20 15:48
Hi,

I haven't stopped using awesome. It dissapeared for awhile then appeared again. 
But I solved it with by providing the --no-argb argument when starting awesome. Thanks for the trick!

**Comment by psychon** [comment] 2017-05-25 13:53
Might be fixed by https://bugs.freedesktop.org/show_bug.cgi?id=99220 (which was just fixed).
