### ISSUE TITLE
Multihead setup: weird behavior when changing screen order

### ISSUE THREAD

**Issue by wucke13** [awesomeWM/awesome#1704] opened 2017-04-03 17:46 UTC
Output of `awesome --version`:

```
awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

* Start awesome in a multihead environment
* change the order of screens using xrandr

**Actual result:**

The screen order appears correct, regarding moving the mouse from the one to the other screen (moving mouse to the right, starting from the left screen ends on the right screen). Everything else however now is the wrong way around: when clicking on the awesome menu icon on the left screen, the menu opens on the right screen. Moving the mouse to a place on the left screen focusses the window on the regarding position on the right screen. 

**Expected result:**

* Having all screens in the correct order
* actions which are done by the user in one screen should have an impact on that screen

**Comment by Veratil** [comment] 2017-04-03 18:22
Possibly related to #1685

**Comment by Elv13** [comment] 2017-04-03 20:01
Duplicate of https://github.com/awesomeWM/awesome/issues/154

**Comment by psychon** [comment] 2017-04-04 07:11
Closing as a duplicate of #154. Which X.org video driver are you using? I think #154 was with the nvidia binary blob.

**Closed by psychon** 2017-04-04 07:11 UTC

**Comment by wucke13** [comment] 2017-04-04 20:40
I used nouveau, when this appeared. Interesting note: this does not happen, when using proprietary nvidia drivers.

**Comment by Elv13** [comment] 2017-04-05 04:10
Back then, I was able to reproduce it both using Xephyr and NVIDIA+Xinerama. I also got the bug last year and just changed the layout until it worked. Are you having the bug **without** xinerama?

**Comment by wucke13** [comment] 2017-04-05 11:25
If have never used xinemara, as far as I can tell!

**Comment by dantix** [comment] 2017-05-13 11:30
I confirm that bug is reproducible when using `nouveau` and gone when switching to proprietary drivers.
