### ISSUE TITLE
Borders only between windows

### ISSUE THREAD

**Issue by julien-f** [awesomeWM/awesome#1633] opened 2017-03-06 11:08 UTC
Hi, is there a way to have borders only between windows, not on the outside (therefore not on maximized/fullscreen)?

Output of `awesome --version`:

```
awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

**Comment by Elv13** [comment] 2017-03-13 03:04
Using some negative screen padding should get the border out of the view. However it will only work with 1 screen and the wibar need to ne forced to be `ontop`.

**Comment by julien-f** [comment] 2017-03-13 08:53
Unfortunately it won't work for me (2 screens) 😢 

Thanks anyway!

**Comment by psychon** [comment] 2017-03-13 09:00
I feel like I do not completely understand your question. Two possible interpretations:

- I do not want a border around fullscreen/maximized clients/windows, but around all other clients/windows
- I do not want a border at the edge of a window that touches the edge of the screen/workarea. So if I have two clients, one takes the complete left part of the visible space while the other takes the complete right part of the visible space, the left client would only have a border at its right edge (and no border top,bottom,left) and the right client... well, vice-versa.

The second option is currently technically impossible. We just tell the X server the border color and the border width. The rest is handled by the server.

> Unfortunately it won't work for me (2 screens) 😢

Sounds to me a bit more like you actually want the second option. Well, here is another hack ontop of the one already suggested by @Elv13: Do not have your screens directly side-by-side. Normally, one does something like `xrandr --output FOO --auto --output BAR --auto --right-of FOO` to get side-by-side displays (or one uses a GUI which, in the end, doesn't do much more than this). If the native resultion if `FOO` is `1600x900`, one could try something like the following instead `xrandr --output FOO --auto --output BAR --auto --pos 1610x0`. This should provide 10 invisible pixels between the screens where borders can be "hidden".

**Comment by julien-f** [comment] 2017-03-13 09:13
For me the ideal setup would be: having a 1px (configurable) separation between each clients/windows, which means:

- no borders for fullscreen/maximized clients (this is a good first step)
- no borders at the edge of the screen (good second step)
- no double borders (only 1px separation between two clients)

This would maximize the use of screen space while keeping the different clients visible (especially necessary for terminals which are hard to tell apart due to their uniform background).

**Comment by actionless** [comment] 2017-03-14 22:01
seems to be related to https://github.com/awesomeWM/awesome/pull/596

i think it's a time to resurrect that one :)

**Comment by Elv13** [comment] 2017-05-25 08:17
Closing as a duplicate of #596, discussion should continue there

**Closed by Elv13** 2017-05-25 08:17 UTC
