### ISSUE TITLE
a menu.clients() menu should emit a signal, or call a function, when it is closed by the keygrabber

### ISSUE THREAD

**Issue by everslick** [awesomeWM/awesome#447] opened 2015-09-12 16:48 UTC
otherwise there is no way to set instance to nil, when the keygrabber closes the menu in the default rc.lua config.

Test:
right click on tasklist -> clients menu opens
press ESC -> menu closes
right click on tasklist -> nothing
right click on tasklist again -> clients list opens

**Comment by blueyed** [comment] 2015-09-12 17:51
Seems to be a duplicate of #420.

**Closed by blueyed** 2015-09-12 17:51 UTC
