### ISSUE TITLE
Awesome wm withcopycat themes wont open terminal

### ISSUE THREAD

**Issue by CDitzel** [awesomeWM/awesome#1810] opened 2017-06-02 07:45 UTC
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✘
 • LGI version: 0.9.0

did 
sudo add-apt-repository  ppa:klaus-vormweg/awesome -y
sudo apt update
sudo apt install  awesome -y

to get awesome version 4, so far I have Xubuntu on my computer

**How to reproduce the issue:**

followed the steps here
https://github.com/copycat-killer/awesome-copycats
to get themes and log in with awesome

**Actual result:**

Everything looks fine, but the clock and date widgets show some undisplayable symbols.
The main problem though is that I cannot start a terminal, neither through mod+return nor via mouse.
Did change the default terminal in rc.lua to xfce4-terminal which seemed to solve the problem. But now when I switch between tags, terminal windows blank out and dont show their content no more

**Expected result:**

The terminal should appear and work flawlessly

**Comment by psychon** [comment] 2017-06-02 07:55
> Did change the default terminal in rc.lua to xfce4-terminal which seemed to solve the problem. 

So the problem from the title of this issue was actually already solved...?

> But now when I switch between tags, terminal windows blank out and dont show their content no more.

Could you try starting awesome with the `--no-argb` command line argument? If that fixes your issue, then this is a bug in your video driver. What video driver are you using?

For "how do I use `--no-argb`": How are you starting awesome? One (brute force) possibility would be to run the following as root (only run this if you understand what it does and how to undo it):
```sh
mv /usr/bin/awesome /usr/bin/awesome.orig
cat > /usr/bin/awesome <<EOF
#!/bin/sh
exec /usr/bin/awesome.orig --no-argb
EOF
chmod a+x /usr/bin/awesome
```

**Comment by CDitzel** [comment] 2017-06-02 08:03
dont understand what it does so I better be careful.

I am using Nvidia binary drivers version 375.66 with my GTX700

I just log out from xfce at the moment and choose awesome before I log in again

**Comment by Elv13** [comment] 2017-06-02 14:45
IMHO, for the blank part, this is a duplicate of https://github.com/awesomeWM/awesome/issues/1357 and will be fixed in v4.2 (to be released soon).

As for `xterm` not being installed, this is a packaging issue.

**Closed by Elv13** 2017-06-02 14:45 UTC

**Comment by CDitzel** [comment] 2017-06-06 13:51
well xterm is installed =/

**Comment by psychon** [comment] 2017-06-06 14:01
The default config seems to use `urxvtc` as the terminal: https://github.com/copycat-killer/awesome-copycats/blob/30f136d244cdc95adf6c5fc85dd8a7cab91b2e6a/rc.lua.template#L65
(And starts `urxvtd` where needed)

So the hint with xterm was wrong and @copycat-killer actually defaults to urxvt.

**Comment by copycat-killer** [comment] 2017-06-07 09:49
@CDitzel You just have to set [this line](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.template#L65) to 

```diff
-local terminal = "urxvtc" or "xterm"
+local terminal = "xterm"
```

Also, remove "urxvtd" and eventually redefine the input [here](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.template#L58).

**Comment by CDitzel** [comment] 2017-06-07 10:44
thank you, what do I have to redefine there?

**Comment by copycat-killer** [comment] 2017-06-07 11:00
Whatever list of autostarting processes you want (comma separated).

If you don't have any, just comment the line with `--`.

**Comment by Elv13** [comment] 2017-06-07 21:09
local terminal = "urxvtc" or "xterm"

Just a note, the code above isn't working because the strings are always true. However, `awful.spawn` can be wrapped in ways that will allow daisy chaining like this to work.

**Comment by psychon** [comment] 2017-06-08 07:11
@copycat-killer Perhaps this helps you:
```
$ lua -e 'print(require("lgi").GLib.find_program_in_path("does_not_exist"))' 
nil
$ lua -e 'print(require("lgi").GLib.find_program_in_path("urxvt"))'         
/usr/bin/urxvt
```

**Comment by copycat-killer** [comment] 2017-06-09 10:06
@Elv13 I know, I used it as a reminder, but it was just a bad habit. I removed it.

@psychon `lgi` is really a blessing to us.

**Comment by CDitzel** [comment] 2017-06-10 18:24
what is lgi and also, what terminals do you personally use or can recommend?

**Comment by actionless** [comment] 2017-06-10 21:22
> local terminal = "urxvtc" or "xterm"

i remember when i was trying and reading one of copycat's configs for a first time i was like "wow, i wasn't expected lua is so cool in providing syntastic sugar"

**Comment by psychon** [comment] 2017-06-11 08:57
@CDitzel LGI makes "everything based on GObject" accessible to Lua. Thanks to LGI, we can use e.g. GLib in Lua. The name stands (I think...) for Lua GObject Introspection.
Personally, I use urxvt.
