### ISSUE TITLE
background of awful.hotkeys_popup.widget

### ISSUE THREAD

**Issue by quizzmaster** [awesomeWM/awesome#1353] opened 2017-01-02 15:33 UTC
Output of `awesome --version`:

awesome v4.0-27-g6c3ac97 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

Set theme.bg_normal to "#22222299" 

**Actual result:**

The background of the hotkeys popup becomes transparent.

**Expected result:**

The background of the hotkeys popup should not be affected by bg_normal. It should rely on its own variable for its background.

**Comment by psychon** [comment] 2017-01-02 16:27
CC @actionless

**Comment by actionless** [comment] 2017-01-03 08:50
looks like a duplicate of https://github.com/awesomeWM/awesome/issues/1352

**Comment by blueyed** [comment] 2017-01-03 13:14
Yep.

**Closed by blueyed** 2017-01-03 13:14 UTC
