### ISSUE TITLE
no border drawn on rounded rectangle notification

### ISSUE THREAD

**Issue by nomadicME** [awesomeWM/awesome#2230] opened 2018-03-21 20:18 UTC
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

here are the pertinent lines from theme.lua:

		local rrect = function(radius)
			return 	function(cr, width, height)
					  gears.shape.rounded_rect(cr, width, height, radius)
					end
		end

		theme.notification_border_width = 5
		theme.notification_border_color = "#285577"	-- light blue
		theme.notification_shape = rrect(10)

**Actual result:**

the shape is applied correctly, but the border is not displayed.

**Expected result:**

a 5 pixel border around the notification.

**Comment by alfunx** [comment] 2018-04-03 22:28
![screenshot](https://i.imgur.com/Ofe8sFu.png)

With exactly your config, v4.2-1 on Arch Linux. Did you try it with bigger border width?

**Comment by ervasive** [comment] 2018-04-04 20:48
It seems like my issue is related to this one to some extent, but let me know if it's better to create a separate issue.

It looks like some values of notifications library can't be overwritten properly by theme variables and by looking into its code, the problem seems to be [in the order of how the variables are being set](https://github.com/awesomeWM/awesome/blob/5e6f5343653a3f69ce353f3a3388a9b6f48e370a/lib/naughty/core.lua#L622-L668):

```lua
local border_width = args.border_width or preset.border_width or 
        beautiful.notification_border_width
```

It never reaches the `beautiful.notification_border_width` part, because of `preset.border_width` is always being set by:

```lua
local preset = gtable.join(naughty.config.defaults or {},
      args.preset or naughty.config.presets.normal or {})
```

So it is possible to set let's say `notification_border_width` through `naughty.config.defaults.border_width` but not through `beautiful.border_width`.

**Comment by actionless** [comment] 2018-04-04 21:26
@ervasive looks like a separate issue

**Comment by ervasive** [comment] 2018-04-04 21:59
@actionless Created separate [issue](https://github.com/awesomeWM/awesome/issues/2237)

**Comment by Elv13** [comment] 2018-06-28 21:02
@nomadicME ping?

Otherwise I will close the issue soon as nobody seems to reproduce

**Comment by Elv13** [comment] 2018-10-06 22:28
Closing due to the `need info` label being set for months with no activity.

**Closed by Elv13** 2018-10-06 22:28 UTC
Labels: need info
