### ISSUE TITLE
naughty.notify() with an icon causes memory consumption to skyrocket

### ISSUE THREAD

**Issue by karlyeurl** [awesomeWM/awesome#2282] opened 2018-06-04 22:25 UTC
Output of `awesome --version`:

```
awesome v4.0-305-g2d91d49b (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version
```

**How to reproduce the issue:**

Call `naughty.notify()` with an icon specified.
example: `naughty.notify({ icon = "/foo/bar/foobar.svg", text = "hello", timeout = 2})`

**Actual result:**

Awesome-wm uses considerably more memory. Without the icon, on my setup, awesome starts at ~250M. With the icon, it's a considerable 370M.

**Expected result:**

Awesome-wm should not use considerably more memory upon `naughty.notify({ icon="/some/icon" })` calls.

**Comment by karlyeurl** [comment] 2018-06-04 22:32
Follow-up comment:

I've dug a little bit into the naughty code, and found two separate calls that cause the memory consumption to grow.

In my version of `naughty/core.lua`:

```
        -- try to guess icon if the provided one is non-existent/readable
        if type(icon) == "string" and not util.file_readable(icon) then
            icon = util.geticonpath(icon, naughty.config.icon_formats, naughty.config.icon_dirs, icon_size) or icon
        end

        -- is the icon file readable?
        icon = surface.load_uncached(icon)
```

* The calls to `util` (either) causes 60% of the memory increase.
* The call to `surface.load_uncached` causes the remaining 40%.

I am aware the version in `master` has changed a bit since (I see a call to `gfs` replaced a call to `util`). I'm not sure the issue can be reproduced on `master`, but I would not be surprised if it were the case.

**Comment by psychon** [comment] 2018-06-05 07:59
> and found two separate calls that cause the memory consumption to grow.

How did you measure this?

>  The call to util (either) causes 60% of the memory increase.

Uhm. `geticonpath` are just three nested for loops that try out lots of file names and check if any of them survives `gears.filesystem.file_readable`. So... What?
Either all the strings that are allocated in there cause this memory usage (but they are not referenced for long and so GC'able?!), or all those calls to `gears.filesystem.file_readable` cause this (but still, the GC should just clean this up?). Once I have some time (and no one beats me to it and tests this first), I'll see if `for _ = 1, 1000000 do require("gears.filesystem").file_readable("foobar") end` has a similar effect.
(todo: make sure I can reproduce the original problem first, else the exercise might be pointless)

>    The call to surface.load_uncached causes the remaining 40%.

Hm. I would have said "huge image", but:

> Note: I have tried with a small 32x32 PNG instead of the SVG, the issue stayed the same.

**Comment by karlyeurl** [comment] 2018-06-05 21:33
Hi psychon, thanks for reading my report.

>> and found two separate calls that cause the memory consumption to grow.
>
> How did you measure this?

Trial and error, by commenting out lines of code in the `naughty/core.lua` file. Removing the `if` clause (and its inner call) caused the memory to only grow up to 299M. Removing the `surface` call and leaving the `if` clause untouched caused the memory to get to 320M.

Note that I've changed the code in three separate ways for the latter test: 
* leaving the condition as is, 
* 
        if type(icon) == "string" and not util.file_readable(icon) then
            --- do nothing
        end
* 
        if type(icon) == "string" then
            icon = util.geticonpath(icon, naughty.config.icon_formats, naughty.config.icon_dirs, icon_size) or icon
        end

All yielded the same result. I think the problem doesn't come from a call to `util.X()`, but from (loading?) `util` itself. It's only a hunch, though.

**Comment by psychon** [comment] 2018-06-06 07:00
> I think the problem doesn't come from a call to util.X(), but from (loading?) util itsel

But `awful.util` is loaded in all cases (by `require("awful.util")` in naughty, but even in rc.lua, just `require("awful")` also loads `awful.util`.

**Comment by karlyeurl** [comment] 2018-06-06 07:57
Perhaps "invoking" would have been a better term. I don't really know what's going on, I am not exactly familiar with how Lua behaves in that regard.

Here's a snippet for a widget (any widget, really) that I believe reproduces the issue. Clicking the first time causes the memory to grow, clicking a second (third, etc.) time does not worsen the issue.

```
someWidget:connect_signal("button::press", function() sendNotification() end)

function sendNotification()
    local iconPath = "/tmp/foo.png"
    naughty.notify({ icon = iconPath, text = "Hi guys" })
end
```

**Comment by psychon** [comment] 2018-06-09 08:38
So, I finally found some time. I appended the following to `rc.lua` (this SVG gets loaded as 380x380 pixels!):
```lua
local function memory_usage()
    local res = {}
    for line in io.lines("/proc/self/status") do
        local k, v = string.match(line, "Vm(%a+):%s+(%d+) kB")
        if k then
            res[k] = v
        end
    end
    return res
end

local function print_memory_usage(info)
    local m = memory_usage()
    print(string.format("%sVirtual: %s kB, residential: %s kB", info or "", m.Size, m.RSS))
end

local function gc(i)
    for _ = 1, 5 do
        collectgarbage("collect")
    end
    print_memory_usage(string.format("after GC %d:      ", i))
end

local icon = "/usr/share/icons/hicolor/scalable/apps/gvim.svg"

gears.timer.start_new(2, function()
    print_memory_usage("after startup:   ")
    naughty.notify{ text = "hello", timeout = 2 }
    print_memory_usage("after notify:    ")
    gears.timer.start_new(1, function()
        print_memory_usage("after visible:   ")
    end)
    gears.timer.start_new(3, function()
        print_memory_usage("after hide:      ")
        gc(1)

        naughty.notify{ icon = icon, text = "hello", timeout = 2 }
        print_memory_usage("after notify 2:  ")
        gears.timer.start_new(1, function()
            print_memory_usage("after visible 2: ")
        end)
        gears.timer.start_new(3, function()
            print_memory_usage("after hide 2:    ")
            gc(2)

            naughty.notify{ icon = icon, text = "hello", timeout = 2 }
            print_memory_usage("after notify 3:  ")
            gears.timer.start_new(1, function()
                print_memory_usage("after visible 3: ")
            end)
            gears.timer.start_new(3, function()

                print_memory_usage("after hide 3:    ")
                gc(3)

                gears.surface.load_uncached(icon)

                print_memory_usage("after load icon: ")
                gc(4)
                awesome.quit()
            end)
        end)
    end)
end)
```
Output is:
```
after startup:   Virtual: 254700 kB, residential: 31800 kB
after notify:    Virtual: 254832 kB, residential: 32064 kB
after visible:   Virtual: 254964 kB, residential: 32064 kB
after hide:      Virtual: 254964 kB, residential: 32064 kB
after GC 1:      Virtual: 245744 kB, residential: 22960 kB
after notify 2:  Virtual: 299860 kB, residential: 27424 kB
after visible 2: Virtual: 299860 kB, residential: 27424 kB
after hide 2:    Virtual: 299860 kB, residential: 27424 kB
after GC 2:      Virtual: 299860 kB, residential: 27424 kB
after notify 3:  Virtual: 299860 kB, residential: 27424 kB
after visible 3: Virtual: 299860 kB, residential: 27424 kB
after hide 3:    Virtual: 299860 kB, residential: 27424 kB
after GC 3:      Virtual: 299860 kB, residential: 27424 kB
after load icon: Virtual: 299860 kB, residential: 27424 kB
after GC 4:      Virtual: 299860 kB, residential: 27424 kB
```
So, for me awesome starts with ~31 MiB residential and ~255 MiB virtual size. Doing a text-only notification increases this slightly (~32 MiB, ~255 MiB), but not much. Forcing a run of the garbage collector brings memory usage down (~23 MiB, ~246 MiB) and then doing a notification with an icon increases usage again a bit (~27 MiB, ~300 MiB). Afterwards, things stop changing.

If I change the code to begin with loading the icon (`gears.surface.load_uncached`) and running the GC, memory usage immediately goes to ~27 MiB and ~300 MiB and stays there.

If I change the code to remove the calls to the garbage collectors, well, memory usage goes up because garbage accumulates. Such is live, I guess...

My summary: There is no memory leak here and you are looking at virtual size. So, just by loading an SVG, you cause `libpixbufloader-svg.so` to be loaded, which can lead to some two megabyte of virtual memory use, plus dependent libraries like librsvg, libxml and whatever.

You really should look at the residential set size (RSS) instead. According to my experiments, that one "does not do anything evil".

What do you think?

**Comment by psychon** [comment] 2018-06-09 11:09
Oh and one more thing:

> Awesome-wm uses considerably more memory. Without the icon, on my setup, awesome starts at ~250M. With the icon, it's a considerable 370M.

Could you get the output of `pmap` for both cases? I.e. `pmap -x $(pidof awesome)`.

**Comment by karlyeurl** [comment] 2018-06-18 22:11
Sorry for taking that long. You're entierly right, I may have been looking at the wrong thing. Not a bug, then.

[`pmap` with notification triggered with the icon](https://github.com/awesomeWM/awesome/files/2113146/with-icon.txt)
[`pmap` without notification triggered](https://github.com/awesomeWM/awesome/files/2113147/no-icon.txt)

**Comment by psychon** [comment] 2018-06-19 09:56
Wow. So, there is lots of tiny stuff (12 KiB of additional stack usage, some anonymous area *shrinking* by 22 KiB, some more of `libgio-2.0.so.0.5600.1` getting dirtied), but the following libraries are additionally loaded (plus some new anonymous areas):
- `libgvfsdbus.so`
- `libgvfscommon.so`
- `libpixbufloader-svg.so`
- `librsvg-2.s0.2.42.4`
- `libcroco-0.6.so.3.0.1`
- `libxml2.so.2.9.8`
- `libgcc_s.so.1`
- `libicuuc.so.61.1`
- `libicudata.so.61.1`
- `libstdc++.so.6.0.25`

Together, loading these libraries uses `1508+2048+48+4+26260+2044+4+1688+2044+76+4+92+2044+4+4+1388+2044+36+4+224+2044+12+4+1436+2048+132+4+8+2044+4+4+224+2048+24+4+176+2044+8+4` KiB of virtual memory (not counting anonymous areas which, I guess, are for `.bss` segments). That's ~53 MiB of virtual memory (and since some of that is dirty, I guess RSS also increases slighty).

If I guess that the largest anonymous area is the heap, heap usage increases by 12 KiB virtual memory and 14 KiB RSS. That's almost nothing.

So yes, there is a slight increase in RSS of awesome itself, but most of the increase is just from loading these libraries. That's not a leak, aka it only happens for the first SVG (and its not "skyrocket").

I'll close this issue. Feel free to complain if you disagree.

**Closed by psychon** 2018-06-19 09:56 UTC
