### ISSUE TITLE
Do something about the failed Lua 5.3 builds

### ISSUE THREAD

**Issue by Elv13** [awesomeWM/awesome#2335] opened 2018-08-03 22:18 UTC
Since more aggressive Lua asserts have been enabled, the Lua 5.3 build randomly fails. 

It sucks because:

 * It makes Mergify fail
 * It put the "borken build" tag on the README page
 * It spam my inbox everytime I merge something with fake broken/fixed builds emails requiring investigation for no reasons.
 * We have to restart the build `n` time to know it passes and it takes sometime hours.

So I say we disable the test until it actually provides value instead of noise.

**Comment by blueyed** [comment] 2018-08-03 23:49
Can you provide a link to a failed build and the test in question?  (have not noticed it myself obviously)

**Comment by psychon** [comment] 2018-08-05 08:06
@blueyed https://travis-ci.org/awesomeWM/awesome/jobs/406276106
```
awesome: lvm.c:436: luaV_equalobj: Assertion `(((t1)->value_).gc)->tt == 5' failed.
2018-07-20 14:37:33 E: awesome: signal_fatal:448: signal 6, dumping backtrace
/home/travis/build/awesomeWM/awesome/build/awesome(backtrace_get+0x49) [0x42d582]
/home/travis/build/awesomeWM/awesome/build/awesome() [0x40f105]
/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0) [0x2b5bb4049cb0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x2b5bb4049c37]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x2b5bb404d028]
/lib/x86_64-linux-gnu/libc.so.6(+0x2fbf6) [0x2b5bb4042bf6]
/lib/x86_64-linux-gnu/libc.so.6(+0x2fca2) [0x2b5bb4042ca2]
/usr/lib/liblua.so(+0x20553) [0x2b5bb3ba8553]
/usr/lib/liblua.so(+0x1cb2d) [0x2b5bb3ba4b2d]
/usr/lib/liblua.so(+0x1d1be) [0x2b5bb3ba51be]
/usr/lib/liblua.so(+0x230c1) [0x2b5bb3bab0c1]
/usr/lib/liblua.so(+0x115ff) [0x2b5bb3b995ff]
/usr/lib/liblua.so(+0x11651) [0x2b5bb3b99651]
/usr/lib/liblua.so(+0x104cf) [0x2b5bb3b984cf]
/usr/lib/liblua.so(+0x11abd) [0x2b5bb3b99abd]
/usr/lib/liblua.so(lua_pcallk+0xca) [0x2b5bb3b9372a]
/home/travis/build/awesomeWM/awesome/build/awesome(signal_object_emit+0x375) [0x431beb]
/home/travis/build/awesomeWM/awesome/build/awesome(luaA_class_emit_signal+0x15) [0x42fb1d]
/home/travis/build/awesomeWM/awesome/build/awesome(luaA_object_emit_signal+0x56f) [0x432293]
/home/travis/build/awesomeWM/awesome/build/awesome() [0x446b8d]
/home/travis/build/awesomeWM/awesome/build/awesome() [0x446c65]
/usr/lib/liblua.so(+0x11113) [0x2b5bb3b99113]
/usr/lib/liblua.so(+0x214db) [0x2b5bb3ba94db]
/usr/lib/liblua.so(+0x115ff) [0x2b5bb3b995ff]
/usr/lib/liblua.so(+0x11651) [0x2b5bb3b99651]
/usr/lib/liblua.so(+0x104cf) [0x2b5bb3b984cf]
/usr/lib/liblua.so(+0x11abd) [0x2b5bb3b99abd]
/usr/lib/liblua.so(lua_pcallk+0xca) [0x2b5bb3b9372a]
/usr/lib/liblua.so(+0x26c20) [0x2b5bb3baec20]
/usr/lib/liblua.so(+0x11113) [0x2b5bb3b99113]
/usr/lib/liblua.so(+0x214db) [0x2b5bb3ba94db]
/usr/lib/liblua.so(+0x115ff) [0x2b5bb3b995ff]
Awesome exited with status code 1
```
and (less interesting) https://travis-ci.org/awesomeWM/awesome/jobs/411931284
```
== Running /home/travis/build/awesomeWM/awesome/tests/test-leaks.lua ==
Error org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
E: dbus-send failed.
make[4]: *** [CMakeFiles/check-integration] Error 1
```

**Comment by psychon** [comment] 2018-08-05 11:08
@Elv13  Is this a duplicate of #2163?

**Comment by Elv13** [comment] 2018-08-05 23:01
> @Elv13 Is this a duplicate of #2163?

yes

**Closed** 2018-08-06 07:38 UTC
Labels: bug, build, duplicate
