### ISSUE TITLE
Build fails because of ldoc error

### ISSUE THREAD

**Issue by actionless** [awesomeWM/awesome#1127] opened 2016-09-30 16:16 UTC
with the current master i have a following build exception:
```
format: using built-in markdown
lua: /usr/share/lua/5.3/ldoc/tools.lua:117: table index is nil
stack traceback:
        /usr/share/lua/5.3/ldoc/tools.lua:117: in method 'add'
        /usr/share/lua/5.3/ldoc/doc.lua:397: in method 'finish'
        /usr/sbin/ldoc:534: in upvalue 'add_special_project_entity'
        /usr/sbin/ldoc:613: in local 'operation'
        /usr/share/lua/5.3/ldoc/tools.lua:534: in function 'ldoc.tools.process_file_list'
        /usr/sbin/ldoc:612: in main chunk
        [C]: in ?
```

i've applyed a quick workaround:
```patch
diff --git a/awesomerc.lua b/awesomerc.lua
index 287a916..43c8515 100755
--- a/awesomerc.lua
+++ b/awesomerc.lua
@@ -499,7 +499,7 @@ awful.rules.rules = {
 }
 -- }}}

--- {{{ Signals
+-- {{{ Signals handling
 -- Signal function to execute when a new client appears.
 -- @DOC_MANAGE_HOOK@
 client.connect_signal("manage", function (c)
```

and afterwards ldoc is passing but still printing warning:
```
reading configuration from config.ld
found master module     /home/lie/build/awesome-git/src/build/luaa.c
found master module     /home/lie/build/awesome-git/src/build/luaa.c
found master module     /home/lie/build/awesome-git/src/build/objects/client.c
/home/lie/build/awesome-git/src/build/lib/awful/mouse/init.lua:40: definition cannot be parsed - not 'name=value' or 'return value'
/home/lie/build/awesome-git/src/build/lib/awful/mouse/init.lua:43: definition cannot be parsed - not 'name=value' or 'return value'
/home/lie/build/awesome-git/src/build/lib/awful/mouse/init.lua:46: definition cannot be parsed - not 'name=value' or 'return value'
/home/lie/build/awesome-git/src/build/lib/awful/mouse/init.lua:49: definition cannot be parsed - not 'name=value' or 'return value'
found master module     /home/lie/build/awesome-git/src/build/mouse.c
/home/lie/build/awesome-git/src/build/lib/awful/screen.lua:231: definition cannot be parsed - not 'name=value' or 'return value'
found master module     /home/lie/build/awesome-git/src/build/objects/screen.c
/home/lie/build/awesome-git/src/build/lib/awful/tag.lua:82: definition cannot be parsed - not 'name=value' or 'return value'
/home/lie/build/awesome-git/src/build/lib/awful/tag.lua:668: definition cannot be parsed - not 'name=value' or 'return value'
found master module     /home/lie/build/awesome-git/src/build/objects/tag.c
found master module     /home/lie/build/awesome-git/src/build/lib/naughty/core.lua
format: using built-in markdown
/home/lie/build/awesome-git/src/build/lib/awful/tag.lua:706: tag.layout: function or section not found: awful.tag.layouts in awful.tag
output written to /home/lie/build/awesome-git/src/build/doc
```

and because of https://github.com/awesomeWM/awesome/commit/4c8128eaa903575a46cc069ea9da3c001f55fb2b those warning are need to be fixed in order to succeed the build

**Comment by psychon** [comment] 2016-09-30 19:02
What's your ldoc version? Travis is currently not using the latest version, but 1.4.4 because of #1098 / https://github.com/stevedonovan/LDoc/issues/248.

**Comment by actionless** [comment] 2016-09-30 19:34
`1.4.5`

**Comment by blueyed** [comment] 2016-09-30 20:08
I can confirm this, of course.
Just tried to update the awesome-luajit-git package for AUR.
Apparently there is no way to pin a lower version there?!

Another issue (once removing/uninstalling `ldoc`):
```
CMake Error at cmake_install.cmake:76 (file):
  file INSTALL cannot find
  "/home/user/builds/awesome-git/src/build/awesomerc.lua".
```

**Comment by Elv13** [comment] 2016-09-30 20:40
Duplicate of #1098

**Closed** 2016-09-30 21:26 UTC
