### ISSUE TITLE
GeoLocation notification shown outside of browser

### ISSUE THREAD

**Issue by Ryuno-Ki** [awesomeWM/awesome#2743] opened 2019-04-07 20:02 UTC
Output of `awesome --version`:

```sh
$awesome --version
awesome v4.2 (Human after all)
 • Compiled against Lua 5.1.5 (running with Lua 5.1)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.0
```

**How to reproduce the issue:**

1. Open Firefox 66.0.1 on (Sabayon) Linux
1. Visit https://openweathermap.org/
1. Wait for the page to load (prompt for asking for GeoLocation will appear)
1. Switch to another AwesomeWM tag

**Actual result:**

Prompt appears without the window (but on the same position):
![geolocation-awesomewm](https://user-images.githubusercontent.com/3097194/55689005-b9891c00-597f-11e9-82a4-3b25c6eef8d0.png)
Interacting with the buttons doesn't close it (but raises highlight on the tab with Firefox).

**Expected result:**

Should be bound to Firefox, i.e. appear only in the same tag as the browser which triggers it.
Clicking the buttons should at least close them (and inform the browser window in Firefox about the decision).

**Comment by Ryuno-Ki** [comment] 2019-04-07 20:02
**Additional info:**

Maybe related to #2729?

```sh
dbus-monitor 
signal time=1554667050.787625 sender=org.freedesktop.DBus -> destination=:1.95 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.95"
signal time=1554667050.787709 sender=org.freedesktop.DBus -> destination=:1.95 serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.95"
method call time=1554667053.568077 sender=:1.96 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1554667053.568102 sender=org.freedesktop.DBus -> destination=:1.96 serial=1 reply_serial=1
   string ":1.96"
signal time=1554667053.568113 sender=org.freedesktop.DBus -> destination=(null destination) serial=145 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.96"
   string ""
   string ":1.96"
signal time=1554667053.568127 sender=org.freedesktop.DBus -> destination=:1.96 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.96"
method call time=1554667053.568438 sender=:1.96 -> destination=org.freedesktop.DBus serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=AddMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.gtk.vfs.Daemon'"
method return time=1554667053.568457 sender=org.freedesktop.DBus -> destination=:1.96 serial=3 reply_serial=2
method call time=1554667053.568532 sender=:1.96 -> destination=org.freedesktop.DBus serial=3 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=StartServiceByName
   string "org.gtk.vfs.Daemon"
   uint32 0
method return time=1554667053.568552 sender=org.freedesktop.DBus -> destination=:1.96 serial=4 reply_serial=3
   uint32 2
method call time=1554667053.568735 sender=:1.96 -> destination=org.freedesktop.DBus serial=4 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=GetNameOwner
   string "org.gtk.vfs.Daemon"
method return time=1554667053.568750 sender=org.freedesktop.DBus -> destination=:1.96 serial=5 reply_serial=4
   string ":1.5"
method call time=1554667053.568960 sender=:1.96 -> destination=:1.5 serial=5 path=/org/gtk/vfs/mounttracker; interface=org.gtk.vfs.MountTracker; member=ListMountableInfo
method return time=1554667053.569497 sender=:1.5 -> destination=:1.96 serial=144 reply_serial=5
   array [
      struct {
         string "nfs"
         string "nfs"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "burn"
         string "burn"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "afc"
         string "afc"
         array [
         ]
         int32 1
         boolean false
      }
      struct {
         string "ftp"
         string "ftp"
         array [
         ]
         int32 21
         boolean true
      }
      struct {
         string "afp-volume"
         string "afp"
         array [
         ]
         int32 548
         boolean true
      }
      struct {
         string "recent"
         string "recent"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "network"
         string "network"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "ftps"
         string "ftps"
         array [
         ]
         int32 21
         boolean true
      }
      struct {
         string "google-drive"
         string "google-drive"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "trash"
         string "trash"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "davs+sd"
         string "davs+sd"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "dav+sd"
         string "dav+sd"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "smb-server"
         string "smb"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "smb-network"
         string "smb"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "archive"
         string "archive"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "admin"
         string "admin"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "gphoto2"
         string "gphoto2"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "smb-share"
         string "smb"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "computer"
         string "computer"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "http"
         string "http"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "mtp"
         string "mtp"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "dns-sd"
         string "dns-sd"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "localtest"
         string "localtest"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "afp-server"
         string "afp"
         array [
         ]
         int32 548
         boolean true
      }
      struct {
         string "sftp"
         string "sftp"
         array [
            string "ssh"
         ]
         int32 22
         boolean true
      }
      struct {
         string "cdda"
         string "cdda"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "davs"
         string "davs"
         array [
         ]
         int32 0
         boolean false
      }
      struct {
         string "dav"
         string "dav"
         array [
         ]
         int32 0
         boolean false
      }
   ]
method call time=1554667053.570699 sender=:1.96 -> destination=org.freedesktop.DBus serial=6 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=RemoveMatch
   string "type='signal',sender='org.freedesktop.DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',path='/org/freedesktop/DBus',arg0='org.gtk.vfs.Daemon'"
method return time=1554667053.570719 sender=org.freedesktop.DBus -> destination=:1.96 serial=6 reply_serial=6
^C
```

**Comment by psychon** [comment] 2019-04-08 15:55
Sorry, but the bug is in Firefox. I reproduces the problem and this popup is a separate window (obviously, since otherwise it could not stay visible). `xwininfo` output for this window is:
```
$ xwininfo -id 0x200034

xwininfo: Window id: 0x200034 "Firefox"

  Absolute upper-left X:  203
  Absolute upper-left Y:  92
  Relative upper-left X:  203
  Relative upper-left Y:  92
  Width: 405
  Height: 170
  Depth: 24
  Visual: 0x2ab
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x200002 (not installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: yes
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +203+92  -416+92  -416-506  +203-506
  -geometry 405x170+203+92

```
`Map State: IsViewable` tells me I got the right window (Firefox has lots of unviewable windows around). `Override Redirect State: yes` tells me that Firefox does not want the WM to see the window. Thus, AwesomeWM does not know anything about the window and cannot (and must not) hide it.

So, sorry, but I have to close this as "not our bug, bug is in Firefox".

**Comment by Ryuno-Ki** [comment] 2019-04-08 18:49
Thanks. I'll fill a bug with Mozilla then :-)
Any specs which would explain what `xwininfo` is doing?
(Haven't checked its manpage yet)

**Comment by psychon** [comment] 2019-04-08 18:59
`xwininfo` provides information about X11 windows. With `xwininfo -root -tree`, one gets a list of all windows and their parent/child relationship. The numbers at the end, like `100x30+0+0` is the size and position of the window. I used the size/position to find the right window (most of them were obviously something else, too small, etc). The line for the right window gives me the window id (the hexadecimal number at the beginning of the line). Then, `xwininfo -id 0x400004` gives me more info about the window, as shown below. With this, I confirmed that the window is viewable and is override-redirect.

When you file a bug with Mozilla, please provide a link to it here. I thought "someone else must already have reported this problem...", but I failed to find an existing bug report with Google.

**Closed by psychon** 2019-04-08 18:59 UTC
