### ISSUE TITLE
Write selease notes / changelog / something like that

### ISSUE THREAD

**Issue by psychon** [awesomeWM/awesome#1649] opened 2017-03-12 14:54 UTC
Judging by the "due date" of the v4.1 milestone, someone wants to have a new release yesterday. So ok, here are the release notes:

[TODO]

Ref: https://awesomewm.org/doing_a_release/

**Comment by Elv13** [comment] 2017-03-12 19:49
Duplicate of https://github.com/awesomeWM/awesome/issues/1547

**Closed by Elv13** 2017-03-12 19:49 UTC
