### ISSUE TITLE
After minimize, focus should still follow mouse

### ISSUE THREAD

**Issue by bitwombat** [awesomeWM/awesome#99] opened 2015-02-03 21:31 UTC
I find when I Mod4 + N a window (minimize it), I'm unsure what window next has focus.  With the default theme, the focussed window has a *very* subtle outline.  I could check in the bar at the top.

Better would be for the focus to follow the mouse as it usually does.  So, if I minimize a window, the new window that is *now* under my cursor has focus and would be the next one to be minimized if I were to hit Mod4 + N again.

As it is, I find myself reaching for the mouse and wiggling it out of the window it's currently over and back again to get the focus to settle on that window.

**Comment by blueyed** [comment] 2015-02-15 13:00
This should be covered by the sloppy focus handler.

Which version of awesome are you using?

It seems like when minimizing a client, the `mouse::enter` signal gets sent with the to-be-minimized client, which changed in 3aeac387 (awesome master, added in January).

/cc @psychon

**Comment by gbell12** [comment] 2015-02-17 20:29
Version 3.4.15 (Ubuntu 14.04 LTS)
Sounds like this has been remedied since 3.4.15?  Excellent!

**Comment by blueyed** [comment] 2015-02-17 20:33
Oh, that's an old version - caused by awesome not being updated in Debian for a while.

Unfortunately I don't believe that it's been fixed in the meantime, or it has been (improved), but then regressed again.

I believed that you were using the latest release or Git and were affected by 3aeac38 maybe.

**Comment by blueyed** [comment] 2015-03-17 15:44
Just checked this again.

With awesome master, there's (still) no `mouse::enter` event when minimizing a client.
Then it falls back to the autofocus module/handler, which sends the `request::activate` signal for the last focused window.

I've tried using `awful.mouse.client_under_pointer()` with the following in a custom request::activate handler, but it seems like this returns the old (to-be-minimized) client:

    if context ==  "autofocus.check_focus" then
        c = awful.mouse.client_under_pointer() or c
    end

**Comment by psychon** [comment] 2015-03-18 21:37
Not having a `mouse::enter` on minimize is by design, although I can't really say why. If you want to get around it, open `banning.c` and remove the call to `client_ignore_enterleave_events()`. Then all bannings (hiding a client e.g. due to tag switch or unminimize) and unbannings (showing a client for the same reasons) will cause mouse events. I bet that this is not appropriate to have in general, but I don't really know why.

**Comment by blueyed** [comment] 2015-03-18 21:49
I see. Thanks for explaining it!

582c4a7 seems to explain it, but is not too confident about it either.

**Comment by psychon** [comment] 2015-11-28 18:01
As I understand this, the issue was fixed. Closing, but feel free to reopen if I am wrong.

**Closed by psychon** 2015-11-28 18:01 UTC
Labels: bug

**Comment by EmbeddedLinuxGuy** [comment] 2016-03-24 16:54
Hi, I'm not aware that this behavior has changed. In fact it is still the behavior in my build of Awesome:

awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔

I believe this is still an outstanding bug in focus handling; should I re-open or start a new Issue? I'm happy to provide additional information as needed. The bug makes my typical workflow of "minimize several windows consecutively" not work very well since I can't follow the focus.

**Comment by Elv13** [comment] 2016-03-24 20:12
@EmbeddedLinuxGuy Hello. Please try again with the current git version of Awesome before filling a new issue. Non trivial bug fixes and behavior breaking changes are not backported into the 3.5 branch anymore and will go into 3.6 (when it's ready)
