### ISSUE TITLE
fullscreen_hide_border (v4.2) and maximized_hide_border (git) broken

### ISSUE THREAD

**Issue by Anarky** [awesomeWM/awesome#2488] opened 2018-11-28 11:24 UTC
Hello,
when I set `fullscreen_hide_border` in `max.fullscreen` layout, the window's border doesn't disappear.
I normally use the 4.2 version but I compiled the last git version to check and the issue is the same.
I found this bug while trying to use the new `maximized_hide_border` from [647756f](https://github.com/awesomeWM/awesome/commit/647756f) in `max` layout without success.
But toggling a window to fullscreen through Super+f does remove the border.

Output of `awesome --version`:

```
awesome v4.2-512-g8ac83cac (Human after all)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

**How to reproduce the issue:**

Add the following lines in `rc.lua`:
```
beautiful.maximized_hide_border = true
beautiful.fullscreen_hide_border = true
```

**Actual result:**

The window's border is still there.

**Expected result:**

The window's border disappear.

**Comment by psychon** [comment] 2018-11-28 12:49
From a quick grep through the source code: This is only supposed to work with windows that have `c.fullscreen == true`. This is not layout-specific.

CC @Elv13

**Comment by Anarky** [comment] 2018-11-30 09:13
Alright, I misunderstood the options and they work fine.
`fullscreen_hide_border` is for Super+f on a window, `maximized_hide_border` is for Super+m.

I will close the ticket, but is there an option to hide the border on the fullscreen and maximized layout?
Maybe it's something I will have to code on my rc.lua, or do you want me to code an option?

**Comment by kajzersoze** [comment] 2018-12-01 14:29
FWIW I don't have window borders in fullscreen and I'm not using fullscreen_hide_border, neither there is something in rc.lua dealing with that.

However, I have to use `maximized_hide_border`, IMO this should be working with max layout, I don't see a point of that layout if I have to use Super+m to maximize the window which should already be maximized.

**Comment by actionless** [comment] 2018-12-01 22:43
@Anarky in your rc.lua you can connect to client `focus` signal and check which layout is currently chosen and based on that override client's border

for example, in my config border and useless_gaps are dependent on the value of `master_fill_policy`:

`master_fill_policy == expand`:
![2018-12-01--1543704147_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/49333648-e5a42300-f5c2-11e8-9ec6-7dacd101972c.png)


`master_fill_policy == master_width_ratio`:
![2018-12-01--1543704152_1920x1080_scrot](https://user-images.githubusercontent.com/1655669/49333651-ea68d700-f5c2-11e8-841c-76ed99e95dd2.png)

**Comment by Elv13** [comment] 2018-12-17 15:11
The `floating`, `fullscreen` and `maximized` properties are not related to the layouts of the same name. I don't think this will ever change given it would add bi-direction coupling more BS to `_implicit_floating`, `is_immobilized` and friends. I will close this since this is the intended behavior.

**Closed by Elv13** 2018-12-17 15:11 UTC
