### ISSUE TITLE
Pressing a function key causes awesome to hang

### ISSUE THREAD

**Issue by laino** [awesomeWM/awesome#1064] opened 2016-09-01 13:00 UTC
Output of `awesome --version`:

awesome v3.5.9 (Mighty Ravendark)
 • Build: Mar 12 2016 01:11:40 for x86_64 by gcc version 5.3.0 (builduser@rw)
 • Compiled against Lua 5.3.2 (running with Lua 5.3)
 • D-Bus support: ✔

**How to reproduce the issue:**

Press any function key (for example volume up, mic mute, etc.)

**Actual result:**

Awesome hangs. At least I suspect it's awesome since I can still move the mouse pointer, but can do
nothing else.

**Expected result:**

It keeps working.

**Comment by psychon** [comment] 2016-09-01 13:41
Do you have any bindings for these function keys in your config? Does it also happen with the default config? Does it also happen when no other program (e.g. nothing using Qt) is running? Any idea what is special about these function keys compared to other keys on your keyboard? Just to be sure: Does it also hang when you use something else than awesome? Do you have anything in your syslog / in journal / in Xorg's log file?

**Comment by laino** [comment] 2016-09-02 16:30
Your command stops outputting stuff once I press any function key. So I guess that confirms that it is really awesome that is hanging (or being affected by something else).

As a side-note: awesome doesn't use any CPU time once it hangs.

**Comment by laino** [comment] 2016-09-02 16:35
Another thing: console windows don't re-draw once the crash occurs. I piped the output of that command into a file to check whether awesome is really hanging.

Weirdly enough other windows will still redraw (i.e. a YouTube video will keep playing after awesome crashed).

**Comment by blueyed** [comment] 2016-09-02 20:35
Can you test if it also happens with the default config and/or awesome master (from Git) and the default config, please?

**Comment by actionless** [comment] 2016-09-03 05:59
seems no one mentioned `--no-argb` before in this thread, have you tried running awesome with that argument?

**Comment by laino** [comment] 2016-09-04 04:34
It also happens with the default config and ``--no-argb`` doesn't make a difference.

**Comment by Elv13** [comment] 2016-09-04 04:56
Please try with the "git master" version. It is very different from 3.5.9. If it still fails, you can use GDB to get the backtrace (use `gdb /path/to/awesome`, then `run`, then `ctrl+c` once it has hang, then `bt full` and the trackback command you can find in the README.md). Also, a simple `strace` or `ltrace` can be useful. Then, in the last resort, we will need an X11trace. With that, we are almost sure to fix the deadlock root cause.

Don't worry, the changes are you wont need to produce all traces, testing master with GDB should hopefully be enough. This problem is so far unheard of and quite serious, there must be something special with your setup or an application misbehave badly (yes, X11 let that happen without any safeguard).

**Comment by psychon** [comment] 2016-09-05 07:51
> Another thing: console windows don't re-draw once the crash occurs

Uhm...

Ok, another idea would be to run `while true ; do date ; sleep 1 ; done`. If this also stops outputting things once you press a function key, then the bug would be in the X11 server (because awesome is not involved in drawing windows, it only places them). However, I do not know what would be involved in the hang then... The X server? But apparently OpenGL still works (or whatever special "make this go fast"-magic is used to play YouTube videos).

**Comment by dumblob** [comment] 2016-09-11 16:24
Surprisingly this happens to me as well (Arch Linux 4.4.20-1-lts,). It started after a major system update. I've confirmed this issue also in FVWM and JWM. I've then compiled and installed -git versions of xorg-server, xf86-input-evdev etc., tried different kernel parameters for i915 (semaphores, c6 state) and tried disabling acpi in kernel, tried all possible combinations of `Option "DRI"` and `Option "AccelMethod"` and `Option "NoAccel"`, installed a new kernel (4.7.x) and tried all the above again without any success.

In the end I noticed, that it's the pressing of any key combination involving an Fn key on my ThinkPad T500. The behavior is exactly what @laino describes (the X server hangs and WMs stop redrawing and functioning; applications though run further and just complain in logs, that they lost connection to X server).

I haven't found absolutely anything anywhere in logs, which could be related to this issue. Does anyone of you have any experience with debugging xorg-server? Could anyone more experienced with X and processes at freedesktop.org fill a bug in their bug trackers?

**Comment by psychon** [comment] 2016-09-12 07:19
@dumblob All I can recommend for debugging the server would be `Xorg.0.log`. However, you issue sounds a bit different, because your issue sounds like the X server crashes/dies/whatever ("applications lose their connection to X server"), while @laino says that he can still move the mouse pointer, which means that the X server is still (at least partly) working.

Still, all of this sounds a lot like some issue in the X server. The best idea that I have for @laino would be to also try some other WMs and see if the same issue occurs there. However, that would just help to confirm "it's not awesome's fault", but nothing more than that.

**Comment by dumblob** [comment] 2016-09-12 08:59
>@dumblob All I can recommend for debugging the server would be Xorg.0.log

That was the first place I looked into before trying all the stuff mentioned. But there is nothing interesting - X server runs further without writing anything else than normal messages to `Xorg.0.log`.

>However, you issue sounds a bit different, because your issue sounds like the X server crashes/dies/whatever ("applications lose their connection to X server"), while @laino says that he can still move the mouse pointer, which means that the X server is still (at least partly) working.

After pressing `Fn`, I can work with non-overlapped parts of applications windows I can see (i.e. have them on the current virtual desktop) without any issues. Cursor works, all applications key combinations work, rendering works, everything works except for window managers and except for connection to X server (e.g. using wmctrl I can't do any window-related operations - move any windows, change any property of windows, spawn any windows - i.e. launch any GUI application, close any window, etc.).

I'm kind of confident it's the same issue. But let's @laino try other window managers first.

**Comment by psychon** [comment] 2016-09-12 09:07
But for @laino, console windows don't redraw anymore...?
Could you run the X server without any window manager (perhaps just two terminals) and test if the issue still occur (e.g.: Does `wmctrl` work after Pressing Fn?)? If there's no problem here, can you get me the output of `xev` for the "evil key press that stops the world"?

**Comment by Elv13** [comment] 2016-09-23 20:30
```
[00:09] <esph> I've been having a problem lately where after pressing certain key combinations, awesome locks up completely. All clients appear to retain normal function, and I can still interact with whichever client was focused at the time of the lock-up, but I can't seem to issue any kind of commands to awesome by either keyboard or mouse (so I can't click on or use mod to navigate to different clients or
[00:09] <esph> tags, and I can't reload or quit awesome without killing it from a separate tty.)
[00:10] <esph> One key combination which I know to cause this is Fn+Up or Fn+Down (which are the key combos for brightness on my laptop).
[00:12] <esph> Just now, this happened on my desktop, and I'm not sure which keys I pressed this time, but I've kept from killing it so far in the hope that somebody could help me figure out what's wrong.
[00:31] <Elv13> esph: Awesome version?
[00:35] <Elv13> esph: In case it is 3.5.*, please try to kill all Qt apps and see if it helps. There was a bug in Qt itself when they moved to libinput. It has been fixed and mitigated on our side. So upgrading everything should fit it. If it is the latest master, revert to a commit last week. We had reports of a potential slowdown on the current HEAD (but no lockups)
[00:43] <esph> Elv13: I'm at 3.5.9-1 right now, it seems. Would this Qt bug only happen when Qt clients are in focus? Right now Sakura (a terminal emulator which doesn't depend on Qt) is in focus. Also, I killed skype, which I believe is the only Qt thing I'm currently running, and the widgit-icon thing disappeared, but the client window is still there and awesome is still locked up.
[00:45] <esph> (it just so happens that the tag I'm stuck on has both my skype and the terminal I'm using to run screen+weechat out of right now)
[00:45] <Elv13> esph: I think a Qt app only has to be running. From your description, there is no deadlock or system freeze. Only the wiboxes/wibars cannot get the input focus. So Awesome is still able to process the inputs themselves, or you would not be able to interact with the focused client
[00:45] <Elv13> (Awesome always listen and process all inputs, this is necessary for shortcuts)
[00:46] <esph> Elv13: okay, but awesome itself doesn't seem to respond to any kind of input directed at the wm itself.
[00:46] <Elv13> no, but it still process them, so it is not frozen
[00:46] <Elv13> otherwise you could not write anything in weechat
[00:46] <esph> Yeah, I said 'lock-up' to try to avoid sounding like it was a hard freeze.
[00:46] <Elv13> it is the first time it happen? did you perform a system update?
[00:47] <esph> My first two messages in the channel contained this info.
[00:48] <esph> I tried to be explicit about what was happening so as to avoid confusion about this being a hard freeze, but I guess I wasn't clear enough.
[00:48] <Elv13> don't worry, it is late here
[00:49] <Elv13> anyway, so how often does it happen?
[00:49] <esph> Only whenever I press certain key combinations, as I said before. So every time I do that, I guess (though I don't know all the key combos that cause this).
[00:50] <esph> Fn+Up or Fn+Down does it on my laptop, for instance (and this wasn't always the case)
[00:50] <esph> A while ago I could change the brightness that way just fine.
[00:51] <Elv13> https://github.com/awesomeWM/awesome/issues/1064
[00:52] <Elv13> Its the closest I can find. It's rather new too. It only happen since a few weeks, and so far to only 1 user. If you think it is the same issue, please comment and add extra details.
[00:55] <esph> Hmm, okay. That definitely sounds similar. Though I tried several combinations with Fn after I first realized that this was happening, and not all of them did it.
[00:55] <esph> I'll have to redo my testing and keep track this time I guess.
[00:56] <Elv13> just please add a comment so you get the notifications when we need testers (and so we know there is multiple users affected)
[00:57] <Elv13> At some point a pattern might emerge, for now it seem a little misterious
[00:57] <Elv13> y*
[00:59] <esph> Alright, will do, and thanks for the help.
```

**Comment by syll-dev** [comment] 2016-09-30 16:24
I have the same problem here with AltGr + E (for € sign).

I can reproduce the bug with awesome or fluxbox on Archlinux.

The bug appears if I launch awesome (or fluxbox) with this command : 'dbus-lauch --exit-with-session awesome' in my .xinitrc and disappears if I launch the WM with only 'awesome'.

It could be linked to a dbus update in archlinux about a month ago.

I don't know how to check this and send this problem to dbus team if this is confirmed...

**Comment by psychon** [comment] 2016-09-30 19:04
@syll-dev Are you also using a thinkpad? Could you run `dbus-monitor` and see what it says when you press the key and things break?

**Comment by syll-dev** [comment] 2016-09-30 22:04
Non, I am not using a thinkpad.

I have run 3 commandes :
(1) while true ; do echo 'return "awesome is still working at "..os.date()' | awesome-client ; sleep 0.5 ; done
(2) while true ; do date ; sleep 0.5 ;  done
(3) dbus-monitor

(1) is frozen when things break and after maybe 30 seconds prints errors every 30 (?) seconds : "Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
(2) continues
(3) does not print something when I press the key but it continues to print some things when (1) print its error message ("at the same time", I don't know if it is a cause or a consequence).

Messages printed by (3) when things are broken :

method call time=1475272121.631175 sender=:1.53 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1475272121.631202 sender=org.freedesktop.DBus -> destination=:1.53 serial=1 reply_serial=1
   string ":1.53"
signal time=1475272121.631215 sender=org.freedesktop.DBus -> destination=(null destination) serial=101 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.53"
   string ""
   string ":1.53"
signal time=1475272121.631230 sender=org.freedesktop.DBus -> destination=:1.53 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.53"
method call time=1475272121.631396 sender=:1.53 -> destination=org.naquadah.awesome.awful serial=2 path=/; interface=org.naquadah.awesome.awful.Remote; member=Eval
   string "return "awesome is still working at "..os.date()"
signal time=1475272122.947179 sender=org.freedesktop.DBus -> destination=:1.0 serial=102 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string "org.freedesktop.Notifications"
signal time=1475272122.947222 sender=org.freedesktop.DBus -> destination=(null destination) serial=103 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.freedesktop.Notifications"
   string ":1.0"
   string ""
signal time=1475272122.947245 sender=org.freedesktop.DBus -> destination=:1.0 serial=104 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string "org.naquadah.awesome.awful"
signal time=1475272122.947260 sender=org.freedesktop.DBus -> destination=(null destination) serial=105 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string "org.naquadah.awesome.awful"
   string ":1.0"
   string ""
signal time=1475272122.947282 sender=org.freedesktop.DBus -> destination=:1.0 serial=106 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameLost
   string ":1.0"
signal time=1475272122.947298 sender=org.freedesktop.DBus -> destination=(null destination) serial=107 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.0"
   string ":1.0"
   string ""
error time=1475272122.947323 sender=org.freedesktop.DBus -> destination=:1.53 error_name=org.freedesktop.DBus.Error.NoReply reply_serial=2
   string "Message recipient disconnected from message bus without replying"
signal time=1475272122.947353 sender=(null sender) -> destination=(null destination) serial=0 path=/org/freedesktop/DBus/Local; interface=org.freedesktop.DBus.Local; member=Disconnected

**Comment by esph** [comment] 2016-10-01 02:50
I believe @syll-dev has identified my problem precisely. Changing the exec call from using dbus-launch to directly starting awesome resolved the issue (this wasn't a problem with older versions of dbus). Since I can't even remember why I needed to launch with dbus, that's a fine workaround for me so far.

A bit of additional info: I experienced this 'hang' with some but not all Fn key combinations like @laino, and some but not all AltGr key combinations like @syll-dev. There may be other combinations that I did not find or test, however.

**Comment by psychon** [comment] 2016-10-01 09:02
Now I want to point at https://github.com/awesomeWM/awesome/issues/1064#issuecomment-244584382, too. Could someone get a gdb backtrace for when awesome hangs?
And just a random thought: Does this also happen when running $SOME_OTHER_WM and running awesome in e.g. Xephyr? That could make things a bit easier to debug for you...

**Comment by dumblob** [comment] 2016-11-17 10:56
@psychon sorry for a late reply. The solution for me was the same as for @esph and @syll-dev (i.e. to run window managers directly without dbus-launch). Anyway, let's answer your old questions.

>But for @laino, console windows don't redraw anymore...?
>Could you run the X server without any window manager (perhaps just two terminals) and test if the issue still occur (e.g.: Does `wmctrl` work after Pressing Fn?)? If there's no problem here, can you get me the output of `xev` for the "evil key press that stops the world"?

This issue did not appear when I ran window manager without dbus-launch and sent some wmctrl commands to it after pressing `Fn`.

There is no output in `xev` as the Fn key on my ThinkPad T500 is a hardware key not propagated to X.

**Comment by jonnor** [comment] 2017-10-10 15:11
I had a problem with the same symptoms as described here, but for me it was triggered by suspend: After resuming from suspend AwesomeWM would freeze and not respond to keybindings, new windows would not be mapped on screen. Sending SIGHUP did not help either. Both closing laptop lid, or using `systemctl suspend` would trigger the issue. Unsure if root cause is same or different, but after removing `dbus-launch` the problem was gone.

However then gnome-terminal would not start, which I found the solution for here (need to import the DISPLAY/XAUTHORITY envvars to dbus activation):
https://unix.stackexchange.com/a/243696

**Comment by psychon** [comment] 2017-11-23 15:19
Possibly related: https://github.com/i3/i3/issues/2979 (or not)

**Comment by laino** [comment] 2017-11-23 23:43
I had completely forgotten about this issue after the symptoms went away with a system update only a few days later. I don't think there was a new version of awesome, so maybe the issue was caused by some other component.

Curious that there is still people encountering this. Maybe it is a common symptom across various bugs?

**Closed** 2017-11-24 08:19 UTC
Labels: bug

**Comment by ploth** [comment] 2019-03-11 19:56
It happens to me since a few days after a system update. Already switched to lts kernel but that doesn't help. I'm using Antergos (Arch) Linux.

```
4.19.28-1-lts
```
```
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```
