### ISSUE TITLE
Focus doesn't return to the last client when closing a client that has opened in a different screen

### ISSUE THREAD

**Issue by lestrozi** [awesomeWM/awesome#2155] opened 2018-01-15 02:14 UTC
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

1) Create a rule (awful.rules.rules) to open Vlc, for instance, on screen=2
2) Use a file manager on screen=1 and open a video using Vlc (it will correctly open on screen 2)
3) Close Vlc

**Actual result:**

Focus will stay on screen=2

**Expected result:**

Focus should return to the previous focused application (file manager on screen=1)

**Comment by lestrozi** [comment] 2018-01-15 05:04
In summary, IMO client:kill() should focus on the last client in _awful.client.focus.history.list_ regardless of its screen. Does that make sense?

If you don't agree, can you tell me how I can override client:kill() or some signal that's emitted after a kill? Thanks

**Comment by psychon** [comment] 2018-01-15 07:14
Well, that's `awful.autofocus`, I guess. On various conditions it checks if a client currently has the focus, and if not, it uses the focus history to find a client to focus. However, it does not focus other screens.
Since I have no idea what would be "good behaviour" for you: Could you read the code of `awful.autofocus` and come up with an idea that would please you?

**Comment by lestrozi** [comment] 2018-01-16 02:09
Thanks!
This worked for me
If you think this change makes sense I can submit a pull request


```
27c27,30
<         local c = aclient.focus.history.get(screen[obj.screen], 0, filter_sticky)
---
>         local c = aclient.focus.history.list[2]
>         if not c then
>             c = aclient.focus.history.get(screen[obj.screen], 0, filter_sticky)
>         end

```

**Comment by lestrozi** [comment] 2018-01-16 02:42
Yeah, I agree.
I noticed that my code has some side-effects also (such as not focusing when a new tag is selected).

I think the right way to fix it would be for check_focus_delayed to send the whole "obj" (not just {obj.screen}) to check_focus() and then do the history selection if obj.valid == false (that way, if I'm getting this correctly, this would run only if the previous client has been killed/unmanaged).

I'll try to make this work for me, but I understand it's not for everybody.

**Comment by psychon** [comment] 2018-01-20 11:16
I'll close this as "works as intended" and "changing that would likely make people unhappy" (plus: can be worked around in `rc.lua`; `awful.autofocus` is even not loaded by default and needs to be explicitly `require`d, so you can just drop that part from your config and write your own logic).

**Closed by psychon** 2018-01-20 11:16 UTC
