### ISSUE TITLE
Cannot close window after changing keyboard layout

### ISSUE THREAD

**Issue by tomoyat1** [awesomeWM/awesome#639] opened 2016-01-19 05:56 UTC
Whenever the keyboard layout is changed, all windows open at that point become unable to close with the close window shortcut. (I believe the default is  Meta + Shift + C)

Steps to reproduce
1. open some window
2. issue setxkbmap <keymap that is not current active>
3. try to close the window opened in step 1.

Just in case it matters, I changed my layout from "jp" to "us"
I've been poking Awesome around with a debugger, but I have no clue what to look for.

Edit: This issue first appeared in version 3.5.7. In 3.5.6 things worked fine.

**Comment by psychon** [comment] 2016-01-19 08:47
I would close this saying that this was fixed in master (what will be awesome 3.6), however you confuse me saying that this worked in 3.5.6. Could you do a git bisect? The only change remotely related to key input is ff799a0f5dba06beed9f13939237899e53ff8fd8, but that has nothing to do with keyboard layouts.

Are you really, really, *really* sure that this worked in 3.5.6?

Also, I have no clue about the jp keyboard layout, does pressing Meta+Shift+C work with the keys from the us layout? As in: Does awesome only partly notice the keyboard layout change?

**Comment by ElGoreLoco** [comment] 2016-01-19 17:40
The same is happening to me. I switch keyboard between `es` and `ro`. I'm pretty sure this is a `3.5.7` issue because I have a log file with my updates, and I updated yesterday at 20:58 (Spain timezone), later that night I remember having that issue.

**Comment by tomoyat1** [comment] 2016-01-20 08:19
I am really really really sure that this worked in 3.5.6.
I did a git bisect, and it told me that (the seemingly unrelated) ff799a0 is the revision that introduced this problem. Also, the problem can be reproduced using either my jp layout keyboard or my us layout keyboard. Changing the layout setting seems to be what triggers it.

**Comment by psychon** [comment] 2016-01-20 09:08
Reverting this will bring #496 back and #640 is the first duplicate of this.

In other news: No idea (yet) what is going on (I agree with @tomoyat1's "seemingly unrelated").

**Comment by tomoyat1** [comment] 2016-01-21 13:50
I did some additional testing, and here are my findings.
1. Every client key is affected. (Maximize, Toggle Float, ...)
1. Windows that were opened *after* setxkbmap was issued are not affected.

**Comment by psychon** [comment] 2016-01-21 17:30
@tomoyat1 Can you test if running the following in a terminal fixes the problem for this terminal? (And if so: Prefixing the command with a `sleep 3 ;` gives you three seconds to focus another window and fix input for that one)
```sh
echo 'client.focus.keys = clientkeys` | awesome-client
```
The command should just re-set all keybindings for the currently focus client. If this fixes anything (by your description it should), then I'm left wondering why this worked in 3.5.6...

**Comment by psychon** [comment] 2016-01-21 17:35
Oh, that was easy. Can someone (any gentoo users out there?) try this patch: https://gist.github.com/psychon/3f6322eb96c1aeac3202
It fixes an obvious oversight in commit ff799a0f5dba06beed9f13939237899e53ff8fd8 and makes awesome do the equivalent of the above on keyboard mapping changes.

**Comment by FloGa** [comment] 2016-01-21 20:26
Hi! I am a Gentoo user and in fact I was looking for this exact problem. Sometimes the clientkeys stopped working all of a sudden.
The patch you posted WORKED for me! No problems afterwards, even if I call `setxkbmap`, which triggered the problem before.
Thanks a lot!

**Comment by tomoyat1** [comment] 2016-01-21 23:11
I'm also a gentoo user : )
Your patch fixes the issue. 
Thank you. Hope this gets applied downstream too.

**Comment by psychon** [comment] 2016-01-22 08:01
Thanks for testing. Can someone also test if my patch also fixes #646? (Something with emacsclient which I don't have installed and can't test for a while)

**Closed** 2016-01-23 12:16 UTC

**Comment by phobosxy** [comment] 2016-01-26 07:02
It's work for me. Respect!
