### ISSUE TITLE
Panel buttons stop working with Qt application open.

### ISSUE THREAD

**Issue by taidg** [awesomeWM/awesome#498] opened 2015-10-05 23:57 UTC
The panel will cease being interactable when an application using the Qt Gui (maybe only qt5) is open. This will only occur after some time of the application being open, or immediately after a suspend/resume. The problem will continue until the application is closed.

Qt Creator and qBittorrent both cause this for instance.

I'm on Arch with awesome v3.5.2-804-gee0e9b.

**Comment by taidg** [comment] 2015-10-06 00:14
Nevermind, seems to be an issue elsewhere, reverted to complete stock and failed to have a problem.

**Comment by taidg** [comment] 2015-10-06 02:37
It seems this only occurs when running a Qt gui app And then connecting my bluetooth headphones (via gui or bluetoothctl). At which point awesome will no longer receive mouse input. This is occuring with both the the current git version and 3.5.6 in the arch repos. I've been testing with Qt Creator as the app, qbittorrent does not seem to be a reliable offender.

**Comment by psychon** [comment] 2015-10-09 18:31
Same issue as #415?

**Comment by spectromas** [comment] 2015-10-22 14:51
I am also experiencing this with qbittorrent built against qt5. For me it seems that hibernate/resume causes it so it may well be the reloading module issue. I didn't get this with qbittorrent built against qt4.

**Comment by psychon** [comment] 2015-11-20 08:33
I'll go with the assumption that this is a duplicate of #415.

According to https://github.com/awesomeWM/awesome/issues/415#issuecomment-157349957, you should run your Qt applications with `QT_XCB_NO_XI2_MOUSE=1` to make this work.

**Closed by psychon** 2015-11-20 08:33 UTC
