### ISSUE TITLE
Assertion failed in notification.lua with Lain/fs widget

### ISSUE THREAD

**Issue by wereii** [awesomeWM/awesome#3428] opened 2021-09-08 17:01 UTC
Output of `awesome --version`:

```
awesome v4.3-1086-g13cd20780 (Too long)
 • Compiled against Lua 5.3.6 (running with Lua 5.3)
 • API level: 4
 • D-Bus support: yes
 • xcb-errors support: yes
 • execinfo support: yes
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
 • Transparency enabled: yes
 • Custom search paths: no
```

**How to reproduce the issue:**

**Have**: (Lightdm +) Awesome @ 13cd20780  + powerarrow-dark from awesome-copycats (fork with my changes: https://github.com/wereii/awesome-copycats)
**Do**: Place mouse over the "drive"/fs widget percent number

**Actual result:**

Fs/disk space table popup does not open at all and errors are generated (when moving over the widget with mouse):

```sh
2021-09-08 18:35:36 W: awesome: luaA_dofunction:78: error while running function!
stack traceback:
	[C]: in function 'assert'
	/usr/share/awesome/lib/naughty/notification.lua:984: in function 'naughty.notification.set_screen'
	(...tail calls...)
	/usr/share/awesome/lib/naughty/core.lua:653: in local 'func'
	/usr/share/awesome/lib/gears/object.lua:198: in function 'naughty.init.emit_signal'
	/usr/share/awesome/lib/gears/object.lua:166: in function 'gears.object.emit_signal'
	/usr/share/awesome/lib/naughty/notification.lua:1202: in function </usr/share/awesome/lib/naughty/notification.lua:1116>
	(...tail calls...)
	/usr/share/awesome/lib/lain/widget/fs.lua:46: in field 'show'
	/usr/share/awesome/lib/lain/widget/fs.lua:134: in local 'func'
	/usr/share/awesome/lib/gears/object.lua:160: in function 'gears.object.emit_signal'
	/usr/share/awesome/lib/wibox/drawable.lua:329: in upvalue 'emit_difference'
	/usr/share/awesome/lib/wibox/drawable.lua:350: in upvalue 'handle_motion'
	/usr/share/awesome/lib/wibox/drawable.lua:443: in function </usr/share/awesome/lib/wibox/drawable.lua:443>
error: /usr/share/awesome/lib/naughty/notification.lua:984: assertion failed!
```

**Expected result:**

Should not error out and instead display overview/table of disk capacity.

**Comment by sclu1034** [comment] 2021-09-08 17:26
Assertions failing usually indicate incorrect API usage. In this case, my guess is lain failing to create notifications correctly.

Given that it fails with `set_screen`, I would start debugging here: https://github.com/lcpz/lain/blob/1db09ba186b076abb34f60e92761bd612b4dc851/widget/fs.lua#L49.

**Comment by wereii** [comment] 2021-09-08 17:41
I was indecisive if this is a valid issue (irc) due to that assertion.
Though consider that the widget works completely alright with manjaro shipped `awesome`

```sh
awesome v4.3 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
```

but not with master, seems weird that it would be caused by code that hasn't changed last 9 months (git blame).

**Comment by wereii** [comment] 2021-09-08 18:08
Something wasn't right.
I went over few things and noticed that manjaro ships it's own `lain` and `freedesktop` packages for awesome, I made sure the modules shipped with the theme (repository submodules) are used and while it still errors out, the error has changed a bit and somehow it does not cause error notifications to popup anymore.

```sh
2021-09-08 20:05:29 E: awesome: Error during a protected call: /usr/share/awesome/lib/naughty/notification.lua:984: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/usr/share/awesome/lib/naughty/notification.lua:984: in function 'naughty.notification.set_screen'
	(...tail calls...)
	/usr/share/awesome/lib/naughty/core.lua:653: in local 'func'
	/usr/share/awesome/lib/gears/object.lua:198: in function 'naughty.emit_signal'
	/usr/share/awesome/lib/gears/object.lua:166: in function 'gears.object.emit_signal'
	/usr/share/awesome/lib/naughty/notification.lua:1202: in function </usr/share/awesome/lib/naughty/notification.lua:1116>
	(...tail calls...)
	/home/tomas/.config/awesome/lain/widget/fs.lua:50: in upvalue 'callback'
	/home/tomas/.config/awesome/lain/widget/fs.lua:141: in function </home/tomas/.config/awesome/lain/widget/fs.lua:138>
	[C]: in function 'xpcall'
	/usr/share/awesome/lib/gears/protected_call.lua:36: in function </usr/share/awesome/lib/gears/protected_call.lua:35>
	(...tail calls...)
2021-09-08 20:05:48 W: awesome: a_glib_poll:470: Last main loop iteration took 0.204925 seconds! Increasing limit for this warning to that value.
```

**Comment by Elv13** [comment] 2021-09-08 21:12
So this is the code:

```lua
function notification:set_screen(s)
    assert(not self._private.screen)

    s = s and capi.screen[s] or nil

    -- Avoid an infinite loop in the management code.
    if s == self._private.weak_screen[1] then return end

    self._private.weak_screen = setmetatable({s}, {__mode="v"})

    self:emit_signal("property::screen", s)
end
```

Lain code is:

```lua
            fs.notification_preset.screen = fs.followtag and focused() or scr or 1
            fs.notification = naughty.notify {
                preset  = fs.notification_preset,
                timeout = type(seconds) == "number" and seconds or 5
            }
```

So lain, sets `notification._private.screen` on the notification by editing the presets. This was never really supported, but then again, there is nothing seriously wrong with it either, so it's a regression in the new notification module. I will make a fix soon to unbreak this.

Longer story, this assert is there because it causes a memory leak. I didn't expect this to be set indirectly by the presets. AwesomeWM git-master has a fully new notification module. It's supposed to be a drop-in replacement and fully compatible with the older one, but getting 100% compat is hard given how messy the old code was.

**Comment by Elv13** [comment] 2021-09-16 23:45
I created https://github.com/awesomeWM/awesome/pull/3436 with a fix for this bug. Please test if you can. Otherwise, it should land in git-master pretty soon.

**Comment by wereii** [comment] 2021-09-17 09:26
Just tested, does not error anymore but does nothing. No popup opens when moving mouse over the fs widget. 
I put some gdebug print_warnings here and there in the fs widget and the methods `fs.show` and `fs.hide` are called though nothing seems to happen.

**Comment by Elv13** [comment] 2021-09-20 21:29
Can you share your `fs` and wibox/wibar code? I tried

```lua
 
173     local filesystem = fs().widget
174     filesystem.forced_width = 100                                                                                                            
175     
176     -- Create the wibox
177     s.mywibox = awful.wibar {
178         position = "top",
179         screen   = s,
180         widget   = {
181             layout = wibox.layout.align.horizontal,
182             { -- Left widgets
183                 layout = wibox.layout.fixed.horizontal,
184                 mylauncher,   
185                 s.mytaglist,  
186                 s.mypromptbox,
187             },
188             s.mytasklist, -- Middle widget
189             { -- Right widgets
190                 layout = wibox.layout.fixed.horizontal,
191                 mykeyboardlayout,
192                 fff,
193                 wibox.widget.systray(),
194                 mytextclock,  
195                 s.mylayoutbox,
196             },
197         }
198     } 
199 end)  
```

And it works for me:

![image](https://user-images.githubusercontent.com/340384/134078246-ec2d764a-23de-4cdf-ad1e-20a58965ff8d.png)

This is on top of the default `rc.lua`. So I guess you created the widget differently?

**Comment by wereii** [comment] 2021-09-21 02:45
https://github.com/wereii/awesome-copycats

I do have wibar on bottom but even if I move it back to top I can't see anything.

**Comment by Elv13** [comment] 2021-09-23 02:36
Ok, I tested exactly that config and exactly that version of lain and could reproduce. This is pretty deep in legacy code. That code is there for backward compatibility only and isn't reachable by modern configs.

What happens is that `lain` set the notification text using a mechanism which was intended to be used for configuration (the deprecated presets). At the time, you were supported to pass the `screen` and `text` properties to the `naughty.notify()` function. But the drawback of that was that it wasn't possible to replace the text later. This was fixed a *looong* time ago, but `lain`/@lpcz code was mostly written in the v3.5 era. So at the time, setting those in the preset was a nice workaround to be able to set the text "elsewhere". With the fix below, the `notification.message` object property explicitly check if this hack was used and "fixes" it.

```patch
commit 21a111d154c3595c8d7e9d74b43fd6321aaa0cd9
Author: Emmanuel Lepage Vallee <elv1313@gmail.com>
Date:   Wed Sep 22 19:15:33 2021 -0700

    naughty: Allow to set the message from the presets again.
    
    This was never really supported and is really not what the presets
    were event meant to be used for. But it worked and `lain` used it.

diff --git a/lib/naughty/notification.lua b/lib/naughty/notification.lua
index 4e602a523..860eec08c 100644
--- a/lib/naughty/notification.lua
+++ b/lib/naughty/notification.lua
@@ -570,6 +570,27 @@ function notification:set_timeout(timeout)
     self:emit_signal("property::timeout", timeout)
 end
 
+function notification:get_message()
+    -- This property was called "text" in older versions.
+    -- Some modules like `lain` abused of the presets (they
+    -- had little choice at the time) to set the message on
+    -- an existing popup.
+    local p = rawget(self, "preset") or {}
+    local message = self._private.message or p.message or ""
+
+    if message == "" and p.text and p.text ~= "" then
+        gdebug.deprecate(
+            "Using the preset configuration to set the notification "..
+            "message is not supported. Please use `n.message = 'text'`.",
+            {deprecated_in=5}
+        )
+
+        return p.text
+    end
+
+    return message
+end
+
 function notification:set_text(txt)
     gdebug.deprecate(
         "The `text` attribute is deprecated, use `message`",
```

**Comment by wereii** [comment] 2021-09-23 14:47
Tested again at commit https://github.com/awesomeWM/awesome/pull/3436/commits/64d190546d759138ebe31c8768021ea5a13e07f0 and it works without any errors :tada: Thank you for doing this!

**Closed** 2021-09-24 14:53 UTC
Labels: bug
