### ISSUE TITLE
Closing programs in the systray makes keyboard unresponsive

### ISSUE THREAD

**Issue by Donearm** [awesomeWM/awesome#135] opened 2015-02-17 08:26 UTC
Since awesome 3.5.6, closing a program from the systray (right click->close) makes the keyboard totally unresponsive. No keys work, neither the default ones nor my own keybinds. Tested with Dropbox and Google-MusicManager (I have no other programs that make use of the systray). To restore keyboard's functionality it's necessary to change tag by clicking with the mouse on the statusbar. No other action is sufficient to make the keyboard responsive again. 

```
awesome v3.5.6 (For Those About To Rock)
 • Build: Jan 10 2015 23:18:34 for x86_64 by gcc version 4.9.2 (builduser@)
 • Compiled against Lua 5.2.3 (running with Lua 5.2)
 • D-Bus support: ✔
```

**Comment by actionless** [comment] 2015-02-17 09:28
is that reproducible for you when using default rc.lua?

**Comment by Donearm** [comment] 2015-02-17 09:36
Yes, and it's even worse: keyboard remains unresponsive even after clicking with the mouse (which still works though). I have to restart Awesome.

**Comment by actionless** [comment] 2015-02-17 09:38
latter part can re related with https://github.com/awesomeWM/awesome/issues/67

**Comment by Donearm** [comment] 2015-02-20 09:15
It probably is. Just tested with xev launched before closing the program in the systray (in this case Dropbox) and the keyboard remained responsive throughout the test. If I close xev, the bug reappears.
Besides, I am launching awesome from startx, no DMs

**Comment by psychon** [comment] 2015-11-28 17:56
Could this perhaps be the same issue as #415? As far as I know, dropbox does use Qt. No idea about google something music.

**Comment by Donearm** [comment] 2015-11-30 14:33
It seems related indeed. Actually Dropbox doesn't cause the bug any more, Google Music still does (and yes, it uses QT too)

**Comment by psychon** [comment] 2015-11-30 14:39
Then please try if running Google Music with `QT_XCB_NO_XI2_MOUSE=1` in its environment makes this issue go away. That did at least help with "that other" issue.

**Comment by Donearm** [comment] 2015-11-30 20:20
It doesn't exactly go away in my case, I have an unresponsive keyboard for about 2 seconds and then it is fully working again. Could it be that until the google music process is dead it still blocks the key presses?

**Comment by psychon** [comment] 2015-12-01 07:53
Everything's possible :-) (I really don't know, but that could be... I guess)

**Comment by kiike** [comment] 2016-11-02 16:00
Can't reproduce this issue on the Qt-based app SimpleScreenRecorder. Running Awesome from git built using the AUR script.

```
awesome v3.5.2-2163-gb2e0e55 (The Fox)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

Here's what I have been trying to reproduce this issue:

![issue135](https://cloud.githubusercontent.com/assets/464625/19936465/c2a0c5c6-a11d-11e6-9f68-e63e24067d82.gif)

I'm trying to think of a GTK-based app now...

**Comment by Elv13** [comment] 2017-05-31 08:12
@psychon Can we assume this is fixed and close this?

**Comment by psychon** [comment] 2017-05-31 08:56
@Elv13 No idea. This is all a big mystery to me and I have no clue what causes it. Keyboard hangs for two seconds just dont make any sense.
@Donearm Sorry, but we cannot really do anything about this and I am out of debugging ideas (well, I never really had any). I'll close this now since it is unrealistic that anything will magically happen. Feel free to reopen if you have some "aha"-idea that provides more hints into what is going on.

**Closed by psychon** 2017-05-31 08:56 UTC
