### ISSUE TITLE
Eclipse: completion popup-window disappearing

### ISSUE THREAD

**Issue by andreas1724** [awesomeWM/awesome#71] opened 2015-01-01 00:01 UTC
Linux: 3.17.6-1-ARCH
Awesome: v3.5.2-225-g30b313f (The Fox)
Eclipse: Luna Service Release 1 (4.4.1)
Java: java-8-jdk, java-8-jre/jre (Oracle), or OpenJDK

Pressing Ctrl+Space in Eclipse activates the content assist. The content assist window with a list of proposals will appear. When I choose an item of the list with the mouse or when I press the Tab-key to give focus to the content assist window, the content assist will stop working flawless: Each time, I hover the cursor above the content assist window, it disappears immediately. I can temporarily fix the content assist, by moving Eclipse to another workspace. But choosing an item of the proposal list with the mouse will corrupt the content assist window again.

I read about the problems with non-reparenting window managers and java (though awesome is a reparenting WM now, I guess) on http://awesome.naquadah.org/wiki/Problems_with_Java: I could not fix the problem.

I replaced awesome 3.5 with awesome 3.4: The problem vanishes, Eclipses content assist works flawless.

P. S.: The same problem occurs to the tooltip-windows in Eclipse: to give focus to a tooltip-window will cause the next calling of a tooltip-window AND completion-window to fail. The problem is related to JFace. Two snippets with the same problem:
- [autocomplete snippet](http://krishnanmohan.wordpress.com/2011/12/12/eclipse-rcp-autocompletecombotext-control/)
- [tooltip snippet](http://www.subshell.com/en/subshell/blog/jface-tooltips-via-information-controls100.html)

Awesome is not the only tiling-WM having this problem:

Same bug as Awesome:
- bspwm 0.8.9
- wmii 3.9.2
- i3 4.8
- qtile 0.8.0
- spectrwm 2.6.1
- wmfs2 (-g3c701a9) 2 beta

No problems with Eclipse detected:
- dwm 6.0
- herbstluftwm 0.6.2
- frankenwm
- notion
- ratpoison 1.4.8
- subtle 0.11.3243
- wmfs 
- xmonad 0.11

**Comment by Airblader** [comment] 2015-03-08 10:36
Thank you for that detailed report! Since this works with awesome 3.4, have you considered bisecting it to track it down?

**Comment by Elv13** [comment] 2015-03-09 15:10
If you bisect between 3.4 and 3.5, you have to use the default rc.lua. There was many  breaking config changes in the last 6 years since the 3.4 and 3.5 branches diverged.

**Comment by andreas1724** [comment] 2015-03-14 16:47
I used the appropriate default rc.lua which comes with each version of awesome.

**Comment by halemmerich** [comment] 2015-07-13 13:24
I have the same behaviour using:
OpenJDK Runtime Environment (IcedTea 2.5.5) (Arch Linux build 7.u79_2.5.5-1-x86_64)
awesome v3.5.6 (For Those About To Rock)
Luna Service Release 2 (4.4.2)

If I give focus to another window and then back to eclipse tooltips and content assist are shown as expected. After focusing it via mouse click it works once as expected, then all following uses the pop up does directly vanish on mouseover.
I tried removing the sloppy focus section from rc.lua, but have not seen a change in the eclipse behaviour.

**Comment by kiike** [comment] 2016-11-02 13:45
Hi @andreas1724! Have you tried newer versions of Awesome WM?

So far, I couldn't reproduce with Awesome Git master from yesterday and a vanilla config.

```
awesome v3.5.2-2163-gb2e0e55 (The Fox)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1
```

Here's a video of me trying to reproduce the bug. Let me know if there's anything else I should try in it.

![eclipse](https://cloud.githubusercontent.com/assets/464625/19930955/00f6a650-a10b-11e6-95f6-38f3762840f6.gif)

**Comment by Airblader** [comment] 2016-11-02 14:14
This issue has been fixed in Eclipse, see the comment in the linked issue over at i3.

**Comment by psychon** [comment] 2016-11-02 14:59
Thanks for the information. Upstream issue is here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=466114

**Closed by psychon** 2016-11-02 14:59 UTC
Labels: bug, Java

**Comment by nathantippy** [comment] 2020-06-20 18:42
This appears to be back again in 2020-03 and 2020-06 on ubuntu 18.04.  As described above if the mouse is used to select the content assist value the cursor will not appear.   As a Hack solution for my own content assist I added the following to computeCompletionProposal and the issue was fixed.

	final StyledText textWidget = viewer.getTextWidget();    	
    	viewer.addTextListener(new ITextListener() {
			@Override
			public void textChanged(TextEvent event) {					
				textWidget.setCaret(textWidget.getCaret());
  				viewer.removeTextListener(this);
			}
    	});

This should provide a clue based on what gets modified when setCaret is called.

**Comment by vlan1337** [comment] 2023-04-02 12:46
This issue happens with Eclipse 2023-03(4.27.0) Build id: 20230309-1520, in Ubuntu 22.0.4.1 (Jammy Jellyfish).

Issue Description: Content-assist pop-up windows (for ex., when hover over an error pointer - see samples attached) disappear when trying to click on them. Therefore, it becomes impossible to apply quick-fixes that are suggested as links, in the content-assist pop-ups (or) even to understand the error by reading the entire pop-up message.

**Sample-1:**
![image](https://user-images.githubusercontent.com/70746097/229353630-4494bdce-fdb5-4b61-b4ca-a8ece4612d2d.png)

**Sample-2:**
![image](https://user-images.githubusercontent.com/70746097/229353303-2ccd211c-688c-4da1-90be-dde2178d909f.png)


**Note:** Not sure if this helps, but this was marked as fixed here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=466114.
