### ISSUE TITLE
How to set a rule for a client in a dynamic way (... screen = screen.count() does not work).  

### ISSUE THREAD

**Issue by sewkokot** [awesomeWM/awesome#2158] opened 2018-01-16 18:49 UTC
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2

**How to reproduce the issue:**

I would like to open a client "xterm" on the second monitor if it's active otherwise on the first one.

I have in my rc.lua the following line under "Rules"
...
`    { rule = { class = "XTerm" }, properties = { screen = screen.count(), tag = "xterm" } },`
...

**Actual result:**

which results in error: attempt to index a nil value. If I set `screen = 2` and there is no second monitor I also get an error?

**Expected result:**

How to set this rule correctly to use the second screen if it is available, otherwise the first screen?

**Comment by Veratil** [comment] 2018-01-16 23:25
You should be able to make any property a function, which will be run when the rule is applied. This allows for more dynamic workings like you want. Currently your rule will always set it to however many screens are active when awesome starts. If you start awesome with 2 and then deactivate, the rule will still try to set it to screen 2.

I believe this should work:

`screen = function() if screen.count() > 1 then return screen.count() else 1 end end`

**Comment by sewkokot** [comment] 2018-01-17 07:46
Vertil, thank you for your answer, however, I realized that debian sid uses the latest awesome version so I found in [1] that screen.count() changed into screen:count(). Then simple `screen = screen:count()` works!
[1] https://awesomewm.org/apidoc/classes/screen.html#screen:count

P.S. After 3-4 years I returned to awesome, and I feel in it as at home. Howewer I need to learn more lua and the latest api :)

**Comment by psychon** [comment] 2018-01-17 08:25
@sewkokot Sorry, but I am definitely sure that your last comment is wrong. The reason the docs mention `screen:count()` instead of `screen.count()` is some problems with LDoc. Both calls do the exact same thing. So, you really need `screen = function() return screen.count() end` (dunno why @Veratil had an `if` in there).

Closing since you say the problem is gone....

**Closed by psychon** 2018-01-17 08:25 UTC

**Comment by sewkokot** [comment] 2018-01-17 12:22
@psychon I changed the rule to `screen = function() return screen.count() end` as you recommended and it works as well as `screen = screen:count()`. While changing doubledot with dot does not work. How to explain it?

**Comment by psychon** [comment] 2018-01-17 15:07
I cannot explain it. `screen:count()` is a shorthand for `screen.count(screen)`. Since this function takes no arguments, this code has exactly the same code as what you wrote in the first comment on this issue as "it doesn't work". So, really, the colon cannot work.

**Comment by Veratil** [comment] 2018-01-17 15:33
I had an if because of lapse of thought. :)
