### ISSUE TITLE
Unexpectedly high memory usage with Terminology

### ISSUE THREAD

**Issue by marekjm** [awesomeWM/awesome#1735] opened 2017-04-17 09:13 UTC
Output of `awesome --version`:

```
awesome v4.1 (Technologic)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

**How to reproduce the issue:**

0. login to Linux console on tty1
1. start AwesomeWM (I launch it through `startx`) 
2. login to Linux console on tty2, and launch `htop` to monitor memory usage
3. in AwesomeWM, launch Terminology
4. let it run for a few minutes

**Actual result:**

In a matter of minutes memory usage of AwesomeWM surges from ~36MB to fill the system's RAM. The increase is incredibly rapid - I can see memory usage growing second-by-second. I once let it run until "something interesting" would happen, and it resulted in the kernel's OOM killer intervening (it killed AwesomeWM). 

**Expected result:**

Memory usage should increase slightly after Terminology is spawned, and then remain relatively constant.

----

Output of `terminology --version`:

```
Version: 1.0.0
```

If any more information would be required, I am happy to assist.
I am aware of issues #368 and #1068 but they seem different to this.

**Comment by blueyed** [comment] 2017-04-17 11:12
Could not reproduce it using Awesome Git master (just launched Terminology from Awesome, and monitored it from there, too - no extra tty).
Using Arch Linux, which has terminology 1.0.0, too.

**Comment by psychon** [comment] 2017-04-17 16:50
> let it run for a few minutes

With nothing happening? What kind of interaction should cause anything here? Is there anything beside the blinking mouse cursor?

Also, what's Terminology?

**Comment by marekjm** [comment] 2017-04-17 17:18
@blueyed Thanks for the input. Maybe it's something else then... I tried to isolate the issue, and the most probably culprit was Terminology (nothing else was running except for it and Awesome).

@psychon With nothing happening. I tried to isolate the issue, and it was sufficient to just launch Terminology and wait. Terminology is a [terminal emulator from EFL](https://www.enlightenment.org/about-terminology).

**Comment by psychon** [comment] 2017-04-17 17:26
@marekjm So you can run `Xephyr :5 ; sleep 5 ; (DISPLAY=:5 awesome & DISPLAY=:5 terminology)`, wait 15 minutes and awesome's memory usage would be high?

**Comment by marekjm** [comment] 2017-04-18 20:13
@psychon Exactly. I didn't try it before in Xephyr, but I can confirm that the behaviour is the same as under "raw" X server - I can just launch Terminology and wait, and the memory usage grows over time.

**Comment by blueyed** [comment] 2017-04-18 21:20
@marekjm 
Do you have some specific config for Terminology?
Can you try it with older tags, and or git-bisect it in general?  (given that it takes a while to see it this might be tedious, and @psychon has probably a better idea about how to debug this)

**Comment by marekjm** [comment] 2017-04-18 21:36
@blueyed Just standard stuff, nothing fancy - I use one of the built-in colorschemes, and didn't include any special config except for changing what's available though the Terminology's GUI.

I know it started when I updated to Awesome 4.0. With 3.x I didn't have this problem. I'll try to bisection (good idea, by the way), but it would have to wait till weekend when I'll have some free time available. Also, checking if the bug exists doesn't take a long time: just a few seconds are needed to see if the memory usage starts increasing.

**Comment by Elv13** [comment] 2017-06-01 21:19
@marekjm ping. Could you bisect this? Otherwise I will close the issue next week as an "EFL bug". However the precise reason why it regressed should be interesting for both parties, so I still suggest you do the bisecting.

**Comment by marekjm** [comment] 2017-06-01 21:32
Oh, right. It fell out of my radar and I kinda forgot about the issue. I'll see if I am still able to reproduce the issue.

**Comment by oscarcarlsson** [comment] 2017-06-02 22:09
I've seen the same issue, after launching terminology (just to try it out) my awesome process used ~10% of my available RAM. Restarting my awesome wm process fixed the issue (awesome now using <1% of RAM).

**Comment by marekjm** [comment] 2017-06-04 09:00
@Elv13 You can close this issue. It must have been something with my configuration as I can't reproduce it on a fresh machine with a clean Awesome 4.x config. Sorry for the confusion.

**Comment by blueyed** [comment] 2017-06-04 11:40
Closing for now.
@oscarcarlsson 
If you see it again, please let us know.

**Closed** 2017-06-04 11:39 UTC
Labels: bug, need info

**Comment by oscarcarlsson** [comment] 2017-06-04 13:44
I've tried to reproduce it several times but without success. If I'm successful I'll create a new issue :)
