### ISSUE TITLE
Global keybinding on modkey doesn't call the release callback

### ISSUE THREAD

**Issue by jazzpi** [awesomeWM/awesome#1416] opened 2017-01-20 11:36 UTC
Output of `awesome --version`:

awesome v4.0 (Harder, Better, Faster, Stronger)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • RandR 1.5 support: ✔
 • LGI version: 0.9.1

**How to reproduce the issue:**

Add a global keybind:

```lua
    awful.key({}, "#133", function() naughty.notify({text="Modkey pressed"}) end, function() naughty.notify({text="Modkey released"}) end, {})
```

**Actual result:**

The "Modkey pressed" notification appears when pressing the modkey, but the "Modkey released" notification doesn't when releasing it.

**Expected result:**

The "Modkey pressed" notification appears when pressing the modkey and the "Modkey released" notification does when releasing it.

**Comment by psychon** [comment] 2017-01-20 12:01
Duplicate of #169

**Closed by psychon** 2017-01-20 12:01 UTC
