### ISSUE TITLE
Awesome freezes on window resize: hard reset needed 

### ISSUE THREAD

**Issue by kierun** [awesomeWM/awesome#2065] opened 2017-10-20 07:46 UTC
Output of `awesome --version`:

awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.4 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1

Fedora 26: Linux nightwatch 4.13.5-200.fc26.x86_64 #1 SMP Thu Oct 5 16:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**How to reproduce the issue:**

Start awesome, resize a window, both mouse and keyboard now no longer do anything… Hard reset to get the system working again. This is the code in `.condig/awesome/rc.lua`:

```
clientbuttons = awful.util.table.join(
    awful.button({ }, 1, function (c) client.focus = c; c:raise() end),
    awful.button({ modkey }, 1, awful.mouse.client.move),
    awful.button({ modkey }, 3, awful.mouse.client.resize))
```

Note that moving the window works just fine.

The odd thing is that maximising in height or width works just fine using these:

```
    awful.key({ modkey }, "F7", function(c) c.maximized_horizontal = not c.maximized_horizontal end),
    awful.key({ modkey }, "F8", function(c) c.maximized_vertical   = not c.maximized_vertical end),
```

**Actual result:**

Awesome freezes.

**Expected result:**

Window is resized and window manager continues working.

*What additional information do you need?*

**Comment by psychon** [comment] 2017-10-20 10:13
Does `awesome-client` continue to work while things freeze (e.g. `sleep 10 ; awesome-client 'return 42'` and then cause the freeze in those 10 seconds)? Does the screen still update (e.g. `sleep 10 ; echo I work` in a terminal`)? Can you move the mouse cursor?

**Comment by psychon** [comment] 2017-10-20 10:24
Oh and: Can you still interact with running applications (e.g. click buttons in browser)?

**Comment by kierun** [comment] 2017-10-20 11:32
The keyboard losses all input. Whatever is typed, nothing happens. The mouse still shows (as only an arrow even in terminal/vim sessions), but clicks get lost in the ether. Music continues to play but that's it.

**Comment by psychon** [comment] 2017-10-21 06:14
Okay, let's try that again:

- [ ] Does awesome-client continue to work while things freeze (e.g. sleep 10 ; awesome-client 'return 42' and then cause the freeze in those 10 seconds)?
- [ ] Does the screen still update (e.g. sleep 10 ; echo I work in a terminal`)?
- [x] Can you move the mouse cursor? (Answer is yes)
- [x] Can you still interact with running applications (e.g. click buttons in browser)? (answer is "no")
- [ ] Do you have "focus-follows-mouse" enabled? Does that still work in this state?

**Comment by kierun** [comment] 2017-10-23 15:12
Apologies. Here are the missing answers.

>    Does awesome-client continue to work while things freeze (e.g. sleep 10 ; awesome-client 'return 42' and then cause the freeze in those 10 seconds)?

No, it does not.

>    Does the screen still update (e.g. sleep 10 ; echo I work in a terminal`)?

No, it does not.

>    Do you have "focus-follows-mouse" enabled? Does that still work in this state?

Yes, I do have `focus-follows-mouse` enabled. It does not work after the resize. 

I did find this: [xsessions-errors.log](https://github.com/awesomeWM/awesome/files/1407672/xsessions-errors.log) which might offer some hints as to what went wrong.

**Comment by psychon** [comment] 2017-10-23 16:31
>> Does the screen still update (e.g. sleep 10 ; echo I work in a terminal`)?
>
> No, it does not.

Then I'd think that the problem is in the X11 server and not in awesome. Awesome is not involved in redrawing terminals like this (in fact, awesome is not even told that the contents of the terminal changed).
You might want to take a look at `/var/log/Xorg.0.log` (and/or `Xorg.0.log.old` if you already restarted the X server). (If your X server is not running as root, the log file is written somewhere in your home directory, but I don't know where).

**Comment by kierun** [comment] 2017-10-27 08:06
> Then I'd think that the problem is in the X11 server and not in awesome.

This does not happen when I run gnome. It only happens when I run awesome.

Did the log file provided give you any clues?

**Comment by psychon** [comment] 2017-10-27 08:12
Nope, I guess the only messages in there from awesome are "I had some problems reading the old wallpaper".

**Comment by kierun** [comment] 2017-10-30 16:05
Nothing in any of the Xorg logs that I can spot as being weird. I have attached one of them in case you can spot something I did not. 

[xorg.log](https://github.com/awesomeWM/awesome/files/1427883/xorg.log)

**Comment by psychon** [comment] 2017-10-30 16:24
Yup, nothing interesting in there. No idea what is going on. What is different about resizing than moving?!?

Another random idea: You could do something like `sleep 10 ; pkill awesome` to kill awesome after 10 seconds, then resize a window before the ten seconds elapsed. If killing awesome doesn't make the system unfreeze (and doesn't have any visible results on-screen), then at least I can claim that this is not a bug in awesome (or that something else has another, additional bug where it fails to clean up correctly).

**Comment by kierun** [comment] 2017-10-31 08:23
> Yup, nothing interesting in there. No idea what is going on. What is different about resizing than >moving?!?

Honestly, I have no idea whatsoever. It baffles the hell out of me! ⍨

One think that *might* be happening is when the cursor is outside of the window. I managed to resize fine a couple of times while doing it careful then went faster. As soon as the cursor was out of the window: freeze. It could be a rate of redrawing as well.

To be fair, I am using Nouveau which is not the best of drivers⸮

> Another random idea: You could do something like sleep 10 ; pkill awesome to kill awesome after 10  seconds, then resize a window before the ten seconds elapsed. If killing awesome doesn't make the  system unfreeze (and doesn't have any visible results on-screen), then at least I can claim that this > is not a bug in awesome (or that something else has another, additional bug where it fails to clean up correctly).

I shall try that with a `nohup` in front of it so it has a chance to run.

**Comment by kierun** [comment] 2017-11-03 07:53
Tried that. No difference whatsoever … ☹ Looks like something in awesome resize causes the window to be updated all the time which looks nice. Is there a way to only redraw the window at the end?

**Comment by psychon** [comment] 2017-11-03 07:56
> Tried that. No difference whatsoever … ☹

So, if killing awesome does not make a difference, then isn't something in X.org locking up, or so?

> Looks like something in awesome resize causes the window to be updated all the time which looks nice. Is there a way to only redraw the window at the end?

Well, resizing a window causes it to be informed about its new size and the need to redraw.

Since somewhen recently there is `awful.mouse.resize.set_mode("after")` which, I think, only applies the resize at the end of everything.

**Comment by kierun** [comment] 2017-11-03 08:04
> So, if killing awesome does not make a difference, then isn't something in X.org locking up, or so?

No idea if awesome was killed. I cannot access a console, do not have a spare machine to ssh into my one, and nothing changes on screen. It's a PITA to debug! 

> Since somewhen recently there is `awful.mouse.resize.set_mode("after")` which, I think, only applies the resize at the end of everything.

I shall give that a try! 

Thank you very much, you are really going beyond the call of duty on this one! ☺

**Comment by psychon** [comment] 2017-11-03 08:22
> I shall give that a try! Where should it go within the ~/.config/awesome/rc.lua file?

Not in the middle of anything else and not before `local awful = require("awful")`, so... just at it to the end of the file.

**Comment by kierun** [comment] 2017-11-03 08:43
So, I tried that. Awesome claims the file is fine but I now cannot move windows. I get an error message about mouse events.

I wonder if my `.config/awesome/rc.lua` is not way too old… This is the tail of the `.xsession-errors`:

```
2017-11-03 08:38:05 W: awful: function ? is deprecated, see awful.spawn.        
stack traceback:    
        /usr/share/awesome/lib/gears/debug.lua:95: in function 'gears.debug.deprecate'
        /usr/share/awesome/lib/awful/init.lua:23: in function 'awful.util.spawn'
        (...tail calls...)              
        /home/yann/.config/awesome/rc.lua:720: in main chunk                    
2017-11-03 08:38:05 W: awful: function ? is deprecated, see awful.spawn.        stack traceback:    
        /usr/share/awesome/lib/gears/debug.lua:95: in function 'gears.debug.deprecate'
        /usr/share/awesome/lib/awful/init.lua:23: in function 'awful.util.spawn'        (...tail calls...)              
        /home/yann/.config/awesome/rc.lua:721: in main chunk                    
urxvt: Loading image icon failed, continuing without.                           
Fri  3 Nov 08:38:05 GMT 2017 1/2315: /home/yann/wallpapers/2015/Fall_of_Gods_Art_thor_destroying.jpg
2017-11-03 08:38:05 W: awesome: a_glib_poll:432: Last main loop iteration took 0.151152 seconds! Increasing limit for this warning to that value.
2017-11-03 08:38:10 W: awesome: luaA_dofunction:77: error while running function!
stack traceback:    
        /usr/share/awesome/lib/awful/mouse/snap.lua:256: in local 'cb'          
        /usr/share/awesome/lib/awful/mouse/resize.lua:169: in function </usr/share/awesome/lib/awful/mouse/resize.lua:156>
error: /usr/share/awesome/lib/awful/mouse/snap.lua:256: attempt to index a nil value (local 'geo')
2017-11-03 08:38:10 W: awesome: event_handle_mousegrabber:123: Stopping mousegrabber.
2017-11-03 08:38:11 W: awesome: luaA_dofunction:77: error while running function!
stack traceback:    
        /usr/share/awesome/lib/awful/mouse/snap.lua:256: in local 'cb'          
        /usr/share/awesome/lib/awful/mouse/resize.lua:169: in function </usr/share/awesome/lib/awful/mouse/resize.lua:156>
error: /usr/share/awesome/lib/awful/mouse/snap.lua:256: attempt to index a nil value (local 'geo')
2017-11-03 08:38:11 W: awesome: event_handle_mousegrabber:123: Stopping mousegrabber.
; QXcbWindow: Unhandled client message: ""       
```

**Comment by psychon** [comment] 2017-11-03 08:59
Okay, so we have that resize mode, but it does not work (and possibly never worked, I don't know)... I open #2101 for that.

**Comment by luckrn** [comment] 2017-12-30 18:47
Hi.
I have the same error : "_Awesome freezes on window resize_" and "_hard reset needed_" :/
My solution is just to **downgrade xorg-server** (bug exist with version 1.19.6.2 >> I downgraded with version 1.19.3-3). I can now resize window with mouse without reboot ; it's work !
My linux : Linux viper 4.14.9-1-ARCH #1 SMP PREEMPT Tue Dec 26 00:18:37 UTC 2017 x86_64 GNU/Linux, awesome v4.2 (Human after all).
Tchao. Have fun

**Comment by blueyed** [comment] 2017-12-30 21:04
@luckrn 
So it is easily reproducible for you then?
How do you resize exactly?  super-right-click and then dragging the mouse?

**Comment by alxbl** [comment] 2017-12-31 00:24
Just chiming in... I started running into that issue a week or so ago, and nothing seemed to work. I switched to i3 just to try, and managed to get the same freeze.

I then switched to Gnome, and everything seemed fine for a while. Then it started happening when switching workspaces or maximizing windows. I scraped the internets to no end, finding almost no information. I also tried XFCE4 (also froze)

Finally after one particular restart, my PC stopped booting altogether (???), which prompted me to nuke my `/` (`/home` is on a different partition, thankfully) and do a clean install of the base system.

I re-installed with nvidia-utils instead of nouveau, and so far it hasn't occurred. (Knock on wood).

I guess what I'm trying to say is that the problem doesn't seem to be awesome related, nor particularly X related, but perhaps config/driver related?

If all else fails, maybe a system re-install can help?

```
λ ~/dotfiles/ master* pacman -Qi xorg-server
Name            : xorg-server
Version         : 1.19.6-2
```

If this can help:
I recall first seeing the system freeze when trying to setup tigervnc, where the tigervnc daemon would segfault randomly after connecting a client to it and seemed very unstable. I'm not sure if this was the cause or a consequence of the issue.

**Comment by luckrn** [comment] 2017-12-31 09:49
@blueyed 
Yes > super-right-click to resize
@alxbl 
I used nouveau (xf86-video-nouveau 1.0.15-2) with my NIVIDIA GeForce GTX 560

**Comment by alxbl** [comment] 2017-12-31 17:52
@luckrn After seeing your comment, I decided to try nouveau again. I still can't reproduce anymore, even with the latest xorg-server.

I guess this rules out faulty drivers? So it must have been something with Xorg's config??

I have an NVIDIA GeForce GTX 750 Ti, just for the record.

**Comment by blueyed** [comment] 2018-01-01 14:48
Chiming in also/addtionally:
I am seeing a hard freeze, where I have to kill awesome from another VT (via SIGKILL - `kill -9`) from time to time when using https://github.com/blueyed/awesome-cyclefocus (but with at least some small local patch): it happens when using <kbd>alt</kbd>-<kbd>Tab</kbd> and coming to some tag layout or client/window apparently.

It would be nice to have instructions for debugging such issues with the "Debugging tips" section in the README, or some external section (e.g. README-dev, or the docs, linked to from the README).

**Comment by Elv13** [comment] 2018-01-01 19:39
Funny enough, it /was/ there until 0707f52ebf978f170bb9e70b0eca7c540826ce0b, but apparently the tip isn't very compatible with modern Lua.

   gdb -i $(pidof awesome)
    thread apply all backtrace full
    print luaL_dostring(globalconf.L.real_L_dont_use_directly, "print(debug.traceback())")

**Comment by kierun** [comment] 2018-01-02 08:34
I am still getting this but only if I am too quick at resizing. If you do it so the window re-draw has time to catch up, it works fine. It not, freeze.

Nvidia GT950 as hardware, in case that matters.

**Comment by Elv13** [comment] 2018-01-02 17:58
@kierun can you run the commands above and give us the output? This assumes the PC isn't in a kernel panic state and can be reached using the VT or SSH.

**Comment by blueyed** [comment] 2018-01-18 21:58
Just tried the commands above (`gdb` needs `sudo`), but got:

> No symbol "luaL_dostring" in current context.

I've managed to make it segfault then, so will have to try again if it happens.

I've found the following, which might come in handy: https://github.com/mkottman/lua-gdb-helper/.

**Comment by psychon** [comment] 2018-01-19 08:32
@blueyed This stuff depends on the lua version. For Lua 5.3 `luaL_dostring(L, s)` is a preprocessor macro that expands to (after lots of indirection): `(luaL_loadstring(L, s) || lua_pcallk(L, 0, -1, 0, 0, NULL))`. For LuaJit (and I guess also fur Lua 5.1?), `lua_pcall` directly is a function and the last two arguments can be left out.

**Comment by Elv13** [comment] 2018-12-22 04:34
Apparently it can happen, but looks like an hardware problem, so I will close this until we have less mysterious data to judge this.

**Closed by Elv13** 2018-12-22 04:34 UTC
Labels: need info
