### ISSUE TITLE
Clients get lost when removing and re-adding a screen / generic screen handling

### ISSUE THREAD

**Issue by blueyed** [awesomeWM/awesome#2185] opened 2018-02-08 14:35 UTC
When using something like `xrandr --output eDP-1 --off; sleep 2; xrandr --output eDP-1 --auto` (as a workaround to issues with the intel graphics driver and external screen), all clients get lost, i.e. no clients are visible and apparently all of them have a nil screen.

Restarting awesome picks them up again.
Output of `awesome --version`:
```
awesome v4.2-249-g584c5cedb-dirty (Human after all)
 • Compiled against Lua 5.1.4 (running with LuaJIT 2.0.5)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.1
```

It seems like only the first `xrandr` command triggers processing in awesome?!

It might also be caused by other errors, since awesome's code often assumes e.g. `capi.mouse.screen` to be not nil.
Also `get_screen` in `awful.layout` (and how it is used there) assumes that there is a screen always: https://github.com/awesomeWM/awesome/blob/cf0a4affa53dd823bbd7f047ced3b482d23890a0/lib/awful/layout/init.lua#L26-L28.

**Comment by psychon** [comment] 2018-02-08 15:18
I'd say the `screen.connect_signal("removed", ...)` in `lib/awful/tag.lua` tries to find some place where to put the clients and fails since, well, no screen survives (if I understand you correctly). Then the C code (`screen_removed` in `objects/screen.c`) comes around and forces all clients to another screen that still refer to the screen-to-be-removed. If no screen remains, this code will call `screen_client_moveto` with `NULL` for the screen argument. I wouldn't be too surprised if some segfaults await in that direction...

And now for "what to do about that": Uhm... Just refuse to remove all screens? Dunno
```diff
diff --git a/objects/screen.c b/objects/screen.c
index d0746c3f..90131c19 100644
--- a/objects/screen.c
+++ b/objects/screen.c
@@ -684,6 +684,7 @@ screen_refresh(void)
             list_changed = true;
         }
     }
+    if (removed_screens.len != globalconf.screens.len) {
     foreach(old_screen, removed_screens) {
         luaA_object_push(L, *old_screen);
         screen_removed(L, -1);
@@ -691,6 +692,7 @@ screen_refresh(void)
         (*old_screen)->valid = false;
         luaA_object_unref(L, *old_screen);
     }
+    }
     screen_array_wipe(&removed_screens);
 
     /* Update changed screens */
```
(`fake_remove` can still remove the last screen)

**Comment by Elv13** [comment] 2018-02-08 17:18
> And now for "what to do about that": Uhm... Just refuse to remove all screens? Dunno

I got a semi completed patchset for that one since like 2.5years. My idea is/was to add a `request::area` to `capi.root` and *always* let the Lua side a chance to create the `screen` object itself then to fallback to the old C codepath if the area has not been filled with a screen.

That way you can handle this (and most other) corner cases alongside the existing `request::screen` code (in Lua) or write custom handlers.

**Comment by Elv13** [comment] 2018-02-08 18:10
> psychon assigned Elv13 21 minutes ago

It might take a while at the speed things are currently progressing. If you have some spare time to implement the `request::area`, I think we could skip most of the unavoidable review cycle loops. The Lua side of this can be implemented later as long as the C side fallbacks to the current behavior.

Btw, this is a duplicate of #1344

**Comment by psychon** [comment] 2018-02-08 18:14
Oh, okay. Closing then.

Also: Nah, sorry. Just "this requires testing with a real X11 server" is enough to put it towards the end of my todo list.

**Closed by psychon** 2018-02-08 18:14 UTC
