### ISSUE TITLE
wayland support how is that going is it even possible?

### ISSUE THREAD

**Issue by Felopater-Melika** [awesomeWM/awesome#3621] opened 2022-05-26 02:54 UTC
```
MayTODO:
[ ] Pixman backend
[ ] FB backend
[ ] Wayland backend
```

The FB and PixMap backends would be quite useful, one less layer of abstraction. I guess it will stay a "wait and see" approach for some time (and well, patches welcome).

_Originally posted by @Elv13 in https://github.com/awesomeWM/awesome/issues/159#issuecomment-77573494_

**Comment by sclu1034** [comment] 2022-05-26 08:13
Duplicate of #159.

"wait and see"-type issues are not helpful and only generate noise and the occasional "what's the status here?" comments.

**Comment by Elv13** [comment] 2022-05-27 22:05
I agree with @sclu1034  here. I don't think there is anything actionable in this issue. Nobody (I am aware of) is currently working on a wlroot backend. Pixman and FB backends are not super useful in practice. Even if getting AwesomeWM to render on pixman/fb (+libinput) isn't that much work, what would be the point? It would not be able to render any apps beside wiboxes. The SVG backend can already be coerced to render on anything with a Cairo backend (including both pixman and fb).

The newer rewrite of waycooler from 2018 (the C one, not the Rust one) is the closest to a fully working wayland port. It can be finished. I think all design issues of the previous 2 attempts are fully fixed and the path toward feature parity was pretty much on track, but the author lost interest.

**Closed by Elv13** 2022-05-27 22:05 UTC

**Comment by OmegaRogue** [comment] 2022-06-25 12:07
Someone should fork and continue way-cooler then

**Comment by Elv13** [comment] 2022-06-25 20:14
Yes, feel free to be that somebody. The lack of that somebody is the main blocker right now.

**Comment by OmegaRogue** [comment] 2022-07-06 16:48
The Repo is forked, now comes the hard part of figuring out the current state of things and what needs to be done https://github.com/OmegaRogue/way-cooler
